/** Chapter 68 · At the airport. */
export const airportLesson = {
  id: 'airport',
  kind: 'airport',
  number: '68',
  title: '第68章に入る前に：なぜ「空港で使う英語」を学ぶのでしょうか？',
  enTitle: 'At the airport',
  ja: '出発から機内、到着後まで、空港で必要になる基本的なやり取りや表現を学びます。',
  cando: 'チェックイン、保安検査、搭乗、入国審査、手荷物受け取り、両替、レンタカーの手続きを確認できる。',
  learn: {
    intro: [
      '空港では、チェックイン、保安検査、搭乗、入国審査、手荷物の受け取りなど、短い時間の中で多くの手続きがあります。',
      '今どこで何をすればいいのかを理解し、フライト状況、ゲート、荷物、機内の指示を必要なときに確認することが大切です。',
      'この章では、出発から機内、到着後まで、空港で必要になる基本的なやり取りや表現を学びます。',
    ],
    functions: [
      ['01', 'フライトとゲートを確認する'],
      ['02', '荷物と保安検査に対応する'],
      ['03', '機内の指示に従う'],
      ['04', '到着後の手続きを進める'],
    ],
    departures: {
      title: '出発・チェックイン・保安検査',
      enTitle: 'Departures, check-in & security',
      intro: 'フライト状況、手荷物預け入れ、保安検査、ゲートと搭乗時刻を確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Where are you flying to today?', meaning: '今日はどちらまで行かれますか？', context: '目的地を尋ねる', register: 'polite' },
        { phrase: 'Cairo. Is the flight on time?', meaning: 'カイロです。フライトは予定通りですか？', context: 'フライト状況を確認する', register: 'polite' },
        { phrase: 'It says our flight is delayed.', meaning: 'フライトが遅れているって書いてあります。', context: '遅延表示を伝える', register: 'neutral' },
        { phrase: "Typical! Oh well, let's grab a coffee.", meaning: 'よくあることね！まあ、コーヒーでも飲みましょう。', context: '遅延への反応', register: 'casual' },
        { phrase: 'Do you need any help?', meaning: '何かお手伝いしましょうか？', context: 'サポートを申し出る', register: 'polite' },
        { phrase: 'How does the bag drop work?', meaning: '手荷物の預け入れはどうすればいいですか？', context: 'bag dropを尋ねる', register: 'polite' },
        { phrase: 'Place your bag in the tray, please!', meaning: 'バッグをトレイに入れてください。', context: '保安検査の指示', register: 'polite' },
        { phrase: 'Then come through the scanner.', meaning: 'それからスキャナーを通ってください。', context: '保安検査を案内する', register: 'neutral' },
        { phrase: 'Which gate is it for Athens?', meaning: 'アテネ行きはどのゲートですか？', context: '搭乗ゲートを尋ねる', register: 'polite' },
        { phrase: "Gate 14. Hurry - it's closing in 10 minutes!", meaning: '14番ゲートです。急いで！あと10分で閉まります！', context: 'ゲートの閉鎖時刻を伝える', register: 'urgent' },
        { phrase: 'What time is boarding?', meaning: '搭乗開始は何時ですか？', context: '搭乗時刻を尋ねる', register: 'polite' },
        { phrase: "What's the gate number?", meaning: 'ゲート番号は何番ですか？', context: 'ゲート番号を尋ねる', register: 'polite' },
        { phrase: 'What time does the gate close?', meaning: 'ゲートは何時に閉まりますか？', context: 'ゲート閉鎖時刻を尋ねる', register: 'polite' },
        { phrase: 'Can I change to a window seat?', meaning: '窓側の席に変更できますか？', context: '座席を変更する', register: 'polite' },
        { phrase: 'How long is the delay?', meaning: '遅延はどのくらいですか？', context: '遅延時間を尋ねる', register: 'polite' },
        { phrase: 'Any chance of an upgrade?', meaning: 'アップグレードの可能性はありますか？', context: 'アップグレードを尋ねる', register: 'casual' },
        { phrase: 'What is your flight number?', meaning: '便名は何番ですか？', context: '便名を尋ねる', register: 'polite' },
        { phrase: 'What is your destination?', meaning: '目的地はどこですか？', context: '目的地を尋ねる', register: 'polite' },
        { phrase: 'Where is the check-in desk?', meaning: 'チェックインカウンターはどこですか？', context: 'カウンターを尋ねる', register: 'polite' },
      ],
      recognition: [
        { phrase: 'on time', meaning: '定刻通り', note: 'フライトが予定どおりか確認します。' },
        { phrase: 'bag drop', meaning: '自動手荷物預け入れ', note: '預け荷物を処理するエリアです。' },
        { phrase: 'boarding', meaning: '搭乗', note: 'boarding time は搭乗開始時刻です。' },
        { phrase: 'gate close', meaning: 'ゲートが閉まる', note: '出発前に締め切られる時間を示します。' },
      ],
    },
    cabin: {
      title: '搭乗・機内・着陸',
      enTitle: 'Boarding, in the cabin & landing',
      intro: '搭乗券を見せ、荷物を収納し、機内アナウンスや着陸前の指示に従います。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Welcome! Can I see your boarding pass?', meaning: 'ようこそ！搭乗券を拝見できますか？', context: '搭乗券を確認する', register: 'polite' },
        { phrase: 'Hello! Here you go.', meaning: 'こんにちは！はい、どうぞ。', context: '搭乗券を渡す', register: 'casual' },
        { phrase: "I'll put our stuff in the overhead locker.", meaning: '荷物を頭上のロッカーに入れますね。', context: '荷物を収納する', register: 'neutral' },
        { phrase: "Thanks. I'll keep my bag under the seat.", meaning: 'ありがとう。バッグは座席の下に置いておきます。', context: '荷物の置き場所を伝える', register: 'neutral' },
        { phrase: 'Ladies and gentlemen, welcome to Flight 86A for Beijing.', meaning: '皆様、北京行き86A便へようこそ。', context: '機内アナウンス', register: 'formal' },
        { phrase: 'We are ready for departure.', meaning: '出発の準備が整いました。', context: '出発を知らせる', register: 'formal' },
        { phrase: "We'll shortly be passing through the cabin with snacks and drinks.", meaning: '間もなく、スナックと飲み物を持って客室を通ります。', context: '機内サービスを案内する', register: 'formal' },
        { phrase: 'This is your captain speaking. We are experiencing some turbulence.', meaning: 'こちらは機長です。現在、多少の乱気流が発生しております。', context: '乱気流を知らせる', register: 'formal' },
        { phrase: 'Please return to your seat and fasten your seat belt.', meaning: '座席に戻り、シートベルトをお締めください。', context: '着陸前の指示', register: 'formal' },
        { phrase: 'Your tray tables should be securely fastened.', meaning: 'トレイテーブルはしっかりと固定してください。', context: '機内設備の指示', register: 'formal' },
        { phrase: 'Make sure your seat is in the upright position.', meaning: '座席を元の直立した位置に戻してください。', context: '座席を戻す指示', register: 'formal' },
        { phrase: 'Please switch your digital devices to "airplane" mode.', meaning: '電子機器は「機内」モードに切り替えてください。', context: '電子機器の指示', register: 'formal' },
        { phrase: 'We will arrive in Beijing at 9.20 local time.', meaning: '北京には現地時間の9時20分に到着いたします。', context: '到着時刻を案内する', register: 'formal' },
      ],
      recognition: [
        { phrase: 'boarding pass', meaning: '搭乗券', note: '搭乗口で提示します。' },
        { phrase: 'overhead locker', meaning: '頭上ロッカー', note: '機内持ち込み荷物を収納します。' },
        { phrase: 'turbulence', meaning: '乱気流', note: 'シートベルト着用の案内と一緒に聞きます。' },
        { phrase: 'upright position', meaning: '直立した位置', note: '着陸前の座席の状態です。' },
      ],
    },
    arrivals: {
      title: '到着・両替・レンタカー',
      enTitle: 'Arrivals, money exchange & hiring a car',
      intro: '入国審査、手荷物受け取り、タクシーとの待ち合わせ、両替、レンタカーの受け取りを進めます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'What is the purpose of your trip?', meaning: '旅行の目的は何ですか？', context: '入国審査で目的を答える', register: 'formal' },
        { phrase: "I'm visiting friends.", meaning: '友達に会いに来ました。', context: '訪問目的を答える', register: 'neutral' },
        { phrase: 'Which baggage reclaim belt do we need to go to?', meaning: 'どの手荷物受取ベルトに行けばいいですか？', context: '手荷物受取所を尋ねる', register: 'polite' },
        { phrase: "It's Belt 3. I'll grab a trolley.", meaning: '3番ベルトです。カートを持ってきますね。', context: 'ベルト番号と荷物を確認する', register: 'casual' },
        { phrase: "I can't see our suitcases anywhere!", meaning: 'スーツケースがどこにも見当たらない！', context: '荷物が見つからない', register: 'casual' },
        { phrase: "Let's go and check at the baggage desk.", meaning: '手荷物サービスカウンターに行って確認しましょう。', context: '荷物の問題に対応する', register: 'neutral' },
        { phrase: 'Where do we meet our taxi?', meaning: 'タクシーとはどこで待ち合わせですか？', context: '送迎場所を尋ねる', register: 'polite' },
        { phrase: 'The driver should be waiting for us.', meaning: 'ドライバーが待っているはずです。', context: '待ち合わせを確認する', register: 'neutral' },
        { phrase: 'Hi, can I help?', meaning: 'こんにちは、何かご用ですか？', context: '両替所で応対する', register: 'polite' },
        { phrase: "Yes, I need to change some Euros. What's your rate?", meaning: 'はい、ユーロをいくらか両替したいのですが。レートはいくらですか？', context: '両替レートを尋ねる', register: 'polite' },
        { phrase: "Hi! I'm here to pick up a hire car. Here's my booking confirmation.", meaning: 'レンタカーを受け取りに来ました。こちらが予約確認書です。', context: 'レンタカーを受け取る', register: 'polite' },
        { phrase: "Great! Can I see your driving licence, please?", meaning: 'ありがとうございます。運転免許証を見せていただけますか？', context: '免許証を確認する', register: 'polite' },
        { phrase: 'Is the car ready for us?', meaning: '車は準備できていますか？', context: '車の準備を確認する', register: 'polite' },
        { phrase: "Yes, it's in Bay 6. Enjoy your trip!", meaning: 'はい、6番駐車スペースにあります。良い旅を！', context: '車の場所を案内する', register: 'polite' },
      ],
      recognition: [
        { phrase: 'baggage reclaim', meaning: '手荷物受取所', note: 'イギリス英語で baggage claim にあたります。' },
        { phrase: 'baggage desk', meaning: '手荷物サービスカウンター', note: '荷物が届かないときに相談します。' },
        { phrase: 'hire car', meaning: 'レンタカー', note: 'アメリカ英語では rental car と言います。' },
        { phrase: 'Bay 6', meaning: '6番駐車スペース', note: '車を停める区画を bay と呼びます。' },
      ],
    },
    vocabulary: {
      title: '空港・機内のボキャブラリー',
      enTitle: 'Vocabulary · Airport & cabin',
      intro: '空港の案内、座席、機内設備、到着後の移動に関する単語を整理します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'overhead locker', meaning: '頭上ロッカー', context: '機内設備', register: 'neutral' },
        { phrase: 'reading light', meaning: '読書灯', context: '機内設備', register: 'neutral' },
        { phrase: 'window seat', meaning: '窓側の席', context: '座席', register: 'neutral' },
        { phrase: 'aisle seat', meaning: '通路側の席', context: '座席', register: 'neutral' },
        { phrase: 'tray table', meaning: 'トレイテーブル', context: '機内設備', register: 'neutral' },
        { phrase: 'seat belt', meaning: 'シートベルト', context: '安全設備', register: 'neutral' },
        { phrase: 'life jacket', meaning: '救命胴衣', context: '安全設備', register: 'neutral' },
        { phrase: 'boarding pass', meaning: '搭乗券', context: '搭乗', register: 'neutral' },
        { phrase: 'bag drop', meaning: '手荷物預け入れ', context: '出発', register: 'neutral' },
        { phrase: 'gate', meaning: '搭乗ゲート', context: '出発', register: 'neutral' },
        { phrase: 'baggage reclaim', meaning: '手荷物受取所', context: '到着', register: 'regional' },
        { phrase: 'trolley', meaning: '手荷物カート', context: '到着', register: 'regional' },
        { phrase: 'hire car', meaning: 'レンタカー', context: '到着', register: 'regional' },
        { phrase: 'aisle', meaning: '通路', context: '機内', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'aisle seat', meaning: '通路側の席', note: 'aisle の s は発音しません。' },
        { phrase: 'trolley', meaning: 'カート', note: 'アメリカ英語の cart にあたります。' },
        { phrase: 'hire car', meaning: 'レンタカー', note: 'イギリス英語でよく使います。' },
        { phrase: 'life jacket', meaning: '救命胴衣', note: '安全案内で聞く語です。' },
      ],
    },
    dialogues: [
      {
        id: 'departures',
        label: 'Pattern A · Departures',
        title: 'フライトと保安検査を確認する',
        lines: [
          { speaker: 'A', en: 'Where are you flying to today?', ja: '今日はどちらまで行かれますか？' },
          { speaker: 'B', en: 'Cairo. Is the flight on time?', ja: 'カイロです。フライトは予定通りですか？' },
          { speaker: 'A', en: 'How does the bag drop work?', ja: '手荷物の預け入れはどうすればいいですか？' },
          { speaker: 'B', en: 'Place your bag in the tray, please!', ja: 'バッグをトレイに入れてください。' },
        ],
      },
      {
        id: 'cabin',
        label: 'Pattern B · On board',
        title: '搭乗して機内の指示を聞く',
        lines: [
          { speaker: 'A', en: 'Welcome! Can I see your boarding pass?', ja: 'ようこそ！搭乗券を拝見できますか？' },
          { speaker: 'B', en: 'Hello! Here you go.', ja: 'こんにちは！はい、どうぞ。' },
          { speaker: 'A', en: "I'll put our stuff in the overhead locker.", ja: '荷物を頭上のロッカーに入れますね。' },
          { speaker: 'B', en: 'Thanks. I\'ll keep my bag under the seat.', ja: 'ありがとう。バッグは座席の下に置いておきます。' },
        ],
      },
      {
        id: 'arrivals',
        label: 'Pattern C · Arrivals',
        title: '入国審査と手荷物受け取りを進める',
        lines: [
          { speaker: 'A', en: 'What is the purpose of your trip?', ja: '旅行の目的は何ですか？' },
          { speaker: 'B', en: "I'm visiting friends.", ja: '友達に会いに来ました。' },
          { speaker: 'A', en: 'Which baggage reclaim belt do we need to go to?', ja: 'どの手荷物受取ベルトに行けばいいですか？' },
          { speaker: 'B', en: "It's Belt 3. I'll grab a trolley.", ja: '3番ベルトです。カートを持ってきますね。' },
        ],
      },
    ],
    tip: 'Typical! は「またか」「いつものこと」と、トラブルに少し皮肉を込めて反応する表現です。bag drop は自動手荷物預け入れ、イギリス英語のカートは trolley、レンタカーは hire car と言います。aisle seat の aisle は s を発音せず、Bay は車を停める区画です。',
  },
  practice: {
    title: '空港の手続きを、英語でスムーズに進める',
    instructions: '日本語訳は見ずに、フライト、荷物、機内、到着後の表現を声に重ねます。',
    coreHeading: 'まずは、フライトとゲートを確認する一文から。',
    dialogueHeading: '出発、機内、到着後の場面で役を切り替える。',
    dialogueDescription: 'フライトと保安検査を確認する、機内の指示を聞く、入国審査と手荷物受け取りを進める3つの場面を練習します。',
    finishTitle: '次に空港へ行くとき、ゲートか手荷物の英語をひとつ使ってみましょう。',
    corePhrases: [
      { phrase: 'Where are you flying to today?', context: '目的地を確認する', rate: 0.8 },
      { phrase: 'Is the flight on time?', context: 'フライト状況を確認する', rate: 0.84 },
      { phrase: 'How does the bag drop work?', context: '手荷物預け入れを尋ねる', rate: 0.78 },
      { phrase: 'Which gate is it for Athens?', context: 'ゲートを尋ねる', rate: 0.8 },
      { phrase: 'What time is boarding?', context: '搭乗時刻を尋ねる', rate: 0.84 },
      { phrase: 'Can I change to a window seat?', context: '座席を変更する', rate: 0.78 },
      { phrase: 'Can I see your boarding pass?', context: '搭乗券を確認する', rate: 0.82 },
      { phrase: 'Please return to your seat and fasten your seat belt.', context: '着陸前の指示', rate: 0.7 },
      { phrase: 'What is the purpose of your trip?', context: '入国審査で目的を答える', rate: 0.76 },
      { phrase: 'Which baggage reclaim belt do we need to go to?', context: '手荷物受取所を尋ねる', rate: 0.7 },
      { phrase: "What's your rate?", context: '両替レートを尋ねる', rate: 0.86 },
      { phrase: "I'm here to pick up a hire car. Here's my booking confirmation.", context: 'レンタカーを受け取る', rate: 0.7 },
    ],
    dialogues: [
      { title: 'Departures', lines: ['Where are you flying to today?', 'Cairo. Is the flight on time?', 'How does the bag drop work?', 'Place your bag in the tray, please!'] },
      { title: 'On board', lines: ['Welcome! Can I see your boarding pass?', 'Hello! Here you go.', "I'll put our stuff in the overhead locker.", "Thanks. I'll keep my bag under the seat."] },
      { title: 'Arrivals', lines: ['What is the purpose of your trip?', "I'm visiting friends.", 'Which baggage reclaim belt do we need to go to?', "It's Belt 3. I'll grab a trolley."] },
    ],
    natural: [
      { full: 'Is the flight scheduled to arrive at the planned time?', natural: 'Is the flight on time?' },
      { full: 'How can I use the self-service baggage drop?', natural: 'How does the bag drop work?' },
      { full: 'Which conveyor belt should we use to collect our luggage?', natural: 'Which baggage reclaim belt do we need to go to?' },
    ],
  },
}
