/** Chapter 49 · Applying for a job. */
export const applyingForJobLesson = {
  id: 'applying-for-job',
  kind: 'applying-for-job',
  number: '49',
  title: '第49章に入る前に：なぜ「求人に応募する英語」を学ぶのでしょうか？',
  enTitle: 'Applying for a job',
  ja: '履歴書、応募フォーム、カバーレター、締め切りについて話す英語を学びます。',
  cando: '応募書類を準備し、必要な情報と提出期限を英語で確認できる。',
  learn: {
    intro: [
      '求人を見つけることは、仕事探しの最初のステップにすぎません。実際に応募するときには、自分の経験、スキル、資格などを明確に伝える必要があります。',
      '何を書くかだけでなく、情報を正確に、分かりやすく、適切な形で伝えることも大切です。履歴書、応募用紙、カバーレター、締め切りは、すべて応募プロセスの一部です。',
      'この章では、応募書類の準備と提出、応募フォームの記入、そして締め切りや必要書類について話す表現を学びます。',
    ],
    functions: [
      ['01', 'CVを更新する'],
      ['02', '締め切りを確認する'],
      ['03', '応募フォームに記入する'],
      ['04', '必要書類を提出する'],
    ],
    preparing: {
      title: '履歴書の準備と提出',
      enTitle: 'Preparing a CV',
      intro: '履歴書を更新し、参考例を探し、締め切りまでに提出する流れを練習します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'I really want to apply for this job. I must update my CV!', meaning: 'この仕事に絶対に応募したい。履歴書を更新しなきゃ！', context: '応募を決める', register: 'casual' },
        { phrase: 'There are loads of examples online to help you.', meaning: 'ネットには参考になる例がたくさんあるよ。', context: '参考例を教える', register: 'casual' },
        { phrase: 'It says the deadline for applications is tomorrow.', meaning: '応募の締め切りは明日って書いてあるよ。', context: '締め切りを確認する', register: 'neutral' },
        { phrase: "Really? I'd better email my CV tonight, then.", meaning: '本当に？ じゃあ、今夜履歴書をメールで送ったほうがいいな。', context: '提出を急ぐ', register: 'casual' },
        { phrase: 'My CV is all checked and ready to go...', meaning: '履歴書のチェックは全部終わって、提出の準備はできた…', context: '提出前の最終確認', register: 'neutral' },
        { phrase: "Don't forget to send your covering letter, too!", meaning: 'カバーレターも忘れずに送ってね！', context: '必要書類を確認する', register: 'casual' },
      ],
      recognition: [
        { phrase: 'loads of', meaning: 'たくさんの', note: 'a lot of / lots of よりカジュアルな言い方です。' },
        { phrase: 'deadline', meaning: '締め切り', note: '応募書類を提出できる最後の日や時刻です。' },
        { phrase: 'covering letter', meaning: 'カバーレター・添え状', note: 'アメリカ英語では cover letter と呼びます。' },
        { phrase: 'ready to go', meaning: '準備ができている', note: '提出や出発など、次の行動に移れる状態です。' },
      ],
    },
    forms: {
      title: '応募用紙への記入',
      enTitle: 'Application forms',
      intro: '応募フォームの進み具合を話し、個人情報の入力や休憩を提案します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Have you finished your application yet?', meaning: '応募書類はもう書き終わった？', context: '進み具合を尋ねる', register: 'casual' },
        { phrase: "I just need to fill in my personal details and it'll be ready.", meaning: 'あとは個人情報を記入するだけで準備完了だよ。', context: '残りの作業を伝える', register: 'neutral' },
        { phrase: 'This application form is taking ages!', meaning: 'この応募用紙、書くのにすごく時間がかかる！', context: '時間がかかるとこぼす', register: 'casual' },
        { phrase: 'Why don\'t you save it and take a break?', meaning: '保存して、少し休憩したら？', context: '休憩を提案する', register: 'casual' },
        { phrase: 'I need to check the closing date before I submit it.', meaning: '提出する前に締め切りを確認する必要があります。', context: '提出前に確認する', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'fill in', meaning: '用紙に記入する', note: 'オンラインフォームの入力にも使えます。' },
        { phrase: 'personal details', meaning: '個人情報・個人の詳細', note: '氏名、住所、連絡先などを指します。' },
        { phrase: 'taking ages', meaning: 'とても時間がかかる', note: '永遠のように長く感じる、というカジュアルな表現です。' },
      ],
    },
    vocabulary: {
      title: '求人応募のボキャブラリー',
      enTitle: 'Vocabulary · Job applications',
      intro: '求人探しから応募書類の提出までに使う基本的な単語を整理します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'job advertisements', meaning: '求人広告', context: '募集を探す', register: 'neutral' },
        { phrase: 'job search website', meaning: '求人検索サイト', context: '求人を探す場所', register: 'neutral' },
        { phrase: 'CV', meaning: '履歴書', context: 'イギリス英語', register: 'neutral' },
        { phrase: 'resume', meaning: '履歴書', context: 'アメリカ英語', register: 'neutral' },
        { phrase: 'deadline', meaning: '締め切り', context: '提出期限', register: 'neutral' },
        { phrase: 'application form', meaning: '応募用紙・応募フォーム', context: '応募書類', register: 'neutral' },
        { phrase: 'covering letter', meaning: 'カバーレター・添え状', context: '応募書類', register: 'neutral' },
        { phrase: 'personal details', meaning: '個人情報', context: 'フォームの項目', register: 'neutral' },
        { phrase: 'submit an application', meaning: '応募書類を提出する', context: '応募の手続き', register: 'polite' },
      ],
      recognition: [
        { phrase: 'CV / resume', meaning: '履歴書', note: 'イギリス英語とアメリカ英語の違いです。' },
        { phrase: 'covering letter / cover letter', meaning: 'カバーレター', note: '履歴書に添える自己PRや志望動機の手紙です。' },
        { phrase: 'application deadline', meaning: '応募締め切り', note: 'deadline と組み合わせて使います。' },
      ],
    },
    dialogues: [
      {
        id: 'cv',
        label: 'Pattern A · Preparing a CV',
        title: '履歴書を更新して提出する',
        lines: [
          { speaker: 'A', en: 'I really want to apply for this job. I must update my CV!', ja: 'この仕事に絶対に応募したい。履歴書を更新しなきゃ！' },
          { speaker: 'B', en: 'There are loads of examples online to help you.', ja: 'ネットには参考になる例がたくさんあるよ。' },
          { speaker: 'A', en: 'It says the deadline for applications is tomorrow.', ja: '応募の締め切りは明日って書いてあるよ。' },
          { speaker: 'B', en: "Really? I'd better email my CV tonight, then.", ja: '本当に？ じゃあ、今夜履歴書をメールで送ったほうがいいな。' },
        ],
      },
      {
        id: 'form',
        label: 'Pattern B · Completing an application',
        title: '応募フォームの残りを確認する',
        lines: [
          { speaker: 'A', en: 'Have you finished your application yet?', ja: '応募書類はもう書き終わった？' },
          { speaker: 'B', en: "I just need to fill in my personal details and it'll be ready.", ja: 'あとは個人情報を記入するだけで準備完了だよ。' },
          { speaker: 'A', en: 'This application form is taking ages!', ja: 'この応募用紙、書くのにすごく時間がかかる！' },
          { speaker: 'B', en: "Why don't you save it and take a break?", ja: '保存して、少し休憩したら？' },
        ],
      },
      {
        id: 'final-check',
        label: 'Pattern C · Final document check',
        title: '提出前に必要書類を確認する',
        lines: [
          { speaker: 'A', en: 'My CV is all checked and ready to go...', ja: '履歴書のチェックは全部終わって、提出の準備はできた…' },
          { speaker: 'B', en: "Don't forget to send your covering letter, too!", ja: 'カバーレターも忘れずに送ってね！' },
          { speaker: 'A', en: 'Right. I need to check the closing date, too.', ja: 'そうだね。締め切りも確認しないと。' },
          { speaker: 'B', en: 'Good luck with your application!', ja: '応募、うまくいくといいね！' },
        ],
      },
    ],
    tip: 'イギリス英語では履歴書を CV、アメリカ英語では resume と呼びます。カバーレターはイギリス英語で covering letter、アメリカ英語で cover letter です。loads of は「たくさんの」、fill in は「記入する」、taking ages は「とても時間がかかる」というカジュアルな表現です。',
  },
  practice: {
    title: '応募書類を、英語で整えて提出する',
    instructions: '日本語訳は見ずに、CVの準備、締め切り、応募フォーム、必要書類について声に重ねます。',
    coreHeading: 'まずは、求人応募でそのまま使える一文から。',
    dialogueHeading: '準備、フォーム、最終確認の場面で役を切り替える。',
    dialogueDescription: 'CVを更新する、応募フォームを完成させる、必要書類を確認する3つの場面を練習します。',
    finishTitle: '次に応募書類を作るとき、締め切りか必要書類を英語でひとつ確認してみましょう。',
    corePhrases: [
      { phrase: 'I really want to apply for this job.', context: '応募を決める', rate: 0.8 },
      { phrase: 'I must update my CV!', context: 'CVを更新する', rate: 0.82 },
      { phrase: 'There are loads of examples online to help you.', context: '参考例を教える', rate: 0.78 },
      { phrase: 'It says the deadline for applications is tomorrow.', context: '締め切りを確認する', rate: 0.76 },
      { phrase: "I'd better email my CV tonight, then.", context: '提出を急ぐ', rate: 0.78 },
      { phrase: 'Have you finished your application yet?', context: '応募フォームの進み具合を聞く', rate: 0.78 },
      { phrase: "I just need to fill in my personal details and it'll be ready.", context: '残りの入力を伝える', rate: 0.74 },
      { phrase: 'This application form is taking ages!', context: '時間がかかるとこぼす', rate: 0.82 },
      { phrase: "Why don't you save it and take a break?", context: '休憩を提案する', rate: 0.78 },
      { phrase: "Don't forget to send your covering letter, too!", context: '必要書類を確認する', rate: 0.78 },
    ],
    dialogues: [
      { title: 'Preparing a CV', lines: ['I really want to apply for this job. I must update my CV!', 'There are loads of examples online to help you.', 'It says the deadline for applications is tomorrow.', "I'd better email my CV tonight, then."] },
      { title: 'Completing an application', lines: ['Have you finished your application yet?', "I just need to fill in my personal details and it'll be ready.", 'This application form is taking ages!', "Why don't you save it and take a break?"] },
      { title: 'Final document check', lines: ['My CV is all checked and ready to go...', "Don't forget to send your covering letter, too!", 'I need to check the closing date, too.', 'Good luck with your application!'] },
    ],
    natural: [
      { full: 'I have to update my curriculum vitae.', natural: 'I must update my CV!' },
      { full: 'There are many examples on the internet to help you.', natural: 'There are loads of examples online to help you.' },
      { full: 'I only need to enter my personal information and then it will be ready.', natural: "I just need to fill in my personal details and it'll be ready." },
    ],
  },
}
