/** Chapter 82 · Booking an appointment. */
export const appointmentLesson = {
  id: 'booking-appointment',
  kind: 'booking-appointment',
  number: '82',
  title: '第82章に入る前に：なぜ「診察の予約で使う英語」を学ぶのでしょうか？',
  enTitle: 'Booking an appointment',
  ja: '診察の予約、空き時間の確認、予約の変更やキャンセルに使う表現を学びます。',
  cando: '診察を予約し、緊急度や空き時間を伝え、日時の変更やキャンセルを依頼できる。',
  learn: {
    intro: [
      '病院やクリニックでは、診察を受ける前に、まず自分の都合と病院の空き時間を合わせる必要があります。急いでいるのか、いつなら行けるのかを伝えることも大切です。',
      '必要な診察を、必要なタイミングで受けられるように予定を調整します。',
      'この章では、診察の予約、空き時間の確認、そして予約の変更やキャンセルに使う表現を学びます。',
    ],
    functions: [
      ['01', '診察予約と患者情報を伝える'],
      ['02', '今日の空きや緊急度を確認する'],
      ['03', '予約変更・キャンセルを依頼する'],
    ],
    booking: {
      title: '診察の予約をする',
      enTitle: 'Booking an appointment',
      intro: '電話やクリニックの窓口で、医師の予約を依頼し、患者登録や生年月日を確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "Hello, I'd like to book an appointment with Dr Patel, please.", meaning: 'こんにちは、パテル先生の診察予約をしたいのですが。', context: '医師の診察を予約する', register: 'polite' },
        { phrase: 'Are you registered with us?', meaning: '当院に登録されていますか？', context: '患者登録を確認する', register: 'polite' },
        { phrase: 'Yes, I am. My name is Hanan.', meaning: 'はい、登録しています。名前はハナンです。', context: '登録と名前を伝える', register: 'polite' },
        { phrase: "What's your date of birth?", meaning: '生年月日はいつですか？', context: '本人確認をする', register: 'polite' },
        { phrase: 'The 14th of August 1993.', meaning: '1993年8月14日です。', context: '生年月日を答える', register: 'polite' },
        { phrase: 'We have an opening on Thursday at 10am.', meaning: '木曜日の午前10時に空きがありますよ。', context: '空いている時間を提案する', register: 'helpful' },
        { phrase: 'That works for me. Thank you.', meaning: 'それで大丈夫です。ありがとうございます。', context: '日時の提案を受ける', register: 'warm' },
        { phrase: "I'd like to make an appointment to see the doctor.", meaning: '医師の診察予約を取りたいのですが。', context: '予約を切り出す', register: 'polite' },
        { phrase: 'Is Dr Patel available on Friday morning?', meaning: '金曜日の午前中、パテル先生は空いていますか？', context: '医師の空き時間を尋ねる', register: 'polite' },
        { phrase: "Can I check if I'm registered here?", meaning: '私がこちらに登録されているか確認できますか？', context: '登録状況を確認する', register: 'polite' },
      ],
      recognition: [
        { phrase: 'book / make an appointment', meaning: '予約を取る', note: '診察の予約を確保する表現です。' },
        { phrase: 'registered with us', meaning: '当院に登録されている', note: 'かかりつけの患者かを確認します。' },
        { phrase: 'date of birth', meaning: '生年月日', note: '本人確認でよく尋ねられます。' },
        { phrase: 'an opening', meaning: '空き枠', note: '予約を入れられる時間を表します。' },
        { phrase: 'That works for me.', meaning: 'それで都合がよい', note: '提案された日時を受ける自然な表現です。' },
      ],
    },
    availability: {
      title: '緊急の予約や空き状況の確認',
      enTitle: 'Urgent appointments and availability',
      intro: '今日すぐに診てもらいたいときや、希望する日時に空きがあるかを尋ねます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Do you have any appointments available today?', meaning: '今日、空いている予約枠はありますか？', context: '当日の空きを尋ねる', register: 'polite' },
        { phrase: 'Is it urgent?', meaning: 'お急ぎ（緊急）ですか？', context: '緊急度を確認する', register: 'polite' },
        { phrase: 'Yes, I really need to see someone today.', meaning: 'はい、どうしても今日誰かに診ていただく必要があります。', context: '当日受診の必要を伝える', register: 'urgent' },
        { phrase: "We're fully booked today, but we can fit you in tomorrow morning.", meaning: '今日は予約でいっぱいですが、明日の午前中ならなんとかお入れできます。', context: '満員でも時間を作る', register: 'helpful' },
        { phrase: 'No, it can wait. Next week is fine.', meaning: 'いいえ、急ぎません。来週で大丈夫です。', context: '急ぎではないと伝える', register: 'polite' },
        { phrase: 'What is the reason for the appointment?', meaning: '受診の理由は何ですか？', context: '予約理由を尋ねる', register: 'polite' },
        { phrase: 'The earliest appointment we have is on Monday.', meaning: '一番早い予約で月曜日になります。', context: '最短の空き日を伝える', register: 'helpful' },
        { phrase: "I can't make that. Is there anything else available?", meaning: 'その時間は都合がつきません。他に空いている時間はありますか？', context: '別の時間を尋ねる', register: 'polite' },
      ],
      recognition: [
        { phrase: 'available today', meaning: '今日利用できる・空いている', note: '当日の予約枠を確認します。' },
        { phrase: 'fully booked', meaning: '予約でいっぱい', note: '空きがない状態です。' },
        { phrase: 'fit you in', meaning: '何とか予約を入れる', note: 'いっぱいの予定に時間を作る表現です。' },
        { phrase: 'earliest appointment', meaning: '一番早い予約', note: '最短で受診できる枠を指します。' },
      ],
    },
    rearranging: {
      title: '予約の変更とキャンセル',
      enTitle: 'Rearranging and cancelling',
      intro: '予約をキャンセルしたり、別の日へ変更したり、経過観察の予約を入れたりします。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'I need to cancel my appointment for Tuesday.', meaning: '火曜日の予約をキャンセルしたいのですが。', context: '予約をキャンセルする', register: 'polite' },
        { phrase: 'Would you like to rearrange it?', meaning: '別の日に変更されますか？', context: '予約変更を提案する', register: 'polite' },
        { phrase: 'Yes, please. Can I book a double appointment?', meaning: 'はい、お願いします。2コマ分（長めの）予約を入れられますか？', context: '長めの予約を依頼する', register: 'polite' },
        { phrase: "I'd like to book a follow-up appointment.", meaning: '経過観察の予約（次回の予約）を入れたいのですが。', context: '次回の診察を予約する', register: 'polite' },
        { phrase: "I'm sorry, I have to reschedule my appointment.", meaning: 'すみません、予約を変更しなければなりません。', context: '予約変更を依頼する', register: 'polite' },
        { phrase: 'Can I book an appointment for my son?', meaning: '息子の代わりに予約を入れられますか？', context: '家族の予約を取る', register: 'polite' },
        { phrase: "What's his name and date of birth?", meaning: '彼の名前と生年月日はいつですか？', context: '家族の本人情報を確認する', register: 'polite' },
        { phrase: "I'll send you a text message with your appointment details.", meaning: '予約内容の詳細をテキストメッセージで送信しますね。', context: '予約詳細を送る', register: 'helpful' },
      ],
      recognition: [
        { phrase: 'rearrange / reschedule', meaning: '予約を変更する', note: '別の日や時間に予約を移します。' },
        { phrase: 'double appointment', meaning: '2コマ分の長めの予約', note: '通常より長い診察枠を指します。' },
        { phrase: 'follow-up appointment', meaning: '経過観察の予約', note: '診察後の次回予約です。' },
        { phrase: 'appointment details', meaning: '予約の詳細', note: '日時などの情報をまとめて表します。' },
      ],
    },
    dialogues: [
      {
        id: 'booking',
        label: 'Pattern A · Booking',
        title: '診察を予約して本人情報を確認する',
        lines: [
          { speaker: 'A', en: "Hello, I'd like to book an appointment with Dr Patel, please.", ja: 'パテル先生の診察予約をしたいのですが。' },
          { speaker: 'B', en: 'Are you registered with us?', ja: '当院に登録されていますか？' },
          { speaker: 'A', en: 'Yes, I am. My name is Hanan.', ja: 'はい、登録しています。名前はハナンです。' },
          { speaker: 'B', en: "What's your date of birth?", ja: '生年月日はいつですか？' },
        ],
      },
      {
        id: 'availability',
        label: 'Pattern B · Availability',
        title: '今日の空きと緊急度を相談する',
        lines: [
          { speaker: 'A', en: 'Do you have any appointments available today?', ja: '今日、空いている予約枠はありますか？' },
          { speaker: 'B', en: 'Is it urgent?', ja: 'お急ぎですか？' },
          { speaker: 'A', en: 'Yes, I really need to see someone today.', ja: 'はい、今日診ていただく必要があります。' },
          { speaker: 'B', en: "We're fully booked today, but we can fit you in tomorrow morning.", ja: '今日はいっぱいですが、明日の午前中なら何とか入れられます。' },
        ],
      },
      {
        id: 'rearranging',
        label: 'Pattern C · Rearranging',
        title: '予約を変更して次回の診察を取る',
        lines: [
          { speaker: 'A', en: 'I need to cancel my appointment for Tuesday.', ja: '火曜日の予約をキャンセルしたいのですが。' },
          { speaker: 'B', en: 'Would you like to rearrange it?', ja: '別の日に変更されますか？' },
          { speaker: 'A', en: 'Yes, please. Can I book a double appointment?', ja: 'はい、2コマ分の予約を取れますか？' },
          { speaker: 'B', en: "I'd like to book a follow-up appointment.", ja: '経過観察の予約を入れたいのですが。' },
        ],
      },
    ],
    tip: '予約では、患者情報、緊急度、希望日時を順番に伝えます。book と make、That works for me、fit you in、follow-up appointmentを使い分けましょう。',
    tips: [
      { title: 'book と make の違い', body: 'book an appointment と make an appointment はどちらも「予約を取る」です。book は予定を確保するニュアンスが少し強く、診察予約でよく使われます。' },
      { title: "イギリス英語の doctor's surgery", body: "イギリス英語では、かかりつけ医の診療所を doctor's surgery と呼ぶことがあります。アメリカ英語の doctor's office にあたります。" },
      { title: 'That works for me と fit you in', body: '提案された日時に都合がよいときは That works for me. と答えます。満員の予定に時間を作るときは fit you in を使います。' },
      { title: 'follow-up appointment', body: '診察後の経過観察の予約は follow-up appointment と言います。予約を変更する rearrange / reschedule と合わせて覚えましょう。' },
    ],
  },
  practice: {
    title: '診察の予約と変更を、英語で調整する',
    instructions: '日本語訳は見ずに、希望日時、緊急度、予約変更の表現を声に重ねます。',
    coreHeading: 'まずは、予約を取りたい一文から。',
    dialogueHeading: '予約、緊急枠、変更の場面で役を切り替える。',
    dialogueDescription: '診察を予約する、今日の空きと緊急度を相談する、予約を変更して次回枠を取る3つの場面を練習します。',
    finishTitle: '次に診察を予約するとき、希望日時か変更のお願いを英語でひとつ伝えてみましょう。',
    corePhrases: [
      { phrase: "Hello, I'd like to book an appointment with Dr Patel, please.", context: '医師の診察を予約する', rate: 0.7 },
      { phrase: 'Are you registered with us?', context: '患者登録を確認する', rate: 0.82 },
      { phrase: "What's your date of birth?", context: '生年月日を確認する', rate: 0.82 },
      { phrase: 'We have an opening on Thursday at 10am.', context: '空き時間を提案する', rate: 0.74 },
      { phrase: 'That works for me. Thank you.', context: '日時の提案を受ける', rate: 0.82 },
      { phrase: 'Do you have any appointments available today?', context: '今日の空きを尋ねる', rate: 0.72 },
      { phrase: 'Is it urgent?', context: '緊急度を確認する', rate: 0.82 },
      { phrase: 'Yes, I really need to see someone today.', context: '当日受診の必要を伝える', rate: 0.72 },
      { phrase: "We're fully booked today, but we can fit you in tomorrow morning.", context: '別の枠を提案する', rate: 0.68 },
      { phrase: 'I need to cancel my appointment for Tuesday.', context: '予約をキャンセルする', rate: 0.76 },
      { phrase: "I'm sorry, I have to reschedule my appointment.", context: '予約を変更する', rate: 0.74 },
      { phrase: "I'd like to book a follow-up appointment.", context: '次回予約を取る', rate: 0.78 },
    ],
    dialogues: [
      { title: 'Booking', lines: ["Hello, I'd like to book an appointment with Dr Patel, please.", 'Are you registered with us?', 'Yes, I am. My name is Hanan.', "What's your date of birth?"] },
      { title: 'Availability', lines: ['Do you have any appointments available today?', 'Is it urgent?', 'Yes, I really need to see someone today.', "We're fully booked today, but we can fit you in tomorrow morning."] },
      { title: 'Rearranging', lines: ['I need to cancel my appointment for Tuesday.', 'Would you like to rearrange it?', 'Yes, please. Can I book a double appointment?', "I'd like to book a follow-up appointment."] },
    ],
    natural: [
      { full: 'I would like to reserve a consultation with Dr Patel.', natural: "I'd like to book an appointment with Dr Patel, please." },
      { full: 'Is there an appointment slot open today?', natural: 'Do you have any appointments available today?' },
      { full: 'I need to move my appointment to another time.', natural: "I'm sorry, I have to reschedule my appointment." },
    ],
  },
}
