/** Chapter 77 · At the beach. */
export const beachLesson = {
  id: 'beach',
  kind: 'beach',
  number: '77',
  title: '第77章に入る前に：なぜ「ビーチで使う英語」を学ぶのでしょうか？',
  enTitle: 'At the beach',
  ja: 'ビーチでの安全確認、マリンアクティビティ、レンタルや買い物、海辺で使う基本的な表現を学びます。',
  cando: '海で安全に泳げるか確認し、アクティビティ・レンタル・買い物について必要な情報を尋ねられる。',
  learn: {
    intro: [
      'ビーチでは、楽しむことだけでなく、安全を確認したり、必要な道具を借りたり、アクティビティについて質問したりする場面があります。',
      '「何をしたいのか」「何が必要なのか」「安全に楽しめるか」をきちんと確認することが大切です。',
      'この章では、ビーチでの安全確認、マリンアクティビティ、レンタルや買い物、そして海辺で使う基本的な表現を学びます。',
    ],
    functions: [
      ['01', '泳ぐ場所と安全ルールを確認する'],
      ['02', '日陰や休憩場所を見つける'],
      ['03', 'マリンアクティビティを予約する'],
      ['04', '道具を借りたり買ったりする'],
    ],
    safety: {
      title: 'ビーチへの到着と安全確認',
      enTitle: 'Arriving at the beach & safety',
      intro: 'ビーチに着いた気持ちを伝え、日陰や安全に泳げる区域を確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "Wow, I can't wait to go swimming!", meaning: 'わあ、泳ぎに行くのが待ちきれないよ！', context: '楽しみを伝える', register: 'casual' },
        { phrase: "There's a nice shady spot just over there.", meaning: 'ちょうどあそこに、いい日陰がありますよ。', context: '休憩場所を見つける', register: 'friendly' },
        { phrase: 'Is it safe to swim today?', meaning: '今日は泳いでも安全ですか？', context: '安全を確認する', register: 'polite' },
        { phrase: 'Yes, but you must stay between the flags.', meaning: 'はい、でも旗の間にとどまらなければいけません。', context: '安全ルールを案内する', register: 'firm' },
      ],
      recognition: [
        { phrase: "can't wait to", meaning: '〜するのが待ちきれない', note: '楽しみでたまらない気持ちを表す口語です。' },
        { phrase: 'shady spot', meaning: '日陰の場所', note: '休憩や日差しを避ける場所です。' },
        { phrase: 'safe to swim', meaning: '泳いでも安全', note: '波や監視状況を確認するときに使います。' },
        { phrase: 'between the flags', meaning: '旗の間で', note: 'ライフガードが示す安全区域です。' },
      ],
    },
    activities: {
      title: 'マリンアクティビティとレンタル・購入',
      enTitle: 'Beach activities',
      intro: 'サーフィン、ペダロ、ウェットスーツ、ボディボード、砂遊び用品について尋ねます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Do you do surfing lessons?', meaning: 'サーフィンのレッスンは行っていますか？', context: 'レッスンを尋ねる', register: 'polite' },
        { phrase: 'Can we hire a pedalo here?', meaning: 'ここでペダロ（足漕ぎボート）を借りることはできますか？', context: 'ボートをレンタルする', register: 'polite' },
        { phrase: "Do you sell children's wet suits?", meaning: '子供用のウェットスーツは販売していますか？', context: '商品を尋ねる', register: 'polite' },
        { phrase: 'How much is a bodyboard for the day?', meaning: 'ボディボードは1日いくらですか？', context: 'レンタル料金を尋ねる', register: 'polite' },
        { phrase: 'Where can we buy a bucket and spade?', meaning: 'バケツとシャベルはどこで買えますか？', context: '砂遊び用品を探す', register: 'polite' },
      ],
      recognition: [
        { phrase: 'surfing lessons', meaning: 'サーフィンのレッスン', note: '初心者向けの講習を含みます。' },
        { phrase: 'hire', meaning: '有料で借りる', note: 'イギリス英語でレンタルを表します。' },
        { phrase: 'for the day', meaning: '1日分・その日の間', note: 'レンタル料金の期間を尋ねる表現です。' },
        { phrase: 'a bucket and spade', meaning: 'バケツとシャベルのセット', note: '砂遊びの定番の組み合わせです。' },
      ],
    },
    vocab: {
      title: 'ビーチに関するボキャブラリー',
      enTitle: 'Vocabulary at the beach',
      intro: '海のアクティビティ、休憩、安全、砂遊びに関する基本語彙をまとめます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'wet suit', meaning: 'ウェットスーツ', context: '水上スポーツ', register: 'neutral' },
        { phrase: 'bodyboard', meaning: 'ボディボード', context: '水上スポーツ', register: 'neutral' },
        { phrase: 'paddleboard', meaning: 'パドルボード・SUP用ボード', context: '水上スポーツ', register: 'neutral' },
        { phrase: 'pedalo', meaning: 'ペダロ・足漕ぎボート', context: 'レンタル', register: 'regional' },
        { phrase: 'flag', meaning: '旗・安全区域を示すフラッグ', context: '安全', register: 'neutral' },
        { phrase: 'lifeguard', meaning: 'ライフガード・監視員', context: '安全', register: 'neutral' },
        { phrase: 'surfboard', meaning: 'サーフボード', context: '水上スポーツ', register: 'neutral' },
        { phrase: 'beach ball', meaning: 'ビーチボール', context: '遊び', register: 'neutral' },
        { phrase: 'deck chair', meaning: 'デッキチェア', context: '休憩', register: 'neutral' },
        { phrase: 'sun lounger', meaning: 'サンラウンジャー・寝椅子', context: '休憩', register: 'regional' },
        { phrase: 'spade', meaning: 'シャベル・砂遊び用の小型シャベル', context: '砂遊び', register: 'regional' },
        { phrase: 'bucket', meaning: 'バケツ', context: '砂遊び', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'lifeguard', meaning: '監視員', note: '海の安全を見守る人です。' },
        { phrase: 'sun lounger', meaning: '寝椅子', note: 'イギリス英語でよく使われる表現です。' },
        { phrase: 'spade', meaning: 'シャベル', note: 'ビーチの砂遊びでは bucket とセットで使います。' },
        { phrase: 'pedalo', meaning: '足漕ぎボート', note: 'イギリスやヨーロッパでよく見かけます。' },
      ],
    },
    dialogues: [
      {
        id: 'safety',
        label: 'Pattern A · Arriving at the beach',
        title: '泳ぐ場所と日陰を確認する',
        lines: [
          { speaker: 'A', en: "Wow, I can't wait to go swimming!", ja: 'わあ、泳ぎに行くのが待ちきれないよ！' },
          { speaker: 'B', en: "There's a nice shady spot just over there.", ja: 'ちょうどあそこに、いい日陰があるよ。' },
          { speaker: 'A', en: 'Is it safe to swim today?', ja: '今日は泳いでも安全ですか？' },
          { speaker: 'B', en: 'Yes, but you must stay between the flags.', ja: 'はい、でも旗の間にとどまらなければいけません。' },
        ],
      },
      {
        id: 'activities',
        label: 'Pattern B · Beach activities',
        title: 'マリンアクティビティを借りる',
        lines: [
          { speaker: 'A', en: 'Do you do surfing lessons?', ja: 'サーフィンのレッスンは行っていますか？' },
          { speaker: 'B', en: 'Yes, and you can hire a pedalo here, too.', ja: 'はい、ここではペダロも借りられます。' },
          { speaker: 'A', en: 'How much is a bodyboard for the day?', ja: 'ボディボードは1日いくらですか？' },
          { speaker: 'B', en: 'It is £15, including a wet suit.', ja: 'ウェットスーツ込みで15ポンドです。' },
        ],
      },
      {
        id: 'shopping',
        label: 'Pattern C · Beach shopping',
        title: '砂遊び用品を探す',
        lines: [
          { speaker: 'A', en: 'Do you sell children\'s wet suits?', ja: '子供用のウェットスーツは販売していますか？' },
          { speaker: 'B', en: 'Yes, they are next to the beach balls.', ja: 'はい、ビーチボールの隣にあります。' },
          { speaker: 'A', en: 'Where can we buy a bucket and spade?', ja: 'バケツとシャベルはどこで買えますか？' },
          { speaker: 'B', en: 'The beach shop is by the pier.', ja: 'ビーチショップは桟橋のそばです。' },
        ],
      },
    ],
    tip: "can't wait to は楽しみで待ちきれない気持ち、spade はイギリス英語のシャベル、pedalo は足漕ぎボートを表します。between the flags はライフガードが示す安全な遊泳区域にいることを表す大切なルールです。",
  },
  practice: {
    title: 'ビーチで安全と希望を、英語で確認する',
    instructions: '日本語訳は見ずに、安全確認、アクティビティ、レンタル、買い物の表現を声に重ねます。',
    coreHeading: 'まずは、ビーチで尋ねる一文から。',
    dialogueHeading: '安全、アクティビティ、買い物の場面で役を切り替える。',
    dialogueDescription: '泳ぐ場所と日陰を確認する、マリンアクティビティを借りる、砂遊び用品を探す3つの場面を練習します。',
    finishTitle: '次にビーチへ行くとき、安全か必要な道具について英語でひとつ尋ねてみましょう。',
    corePhrases: [
      { phrase: "I can't wait to go swimming!", context: '楽しみを伝える', rate: 0.84 },
      { phrase: "There's a nice shady spot just over there.", context: '日陰を見つける', rate: 0.78 },
      { phrase: 'Is it safe to swim today?', context: '安全を尋ねる', rate: 0.84 },
      { phrase: 'You must stay between the flags.', context: '安全ルールを伝える', rate: 0.82 },
      { phrase: 'Do you do surfing lessons?', context: 'レッスンを尋ねる', rate: 0.82 },
      { phrase: 'Can we hire a pedalo here?', context: 'ボートを借りる', rate: 0.8 },
      { phrase: "Do you sell children's wet suits?", context: '商品を尋ねる', rate: 0.78 },
      { phrase: 'How much is a bodyboard for the day?', context: 'レンタル料金を尋ねる', rate: 0.76 },
      { phrase: 'Where can we buy a bucket and spade?', context: '砂遊び用品を探す', rate: 0.76 },
      { phrase: 'lifeguard', context: '監視員の語彙', rate: 0.88 },
      { phrase: 'sun lounger', context: '寝椅子の語彙', rate: 0.84 },
      { phrase: 'paddleboard', context: 'パドルボードの語彙', rate: 0.82 },
    ],
    dialogues: [
      { title: 'Arriving at the beach', lines: ["Wow, I can't wait to go swimming!", "There's a nice shady spot just over there.", 'Is it safe to swim today?', 'Yes, but you must stay between the flags.'] },
      { title: 'Beach activities', lines: ['Do you do surfing lessons?', 'Yes, and you can hire a pedalo here, too.', 'How much is a bodyboard for the day?', 'It is £15, including a wet suit.'] },
      { title: 'Beach shopping', lines: ["Do you sell children's wet suits?", 'Yes, they are next to the beach balls.', 'Where can we buy a bucket and spade?', 'The beach shop is by the pier.'] },
    ],
    natural: [
      { full: 'I am extremely excited about going for a swim.', natural: "I can't wait to go swimming!" },
      { full: 'Could you tell us whether swimming is safe today?', natural: 'Is it safe to swim today?' },
      { full: 'What is the cost of renting a bodyboard for one day?', natural: 'How much is a bodyboard for the day?' },
    ],
  },
}
