/** Chapter 73 · Booking a holiday. */
export const bookingHolidayLesson = {
  id: 'booking-holiday',
  kind: 'booking-holiday',
  number: '73',
  title: '第73章に入る前に：なぜ「旅行の予約で使う英語」を学ぶのでしょうか？',
  enTitle: 'Booking a holiday',
  ja: '旅行プランの相談や予約、設備やキャンセル条件についての質問、さまざまな旅行スタイルに関する表現を学びます。',
  cando: '希望する旅行スタイルを伝え、料金・食事・設備・キャンセル条件などを予約前に確認できる。',
  learn: {
    intro: [
      '旅行を予約するときは、ただ行き先を決めるだけではありません。どんな旅をしたいのか、何が含まれているのか、料金や条件はどうなっているのかを確認する必要があります。',
      '自分の希望を伝え、予約する前に必要な条件をきちんと確認することが大切です。',
      'この章では、旅行プランの相談や予約、設備やキャンセル条件についての質問、そしてさまざまな旅行スタイルに関する表現を学びます。',
    ],
    functions: [
      ['01', '希望する旅行スタイルを伝える'],
      ['02', '食事・設備・割引を確認する'],
      ['03', 'キャンセルやビザの条件を尋ねる'],
      ['04', '内容に納得して予約を決める'],
    ],
    agent: {
      title: '旅行代理店での会話',
      enTitle: 'Talking to the travel agent',
      intro: 'エージェントに希望を伝え、プランの内容、食事、評価、割引を見ながら予約を決めます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'So what kind of thing are you looking for?', meaning: '具体的にどのような旅をご希望ですか？', context: '希望を尋ねる', register: 'friendly' },
        { phrase: 'I was thinking about a safari. What do you offer?', meaning: 'サファリ旅行を考えています。どのようなプランがありますか？', context: '希望を伝える', register: 'polite' },
        { phrase: 'I saw a cruise on your website. Is it all-inclusive?', meaning: 'ウェブサイトでクルーズ旅行を見ました。オールインクルーシブですか？', context: 'プラン内容を尋ねる', register: 'polite' },
        { phrase: 'Yes, it offers full board, entertainment, and activities.', meaning: 'はい、全食事、エンターテインメント、各種アクティビティが含まれています。', context: '含まれるものを説明する', register: 'neutral' },
        { phrase: 'This spa break looks amazing...', meaning: 'このスパ休暇プラン、とても良さそうですね。', context: 'プランの感想を言う', register: 'casual' },
        { phrase: "It's got five-star reviews...", meaning: '星5つのレビューを獲得していますね。', context: '評価を確認する', register: 'casual' },
        { phrase: 'Adults only...', meaning: '大人専用ですね。', context: '対象者を確認する', register: 'neutral' },
        { phrase: '20% discount...', meaning: '20%割引ですね。', context: '割引を確認する', register: 'neutral' },
        { phrase: "Sounds ideal. Let's book it!", meaning: '理想的ですね。予約しましょう！', context: '予約を決める', register: 'enthusiastic' },
      ],
      recognition: [
        { phrase: 'what kind of thing', meaning: 'どのようなもの・旅', note: '希望を柔らかく尋ねる表現です。' },
        { phrase: 'all-inclusive', meaning: 'すべて込みの', note: '食事や活動料金などが含まれるプランです。' },
        { phrase: 'full board', meaning: '3食付き', note: '朝・昼・夕食が含まれます。' },
        { phrase: 'five-star reviews', meaning: '星5つのレビュー', note: '高評価の口コミを表します。' },
      ],
    },
    questions: {
      title: '予約時の具体的な質問',
      enTitle: 'More questions to ask',
      intro: '設備、キャンセル、ビザ、子ども、盲導犬など、予約を確定する前に確認します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'What facilities are there?', meaning: 'どのような設備がありますか？', context: '設備を尋ねる', register: 'polite' },
        { phrase: "What's your cancellation policy?", meaning: 'キャンセル規定はどうなっていますか？', context: 'キャンセル条件を尋ねる', register: 'polite' },
        { phrase: 'Do I need a visa?', meaning: 'ビザは必要ですか？', context: '入国条件を尋ねる', register: 'polite' },
        { phrase: 'Is it suitable for young children?', meaning: '小さな子供連れに適していますか？', context: '家族向けか尋ねる', register: 'polite' },
        { phrase: 'Can I bring my guide dog?', meaning: '盲導犬を同伴できますか？', context: '補助犬の同伴を尋ねる', register: 'polite' },
      ],
      recognition: [
        { phrase: 'facilities', meaning: '設備・施設', note: 'プールやジムなどをまとめて尋ねます。' },
        { phrase: 'cancellation policy', meaning: 'キャンセル規定', note: '返金や期限などの条件です。' },
        { phrase: 'suitable for', meaning: '〜に適している', note: '子ども連れなどの条件を確認します。' },
        { phrase: 'guide dog', meaning: '盲導犬', note: '宿泊やツアーへの同伴条件を尋ねます。' },
      ],
    },
    types: {
      title: '旅行のスタイル',
      enTitle: 'Types of holiday',
      intro: '過ごし方や行き先に合わせて、旅行プランの種類を選びます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'beach holiday', meaning: 'ビーチリゾートでの休暇', context: '旅行スタイル', register: 'neutral' },
        { phrase: 'city break', meaning: '都市への短期旅行', context: '旅行スタイル', register: 'regional' },
        { phrase: 'spa break', meaning: 'スパでのリフレッシュ休暇', context: '旅行スタイル', register: 'regional' },
        { phrase: 'winter sports holiday', meaning: 'ウィンタースポーツの休暇', context: '旅行スタイル', register: 'neutral' },
        { phrase: 'camper van holiday', meaning: 'キャンピングカー旅行', context: '旅行スタイル', register: 'neutral' },
        { phrase: 'camping trip', meaning: 'キャンプ旅行', context: '旅行スタイル', register: 'neutral' },
        { phrase: 'hiking tour', meaning: 'ハイキングツアー', context: '旅行スタイル', register: 'neutral' },
        { phrase: 'cruise', meaning: 'クルーズ船の旅', context: '旅行スタイル', register: 'neutral' },
        { phrase: 'safari', meaning: 'サファリツアー', context: '旅行スタイル', register: 'neutral' },
        { phrase: 'all-inclusive', meaning: 'オールインクルーシブプラン', context: '料金プラン', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'city break', meaning: '都市への短期旅行', note: '週末や数日間の旅行です。' },
        { phrase: 'spa break', meaning: 'スパ休暇', note: '温浴やマッサージで休む旅行です。' },
        { phrase: 'camper van holiday', meaning: 'キャンピングカー旅行', note: '移動しながら泊まるスタイルです。' },
        { phrase: 'all-inclusive', meaning: '料金に多くのものが含まれる', note: 'クルーズやリゾートでよく見かけます。' },
      ],
    },
    terms: {
      title: '予約プランのキーワード',
      enTitle: 'Booking terms',
      intro: 'パンフレットやウェブサイトで、食事、評価、割引、対象者を確認する単語です。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'all-inclusive', meaning: 'オールインクルーシブ・すべて込み', context: '料金プラン', register: 'neutral' },
        { phrase: 'full board', meaning: '3食付き', context: '食事プラン', register: 'regional' },
        { phrase: 'half board', meaning: '2食付き', context: '食事プラン', register: 'regional' },
        { phrase: 'five-star reviews', meaning: '星5つのレビュー', context: '評価', register: 'neutral' },
        { phrase: 'adults only', meaning: '大人専用', context: '対象者', register: 'neutral' },
        { phrase: '20% discount', meaning: '20%割引', context: '料金', register: 'neutral' },
        { phrase: 'cancellation policy', meaning: 'キャンセル規定', context: '条件', register: 'neutral' },
        { phrase: 'facilities', meaning: '設備・施設', context: '設備', register: 'neutral' },
        { phrase: 'visa', meaning: 'ビザ', context: '入国条件', register: 'neutral' },
        { phrase: 'guide dog', meaning: '盲導犬', context: '同行者・サポート', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'full board / half board', meaning: '3食付き / 2食付き', note: '食事の含まれる回数を表します。' },
        { phrase: 'adults only', meaning: '大人専用', note: '子どもは利用できないプランです。' },
        { phrase: 'discount', meaning: '割引', note: '料金が通常より安くなることです。' },
        { phrase: 'cancellation policy', meaning: 'キャンセル規定', note: '予約前に確認したい重要語です。' },
      ],
    },
    dialogues: [
      {
        id: 'agent',
        label: 'Pattern A · Talking to the travel agent',
        title: '旅行の希望とプラン内容を相談する',
        lines: [
          { speaker: 'A', en: 'So what kind of thing are you looking for?', ja: 'どのような旅をご希望ですか？' },
          { speaker: 'B', en: 'I was thinking about a safari. What do you offer?', ja: 'サファリ旅行を考えています。どんなプランがありますか？' },
          { speaker: 'A', en: 'I saw a cruise on your website. Is it all-inclusive?', ja: 'ウェブサイトでクルーズを見ました。すべて込みですか？' },
          { speaker: 'B', en: 'Yes, it offers full board, entertainment, and activities.', ja: 'はい、全食事、エンターテインメント、活動が含まれます。' },
        ],
      },
      {
        id: 'questions',
        label: 'Pattern B · Questions before booking',
        title: '設備と条件を予約前に確認する',
        lines: [
          { speaker: 'A', en: 'What facilities are there?', ja: 'どのような設備がありますか？' },
          { speaker: 'B', en: 'There is a pool, a gym, and free Wi-Fi.', ja: 'プール、ジム、無料Wi-Fiがあります。' },
          { speaker: 'A', en: "What's your cancellation policy?", ja: 'キャンセル規定はどうなっていますか？' },
          { speaker: 'B', en: 'You can cancel up to 14 days before departure.', ja: '出発の14日前までキャンセルできます。' },
        ],
      },
      {
        id: 'decision',
        label: 'Pattern C · Choosing a holiday',
        title: 'レビューと割引を見て予約を決める',
        lines: [
          { speaker: 'A', en: 'This spa break looks amazing...', ja: 'このスパ休暇、とても良さそうです。' },
          { speaker: 'B', en: "It's got five-star reviews...", ja: '星5つのレビューがありますね。' },
          { speaker: 'A', en: 'Adults only... 20% discount...', ja: '大人専用で、20%割引ですね。' },
          { speaker: 'B', en: "Sounds ideal. Let's book it!", ja: '理想的ですね。予約しましょう！' },
        ],
      },
    ],
    tip: 'all-inclusive は食事や活動などが料金に含まれるプラン、full board は3食付き、half board は通常2食付きです。city break は短い都市旅行、spa break はリラクゼーション休暇を表します。',
  },
  practice: {
    title: '旅行プランの条件を、英語で確認して予約する',
    instructions: '日本語訳は見ずに、希望、料金、設備、キャンセル条件、旅行スタイルの表現を声に重ねます。',
    coreHeading: 'まずは、どんな旅を探しているか伝える一文から。',
    dialogueHeading: '代理店相談、条件確認、予約決定の場面で役を切り替える。',
    dialogueDescription: '旅行の希望と内容を相談する、設備とキャンセル条件を確認する、レビューと割引を見て予約する3つの場面を練習します。',
    finishTitle: '次に旅行を予約するとき、条件を尋ねる英語をひとつ使ってみましょう。',
    corePhrases: [
      { phrase: 'So what kind of thing are you looking for?', context: '希望を尋ねる', rate: 0.76 },
      { phrase: 'I was thinking about a safari. What do you offer?', context: '希望を伝える', rate: 0.72 },
      { phrase: 'I saw a cruise on your website. Is it all-inclusive?', context: 'プラン内容を尋ねる', rate: 0.72 },
      { phrase: 'Yes, it offers full board, entertainment, and activities.', context: '含まれるものを説明する', rate: 0.7 },
      { phrase: 'This spa break looks amazing...', context: 'プランの感想を言う', rate: 0.82 },
      { phrase: "It's got five-star reviews...", context: '評価を確認する', rate: 0.8 },
      { phrase: '20% discount...', context: '割引を確認する', rate: 0.86 },
      { phrase: "Sounds ideal. Let's book it!", context: '予約を決める', rate: 0.8 },
      { phrase: 'What facilities are there?', context: '設備を尋ねる', rate: 0.82 },
      { phrase: "What's your cancellation policy?", context: 'キャンセル条件を尋ねる', rate: 0.78 },
      { phrase: 'Do I need a visa?', context: 'ビザを尋ねる', rate: 0.86 },
      { phrase: 'Can I bring my guide dog?', context: '盲導犬の同伴を尋ねる', rate: 0.8 },
    ],
    dialogues: [
      { title: 'Talking to the travel agent', lines: ['So what kind of thing are you looking for?', 'I was thinking about a safari. What do you offer?', 'I saw a cruise on your website. Is it all-inclusive?', 'Yes, it offers full board, entertainment, and activities.'] },
      { title: 'Questions before booking', lines: ['What facilities are there?', 'There is a pool, a gym, and free Wi-Fi.', "What's your cancellation policy?", 'You can cancel up to 14 days before departure.'] },
      { title: 'Choosing a holiday', lines: ['This spa break looks amazing...', "It's got five-star reviews...", 'Adults only... 20% discount...', "Sounds ideal. Let's book it!"] },
    ],
    natural: [
      { full: 'What sort of holiday package are you searching for?', natural: 'So what kind of thing are you looking for?' },
      { full: 'Does the price include all meals, entertainment, and activities?', natural: 'Is it all-inclusive?' },
      { full: 'Could you explain the rules for cancelling this booking?', natural: "What's your cancellation policy?" },
    ],
  },
}
