/** Chapter 66 · Buses and coaches. */
export const busesCoachesLesson = {
  id: 'buses-coaches',
  kind: 'buses-coaches',
  number: '66',
  title: '第66章に入る前に：なぜ「バスで使う英語」を学ぶのでしょうか？',
  enTitle: 'Buses and coaches',
  ja: 'バスや長距離バスの乗り方、チケット、目的地・時間の確認、車内設備について話す英語を学びます。',
  cando: 'バスの行き先、停留所、運賃、時刻、車内設備を確認し、目的地まで安心して移動できる。',
  learn: {
    intro: [
      'バスを利用するときは、ただ乗るだけではなく、行き先や停留所、運賃、時間などを自分で確認する必要があります。',
      '特に知らない土地では、このバスで合っているか、どこで降りるか、いつ着くかを質問できると移動の不安が大きく減ります。',
      'この章では、バスや長距離バスの乗り方、チケットの購入、目的地や時間の確認、そして車内で使う表現を学びます。',
    ],
    functions: [
      ['01', '行き先と経由地を確認する'],
      ['02', '切符と運賃を尋ねる'],
      ['03', '降りる停留所と時間を確認する'],
      ['04', '長距離バスの設備を尋ねる'],
    ],
    gettingBus: {
      title: 'バスに乗る',
      enTitle: 'Getting the bus',
      intro: '路線バスの行き先、経由地、切符、タッチ決済、降車場所を確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Does this bus go to the town centre?', meaning: 'このバスはタウンセンターに行きますか？', context: '行き先を確認する', register: 'neutral' },
        { phrase: 'Yes, via the train station.', meaning: 'はい、駅経由で行きます。', context: '経由地を伝える', register: 'neutral' },
        { phrase: 'Can I have a single to the museum, please?', meaning: '美術館までの片道切符を1枚ください。', context: '片道切符を買う', register: 'polite' },
        { phrase: "That'll be £3.", meaning: '3ポンドになります。', context: '運賃を伝える', register: 'neutral' },
        { phrase: "Thanks. I'll pay by contactless.", meaning: 'ありがとう。タッチ決済で払います。', context: '支払い方法を伝える', register: 'polite' },
        { phrase: 'Are we nearly at the library?', meaning: 'もうすぐ図書館に着きますか？', context: '目的地への距離を尋ねる', register: 'casual' },
        { phrase: "We're almost there - it's the next stop.", meaning: 'ほぼ到着しています。次の停留所です。', context: '降車場所を伝える', register: 'casual' },
      ],
      recognition: [
        { phrase: 'go to', meaning: '〜へ行く', note: 'バスの行き先を尋ねる基本表現です。' },
        { phrase: 'via', meaning: '〜経由で', note: '途中で通る場所を示します。' },
        { phrase: 'a single to', meaning: '〜までの片道切符', note: '目的地を続けて伝えます。' },
        { phrase: 'contactless', meaning: 'タッチ決済', note: 'カードやスマホをかざす支払いです。' },
      ],
    },
    questions: {
      title: 'バスに関する質問',
      enTitle: 'More questions',
      intro: '最寄りの停留所、正しい乗り場、運賃、次の便と最終便を尋ねます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Where is the nearest bus stop?', meaning: '最寄りのバス停はどこですか？', context: '停留所を尋ねる', register: 'polite' },
        { phrase: 'Is this the right stop for the airport bus?', meaning: 'これは空港行きのバスの正しい停留所ですか？', context: '乗り場が合っているか確認する', register: 'polite' },
        { phrase: 'How much is the fare?', meaning: '運賃はいくらですか？', context: '料金を尋ねる', register: 'polite' },
        { phrase: 'Are you stopping at the shopping centre?', meaning: 'ショッピングセンターに止まりますか？', context: '停車場所を尋ねる', register: 'polite' },
        { phrase: 'What time is the next bus?', meaning: '次のバスは何時ですか？', context: '次の便を尋ねる', register: 'polite' },
        { phrase: 'What time is the last bus from this stop?', meaning: 'この停留所からの最終バスは何時ですか？', context: '最終便を尋ねる', register: 'polite' },
      ],
      recognition: [
        { phrase: 'nearest bus stop', meaning: '最寄りのバス停', note: 'nearest は「最も近い」です。' },
        { phrase: 'right stop for', meaning: '〜に合った停留所', note: '目的地に行く乗り場か確認します。' },
        { phrase: 'fare', meaning: '運賃', note: 'bus fare のように使います。' },
        { phrase: 'last bus', meaning: '最終バス', note: '帰りの時間を確認するときに重要です。' },
      ],
    },
    coach: {
      title: '長距離バスの旅',
      enTitle: 'Coach journeys',
      intro: '長距離バスのチケット、到着時刻、トイレ、Wi-Fiなどの車内設備を確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Could I see your ticket, please?', meaning: 'チケットを見せていただけますか？', context: 'チケットを確認する', register: 'polite' },
        { phrase: 'Here you go.', meaning: 'はい、どうぞ。', context: 'チケットを渡す', register: 'casual' },
        { phrase: 'Lovely. We arrive in Cardiff at 16.45.', meaning: '結構です。カーディフには16時45分に到着します。', context: '到着時刻を伝える', register: 'regional' },
        { phrase: 'Hello, are there toilets on the coach?', meaning: '長距離バスの中にトイレはありますか？', context: '設備を尋ねる', register: 'polite' },
        { phrase: "Yes, they're right at the back.", meaning: 'はい、一番後ろにあります。', context: '場所を案内する', register: 'neutral' },
        { phrase: 'And is there Wi-Fi on board?', meaning: 'あと、車内にWi-Fiはありますか？', context: '車内サービスを尋ねる', register: 'polite' },
        { phrase: 'Yup, just log on to our network.', meaning: 'ええ、ネットワークにログインするだけです。', context: '接続方法を伝える', register: 'casual' },
      ],
      recognition: [
        { phrase: 'coach', meaning: '長距離バス・観光バス', note: '街中の bus と区別します。' },
        { phrase: 'right at the back', meaning: 'ちょうど一番後ろ', note: '車内の奥の場所を指します。' },
        { phrase: 'on board', meaning: '車内・機内に', note: 'coach や plane の中を表します。' },
        { phrase: 'log on to', meaning: '〜にログインする', note: 'Wi-Fiネットワークへの接続に使います。' },
      ],
    },
    vocabulary: {
      title: 'バスとコーチのボキャブラリー',
      enTitle: 'Vocabulary · Buses & coaches',
      intro: '路線バスと長距離バス、停留所、運賃、車内設備を表す言葉を整理します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'bus', meaning: '路線バス', context: '市内交通', register: 'neutral' },
        { phrase: 'coach', meaning: '長距離バス・観光バス', context: '都市間交通', register: 'regional' },
        { phrase: 'bus stop', meaning: 'バス停', context: '乗り場', register: 'neutral' },
        { phrase: 'fare', meaning: '運賃', context: '料金', register: 'neutral' },
        { phrase: 'single', meaning: '片道切符', context: 'チケット', register: 'regional' },
        { phrase: 'return', meaning: '往復切符', context: 'チケット', register: 'regional' },
        { phrase: 'contactless', meaning: 'タッチ決済', context: '支払い', register: 'regional' },
        { phrase: 'on board', meaning: '車内・機内に', context: '車内設備', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'bus vs coach', meaning: '路線バスと長距離バス', note: 'coach は予約制で設備があることが多い長距離移動です。' },
        { phrase: 'a single / a return', meaning: '片道 / 往復', note: 'イギリス英語のチケット表現です。' },
        { phrase: 'contactless', meaning: 'タッチ決済', note: '現金を使わずカードやスマホで支払います。' },
        { phrase: 'via', meaning: '〜経由で', note: 'ルートを説明する短い語です。' },
      ],
    },
    dialogues: [
      {
        id: 'getting-bus',
        label: 'Pattern A · Getting the bus',
        title: '行き先と運賃を確認して乗る',
        lines: [
          { speaker: 'A', en: 'Does this bus go to the town centre?', ja: 'このバスはタウンセンターに行きますか？' },
          { speaker: 'B', en: 'Yes, via the train station.', ja: 'はい、駅経由で行きます。' },
          { speaker: 'A', en: 'Can I have a single to the museum, please?', ja: '美術館までの片道切符を1枚ください。' },
          { speaker: 'B', en: "Thanks. I'll pay by contactless.", ja: 'ありがとう。タッチ決済で払います。' },
        ],
      },
      {
        id: 'questions',
        label: 'Pattern B · More questions',
        title: '停留所と時間を尋ねる',
        lines: [
          { speaker: 'A', en: 'Where is the nearest bus stop?', ja: '最寄りのバス停はどこですか？' },
          { speaker: 'B', en: 'Is this the right stop for the airport bus?', ja: 'これは空港行きのバスの正しい停留所ですか？' },
          { speaker: 'A', en: 'What time is the next bus?', ja: '次のバスは何時ですか？' },
          { speaker: 'B', en: 'What time is the last bus from this stop?', ja: 'この停留所からの最終バスは何時ですか？' },
        ],
      },
      {
        id: 'coach',
        label: 'Pattern C · Coach journeys',
        title: '長距離バスの設備を確認する',
        lines: [
          { speaker: 'A', en: 'Hello, are there toilets on the coach?', ja: '長距離バスの中にトイレはありますか？' },
          { speaker: 'B', en: "Yes, they're right at the back.", ja: 'はい、一番後ろにあります。' },
          { speaker: 'A', en: 'And is there Wi-Fi on board?', ja: 'あと、車内にWi-Fiはありますか？' },
          { speaker: 'B', en: 'Yup, just log on to our network.', ja: 'ええ、ネットワークにログインするだけです。' },
        ],
      },
    ],
    tip: '街中の路線バスは bus、都市間の長距離バスは coach と呼びます。片道は a single、往復は a return、タッチ決済は contactless です。via は経由地、on board は車内を表します。',
  },
  practice: {
    title: 'バスの行き先と時間を、英語で安心して確認する',
    instructions: '日本語訳は見ずに、行き先、運賃、停留所、長距離バスの設備を声に重ねます。',
    coreHeading: 'まずは、このバスで合っているか尋ねる一文から。',
    dialogueHeading: '路線バス、質問、長距離バスの場面で役を切り替える。',
    dialogueDescription: '行き先と運賃を確認する、停留所と時刻を尋ねる、車内設備を確認する3つの場面を練習します。',
    finishTitle: '次にバスに乗るとき、行き先か降車場所を英語でひとつ確認してみましょう。',
    corePhrases: [
      { phrase: 'Does this bus go to the town centre?', context: '行き先を確認する', rate: 0.78 },
      { phrase: 'Yes, via the train station.', context: '経由地を伝える', rate: 0.82 },
      { phrase: 'Can I have a single to the museum, please?', context: '片道切符を買う', rate: 0.76 },
      { phrase: "I'll pay by contactless.", context: 'タッチ決済を伝える', rate: 0.8 },
      { phrase: 'Are we nearly at the library?', context: '目的地への距離を尋ねる', rate: 0.8 },
      { phrase: "We're almost there - it's the next stop.", context: '降車場所を伝える', rate: 0.76 },
      { phrase: 'Where is the nearest bus stop?', context: '停留所を尋ねる', rate: 0.82 },
      { phrase: 'How much is the fare?', context: '運賃を尋ねる', rate: 0.84 },
      { phrase: 'What time is the next bus?', context: '次の便を尋ねる', rate: 0.84 },
      { phrase: 'Could I see your ticket, please?', context: 'チケットを確認する', rate: 0.8 },
      { phrase: 'Are there toilets on the coach?', context: '車内設備を尋ねる', rate: 0.8 },
      { phrase: 'Is there Wi-Fi on board?', context: '車内Wi-Fiを尋ねる', rate: 0.82 },
    ],
    dialogues: [
      { title: 'Getting the bus', lines: ['Does this bus go to the town centre?', 'Yes, via the train station.', 'Can I have a single to the museum, please?', "Thanks. I'll pay by contactless."] },
      { title: 'More questions', lines: ['Where is the nearest bus stop?', 'Is this the right stop for the airport bus?', 'What time is the next bus?', 'What time is the last bus from this stop?'] },
      { title: 'Coach journeys', lines: ['Hello, are there toilets on the coach?', "Yes, they're right at the back.", 'And is there Wi-Fi on board?', 'Yup, just log on to our network.'] },
    ],
    natural: [
      { full: 'Does this vehicle travel to the central area of town?', natural: 'Does this bus go to the town centre?' },
      { full: 'Could I purchase one one-way ticket to the museum?', natural: 'Can I have a single to the museum, please?' },
      { full: 'Are there bathroom facilities inside the long-distance bus?', natural: 'Are there toilets on the coach?' },
    ],
  },
}
