/** Chapter 76 · Going camping. */
export const campingLesson = {
  id: 'camping',
  kind: 'camping',
  number: '76',
  title: '第76章に入る前に：なぜ「キャンプで使う英語」を学ぶのでしょうか？',
  enTitle: 'Going camping',
  ja: 'キャンプ場での受付、場所やルールの確認、売店でのやり取り、キャンプ用品に関する表現を学びます。',
  cando: 'キャンプ場で予約や区画、設備、ルールを確認し、売店で必要な用品を頼める。',
  learn: {
    intro: [
      'キャンプでは、ホテルのようにすべてが用意されているわけではありません。場所を確認し、自分たちで準備をし、必要な物をそろえながら過ごします。',
      '「どこで何ができるのか」「何が必要なのか」を自分で確認しながら行動することが大切です。',
      'この章では、キャンプ場での受付、場所やルールの確認、売店でのやり取り、そしてキャンプ用品に関する表現を学びます。',
    ],
    functions: [
      ['01', '予約とキャンプ区画を確認する'],
      ['02', 'テントや車の場所を尋ねる'],
      ['03', 'キャンプ場のルールと設備を聞く'],
      ['04', '売店で忘れ物や燃料をそろえる'],
    ],
    arrival: {
      title: 'キャンプ場への到着と受付',
      enTitle: 'Arriving at the campsite',
      intro: '受付で予約、テントの区画、キャンピングカーの駐車場所を確認し、設営と探索の予定を話します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Hello, how can I help you?', meaning: 'こんにちは、どのようなご用件でしょうか？', context: '受付で用件を尋ねる', register: 'polite' },
        { phrase: "Hi, we've booked a pitch for two nights.", meaning: 'こんにちは、2泊で区画を予約しています。', context: '予約を伝える', register: 'polite' },
        { phrase: 'Where can we pitch our tent?', meaning: 'テントはどこに張ればいいですか？', context: 'テントの場所を尋ねる', register: 'polite' },
        { phrase: 'Over in that field, opposite the caravans.', meaning: 'あそこの広場、キャンピングトレーラーの向かい側ですよ。', context: '区画を案内する', register: 'neutral' },
        { phrase: 'Can we park our camper van near the site shop?', meaning: 'キャンピングカーを売店の近くに停めてもいいですか？', context: '駐車場所を尋ねる', register: 'polite' },
        { phrase: 'Yes, of course.', meaning: 'ええ、もちろんですよ。', context: '許可する', register: 'friendly' },
        { phrase: "There's loads to do here! The beach is just over there...", meaning: 'ここはできることがたくさんあるね！ビーチもすぐそこにあるし…。', context: '周辺の楽しみを話す', register: 'casual' },
        { phrase: "Great! We'll set up camp then head out to explore.", meaning: 'いいね！キャンプの設営をしてから、探索に出かけよう。', context: '設営後の予定を話す', register: 'casual' },
      ],
      recognition: [
        { phrase: 'book a pitch', meaning: 'キャンプ区画を予約する', note: 'pitch はテント用に割り当てられた一区画です。' },
        { phrase: 'pitch our tent', meaning: 'テントを張る', note: 'pitch は動詞で「設営する」という意味にもなります。' },
        { phrase: 'opposite the caravans', meaning: 'キャラバンの向かい側', note: '場所を案内するときの表現です。' },
        { phrase: 'set up camp', meaning: 'キャンプを設営する', note: 'テントや道具を整えて生活拠点を作ります。' },
      ],
    },
    shop: {
      title: 'キャンプ場内の売店での会話',
      enTitle: 'At the site shop',
      intro: 'キャンプファイヤーの許可を確認し、薪やキャンプ用ガス、マッチなど忘れた用品を買います。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Can we light a campfire?', meaning: 'キャンプファイヤー（焚き火）をしてもいいですか？', context: '焚き火の許可を尋ねる', register: 'polite' },
        { phrase: 'Yes, you can. Do you need firewood?', meaning: 'ええ、大丈夫ですよ。薪は必要ですか？', context: '許可と用品を案内する', register: 'friendly' },
        { phrase: "We forgot to bring camping gas! Have you got any?", meaning: 'キャンプ用のガス缶を持ってくるのを忘れちゃった！置いてありますか？', context: '燃料の在庫を尋ねる', register: 'casual' },
        { phrase: 'Sure, on that shelf over there. Anything else?', meaning: 'ありますよ、あそこの棚に。他には何かお探しですか？', context: '商品の場所を案内する', register: 'friendly' },
        { phrase: "Yes, I'll take a box of matches, too.", meaning: 'はい、マッチも1箱いただきます。', context: '追加の商品を買う', register: 'polite' },
      ],
      recognition: [
        { phrase: 'light a campfire', meaning: '焚き火をする', note: 'キャンプ場では許可が必要なことがあります。' },
        { phrase: 'firewood', meaning: '薪', note: '焚き火に使う木材です。' },
        { phrase: 'camping gas', meaning: 'キャンプ用ガス缶', note: '携帯用コンロなどの燃料です。' },
        { phrase: 'a box of matches', meaning: 'マッチ1箱', note: '必要な数量や容器と一緒に覚えます。' },
      ],
    },
    vocab: {
      title: 'キャンプに関するボキャブラリー',
      enTitle: 'Vocabulary camping',
      intro: 'テント、車、共同設備、売店、調理用品など、キャンプ場で目にする基本語彙です。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'tent', meaning: 'テント', context: '宿泊・道具', register: 'neutral' },
        { phrase: 'campfire', meaning: 'キャンプファイヤー・焚き火', context: '活動', register: 'neutral' },
        { phrase: 'shower block', meaning: 'シャワー棟', context: '共同設備', register: 'regional' },
        { phrase: 'caravan', meaning: '牽引式のキャンピングトレーラー', context: '車・宿泊', register: 'regional' },
        { phrase: 'camper van', meaning: 'キャンピングカー', context: '車・宿泊', register: 'regional' },
        { phrase: 'site shop', meaning: 'キャンプ場内の売店', context: '施設', register: 'regional' },
        { phrase: 'matches', meaning: 'マッチ', context: '用品', register: 'neutral' },
        { phrase: 'camping stove', meaning: 'キャンプ用コンロ・ポータブルバーナー', context: '調理用品', register: 'neutral' },
        { phrase: 'camping gas', meaning: 'キャンプ用ガス缶', context: '燃料', register: 'regional' },
      ],
      recognition: [
        { phrase: 'shower block', meaning: '共同シャワー棟', note: 'キャンプ場の共同設備を指します。' },
        { phrase: 'caravan', meaning: '牽引式トレーラー', note: '自走する camper van と区別します。' },
        { phrase: 'camper van', meaning: '自走式キャンピングカー', note: 'それ自体を運転して移動します。' },
        { phrase: 'camping stove', meaning: 'キャンプ用コンロ', note: '屋外で調理する携帯用ストーブです。' },
      ],
    },
    dialogues: [
      {
        id: 'arrival',
        label: 'Pattern A · Arriving at the campsite',
        title: '予約とテントの区画を確認する',
        lines: [
          { speaker: 'A', en: 'Hello, how can I help you?', ja: 'こんにちは、どのようなご用件でしょうか？' },
          { speaker: 'B', en: "Hi, we've booked a pitch for two nights.", ja: 'こんにちは、2泊で区画を予約しています。' },
          { speaker: 'A', en: 'Where can we pitch our tent?', ja: 'テントはどこに張ればいいですか？' },
          { speaker: 'B', en: 'Over in that field, opposite the caravans.', ja: 'あそこの広場、キャンピングトレーラーの向かい側ですよ。' },
        ],
      },
      {
        id: 'setting-up',
        label: 'Pattern B · Setting up camp',
        title: '駐車場所とキャンプ後の予定を話す',
        lines: [
          { speaker: 'A', en: 'Can we park our camper van near the site shop?', ja: 'キャンピングカーを売店の近くに停めてもいいですか？' },
          { speaker: 'B', en: 'Yes, of course.', ja: 'ええ、もちろんですよ。' },
          { speaker: 'A', en: "There's loads to do here! The beach is just over there...", ja: 'ここはできることがたくさんあるね！ビーチもすぐそこにあるし…。' },
          { speaker: 'B', en: "We'll set up camp then head out to explore.", ja: 'キャンプの設営をしてから、探索に出かけよう。' },
        ],
      },
      {
        id: 'shop',
        label: 'Pattern C · At the site shop',
        title: '焚き火と忘れ物の用品を確認する',
        lines: [
          { speaker: 'A', en: 'Can we light a campfire?', ja: 'キャンプファイヤーをしてもいいですか？' },
          { speaker: 'B', en: 'Yes, you can. Do you need firewood?', ja: 'ええ、大丈夫ですよ。薪は必要ですか？' },
          { speaker: 'A', en: 'We forgot to bring camping gas! Have you got any?', ja: 'キャンプ用のガス缶を忘れました。ありますか？' },
          { speaker: 'B', en: "Sure, on that shelf over there. Anything else?", ja: 'ありますよ、あそこの棚に。他には何かお探しですか？' },
        ],
      },
    ],
    tip: 'pitch は名詞では「テント用区画」、動詞では「テントを張る」です。set up camp はキャンプの生活拠点を設営すること、caravan は牽引式、camper van は自走式のキャンピングカーを表します。loads to do は「やることが山ほどある」というカジュアルな表現です。',
  },
  practice: {
    title: 'キャンプ場で必要なことを、英語で確認する',
    instructions: '日本語訳は見ずに、受付、設営、売店、キャンプ用品の表現を声に重ねます。',
    coreHeading: 'まずは、キャンプ場で尋ねる一文から。',
    dialogueHeading: '受付、設営、売店の場面で役を切り替える。',
    dialogueDescription: '予約と区画を確認する、駐車と設営の予定を話す、焚き火と用品を尋ねる3つの場面を練習します。',
    finishTitle: '次にキャンプへ行くとき、区画か必要な用品を英語でひとつ尋ねてみましょう。',
    corePhrases: [
      { phrase: "We've booked a pitch for two nights.", context: '予約を伝える', rate: 0.78 },
      { phrase: 'Where can we pitch our tent?', context: 'テントの場所を尋ねる', rate: 0.82 },
      { phrase: 'Over in that field, opposite the caravans.', context: '区画を案内する', rate: 0.72 },
      { phrase: 'Can we park our camper van near the site shop?', context: '駐車場所を尋ねる', rate: 0.7 },
      { phrase: "There's loads to do here! The beach is just over there...", context: '周辺の楽しみを話す', rate: 0.7 },
      { phrase: "We'll set up camp then head out to explore.", context: '設営後の予定を話す', rate: 0.76 },
      { phrase: 'Can we light a campfire?', context: '焚き火の許可を尋ねる', rate: 0.84 },
      { phrase: 'Do you need firewood?', context: '薪を案内する', rate: 0.84 },
      { phrase: 'We forgot to bring camping gas! Have you got any?', context: '燃料の在庫を尋ねる', rate: 0.7 },
      { phrase: 'Sure, on that shelf over there. Anything else?', context: '商品の場所を案内する', rate: 0.74 },
      { phrase: "I'll take a box of matches, too.", context: '追加の商品を買う', rate: 0.82 },
      { phrase: 'The shower block is near the site shop.', context: '設備の場所を伝える', rate: 0.76 },
    ],
    dialogues: [
      { title: 'Arriving at the campsite', lines: ['Hello, how can I help you?', "Hi, we've booked a pitch for two nights.", 'Where can we pitch our tent?', 'Over in that field, opposite the caravans.'] },
      { title: 'Setting up camp', lines: ['Can we park our camper van near the site shop?', 'Yes, of course.', "There's loads to do here! The beach is just over there...", "We'll set up camp then head out to explore."] },
      { title: 'At the site shop', lines: ['Can we light a campfire?', 'Yes, you can. Do you need firewood?', 'We forgot to bring camping gas! Have you got any?', 'Sure, on that shelf over there. Anything else?'] },
    ],
    natural: [
      { full: 'Could you tell us which area has been allocated for our tent?', natural: 'Where can we pitch our tent?' },
      { full: 'We will establish our campsite and then go out to look around.', natural: "We'll set up camp then head out to explore." },
      { full: 'Do you happen to sell any fuel for a portable camping stove?', natural: 'Have you got any camping gas?' },
    ],
  },
}
