/** Chapter 60 · Household chores. */
export const choresLesson = {
  id: 'chores',
  kind: 'chores',
  number: '60',
  title: '第60章に入る前に：なぜ「家事に関する英語」を学ぶのでしょうか？',
  enTitle: 'Household chores',
  ja: '家事の分担、掃除や片付け、日常的な家事について話す英語を学びます。',
  cando: '家事の内容や当番を確認し、手伝いを頼みながら家の作業を調整できる。',
  learn: {
    intro: [
      '家事は毎日の生活に欠かせないものですが、一人ですべてをするとは限りません。家族や同居している人と、誰が何をするか相談することもあります。',
      '洗濯、皿洗い、掃除、ゴミ出しなどを分担するときは、作業の内容だけでなく、誰の番か、いつまでにするかも分かりやすく伝えることが大切です。',
      '大掃除のあとには、家がどれだけきれいになったかを話し、お互いの頑張りをねぎらいます。使ったものを元の場所に戻すときは put away が便利です。',
      'この章では、家事の分担、掃除や片付けについての会話、そして日常的な家事の表現を学びます。',
    ],
    functions: [
      ['01', '家事の当番を決める'],
      ['02', '誰の番か確認する'],
      ['03', '手伝いと片付けを頼む'],
      ['04', '掃除の成果を伝える'],
    ],
    sharing: {
      title: '家事の分担',
      enTitle: 'Sharing tasks',
      intro: '家事の当番表を作り、誰が何をするか、前回は誰が担当したかを確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Hey, what are you up to?', meaning: 'ねえ、何をしているの？', context: '相手の作業を尋ねる', register: 'casual' },
        { phrase: "I'm making a rota for the chores.", meaning: '家事の当番表を作っているんだ。', context: '当番表を作る', register: 'neutral' },
        { phrase: 'Your turn to do the washing-up, then!', meaning: 'じゃあ、次はお皿を洗う君の番だね！', context: '担当を伝える', register: 'casual' },
        { phrase: 'Whose turn is it to empty the dishwasher?', meaning: '食洗機を空にするのは誰の番？', context: '順番を確認する', register: 'casual' },
        { phrase: "I did it last time, so it's yours!", meaning: '前回は私がやったから、今回はあなたの番だよ！', context: '交代を主張する', register: 'casual' },
        { phrase: 'Have you finished doing the laundry yet?', meaning: 'もう洗濯は終わった？', context: '作業の進み具合を尋ねる', register: 'neutral' },
        { phrase: 'Nearly! Can you help me put it away?', meaning: 'ほぼ終わったよ！片付けるのを手伝ってくれる？', context: '片付けを頼む', register: 'polite' },
        { phrase: 'Can you help me put it away?', meaning: '片付けるのを手伝ってくれる？', context: '収納を頼む', register: 'polite' },
      ],
      recognition: [
        { phrase: 'rota', meaning: '当番表・勤務表', note: 'イギリス英語で、順番を決める表に使います。' },
        { phrase: 'washing-up', meaning: '皿洗い', note: 'イギリス英語で do the washing-up と言います。' },
        { phrase: 'whose turn', meaning: '誰の番', note: '分担や順番を確認する定番表現です。' },
        { phrase: 'put away', meaning: '元の場所にしまう', note: '洗濯物や道具を収納するときに使います。' },
      ],
    },
    cleaning: {
      title: '大掃除',
      enTitle: 'Spring cleaning',
      intro: '徹底的な掃除が終わったあと、家の変化や頑張りを一緒に振り返ります。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'There we go. The house looks much tidier now!', meaning: 'よし、できた。家がずいぶんきれいになったね！', context: '掃除の成果を伝える', register: 'casual' },
        { phrase: 'Phew! That was a proper spring clean!', meaning: 'ふう！本格的な大掃除だったね！', context: '大掃除を振り返る', register: 'casual' },
        { phrase: "I've cleaned the worktops and the oven.", meaning: '調理台とオーブンをきれいにしたよ。', context: '掃除した場所を言う', register: 'neutral' },
        { phrase: 'Great job! The kitchen was in a right state.', meaning: 'お疲れ様！キッチンは本当にひどい状態だったからね。', context: '状態と成果を話す', register: 'casual' },
        { phrase: 'The house looks much tidier now!', meaning: '家がずいぶん片付いた状態になったね！', context: '見た目の変化を伝える', register: 'casual' },
        { phrase: 'Let us clean the windows while we are at it.', meaning: 'せっかくだから窓も掃除しましょう。', context: '作業を追加する', register: 'neutral' },
        { phrase: 'I will sweep the floor if you vacuum the stairs.', meaning: 'あなたが階段に掃除機をかけるなら、私は床を掃きます。', context: '作業を分ける', register: 'neutral' },
        { phrase: 'We can take the rubbish out when we finish.', meaning: '終わったらゴミを出せます。', context: '最後の作業を決める', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'There we go', meaning: 'よし、できた', note: '作業がうまく終わったときの一言です。' },
        { phrase: 'a proper spring clean', meaning: '本格的な大掃除', note: '季節を問わず徹底的な掃除を表します。' },
        { phrase: 'in a right state', meaning: 'ひどい状態で', note: '主にイギリス英語のカジュアルな表現です。' },
        { phrase: 'tidier', meaning: 'より片付いた', note: 'tidy の比較級で、掃除後の変化に使います。' },
      ],
    },
    routines: {
      title: '日常の家事',
      enTitle: 'Everyday chores',
      intro: '洗濯、皿洗い、掃除機、ゴミ出しなどを、実際の生活の動作として話します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'I need to do the laundry tonight.', meaning: '今夜、洗濯をしなければなりません。', context: '洗濯の予定を話す', register: 'neutral' },
        { phrase: 'Could you do the washing-up after dinner?', meaning: '夕食後に皿洗いをしてもらえますか？', context: '家事を頼む', register: 'polite' },
        { phrase: 'I will do the vacuuming upstairs.', meaning: '上の階は私が掃除機をかけます。', context: '担当を分ける', register: 'neutral' },
        { phrase: 'Whose job is it to clean the bath?', meaning: 'お風呂を掃除するのは誰の仕事？', context: '担当を確認する', register: 'casual' },
        { phrase: 'Please put the rubbish out before bed.', meaning: '寝る前にゴミを出してください。', context: '期限を添えて頼む', register: 'polite' },
        { phrase: 'I have already made the bed.', meaning: 'もうベッドを整えました。', context: '家事の完了を伝える', register: 'neutral' },
        { phrase: 'Can you sweep the floor in the hallway?', meaning: '廊下の床を掃いてくれる？', context: '場所を指定して頼む', register: 'polite' },
        { phrase: 'The dishwasher is empty now.', meaning: '食洗機はもう空になっています。', context: '作業の完了を伝える', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'do the laundry', meaning: '洗濯をする', note: '洗って乾かす一連の洗濯に使います。' },
        { phrase: 'do the vacuuming', meaning: '掃除機をかける', note: 'vacuum は名詞にも動詞にもなります。' },
        { phrase: 'put the rubbish out', meaning: 'ゴミを出す', note: 'イギリス英語でよく使う表現です。' },
        { phrase: 'make the bed', meaning: 'ベッドを整える', note: 'make と do の代表的な使い分けです。' },
      ],
    },
    vocabulary: {
      title: '家事のボキャブラリー',
      enTitle: 'Vocabulary · Housework',
      intro: '日常の家事を表す動詞フレーズを、分担や当番の会話と一緒に覚えます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'do the laundry', meaning: '洗濯をする', context: '洗濯', register: 'neutral' },
        { phrase: 'do the washing-up', meaning: '皿洗いをする', context: '台所', register: 'neutral' },
        { phrase: 'do the vacuuming', meaning: '掃除機をかける', context: '掃除', register: 'neutral' },
        { phrase: 'empty the dishwasher', meaning: '食洗機を空にする', context: '台所', register: 'neutral' },
        { phrase: 'clean the bath', meaning: 'お風呂を掃除する', context: '浴室', register: 'neutral' },
        { phrase: 'sweep the floor', meaning: '床を掃く', context: '掃除', register: 'neutral' },
        { phrase: 'put the rubbish out', meaning: 'ゴミを出す', context: 'ゴミ出し', register: 'neutral' },
        { phrase: 'tidy up', meaning: '片付ける・整理整頓する', context: '整理', register: 'neutral' },
        { phrase: 'make the bed', meaning: 'ベッドメイキングをする', context: '寝室', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'do vs make', meaning: 'do と make の使い分け', note: '家事は do が基本ですが、ベッドは make the bed と言います。' },
        { phrase: 'turn', meaning: '順番・交代の番', note: 'Your turn! や Whose turn is it? に使います。' },
        { phrase: 'put away', meaning: '収納場所にしまう', note: 'tidy up より「元の場所に戻す」意味が明確です。' },
        { phrase: 'spring clean', meaning: '大掃除する・大掃除', note: '季節を問わず大規模な掃除を指します。' },
      ],
    },
    dialogues: [
      {
        id: 'sharing',
        label: 'Pattern A · Sharing tasks',
        title: '家事の当番を確認する',
        lines: [
          { speaker: 'A', en: 'Hey, what are you up to?', ja: 'ねえ、何をしているの？' },
          { speaker: 'B', en: "I'm making a rota for the chores.", ja: '家事の当番表を作っているんだ。' },
          { speaker: 'A', en: 'Whose turn is it to empty the dishwasher?', ja: '食洗機を空にするのは誰の番？' },
          { speaker: 'B', en: "I did it last time, so it's yours!", ja: '前回は私がやったから、今回はあなたの番だよ！' },
        ],
      },
      {
        id: 'cleaning',
        label: 'Pattern B · Spring cleaning',
        title: '大掃除の成果を話す',
        lines: [
          { speaker: 'A', en: 'There we go. The house looks much tidier now!', ja: 'よし、できた。家がずいぶんきれいになったね！' },
          { speaker: 'B', en: 'Phew! That was a proper spring clean!', ja: 'ふう！本格的な大掃除だったね！' },
          { speaker: 'A', en: "I've cleaned the worktops and the oven.", ja: '調理台とオーブンをきれいにしたよ。' },
          { speaker: 'B', en: 'Great job! The kitchen was in a right state.', ja: 'お疲れ様！キッチンは本当にひどい状態だったからね。' },
        ],
      },
      {
        id: 'routines',
        label: 'Pattern C · Everyday chores',
        title: '日常の家事を頼む',
        lines: [
          { speaker: 'A', en: 'Have you finished doing the laundry yet?', ja: 'もう洗濯は終わった？' },
          { speaker: 'B', en: 'Nearly! Can you help me put it away?', ja: 'ほぼ終わったよ！片付けるのを手伝ってくれる？' },
          { speaker: 'A', en: 'Sure. I will make the bed while you fold the clothes.', ja: 'もちろん。あなたが服をたたむ間に、私がベッドを整えるね。' },
          { speaker: 'B', en: 'Thanks. We can put the rubbish out afterwards.', ja: 'ありがとう。そのあとゴミを出せるね。' },
        ],
      },
    ],
    tip: '家事の作業には do を使うことが多く、do the laundry、do the washing-up、do the vacuuming のように言います。代表的な例外は make the bed です。turn は順番、put away は元の場所にしまうことを表します。in a right state はひどい状態、a proper spring clean は本格的な大掃除というイギリス英語の表現です。',
  },
  practice: {
    title: '家事の分担を、英語で気持ちよく調整する',
    instructions: '日本語訳は見ずに、当番、大掃除、日常家事の表現を声に重ねます。',
    coreHeading: 'まずは、誰の番かを確認する一文から。',
    dialogueHeading: '分担、掃除後、日常家事の場面で役を切り替える。',
    dialogueDescription: '当番表と順番を確認する、大掃除の成果を話す、洗濯や片付けを頼む3つの場面を練習します。',
    finishTitle: '次に家事を分担するとき、誰の番かを英語でひとつ確認してみましょう。',
    corePhrases: [
      { phrase: "I'm making a rota for the chores.", context: '当番表を作る', rate: 0.8 },
      { phrase: 'Your turn to do the washing-up, then!', context: '担当を伝える', rate: 0.8 },
      { phrase: 'Whose turn is it to empty the dishwasher?', context: '順番を確認する', rate: 0.76 },
      { phrase: "I did it last time, so it's yours!", context: '交代を主張する', rate: 0.78 },
      { phrase: 'Have you finished doing the laundry yet?', context: '進み具合を尋ねる', rate: 0.78 },
      { phrase: 'Nearly! Can you help me put it away?', context: '片付けを頼む', rate: 0.76 },
      { phrase: 'There we go. The house looks much tidier now!', context: '掃除の成果を伝える', rate: 0.74 },
      { phrase: 'Phew! That was a proper spring clean!', context: '大掃除を振り返る', rate: 0.76 },
      { phrase: "I've cleaned the worktops and the oven.", context: '掃除した場所を言う', rate: 0.78 },
      { phrase: 'Great job! The kitchen was in a right state.', context: '成果をねぎらう', rate: 0.74 },
      { phrase: 'Please put the rubbish out before bed.', context: 'ゴミ出しを頼む', rate: 0.78 },
      { phrase: 'I have already made the bed.', context: '家事の完了を伝える', rate: 0.8 },
    ],
    dialogues: [
      { title: 'Sharing tasks', lines: ['Hey, what are you up to?', "I'm making a rota for the chores.", 'Whose turn is it to empty the dishwasher?', "I did it last time, so it's yours!"] },
      { title: 'Spring cleaning', lines: ['There we go. The house looks much tidier now!', 'Phew! That was a proper spring clean!', "I've cleaned the worktops and the oven.", 'Great job! The kitchen was in a right state.'] },
      { title: 'Everyday chores', lines: ['Have you finished doing the laundry yet?', 'Nearly! Can you help me put it away?', 'Sure. I will make the bed while you fold the clothes.', 'Thanks. We can put the rubbish out afterwards.'] },
    ],
    natural: [
      { full: 'Whose responsibility is it to empty the dishwasher?', natural: 'Whose turn is it to empty the dishwasher?' },
      { full: 'Can you help me return the laundry to its storage place?', natural: 'Can you help me put it away?' },
      { full: 'The kitchen was in a very bad condition.', natural: 'The kitchen was in a right state.' },
    ],
  },
}
