/** Chapter 27 · At the cinema. */
export const cinemaLesson = {
  id: 'cinema',
  kind: 'cinema',
  number: '27',
  title: 'なぜ「映画館で使う英語」を学ぶのでしょうか？',
  enTitle: 'At the cinema',
  ja: '上映時間、チケット、座席、字幕を確認し、映画の感想を伝えます。',
  cando: '映画館で必要な情報を尋ね、見終わった映画の感想を自然に話せる。',
  learn: {
    intro: [
      '映画館では、ただ映画を見るだけではありません。映画が始まる前には、上映時間、チケット、座席、字幕などについて確認する必要があります。',
      'そして映画を見終わった後は、今度は自分がどう感じたか、どう思ったかを相手と話します。必要な情報を得るための英語と、自分の感想を伝える英語の両方が必要です。',
      'この章では、映画館で使う実用的な質問と、映画について自然に感想を話す表現を学びます。',
    ],
    functions: [
      ['01', '上映を確認する'],
      ['02', '席とアクセスを尋ねる'],
      ['03', '字幕と年齢制限を確認する'],
      ['04', '感想を伝える'],
    ],
    tickets: {
      title: 'チケットを買う・質問する',
      enTitle: 'Getting tickets & other questions',
      intro: '窓口で上映時間、席、スクリーン、売り切れなどを短く確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'What time is the next screening?', meaning: '次の上映は何時ですか？', context: '次の上映時間を尋ねる', register: 'polite' },
        { phrase: "It's at 2pm. We're just in time!", meaning: '午後2時です。ちょうど間に合いましたね！', context: '上映時間を答える', register: 'casual' },
        { phrase: 'Three tickets for the 2pm screening, please.', meaning: '午後2時の上映のチケットを3枚お願いします。', context: 'チケットを買う', register: 'polite' },
        { phrase: 'How long is the film?', meaning: '映画の上映時間はどのくらいですか？', context: '上映時間の長さを尋ねる', register: 'neutral' },
        { phrase: 'Which screen is it showing at?', meaning: 'どのスクリーンで上映していますか？', context: 'スクリーン番号を尋ねる', register: 'polite' },
        { phrase: 'Is there time to get popcorn?', meaning: 'ポップコーンを買う時間はありますか？', context: '上映前の時間を確認する', register: 'casual' },
        { phrase: 'Is the next screening sold out?', meaning: '次の上映は売り切れですか？', context: 'チケットの在庫を尋ねる', register: 'polite' },
        { phrase: 'Can we have seats at the back?', meaning: '後方の席にしてもらえますか？', context: '席の希望を伝える', register: 'polite' },
      ],
      recognition: [
        { phrase: 'screening', meaning: '上映', note: 'screening time で「上映時間」、screening room で「上映室」のように使います。' },
        { phrase: 'sold out', meaning: '売り切れ', note: 'チケットやイベントの席がもう残っていない状態です。' },
      ],
    },
    access: {
      title: 'アクセスや年齢制限について尋ねる',
      enTitle: 'Asking questions about access',
      intro: '字幕、吹き替え、年齢レーティング、スクリーンへの行き方を確認します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Is the film okay for kids under 10?', meaning: 'この映画は10歳以下の子どもでも大丈夫ですか？', context: '年齢制限を尋ねる', register: 'polite' },
        { phrase: "It's a 'U', so it's fine for all ages!", meaning: '「U」指定なので、全年齢対象で大丈夫ですよ！', context: 'レーティングを説明する', register: 'neutral' },
        { phrase: 'Is this the subtitled screening?', meaning: 'これは字幕版の上映ですか？', context: '字幕版か確認する', register: 'polite' },
        { phrase: 'The dubbed version starts at 5pm.', meaning: '吹き替え版は午後5時に始まります。', context: '吹き替え版を案内する', register: 'neutral' },
        { phrase: 'Can I get to Screen 2 this way?', meaning: 'この道でスクリーン2に行けますか？', context: '行き方を尋ねる', register: 'polite' },
        { phrase: 'Yes, just follow the ramps.', meaning: 'はい、スロープに沿って進んでください。', context: 'アクセス方法を答える', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'U (Universal)', meaning: '全年齢対象のレーティング（UK）', note: '日本のGに近い、イギリスの表示です。' },
        { phrase: 'subtitled / dubbed', meaning: '字幕版／吹き替え版', note: '映画の音声と言語の違いを確認するときに使います。' },
      ],
    },
    reactions: {
      title: '映画の感想を言い合う',
      enTitle: 'Discussing the film',
      intro: '映画を見終わったあと、ポジティブな感想も、少し厳しい感想も自然に伝えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'How good was that?', meaning: 'すごくよかったよね？／最高だったね！', context: '強い感動を共有する', register: 'casual' },
        { phrase: 'Those action scenes really blew me away!', meaning: 'あのアクションシーンには本当に圧倒されたよ！', context: '感動や驚きを伝える', register: 'casual' },
        { phrase: 'The 3D glasses made it so realistic!', meaning: '3Dメガネのおかげですごくリアルだったね！', context: '映画の効果をほめる', register: 'casual' },
        { phrase: 'That was way too long!', meaning: 'あれは長すぎたよ！', context: '長さに不満を言う', register: 'casual' },
        { phrase: 'The acting was rubbish.', meaning: '演技がひどかった。', context: '演技を厳しく批評する', register: 'casual' },
        { phrase: "I wasn't keen on the ending.", meaning: '結末はあまり好きじゃなかったな。', context: '結末への不満をやわらげる', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'blow me away', meaning: '圧倒する・とても感動させる', note: '直訳の「吹き飛ばす」から、強い驚きや感動を表します。' },
        { phrase: 'rubbish', meaning: 'ひどい・くだらない（UK）', note: '物のゴミだけでなく、映画やアイデアの酷評にも使います。' },
        { phrase: 'not keen on …', meaning: '…があまり好きではない', note: '強く否定せずに好みを伝える表現です。' },
      ],
    },
    dialogues: [
      {
        id: 'tickets',
        label: 'Pattern A · Getting tickets',
        title: '上映とチケットを確認する',
        lines: [
          { speaker: 'A', en: 'What time is the next screening?', ja: '次の上映は何時ですか？' },
          { speaker: 'B', en: "It's at 2pm. We're just in time!", ja: '午後2時です。ちょうど間に合いましたね！' },
          { speaker: 'A', en: 'Three tickets for the 2pm screening, please.', ja: '午後2時の上映のチケットを3枚お願いします。' },
        ],
      },
      {
        id: 'access',
        label: 'Pattern B · Access and subtitles',
        title: '字幕とスクリーンを確認する',
        lines: [
          { speaker: 'A', en: 'Is this the subtitled screening?', ja: 'これは字幕版の上映ですか？' },
          { speaker: 'B', en: 'Yes. Screen 2 is just up the ramps.', ja: 'はい。スクリーン2はスロープを上がったところです。' },
          { speaker: 'A', en: 'Great, thanks.', ja: 'わかりました、ありがとう。' },
        ],
      },
      {
        id: 'reactions',
        label: 'Pattern C · Discussing the film',
        title: '映画の感想を話す',
        lines: [
          { speaker: 'A', en: 'How good was that?', ja: 'すごくよかったよね？' },
          { speaker: 'B', en: 'Those action scenes really blew me away!', ja: 'あのアクションシーンには本当に圧倒されたよ！' },
          { speaker: 'A', en: "I wasn't keen on the ending.", ja: '結末はあまり好きじゃなかったな。' },
        ],
      },
    ],
    tip: 'イギリスでは cinema と film、rubbish がよく使われます。アメリカ英語では movie theater、movie、trash / garbage にあたります。',
  },
  practice: {
    title: '映画館での質問と感想を、自然に声にする',
    instructions: '日本語の説明はここまで。上映、字幕、アクセス、映画の感想を英語だけで声に重ねます。',
    coreHeading: 'まずは、映画館でそのまま使える一文から。',
    dialogueHeading: '確認して、観て、感想を交換する流れを感じる。',
    dialogueDescription: '上映前の質問を聞き、映画のあとには自分の感想を自然な英語で返します。',
    finishTitle: '次に映画を見るとき、ひとつだけ英語で質問か感想を言ってみましょう。',
    corePhrases: [
      { phrase: 'What time is the next screening?', context: '上映時間を尋ねる', rate: 0.8 },
      { phrase: 'Three tickets for the 2pm screening, please.', context: 'チケットを買う', rate: 0.78 },
      { phrase: 'How long is the film?', context: '上映時間を尋ねる', rate: 0.84 },
      { phrase: 'Which screen is it showing at?', context: 'スクリーンを尋ねる', rate: 0.78 },
      { phrase: 'Is this the subtitled screening?', context: '字幕版を確認する', rate: 0.8 },
      { phrase: 'Can I get to Screen 2 this way?', context: '行き方を尋ねる', rate: 0.78 },
      { phrase: 'How good was that?', context: '感動を共有する', rate: 0.86 },
      { phrase: 'Those action scenes really blew me away!', context: '映画をほめる', rate: 0.76 },
      { phrase: 'That was way too long!', context: '長さに不満を言う', rate: 0.84 },
      { phrase: "I wasn't keen on the ending.", context: '結末への感想を言う', rate: 0.8 },
    ],
    dialogues: [
      { title: 'Getting tickets', lines: ['What time is the next screening?', "It's at 2pm. We're just in time!", 'Three tickets for the 2pm screening, please.'] },
      { title: 'Access and subtitles', lines: ['Is this the subtitled screening?', 'Yes. Screen 2 is just up the ramps.', 'Great, thanks.'] },
      { title: 'Discussing the film', lines: ['How good was that?', 'Those action scenes really blew me away!', "I wasn't keen on the ending."] },
    ],
    natural: [
      { full: 'What time does the next showing start?', natural: 'What time is the next screening?' },
      { full: 'The action scenes impressed me very much.', natural: 'Those action scenes really blew me away!' },
      { full: 'I did not really like the ending.', natural: "I wasn't keen on the ending." },
    ],
  },
}
