/** Chapter 75 · City sightseeing. */
export const citySightseeingLesson = {
  id: 'city-sightseeing',
  kind: 'city-sightseeing',
  number: '75',
  title: '第75章に入る前に：なぜ「市内観光で使う英語」を学ぶのでしょうか？',
  enTitle: 'City sightseeing',
  ja: '観光名所での質問、チケットの購入、ツアーバスでの会話、観光に必要な基本表現を学びます。',
  cando: '観光名所の時間・料金・設備を確認し、チケットを買い、ツアーバスで案内や移動を理解できる。',
  learn: {
    intro: [
      '観光では、ただ景色を見るだけでなく、開館時間を確認したり、チケットを買ったり、ツアーの情報を聞いたりしながら行動します。',
      '限られた時間の中で必要な情報を集め、自分の行きたい場所を楽しめるようにすることが大切です。',
      'この章では、観光名所での質問、チケットの購入、ツアーバスでの会話、そして観光に必要な基本表現を学びます。',
    ],
    functions: [
      ['01', '開館時間と入場条件を確認する'],
      ['02', 'チケットとガイドを手配する'],
      ['03', '観光バスの案内を聞き取る'],
      ['04', '地図を見て次の行き先を決める'],
    ],
    sights: {
      title: '観光名所を訪れる',
      enTitle: 'Visiting the sights',
      intro: '宮殿や博物館で時間、チケット、ガイドツアーを確認し、入場に必要な情報を集めます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'What time does the palace open?', meaning: '宮殿は何時に開きますか？', context: '開館時間を尋ねる', register: 'polite' },
        { phrase: 'In 10 minutes. You can join the queue here.', meaning: '10分後です。こちらの列にお並びいただけますよ。', context: '開館と列を案内する', register: 'polite' },
        { phrase: "I'd like two tickets for the museum, please.", meaning: '博物館のチケットを2枚ください。', context: 'チケットを買う', register: 'polite' },
        { phrase: "Here you go. There's a guided tour at 10.30.", meaning: 'はい、どうぞ。10時30分からガイド付きツアーがあります。', context: 'チケットとツアーを案内する', register: 'friendly' },
        { phrase: 'How much is the entrance fee?', meaning: '入場料はいくらですか？', context: '料金を尋ねる', register: 'polite' },
        { phrase: 'What time is the next guided tour?', meaning: '次のガイド付きツアーは何時ですか？', context: 'ツアー時刻を尋ねる', register: 'polite' },
        { phrase: 'Could I have an audio guide, please?', meaning: '音声ガイドをいただけますか？', context: '音声ガイドを頼む', register: 'polite' },
        { phrase: 'What are your opening times?', meaning: '開館・開園時間は何時ですか？', context: '営業時間を尋ねる', register: 'polite' },
        { phrase: 'Is there wheelchair access?', meaning: '車椅子用のアクセスはありますか？', context: 'バリアフリー対応を尋ねる', register: 'polite' },
      ],
      recognition: [
        { phrase: 'join the queue', meaning: '列に並ぶ', note: 'イギリス英語で queue は待ち行列です。' },
        { phrase: 'entrance fee', meaning: '入場料', note: '観光名所に入るための料金です。' },
        { phrase: 'opening times', meaning: '開館・開園時間', note: '複数の時間帯をまとめて尋ねる表現です。' },
        { phrase: 'wheelchair access', meaning: '車椅子対応の入口・経路', note: 'バリアフリー設備の有無を確認します。' },
      ],
    },
    questions: {
      title: '観光に役立つその他の表現',
      enTitle: 'More questions',
      intro: '入場料、次のツアー、音声ガイド、開館時間、車椅子アクセスなどを短く確認します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'How much is the entrance fee?', meaning: '入場料はいくらですか？', context: '料金を確認する', register: 'polite' },
        { phrase: 'What time is the next guided tour?', meaning: '次のガイド付きツアーは何時ですか？', context: 'ツアーを確認する', register: 'polite' },
        { phrase: 'Could I have an audio guide, please?', meaning: '音声ガイドをいただけますか？', context: 'ガイドを頼む', register: 'polite' },
        { phrase: 'What are your opening times?', meaning: '開館・開園時間は何時ですか？', context: '時間を確認する', register: 'polite' },
        { phrase: 'Is there wheelchair access?', meaning: '車椅子用のアクセスはありますか？', context: 'アクセスを確認する', register: 'polite' },
      ],
      recognition: [
        { phrase: 'audio guide', meaning: '音声ガイド', note: 'イヤホンなどで説明を聞くガイドです。' },
        { phrase: 'guided tour', meaning: 'ガイド付きツアー', note: 'ガイドの説明を聞きながら見学します。' },
        { phrase: 'access', meaning: '利用・入場のしやすさ', note: 'wheelchair access で車椅子対応を表します。' },
      ],
    },
    bus: {
      title: '観光ツアーバスでの会話',
      enTitle: 'On a tour bus',
      intro: 'ツアーバスのアナウンスを聞き、地図を見ながら景色や降車場所について話します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "On your right, you'll see the oldest building in the city.", meaning: '右手に見えますのが、この街で最も古い建物です。', context: '景色を案内する', register: 'polite' },
        { phrase: "Look - we're here on the map and there's our hotel!", meaning: '見て、地図だと私たちはここにいて、あそこに私たちのホテルがあるよ！', context: '地図で位置を確認する', register: 'casual' },
        { phrase: 'Wow! Check that out!', meaning: 'わあ！あれを見て！', context: '目を引くものを知らせる', register: 'casual' },
        { phrase: 'Quick! Take a picture!', meaning: '急いで！写真を撮って！', context: '写真を頼む', register: 'casual' },
        { phrase: 'Shall we get off at the next stop?', meaning: '次の停留所で降りましょうか？', context: '降車を相談する', register: 'casual' },
      ],
      recognition: [
        { phrase: 'on your right', meaning: '右手に', note: '車窓から見えるものを案内します。' },
        { phrase: 'Check that out!', meaning: 'あれを見て！', note: '面白いものに注目してほしいときの口語表現です。' },
        { phrase: 'get off', meaning: '降りる', note: 'バスや電車から降りるときに使います。' },
      ],
    },
    vocab: {
      title: '観光に欠かせないボキャブラリー',
      enTitle: 'Tourist essentials',
      intro: '観光案内、チケット、ツアー、移動に関する基本語彙をまとめます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'tour bus', meaning: '観光バス・ツアーバス', context: '乗り物', register: 'neutral' },
        { phrase: 'queue', meaning: '順番を待つ列', context: '入場', register: 'regional' },
        { phrase: 'guided tour', meaning: 'ガイド付きツアー', context: 'ツアー', register: 'neutral' },
        { phrase: 'audio guide', meaning: '音声ガイド', context: '案内', register: 'neutral' },
        { phrase: 'ticket', meaning: 'チケット・入場券', context: '入場', register: 'neutral' },
        { phrase: 'tourist office', meaning: '観光案内所', context: '案内', register: 'neutral' },
        { phrase: 'map', meaning: '地図', context: '案内', register: 'neutral' },
        { phrase: 'guidebook', meaning: 'ガイドブック', context: '案内', register: 'neutral' },
        { phrase: 'souvenir', meaning: 'お土産・記念品', context: '買い物', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'tourist office', meaning: '観光案内所', note: '地図やツアー情報を入手できます。' },
        { phrase: 'guidebook', meaning: 'ガイドブック', note: '観光地や街の情報をまとめた本です。' },
        { phrase: 'souvenir', meaning: '旅の記念品', note: 'キーホルダーやポストカードなどを指します。' },
      ],
    },
    dialogues: [
      {
        id: 'sights',
        label: 'Pattern A · Visiting the sights',
        title: '時間を確認してチケットを買う',
        lines: [
          { speaker: 'A', en: 'What time does the palace open?', ja: '宮殿は何時に開きますか？' },
          { speaker: 'B', en: 'In 10 minutes. You can join the queue here.', ja: '10分後です。こちらの列にお並びいただけますよ。' },
          { speaker: 'A', en: "I'd like two tickets for the museum, please.", ja: '博物館のチケットを2枚ください。' },
          { speaker: 'B', en: "Here you go. There's a guided tour at 10.30.", ja: 'はい、どうぞ。10時30分からガイド付きツアーがあります。' },
        ],
      },
      {
        id: 'questions',
        label: 'Pattern B · Tourist questions',
        title: '料金とアクセスを確認する',
        lines: [
          { speaker: 'A', en: 'How much is the entrance fee?', ja: '入場料はいくらですか？' },
          { speaker: 'B', en: 'It is £12, and an audio guide is included.', ja: '12ポンドで、音声ガイドも含まれています。' },
          { speaker: 'A', en: 'Is there wheelchair access?', ja: '車椅子用のアクセスはありますか？' },
          { speaker: 'B', en: 'Yes, please use the entrance on the left.', ja: 'はい、左側の入口をご利用ください。' },
        ],
      },
      {
        id: 'tour-bus',
        label: 'Pattern C · On a tour bus',
        title: '車窓の景色を楽しみ、降車を相談する',
        lines: [
          { speaker: 'A', en: "On your right, you'll see the oldest building in the city.", ja: '右手に見えますのが、この街で最も古い建物です。' },
          { speaker: 'B', en: 'Wow! Check that out!', ja: 'わあ！あれを見て！' },
          { speaker: 'A', en: 'Quick! Take a picture!', ja: '急いで！写真を撮って！' },
          { speaker: 'B', en: 'Shall we get off at the next stop?', ja: '次の停留所で降りましょうか？' },
        ],
      },
    ],
    tip: 'Check that out! は観光中に目を引くものを「あれ見て！」と伝える自然な表現です。queue はイギリス英語の「列」、souvenir は旅の記念品、wheelchair access は車椅子で利用できる入口や経路を表します。',
  },
  practice: {
    title: '観光に必要な情報を、英語で確認する',
    instructions: '日本語訳は見ずに、観光名所、チケット、ツアーバス、観光語彙の表現を声に重ねます。',
    coreHeading: 'まずは、観光名所で尋ねる一文から。',
    dialogueHeading: '名所、窓口、ツアーバスの場面で役を切り替える。',
    dialogueDescription: '時間とチケットを確認する、料金とアクセスを尋ねる、ツアーバスで景色と降車を話す3つの場面を練習します。',
    finishTitle: '次に観光するとき、開館時間か入場料を英語でひとつ尋ねてみましょう。',
    corePhrases: [
      { phrase: 'What time does the palace open?', context: '開館時間を尋ねる', rate: 0.82 },
      { phrase: 'You can join the queue here.', context: '列を案内する', rate: 0.82 },
      { phrase: "I'd like two tickets for the museum, please.", context: 'チケットを買う', rate: 0.76 },
      { phrase: 'How much is the entrance fee?', context: '料金を尋ねる', rate: 0.84 },
      { phrase: 'What time is the next guided tour?', context: 'ツアー時刻を尋ねる', rate: 0.76 },
      { phrase: 'Could I have an audio guide, please?', context: '音声ガイドを頼む', rate: 0.78 },
      { phrase: 'What are your opening times?', context: '開館時間を確認する', rate: 0.78 },
      { phrase: 'Is there wheelchair access?', context: 'バリアフリーを尋ねる', rate: 0.82 },
      { phrase: "On your right, you'll see the oldest building in the city.", context: '景色を案内する', rate: 0.68 },
      { phrase: 'Wow! Check that out!', context: '注目を促す', rate: 0.86 },
      { phrase: 'Quick! Take a picture!', context: '写真を頼む', rate: 0.84 },
      { phrase: 'Shall we get off at the next stop?', context: '降車を相談する', rate: 0.78 },
    ],
    dialogues: [
      { title: 'Visiting the sights', lines: ['What time does the palace open?', 'In 10 minutes. You can join the queue here.', "I'd like two tickets for the museum, please.", "Here you go. There's a guided tour at 10.30."] },
      { title: 'Tourist questions', lines: ['How much is the entrance fee?', 'It is £12, and an audio guide is included.', 'Is there wheelchair access?', 'Yes, please use the entrance on the left.'] },
      { title: 'On a tour bus', lines: ["On your right, you'll see the oldest building in the city.", 'Wow! Check that out!', 'Quick! Take a picture!', 'Shall we get off at the next stop?'] },
    ],
    natural: [
      { full: 'Could you tell me at what time the palace opens to visitors?', natural: 'What time does the palace open?' },
      { full: 'Would it be possible for me to get two admissions to the museum?', natural: "I'd like two tickets for the museum, please." },
      { full: 'Please look at that remarkable building over there.', natural: 'Wow! Check that out!' },
    ],
  },
}
