/** Chapter 39 · Buying clothes and shoes. */
export const clothesLesson = {
  id: 'clothes-shoes',
  kind: 'clothes-shoes',
  number: '39',
  title: '第39章に入る前に：なぜ「洋服や靴を買うときの英語」を学ぶのでしょうか？',
  enTitle: 'Buying clothes and shoes',
  ja: 'サイズ、試着、在庫、セールについて尋ねる英語を学びます。',
  cando: '洋服や靴のサイズ・在庫を尋ね、試着やセールについて自然に確認できる。',
  learn: {
    intro: [
      '洋服や靴の買い物は、ほかの商品を買う場合よりも少し個人的です。商品があるだけではなく、自分の体に合うか、着心地がよいか、そして自分の好みに合っているかを確認する必要があります。',
      'そのため、違うサイズを尋ねたり、試着したり、在庫を確認したり、セール品かどうかを聞いたりする場面が多くあります。',
      'この章では、サイズや在庫の尋ね方、試着するときの表現、そして店員と自然にやり取りするための英語を学びます。',
    ],
    functions: [
      ['01', 'サイズを確認する'],
      ['02', '試着をお願いする'],
      ['03', '在庫を尋ねる'],
      ['04', 'セールを確認する'],
    ],
    clothes: {
      title: '洋服屋での会話・試着とサイズ',
      enTitle: 'At the clothes shop',
      intro: 'サイズが合うかを伝え、別のサイズや試着室について尋ねます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Have you got this shirt in a larger size?', meaning: 'このシャツのもう少し大きいサイズはありますか？', context: '大きいサイズを尋ねる', register: 'polite' },
        { phrase: 'Let me go and check.', meaning: '行って確認してまいります。', context: '在庫を確認する', register: 'neutral' },
        { phrase: 'These trousers feel too big.', meaning: 'このズボンは少し大きすぎます。', context: 'サイズ感を伝える', register: 'neutral' },
        { phrase: "I'll go and get you the next size down.", meaning: 'ワンサイズ下のものを持ってきますね。', context: '別サイズを提案する', register: 'neutral' },
        { phrase: 'Can I try these dresses on, please?', meaning: 'これらのワンピースを試着してもいいですか？', context: '試着をお願いする', register: 'polite' },
        { phrase: 'You can take up to four items in.', meaning: '4点まで試着室に持ち込めます。', context: '試着室のルールを伝える', register: 'neutral' },
        { phrase: 'Do you have the next size up?', meaning: 'ワンサイズ上はありますか？', context: '大きいサイズを確認する', register: 'polite' },
      ],
      recognition: [
        { phrase: 'the next size down', meaning: 'ワンサイズ下', note: 'the next size up はワンサイズ上です。' },
        { phrase: 'try ... on', meaning: '〜を試着する', note: 'try these dresses on のように使います。' },
        { phrase: 'take up to four items in', meaning: '4点まで持ち込む', note: '試着室に入れられる商品の数を表します。' },
      ],
    },
    shoes: {
      title: '靴屋での会話・在庫とセールの確認',
      enTitle: 'At the shoe shop',
      intro: 'ウェブサイトの在庫、サイズ、セール対象かどうかを確認します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Have you got these trainers in a size 10?', meaning: 'このスニーカーのサイズ10はありますか？', context: '靴のサイズを尋ねる', register: 'polite' },
        { phrase: "I don't think so, but I'll just check for you.", meaning: 'ないと思いますが、念のため確認しますね。', context: '在庫を確認する', register: 'neutral' },
        { phrase: "Your website says you've got these sandals in stock.", meaning: 'ウェブサイトには、このサンダルの在庫があるとのことでした。', context: 'オンライン在庫を伝える', register: 'neutral' },
        { phrase: 'Yes, they came in yesterday.', meaning: 'はい、昨日入荷しました。', context: '入荷を伝える', register: 'neutral' },
        { phrase: 'Are these boots in the sale?', meaning: 'このブーツはセールになっていますか？', context: 'セール対象か尋ねる', register: 'polite' },
        { phrase: 'All the sale items are on this rack.', meaning: 'セール品はすべてこちらのラックにあります。', context: 'セール売り場を案内する', register: 'neutral' },
        { phrase: 'Could I try these on in a size 8?', meaning: 'これをサイズ8で試着してもいいですか？', context: '靴を試す', register: 'polite' },
      ],
      recognition: [
        { phrase: 'in stock', meaning: '在庫がある', note: 'out of stock は在庫切れです。' },
        { phrase: 'came in', meaning: '入荷した', note: '新しい商品が店に届いたときに使います。' },
        { phrase: 'in the sale', meaning: 'セール対象の', note: 'イギリス英語で値下げ販売について尋ねる表現です。' },
      ],
    },
    vocabulary: {
      title: '洋服と靴のボキャブラリー',
      enTitle: 'Vocabulary · Clothes and shoes',
      intro: '服や靴の名前を、イギリス英語でよく使う形で覚えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'trousers', meaning: 'ズボン', context: '脚を覆う衣類', register: 'neutral' },
        { phrase: 'skirt', meaning: 'スカート', context: '腰から下に着る衣類', register: 'neutral' },
        { phrase: 'dress', meaning: 'ワンピース・ドレス', context: '上下一体の衣類', register: 'neutral' },
        { phrase: 'jacket', meaning: 'ジャケット', context: '上着', register: 'neutral' },
        { phrase: 'coat', meaning: 'コート', context: '防寒用の上着', register: 'neutral' },
        { phrase: 'shorts', meaning: 'ショートパンツ・半ズボン', context: '短い丈のズボン', register: 'neutral' },
        { phrase: 'suit', meaning: 'スーツ', context: '上下のフォーマルウェア', register: 'neutral' },
        { phrase: 'jumper', meaning: 'セーター', context: 'イギリス英語の sweater', register: 'neutral' },
        { phrase: 'shirt', meaning: 'シャツ', context: '襟のある上着', register: 'neutral' },
        { phrase: 'T-shirt', meaning: 'Tシャツ', context: 'カジュアルな上着', register: 'neutral' },
        { phrase: 'sandals', meaning: 'サンダル', context: '夏に履く靴', register: 'neutral' },
        { phrase: 'trainers', meaning: 'スニーカー・運動靴', context: 'イギリス英語の sneakers', register: 'neutral' },
        { phrase: 'boots', meaning: 'ブーツ', context: '足首以上を覆う靴', register: 'neutral' },
        { phrase: 'socks', meaning: '靴下', context: '足に履く衣類', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'trousers', meaning: 'ズボン', note: 'アメリカ英語では pants と言います。' },
        { phrase: 'jumper', meaning: 'セーター', note: 'アメリカ英語の sweater にあたります。' },
        { phrase: 'trainers', meaning: 'スニーカー', note: 'アメリカ英語の sneakers にあたります。' },
      ],
    },
    dialogues: [
      {
        id: 'fitting',
        label: 'Pattern A · Fitting and size',
        title: 'サイズを変えて試着する',
        lines: [
          { speaker: 'A', en: 'Have you got this shirt in a larger size?', ja: 'このシャツのもう少し大きいサイズはありますか？' },
          { speaker: 'B', en: 'Let me go and check.', ja: '行って確認してまいります。' },
          { speaker: 'A', en: 'Can I try these dresses on, please?', ja: 'これらのワンピースを試着してもいいですか？' },
          { speaker: 'B', en: 'Yes, you can take up to four items in.', ja: 'はい、4点まで試着室に持ち込めます。' },
        ],
      },
      {
        id: 'shoes',
        label: 'Pattern B · Shoes and stock',
        title: '靴のサイズと在庫を確認する',
        lines: [
          { speaker: 'A', en: 'Have you got these trainers in a size 10?', ja: 'このスニーカーのサイズ10はありますか？' },
          { speaker: 'B', en: "I don't think so, but I'll just check for you.", ja: 'ないと思いますが、念のため確認しますね。' },
          { speaker: 'A', en: "Your website says you've got these sandals in stock.", ja: 'ウェブサイトには、このサンダルの在庫があるとのことでした。' },
          { speaker: 'B', en: 'Yes, they came in yesterday.', ja: 'はい、昨日入荷しました。' },
        ],
      },
      {
        id: 'sale',
        label: 'Pattern C · Sale check',
        title: 'セール売り場を尋ねる',
        lines: [
          { speaker: 'A', en: 'Are these boots in the sale?', ja: 'このブーツはセールになっていますか？' },
          { speaker: 'B', en: 'Sorry, no. All the sale items are on this rack.', ja: '申し訳ありません、違います。セール品はこちらのラックです。' },
          { speaker: 'A', en: 'These trousers feel too big.', ja: 'このズボンは少し大きすぎます。' },
          { speaker: 'B', en: "I'll go and get you the next size down.", ja: 'ワンサイズ下のものを持ってきますね。' },
        ],
      },
    ],
    tip: 'trousers はイギリス英語で「ズボン」、jumper は「セーター」、trainers は「スニーカー」です。アメリカ英語と単語が違うので、買い物の場所に合わせて聞き取りましょう。イギリスの店では Have you got...? が「〜はありますか？」の自然な言い方です。',
  },
  practice: {
    title: '洋服と靴のサイズを英語で相談する',
    instructions: '日本語の説明はここまで。サイズ、試着、在庫、セールについて尋ねる英語を声に重ねます。',
    coreHeading: 'まずは、買い物でそのまま使える一文から。',
    dialogueHeading: 'サイズを試し、在庫を確認し、セールを尋ねる。',
    dialogueDescription: '服のサイズを変える声、靴の在庫を尋ねる声、セールを確認する声を切り替えます。',
    finishTitle: '次に服や靴を買うとき、サイズか在庫をひとつ英語で尋ねてみましょう。',
    corePhrases: [
      { phrase: 'Have you got this shirt in a larger size?', context: '大きいサイズを尋ねる', rate: 0.78 },
      { phrase: 'These trousers feel too big.', context: 'サイズ感を伝える', rate: 0.82 },
      { phrase: 'Can I try these dresses on, please?', context: '試着をお願いする', rate: 0.78 },
      { phrase: 'Do you have the next size up?', context: 'ワンサイズ上を尋ねる', rate: 0.82 },
      { phrase: 'Have you got these trainers in a size 10?', context: '靴のサイズを尋ねる', rate: 0.76 },
      { phrase: "Your website says you've got these sandals in stock.", context: 'オンライン在庫を伝える', rate: 0.74 },
      { phrase: 'Are these boots in the sale?', context: 'セール対象か尋ねる', rate: 0.82 },
      { phrase: 'Where are all the sale items?', context: 'セール売り場を尋ねる', rate: 0.84 },
    ],
    dialogues: [
      { title: 'Fitting and size', lines: ['Have you got this shirt in a larger size?', 'Let me go and check.', 'Can I try these dresses on, please?', 'Yes, you can take up to four items in.'] },
      { title: 'Shoes and stock', lines: ['Have you got these trainers in a size 10?', "I don't think so, but I'll just check for you.", "Your website says you've got these sandals in stock.", 'Yes, they came in yesterday.'] },
      { title: 'Sale check', lines: ['Are these boots in the sale?', 'Sorry, no. All the sale items are on this rack.', 'These trousers feel too big.', "I'll go and get you the next size down."] },
    ],
    natural: [
      { full: 'Do you have this shirt in a bigger size?', natural: 'Have you got this shirt in a larger size?' },
      { full: 'Can I put on these dresses?', natural: 'Can I try these dresses on, please?' },
      { full: 'Are these boots discounted?', natural: 'Are these boots in the sale?' },
    ],
  },
}
