/** Chapter 29 · Concerts and festivals. */
export const concertsLesson = {
  id: 'concerts',
  kind: 'concerts',
  number: '29',
  title: 'なぜ「コンサートやフェスティバルで使う英語」を学ぶのでしょうか？',
  enTitle: 'Concerts and festivals',
  ja: '会場内の移動、出演時間、手荷物検査、フェスの案内、演奏への感想を伝えます。',
  cando: '音楽イベントで必要な案内を尋ね、友人と合流し、体験や演奏の感動を話せる。',
  learn: {
    intro: [
      'コンサートやフェスティバルは、ただ音楽を聴くだけの場所ではありません。会場内を移動したり、案内を理解したり、友人と待ち合わせたり、出演時間を確認したり、手荷物検査などに対応したりする必要があります。',
      'また、音楽イベントは多くの人と同じ体験を共有する場でもあるため、感動や楽しさ、驚きなどを言葉で表現することも大切です。',
      'この章では、音楽イベントで必要になる実用的な英語と、演奏や体験について自然に話すための表現を学びます。',
    ],
    functions: [
      ['01', '入場に対応する'],
      ['02', '会場で合流する'],
      ['03', '出演者を確認する'],
      ['04', '感動を伝える'],
    ],
    concert: {
      title: 'コンサートやライブ会場での会話',
      enTitle: 'At a concert',
      intro: '入り口で手荷物検査に対応し、出演時間や会場内の場所を確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Have your bags ready for inspection, please.', meaning: '手荷物検査のために、カバンの準備をお願いします。', context: 'スタッフが入場前に案内する', register: 'polite' },
        { phrase: "Sorry, you can't take bottles in.", meaning: '申し訳ありませんが、ボトルは持ち込めません。', context: '持ち込み禁止を伝える', register: 'polite' },
        { phrase: 'What time does the main gig start?', meaning: 'メインのライブは何時に始まりますか？', context: 'メイン出演の時間を尋ねる', register: 'neutral' },
        { phrase: '9pm, but the support band has just come on.', meaning: '午後9時ですが、サポートバンドがちょうど登場したところです。', context: '出演の流れを答える', register: 'neutral' },
        { phrase: "Let's find the refreshment stand. I'm thirsty!", meaning: '売店を探そう。喉が渇いた！', context: '飲み物を買いに行く', register: 'casual' },
        { phrase: "I'll meet you back in the main arena.", meaning: '後でメインアリーナで合流しよう。', context: '友人との待ち合わせを決める', register: 'casual' },
      ],
      recognition: [
        { phrase: 'gig', meaning: 'ライブ・コンサート（カジュアルなUK英語）', note: 'ポップスやロックなどのライブを指します。' },
        { phrase: 'support band', meaning: '前座・サポートバンド', note: 'メインの出演者の前に演奏するバンドです。' },
        { phrase: 'refreshment stand', meaning: '軽食・飲み物の売店', note: '会場内の飲み物や食べ物を売る場所です。' },
      ],
    },
    festival: {
      title: '野外フェスや屋外イベントにて',
      enTitle: 'At an open-air festival',
      intro: '出演者、キャンプサイト、テント、フードトラック、列などを確認します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: "Who's playing on the main stage tonight?", meaning: '今夜のメインステージでは誰が演奏するの？', context: '出演者を尋ねる', register: 'casual' },
        { phrase: "Here's the line-up for the whole weekend. Enjoy!", meaning: 'これが週末全体のラインナップだよ。楽しんで！', context: '出演者リストを案内する', register: 'casual' },
        { phrase: 'Is the campsite open yet?', meaning: 'キャンプサイトはもう開いていますか？', context: 'キャンプ場の利用開始を尋ねる', register: 'polite' },
        { phrase: "I can't find my tent.", meaning: '自分のテントが見つからないよ。', context: '場所が分からないと伝える', register: 'casual' },
        { phrase: 'Can I see your wristband, please?', meaning: 'リストバンドを拝見できますか？', context: 'スタッフが通行証を確認する', register: 'polite' },
        { phrase: 'That food truck sells great burgers.', meaning: 'あのフードトラック、すごく美味しいハンバーガーを売っているよ。', context: '食べ物をすすめる', register: 'casual' },
        { phrase: 'The toilet queue is too long!', meaning: 'トイレの列が長すぎる！', context: '待ち時間に反応する', register: 'casual' },
      ],
      recognition: [
        { phrase: 'line-up', meaning: '出演者リスト・ラインナップ', note: 'イベントに出るアーティストの一覧です。' },
        { phrase: 'wristband', meaning: 'リストバンド型の通行証', note: 'チケットの代わりに手首につけることがあります。' },
        { phrase: 'queue', meaning: '列（UK）', note: 'アメリカ英語では line が一般的です。並ぶことは queue up と言います。' },
      ],
    },
    classical: {
      title: 'クラシックコンサートにて',
      enTitle: 'At a classical concert',
      intro: '無料の演奏会に誘い、予約の必要を確認し、演奏への感想を伝えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "There's a free classical concert at the park tonight.", meaning: '今夜、公園で無料のクラシックコンサートがあるよ。', context: 'イベントに誘う', register: 'casual' },
        { phrase: 'Do we have to book tickets?', meaning: 'チケットを予約しなきゃいけない？', context: '予約の必要を尋ねる', register: 'casual' },
        { phrase: 'No, we can just turn up.', meaning: 'ううん、ただ行けばいいだけだよ。', context: '予約不要と答える', register: 'casual' },
        { phrase: 'That was really impressive!', meaning: '本当に素晴らしかった！', context: '演奏をほめる', register: 'casual' },
        { phrase: 'What an amazing performance!', meaning: 'なんて素晴らしい演奏なんだろう！', context: '強い感動を伝える', register: 'casual' },
        { phrase: 'Encore! Encore!', meaning: 'アンコール！アンコール！', context: '追加演奏を求める', register: 'casual' },
      ],
      recognition: [
        { phrase: 'turn up', meaning: '現れる・ふらっと来る', note: '予約なしで参加できるイベントについて話すときにも使います。' },
        { phrase: 'encore', meaning: 'アンコール・追加演奏', note: '観客がもう一度の演奏を求める掛け声です。' },
      ],
    },
    dialogues: [
      {
        id: 'concert',
        label: 'Pattern A · At a concert',
        title: '入場して友人と合流する',
        lines: [
          { speaker: 'A', en: 'What time does the main gig start?', ja: 'メインのライブは何時に始まりますか？' },
          { speaker: 'B', en: '9pm, but the support band has just come on.', ja: '午後9時ですが、サポートバンドがちょうど登場したところです。' },
          { speaker: 'A', en: "I'll meet you back in the main arena.", ja: '後でメインアリーナで合流しよう。' },
        ],
      },
      {
        id: 'festival',
        label: 'Pattern B · At an open-air festival',
        title: 'フェスで場所を探す',
        lines: [
          { speaker: 'A', en: "Who's playing on the main stage tonight?", ja: '今夜のメインステージでは誰が演奏するの？' },
          { speaker: 'B', en: "Here's the line-up for the whole weekend. Enjoy!", ja: 'これが週末全体のラインナップだよ。楽しんで！' },
          { speaker: 'A', en: "I can't find my tent.", ja: '自分のテントが見つからないよ。' },
        ],
      },
      {
        id: 'classical',
        label: 'Pattern C · A classical concert',
        title: '演奏会に誘い感想を話す',
        lines: [
          { speaker: 'A', en: "There's a free classical concert at the park tonight.", ja: '今夜、公園で無料のクラシックコンサートがあるよ。' },
          { speaker: 'B', en: 'Do we have to book tickets?', ja: 'チケットを予約しなきゃいけない？' },
          { speaker: 'A', en: 'No, we can just turn up.', ja: 'ううん、ただ行けばいいだけだよ。' },
          { speaker: 'B', en: 'That was really impressive!', ja: '本当に素晴らしかった！' },
        ],
      },
    ],
    tip: 'gig はライブ、turn up は現れる、queue はイギリス英語で「列」です。フェスやライブでは、この3つを聞き取れると案内が楽になります。',
  },
  practice: {
    title: 'コンサートとフェスの案内を、自然に声にする',
    instructions: '日本語の説明はここまで。入場、出演者、待ち合わせ、演奏への感想を英語だけで声に重ねます。',
    coreHeading: 'まずは、音楽イベントでそのまま使える一文から。',
    dialogueHeading: '入場して、合流して、感動を分かち合う流れを感じる。',
    dialogueDescription: 'スタッフの案内を聞き、友人と場所や出演時間を確認し、演奏の感想を返します。',
    finishTitle: '次に音楽イベントへ行ったら、ひとつだけ英語で質問か感想を言ってみましょう。',
    corePhrases: [
      { phrase: 'Have your bags ready for inspection, please.', context: '手荷物検査に対応する', rate: 0.76 },
      { phrase: "What time does the main gig start?", context: 'メイン出演の時間を尋ねる', rate: 0.8 },
      { phrase: "Let's find the refreshment stand.", context: '売店を探す', rate: 0.84 },
      { phrase: "I'll meet you back in the main arena.", context: '友人と合流する', rate: 0.78 },
      { phrase: "Who's playing on the main stage tonight?", context: '出演者を尋ねる', rate: 0.76 },
      { phrase: 'Is the campsite open yet?', context: 'キャンプサイトを確認する', rate: 0.82 },
      { phrase: "I can't find my tent.", context: '場所が分からないと伝える', rate: 0.84 },
      { phrase: 'Do we have to book tickets?', context: '予約の必要を尋ねる', rate: 0.82 },
      { phrase: 'That was really impressive!', context: '演奏をほめる', rate: 0.86 },
      { phrase: 'What an amazing performance!', context: '感動を伝える', rate: 0.8 },
    ],
    dialogues: [
      { title: 'At a concert', lines: ['What time does the main gig start?', '9pm, but the support band has just come on.', "I'll meet you back in the main arena."] },
      { title: 'At an open-air festival', lines: ["Who's playing on the main stage tonight?", "Here's the line-up for the whole weekend. Enjoy!", "I can't find my tent."] },
      { title: 'A classical concert', lines: ["There's a free classical concert at the park tonight.", 'Do we have to book tickets?', 'No, we can just turn up.'] },
    ],
    natural: [
      { full: 'What time does the main concert begin?', natural: 'What time does the main gig start?' },
      { full: 'I will meet you again in the main arena.', natural: "I'll meet you back in the main arena." },
      { full: 'We do not need to reserve tickets.', natural: 'We can just turn up.' },
    ],
  },
}
