/** Chapter 69 · Cycling. */
export const cyclingLesson = {
  id: 'cycling',
  kind: 'cycling',
  number: '69',
  title: '第69章に入る前に：なぜ「自転車に関する英語」を学ぶのでしょうか？',
  enTitle: 'Cycling',
  ja: '自転車の購入やレンタル、トラブルの伝え方、そして自転車のパーツに関する表現を学びます。',
  cando: '自転車の用途や予算を伝え、レンタサイクルの使い方や故障の状態を確認できる。',
  learn: {
    intro: [
      '自転車は、通勤や買い物、旅行など、日常の移動にとても便利な手段です。自分に合った自転車を選んだり、レンタルしたりする場面があります。',
      '乗っている途中にトラブルが起きたら、チェーン、タイヤ、ブレーキ、バッテリーなどの状態を分かりやすく説明することも大切です。',
      'この章では、自転車の購入やレンタル、トラブルの伝え方、そして自転車のパーツに関する表現を学びます。',
    ],
    functions: [
      ['01', '用途と予算を伝える'],
      ['02', '自転車を試乗・レンタルする'],
      ['03', '故障や状態を説明する'],
      ['04', 'パーツと修理を確認する'],
    ],
    buying: {
      title: '自転車の購入と質問',
      enTitle: 'Buying a bike & questions',
      intro: '通勤や街中での用途、予算、試乗、公共交通機関への持ち込みについて尋ねます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'I need a bike to get to and from work.', meaning: '通勤用に自転車が必要なんです。', context: '用途を伝える', register: 'neutral' },
        { phrase: "Okay, let's look at some commuter bikes.", meaning: 'わかりました。通勤用自転車をいくつか見てみましょう。', context: '商品を提案する', register: 'friendly' },
        { phrase: 'What do you want to use the e-bike for?', meaning: 'その電動アシスト自転車を何に使う予定ですか？', context: '用途を尋ねる', register: 'polite' },
        { phrase: 'For getting around town, mainly.', meaning: '主に街中を移動するためです。', context: '用途に答える', register: 'neutral' },
        { phrase: 'What type of bike do you want?', meaning: 'どのようなタイプの自転車をご希望ですか？', context: 'タイプを尋ねる', register: 'polite' },
        { phrase: "What's your budget?", meaning: 'ご予算はいくらですか？', context: '予算を尋ねる', register: 'polite' },
        { phrase: 'Would you like a test ride?', meaning: '試乗してみますか？', context: '試乗を勧める', register: 'polite' },
        { phrase: 'Will you be taking it on public transport?', meaning: '公共交通機関に載せる予定はありますか？', context: '持ち運び方を尋ねる', register: 'polite' },
      ],
      recognition: [
        { phrase: 'commuter bike', meaning: '通勤用自転車', note: '日常の移動向けの実用的な自転車です。' },
        { phrase: 'e-bike', meaning: '電動アシスト自転車', note: 'electric bike の短い言い方です。' },
        { phrase: 'get to and from work', meaning: '職場への往復をする', note: '通勤の行き帰りをまとめて表します。' },
        { phrase: 'test ride', meaning: '試乗', note: '購入前に乗り心地を確かめます。' },
      ],
    },
    hiring: {
      title: 'レンタサイクルの利用',
      enTitle: 'Hiring a bike',
      intro: 'シェアサイクルの借り方や、乗った後に返却・駐輪する場所を確認します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'How do I hire this city bike?', meaning: 'このシェアサイクルはどうやって借りるのですか？', context: '借り方を尋ねる', register: 'polite' },
        { phrase: 'You just need to download the app!', meaning: 'アプリをダウンロードするだけですよ！', context: '利用方法を案内する', register: 'friendly' },
        { phrase: 'Where can we park after our ride?', meaning: '乗った後はどこに停められますか？', context: '返却場所を尋ねる', register: 'polite' },
        { phrase: 'There are parking bays all over town!', meaning: '街中に専用の駐輪スペースがありますよ！', context: '駐輪場所を案内する', register: 'friendly' },
      ],
      recognition: [
        { phrase: 'hire', meaning: '有料で一時的に借りる', note: 'イギリス英語で rent にあたります。' },
        { phrase: 'city bike', meaning: 'シェアサイクル・街乗り自転車', note: '街中のレンタサイクルを表します。' },
        { phrase: 'parking bay', meaning: '駐輪スペース・ポート', note: '決められた返却区画です。' },
        { phrase: 'after our ride', meaning: '乗った後に', note: '利用後の返却について尋ねます。' },
      ],
    },
    problems: {
      title: '自転車のトラブル',
      enTitle: 'Bike problems',
      intro: 'チェーン、タイヤ、ブレーキ、バッテリーなどの不具合を短く正確に伝えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "What's up with the bike?", meaning: 'その自転車、どうしたの？', context: '問題を尋ねる', register: 'casual' },
        { phrase: 'The chain is broken.', meaning: 'チェーンが切れています。', context: 'チェーンの故障を伝える', register: 'neutral' },
        { phrase: 'The front tyre is flat.', meaning: '前輪がパンクしています。', context: 'タイヤの状態を伝える', register: 'neutral' },
        { phrase: 'The brakes are loose.', meaning: 'ブレーキが緩んでいます。', context: 'ブレーキの不具合を伝える', register: 'neutral' },
        { phrase: 'The battery needs charging.', meaning: 'バッテリーの充電が必要です。', context: 'e-bikeの不具合を伝える', register: 'neutral' },
        { phrase: 'I have a flat tyre.', meaning: 'タイヤがパンクしちゃった。', context: 'パンクを伝える', register: 'casual' },
      ],
      recognition: [
        { phrase: 'flat', meaning: '空気が抜けた・パンクした', note: 'flat tyre でパンクしたタイヤです。' },
        { phrase: 'loose', meaning: '緩んでいる', note: 'brakes are loose のように状態を伝えます。' },
        { phrase: 'needs charging', meaning: '充電が必要', note: '電動自転車のバッテリーに使います。' },
        { phrase: 'broken', meaning: '壊れている・切れている', note: 'chain is broken のように使います。' },
      ],
    },
    parts: {
      title: '自転車のパーツ',
      enTitle: 'Parts of a bicycle',
      intro: '自転車の各部位と、修理を依頼するときに必要な基本語彙を整理します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'saddle', meaning: 'サドル', context: 'パーツ', register: 'neutral' },
        { phrase: 'frame', meaning: 'フレーム', context: 'パーツ', register: 'neutral' },
        { phrase: 'handlebars', meaning: 'ハンドルバー', context: 'パーツ', register: 'neutral' },
        { phrase: 'light', meaning: 'ライト・前照灯', context: '安全装備', register: 'neutral' },
        { phrase: 'pedal', meaning: 'ペダル', context: 'パーツ', register: 'neutral' },
        { phrase: 'wheel', meaning: 'ホイール・車輪', context: 'パーツ', register: 'neutral' },
        { phrase: 'spokes', meaning: 'スポーク', context: '車輪', register: 'neutral' },
        { phrase: 'chain', meaning: 'チェーン', context: '駆動部', register: 'neutral' },
        { phrase: 'gears', meaning: 'ギア・変速機', context: '駆動部', register: 'neutral' },
        { phrase: 'tyre', meaning: 'タイヤ', context: '車輪', register: 'regional' },
        { phrase: 'brake', meaning: 'ブレーキ', context: '安全装備', register: 'neutral' },
        { phrase: 'helmet', meaning: 'ヘルメット', context: '安全装備', register: 'neutral' },
        { phrase: 'to repair', meaning: '修理する', context: '動詞', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'tyre', meaning: 'タイヤ', note: 'アメリカ英語では tire と綴ります。' },
        { phrase: 'handlebars', meaning: 'ハンドルバー', note: '通常複数形で使います。' },
        { phrase: 'gears', meaning: 'ギア・変速機', note: 'gear change や gears とも言います。' },
        { phrase: 'repair', meaning: '修理する', note: 'bike repair で自転車修理です。' },
      ],
    },
    dialogues: [
      {
        id: 'buying',
        label: 'Pattern A · Buying a bike',
        title: '用途と試乗について相談する',
        lines: [
          { speaker: 'A', en: 'I need a bike to get to and from work.', ja: '通勤用に自転車が必要なんです。' },
          { speaker: 'B', en: "Okay, let's look at some commuter bikes.", ja: 'わかりました。通勤用自転車を見てみましょう。' },
          { speaker: 'A', en: "What's your budget?", ja: 'ご予算はいくらですか？' },
          { speaker: 'B', en: 'Would you like a test ride?', ja: '試乗してみますか？' },
        ],
      },
      {
        id: 'hiring',
        label: 'Pattern B · Hiring a bike',
        title: 'シェアサイクルを借りて返す',
        lines: [
          { speaker: 'A', en: 'How do I hire this city bike?', ja: 'このシェアサイクルはどうやって借りるのですか？' },
          { speaker: 'B', en: 'You just need to download the app!', ja: 'アプリをダウンロードするだけですよ！' },
          { speaker: 'A', en: 'Where can we park after our ride?', ja: '乗った後はどこに停められますか？' },
          { speaker: 'B', en: 'There are parking bays all over town!', ja: '街中に専用の駐輪スペースがありますよ！' },
        ],
      },
      {
        id: 'problems',
        label: 'Pattern C · Bike problems',
        title: '故障の状態を説明する',
        lines: [
          { speaker: 'A', en: "What's up with the bike?", ja: 'その自転車、どうしたの？' },
          { speaker: 'B', en: 'The front tyre is flat.', ja: '前輪がパンクしています。' },
          { speaker: 'A', en: 'The brakes are loose.', ja: 'ブレーキが緩んでいます。' },
          { speaker: 'B', en: 'The battery needs charging.', ja: 'バッテリーの充電が必要です。' },
        ],
      },
    ],
    tip: 'flat tyre は「パンクしたタイヤ」、tyre はイギリス英語の綴りです。レンタサイクルを借りるときはイギリス英語で hire、アメリカ英語で rent と言います。通勤用自転車は commuter bike、街中の返却区画は parking bay と表現します。',
  },
  practice: {
    title: '自転車の用途とトラブルを、英語で説明する',
    instructions: '日本語訳は見ずに、購入、レンタル、故障、パーツの表現を声に重ねます。',
    coreHeading: 'まずは、自転車を何に使うか伝える一文から。',
    dialogueHeading: '購入、レンタル、トラブルの場面で役を切り替える。',
    dialogueDescription: '自分に合う自転車を相談する、シェアサイクルを借りる、故障の状態を伝える3つの場面を練習します。',
    finishTitle: '次に自転車に乗るとき、用途かパーツの英語をひとつ使ってみましょう。',
    corePhrases: [
      { phrase: 'I need a bike to get to and from work.', context: '用途を伝える', rate: 0.76 },
      { phrase: "Okay, let's look at some commuter bikes.", context: '商品を提案する', rate: 0.76 },
      { phrase: 'What do you want to use the e-bike for?', context: '用途を尋ねる', rate: 0.74 },
      { phrase: "What's your budget?", context: '予算を尋ねる', rate: 0.86 },
      { phrase: 'Would you like a test ride?', context: '試乗を勧める', rate: 0.82 },
      { phrase: 'How do I hire this city bike?', context: 'レンタル方法を尋ねる', rate: 0.76 },
      { phrase: 'Where can we park after our ride?', context: '返却場所を尋ねる', rate: 0.76 },
      { phrase: "What's up with the bike?", context: '問題を尋ねる', rate: 0.84 },
      { phrase: 'The chain is broken.', context: 'チェーンの故障を伝える', rate: 0.84 },
      { phrase: 'The front tyre is flat.', context: 'パンクを伝える', rate: 0.82 },
      { phrase: 'The brakes are loose.', context: 'ブレーキの不具合を伝える', rate: 0.8 },
      { phrase: 'The battery needs charging.', context: 'バッテリーの状態を伝える', rate: 0.78 },
    ],
    dialogues: [
      { title: 'Buying a bike', lines: ['I need a bike to get to and from work.', "Okay, let's look at some commuter bikes.", "What's your budget?", 'Would you like a test ride?'] },
      { title: 'Hiring a bike', lines: ['How do I hire this city bike?', 'You just need to download the app!', 'Where can we park after our ride?', 'There are parking bays all over town!'] },
      { title: 'Bike problems', lines: ["What's up with the bike?", 'The front tyre is flat.', 'The brakes are loose.', 'The battery needs charging.'] },
    ],
    natural: [
      { full: 'I need a bicycle for traveling to and from my workplace.', natural: 'I need a bike to get to and from work.' },
      { full: 'Could I rent this shared bicycle for the city?', natural: 'How do I hire this city bike?' },
      { full: 'The front tire has lost all its air.', natural: 'The front tyre is flat.' },
    ],
  },
}
