/** Chapter 38 · At the DIY store. */
export const diyLesson = {
  id: 'diy-store',
  kind: 'diy-store',
  number: '38',
  title: '第38章に入る前に：なぜ「DIYストアで使う英語」を学ぶのでしょうか？',
  enTitle: 'At the DIY store',
  ja: '作業の目的を説明し、工具や材料について相談する英語を学びます。',
  cando: 'DIYの作業を英語で説明し、必要な工具・材料・安全上の確認を尋ねられる。',
  learn: {
    intro: [
      'DIYは、多くの場合、家の中の何かを直したり、改善したり、作ったりするところから始まります。そのためには、まず自分が何をしたいのかを説明し、それに必要な道具や材料、アドバイスを探す必要があります。',
      'DIYストアでのコミュニケーションでは、作業の目的をできるだけ明確に伝えることが大切です。作業を説明できれば、店員から必要な道具や材料を紹介してもらいやすくなります。',
      'この章では、作業についてアドバイスを求める表現、工具や材料を探す表現、そして基本的なDIY作業の英語を学びます。',
    ],
    functions: [
      ['01', '作業を説明する'],
      ['02', 'アドバイスを求める'],
      ['03', '道具と材料を探す'],
      ['04', '安全と年齢制限を確認する'],
    ],
    advice: {
      title: '店員にアドバイスを求める',
      enTitle: 'Asking for advice',
      intro: '作業内容を伝え、「何がお勧めですか」「何が必要ですか」と具体的に尋ねます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'What would you recommend for sanding a table?', meaning: 'テーブルにやすりをかけるには、何がお勧めですか？', context: '作業に合う商品を尋ねる', register: 'polite' },
        { phrase: 'What do I need for tiling my bathroom?', meaning: 'バスルームにタイルを貼るには、何が必要ですか？', context: '必要な道具を尋ねる', register: 'polite' },
        { phrase: "What's best for plastering walls?", meaning: '壁にプラスターを塗るには、何が一番いいですか？', context: '材料を比較する', register: 'polite' },
        { phrase: 'What have you got for filling a crack?', meaning: 'ひび割れを埋めるには、どんな商品がありますか？', context: '補修用品を探す', register: 'casual' },
        { phrase: 'What should I use for painting my kitchen?', meaning: 'キッチンの塗装には何を使えばいいですか？', context: '塗料を相談する', register: 'polite' },
        { phrase: "I'm after some advice about plastering.", meaning: 'プラスター塗りについてアドバイスが欲しいのですが。', context: '相談を始める', register: 'casual' },
        { phrase: "I'd like to remodel my bedroom.", meaning: '寝室をリフォームしたいんです。', context: 'したいことを説明する', register: 'neutral' },
        { phrase: 'Could you recommend a paint for a damp room?', meaning: '湿気の多い部屋に合う塗料を勧めてもらえますか？', context: '部屋の条件を伝える', register: 'polite' },
      ],
      recognition: [
        { phrase: "I'm after...", meaning: '〜を探している・求めている', note: "I'm looking for... と同じように使える自然な表現です。" },
        { phrase: 'for + -ing', meaning: '〜するための', note: 'for sanding a table のように作業の目的を続けます。' },
        { phrase: 'remodel', meaning: 'リフォームする', note: '部屋や家を改装することです。' },
      ],
    },
    tools: {
      title: '道具を探す・質問する',
      enTitle: 'Buying tools',
      intro: '売り場の場所、商品の種類、コードレスかどうかなどを確認します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Can you show me to the tools section?', meaning: '工具売り場に案内してもらえますか？', context: '売り場を尋ねる', register: 'polite' },
        { phrase: "I'm looking for a hammer and nails.", meaning: 'ハンマーと釘を探しています。', context: '必要な道具を伝える', register: 'neutral' },
        { phrase: 'Where can I find a saw?', meaning: 'のこぎりはどこにありますか？', context: '商品を探す', register: 'polite' },
        { phrase: 'Where are the screws?', meaning: 'ネジはどこですか？', context: '売り場の場所を尋ねる', register: 'neutral' },
        { phrase: 'Who can I ask about drills?', meaning: 'ドリルについては誰に聞けばいいですか？', context: '担当者を尋ねる', register: 'polite' },
        { phrase: 'What kind of screwdrivers do you sell?', meaning: 'どんな種類のドライバーを売っていますか？', context: '商品の種類を尋ねる', register: 'polite' },
        { phrase: 'Have you got any cordless power tools?', meaning: 'コードレスの電動工具はありますか？', context: '電動工具を探す', register: 'casual' },
        { phrase: 'Will I need ID to buy this saw?', meaning: 'こののこぎりを買うのに身分証明書は必要ですか？', context: '購入条件を確認する', register: 'polite' },
      ],
      recognition: [
        { phrase: 'tools section', meaning: '工具売り場', note: '店員に売り場を案内してもらうときに使います。' },
        { phrase: 'cordless', meaning: 'コードレスの', note: '電源コードなしで使える工具を表します。' },
        { phrase: 'ID', meaning: '身分証明書', note: '年齢確認などで提示する identification の短縮形です。' },
      ],
    },
    vocabulary: {
      title: 'DIYのボキャブラリー',
      enTitle: 'Vocabulary · Tools and home improvements',
      intro: '基本的な工具と、家を直したり改善したりする作業の動詞を覚えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'hammer', meaning: 'ハンマー・金づち', context: '釘を打つ道具', register: 'neutral' },
        { phrase: 'nail', meaning: '釘', context: '木材などを固定するもの', register: 'neutral' },
        { phrase: 'screwdriver', meaning: 'ドライバー', context: 'ネジを回す道具', register: 'neutral' },
        { phrase: 'screw', meaning: 'ネジ', context: '部材を固定するもの', register: 'neutral' },
        { phrase: 'saw', meaning: 'のこぎり', context: '木材などを切る道具', register: 'neutral' },
        { phrase: 'drill', meaning: 'ドリル', context: '穴を開ける電動工具', register: 'neutral' },
        { phrase: 'to paint', meaning: 'ペンキを塗る', context: '壁や家具を塗装する', register: 'neutral' },
        { phrase: 'to plaster', meaning: '漆喰・プラスターを塗る', context: '壁を仕上げる', register: 'neutral' },
        { phrase: 'to sand', meaning: 'やすりをかける', context: '表面をなめらかにする', register: 'neutral' },
        { phrase: 'to tile', meaning: 'タイルを貼る', context: '壁や床にタイルを貼る', register: 'neutral' },
        { phrase: 'to fill', meaning: 'ひび割れや穴を埋める', context: '補修する', register: 'neutral' },
        { phrase: 'to hang', meaning: '絵などを壁に掛ける', context: '壁に物を取り付ける', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'power tools', meaning: '電動工具', note: 'drill など、電気で動く工具の総称です。' },
        { phrase: 'sand', meaning: 'やすりをかける', note: '砂を表す sand と同じつづりですが、ここでは動詞です。' },
        { phrase: 'fill a crack', meaning: 'ひび割れを埋める', note: '壁や家具の補修について話すときに使います。' },
      ],
    },
    dialogues: [
      {
        id: 'advice',
        label: 'Pattern A · Asking for advice',
        title: '作業に合う商品を相談する',
        lines: [
          { speaker: 'A', en: 'What would you recommend for sanding a table?', ja: 'テーブルにやすりをかけるには、何がお勧めですか？' },
          { speaker: 'B', en: "I'd start with medium-grit sandpaper.", ja: '中くらいの粗さのサンドペーパーから始めるといいでしょう。' },
          { speaker: 'A', en: 'Do I need anything else?', ja: 'ほかに何か必要ですか？' },
          { speaker: 'B', en: 'Wear a mask and protect the floor.', ja: 'マスクを着けて、床を保護してください。' },
        ],
      },
      {
        id: 'tools',
        label: 'Pattern B · Buying tools',
        title: '道具の売り場と種類を尋ねる',
        lines: [
          { speaker: 'A', en: 'Can you show me to the tools section?', ja: '工具売り場に案内してもらえますか？' },
          { speaker: 'B', en: "It's at the back, next to the timber.", ja: '奥の、木材売り場の隣です。' },
          { speaker: 'A', en: 'Have you got any cordless power tools?', ja: 'コードレスの電動工具はありますか？' },
          { speaker: 'B', en: "Yes, they're on the second shelf.", ja: 'はい、2段目の棚にあります。' },
        ],
      },
      {
        id: 'safety',
        label: 'Pattern C · Safety check',
        title: 'のこぎりの購入条件を確認する',
        lines: [
          { speaker: 'A', en: 'Will I need ID to buy this saw?', ja: 'こののこぎりを買うのに身分証明書は必要ですか？' },
          { speaker: 'B', en: 'Yes, you must be 18 or over in this store.', ja: 'はい、この店では18歳以上である必要があります。' },
          { speaker: 'A', en: 'Where are the screws?', ja: 'ネジはどこですか？' },
          { speaker: 'B', en: "They're in aisle four, by the screwdrivers.", ja: '4番通路、ドライバーのそばにあります。' },
        ],
      },
    ],
    tip: 'saw などの刃物を買うときに ID が必要かどうかは、国や店によって異なります。Will I need ID...? と聞けば、購入条件を丁寧に確認できます。作業について尋ねるときは for + -ing を使い、for sanding a table のように目的を伝えましょう。',
  },
  practice: {
    title: 'DIYストアで、作業と道具を英語で相談する',
    instructions: '日本語の説明はここまで。作業の目的を伝え、工具や材料を尋ね、安全条件を確認する英語を声に重ねます。',
    coreHeading: 'まずは、DIYストアでそのまま使える一文から。',
    dialogueHeading: '作業を説明し、道具を選び、安全を確認する。',
    dialogueDescription: '店員にアドバイスを求める声、工具を探す声、購入条件を確認する声を切り替えます。',
    finishTitle: '次に何かを直すとき、作業の目的をひとつ英語で説明してみましょう。',
    corePhrases: [
      { phrase: 'What would you recommend for sanding a table?', context: '作業に合う商品を尋ねる', rate: 0.76 },
      { phrase: 'What do I need for tiling my bathroom?', context: '必要な道具を尋ねる', rate: 0.76 },
      { phrase: "What's best for plastering walls?", context: '材料を比較する', rate: 0.8 },
      { phrase: 'What have you got for filling a crack?', context: '補修用品を探す', rate: 0.78 },
      { phrase: 'What should I use for painting my kitchen?', context: '塗料を相談する', rate: 0.76 },
      { phrase: "I'm after some advice about plastering.", context: '相談を始める', rate: 0.8 },
      { phrase: 'Can you show me to the tools section?', context: '工具売り場を尋ねる', rate: 0.78 },
      { phrase: "I'm looking for a hammer and nails.", context: '必要な道具を伝える', rate: 0.82 },
      { phrase: 'Where can I find a saw?', context: '商品を探す', rate: 0.84 },
      { phrase: 'Have you got any cordless power tools?', context: '電動工具を探す', rate: 0.76 },
      { phrase: 'Will I need ID to buy this saw?', context: '購入条件を確認する', rate: 0.76 },
    ],
    dialogues: [
      { title: 'Asking for advice', lines: ['What would you recommend for sanding a table?', "I'd start with medium-grit sandpaper.", 'Do I need anything else?', 'Wear a mask and protect the floor.'] },
      { title: 'Buying tools', lines: ['Can you show me to the tools section?', "It's at the back, next to the timber.", 'Have you got any cordless power tools?', "Yes, they're on the second shelf."] },
      { title: 'Safety check', lines: ['Will I need ID to buy this saw?', 'Yes, you must be 18 or over in this store.', 'Where are the screws?', "They're in aisle four, by the screwdrivers."] },
    ],
    natural: [
      { full: 'What do you recommend for sanding this table?', natural: 'What would you recommend for sanding a table?' },
      { full: 'What do I need to tile my bathroom?', natural: 'What do I need for tiling my bathroom?' },
      { full: 'I need advice about plastering.', natural: "I'm after some advice about plastering." },
    ],
  },
}
