/** Chapter 78 · Finding your way. */
export const findingWayLesson = {
  id: 'finding-way',
  kind: 'finding-way',
  number: '78',
  title: '第78章に入る前に：なぜ「道を尋ねる英語」を学ぶのでしょうか？',
  enTitle: 'Finding your way',
  ja: '道の尋ね方、道案内の聞き方、場所や方向を説明するための基本表現を学びます。',
  cando: '目的地への行き方を尋ね、曲がる・渡る・通り過ぎるなどの道案内を理解して移動できる。',
  learn: {
    intro: [
      '知らない場所では、地図があっても、どちらへ進めばいいのか分からなくなることがあります。そんなとき、人に道を尋ねたり、教えてもらった説明を理解したりする力が必要です。',
      '目的地をはっきり伝え、「曲がる・渡る・通り過ぎる」などの基本的な方向表現を理解することが大切です。',
      'この章では、道の尋ね方、道案内の聞き方、そして場所や方向を説明するための基本表現を学びます。',
    ],
    functions: [
      ['01', '目的地への道を丁寧に尋ねる'],
      ['02', '曲がる・進む・渡るを聞き取る'],
      ['03', '目印との位置関係を確認する'],
      ['04', '教えてもらったら感謝を伝える'],
    ],
    ask: {
      title: '道を尋ねる',
      enTitle: 'Asking for directions',
      intro: 'Excuse me で呼びかけ、目的地への行き方を丁寧に尋ねます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Excuse me, do you know the way to the bus station?', meaning: 'すみません、バスターミナルへの道を知っていますか？', context: '道を尋ねる', register: 'polite' },
        { phrase: "Yes, go straight ahead and it's on your left.", meaning: 'はい、まっすぐ進むと左手にありますよ。', context: '道を案内する', register: 'polite' },
        { phrase: 'Can you tell me how to get to the museum?', meaning: '美術館への行き方を教えていただけますか？', context: '行き方を尋ねる', register: 'polite' },
        { phrase: 'Let me think... Take the first left at the roundabout.', meaning: 'ええと、そうですね…。ラウンドアバウトの1つ目の角を左に曲がってください。', context: '曲がり方を案内する', register: 'friendly' },
      ],
      recognition: [
        { phrase: 'Excuse me', meaning: 'すみません', note: '知らない人に声をかけるクッション表現です。' },
        { phrase: 'the way to', meaning: '〜への道', note: '目的地への道順を尋ねます。' },
        { phrase: 'how to get to', meaning: '〜への行き方', note: '具体的な行き方を尋ねる定番表現です。' },
        { phrase: 'roundabout', meaning: 'ラウンドアバウト・環状交差点', note: '円形の交差点を指します。' },
      ],
    },
    follow: {
      title: '道案内・説明に従う',
      enTitle: 'Following directions',
      intro: 'ステップごとの道案内を聞き、最後に目的地の位置とお礼を確認します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Hi there, is the bank this way?', meaning: 'こんにちは、銀行はこちらの方向で合っていますか？', context: '方向を確認する', register: 'polite' },
        { phrase: 'No, you need to go past the church...', meaning: 'いいえ、教会の前を通り過ぎて…。', context: '目印を案内する', register: 'neutral' },
        { phrase: '...and take the first left...', meaning: '…1つ目の角を左に曲がって…。', context: '曲がり方を案内する', register: 'neutral' },
        { phrase: '...then cross the road...', meaning: '…それから道路を渡って…。', context: '横断を案内する', register: 'neutral' },
        { phrase: '...and turn right at the traffic lights.', meaning: '…信号のところで右に曲がってください。', context: '信号での曲がり方を案内する', register: 'neutral' },
        { phrase: "It's just next to the hospital.", meaning: '病院のすぐ隣にありますよ。', context: '位置を説明する', register: 'neutral' },
        { phrase: 'Thanks for your help!', meaning: '助かりました、ありがとうございます！', context: '案内へのお礼を言う', register: 'friendly' },
      ],
      recognition: [
        { phrase: 'go past', meaning: '〜の前を通り過ぎる', note: '目印を通過する道順です。' },
        { phrase: 'take the first left', meaning: '1つ目の角を左に曲がる', note: '角の順番を具体的に指定します。' },
        { phrase: 'cross the road', meaning: '道路を渡る', note: '道を横断する動作です。' },
        { phrase: 'at the traffic lights', meaning: '信号のところで', note: '信号を目印に曲がる場所を示します。' },
      ],
    },
    vocab: {
      title: '位置・方向に関するボキャブラリー',
      enTitle: 'Vocabulary directions',
      intro: '曲がる、進む、渡る、目印との位置関係を示す基本表現を整理します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'turn left', meaning: '左に曲がる', context: '方向', register: 'neutral' },
        { phrase: 'turn right', meaning: '右に曲がる', context: '方向', register: 'neutral' },
        { phrase: 'go straight ahead', meaning: 'まっすぐ進む', context: '方向', register: 'neutral' },
        { phrase: 'first right', meaning: '1つ目の角を右', context: '角', register: 'neutral' },
        { phrase: 'second left', meaning: '2つ目の角を左', context: '角', register: 'neutral' },
        { phrase: 'go round the corner', meaning: '角を曲がる・回り込む', context: '角', register: 'neutral' },
        { phrase: 'cross the road', meaning: '道路を渡る', context: '横断', register: 'neutral' },
        { phrase: 'go past', meaning: '〜の前を通り過ぎる', context: '目印', register: 'neutral' },
        { phrase: 'next to', meaning: '〜の隣に', context: '位置', register: 'neutral' },
        { phrase: 'behind', meaning: '〜の後ろに', context: '位置', register: 'neutral' },
        { phrase: 'in front of', meaning: '〜の前に', context: '位置', register: 'neutral' },
        { phrase: 'opposite', meaning: '〜の向かいに', context: '位置', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'straight ahead', meaning: 'まっすぐ前へ', note: '曲がらずに進む方向です。' },
        { phrase: 'first right / second left', meaning: '1つ目の右 / 2つ目の左', note: '曲がる角の順番を示します。' },
        { phrase: 'next to / opposite', meaning: '隣 / 向かい', note: '建物どうしの位置関係を表します。' },
        { phrase: 'behind / in front of', meaning: '後ろ / 前', note: '目印との前後関係を説明します。' },
      ],
    },
    dialogues: [
      {
        id: 'ask',
        label: 'Pattern A · Asking for directions',
        title: '目的地への道を尋ねる',
        lines: [
          { speaker: 'A', en: 'Excuse me, do you know the way to the bus station?', ja: 'すみません、バスターミナルへの道を知っていますか？' },
          { speaker: 'B', en: "Yes, go straight ahead and it's on your left.", ja: 'はい、まっすぐ進むと左手にありますよ。' },
          { speaker: 'A', en: 'Can you tell me how to get to the museum?', ja: '美術館への行き方を教えていただけますか？' },
          { speaker: 'B', en: 'Take the first left at the roundabout.', ja: 'ラウンドアバウトの1つ目の角を左に曲がってください。' },
        ],
      },
      {
        id: 'follow',
        label: 'Pattern B · Following directions',
        title: 'ステップごとの案内を理解する',
        lines: [
          { speaker: 'A', en: 'Hi there, is the bank this way?', ja: 'こんにちは、銀行はこちらの方向で合っていますか？' },
          { speaker: 'B', en: 'Go past the church and take the first left.', ja: '教会の前を通り過ぎて、1つ目の角を左に曲がってください。' },
          { speaker: 'B', en: 'Then cross the road and turn right at the traffic lights.', ja: 'それから道路を渡って、信号のところで右に曲がってください。' },
          { speaker: 'A', en: 'Thanks for your help!', ja: '助かりました、ありがとうございます！' },
        ],
      },
      {
        id: 'location',
        label: 'Pattern C · Describing a location',
        title: '目的地の位置を説明する',
        lines: [
          { speaker: 'A', en: 'Where is the pharmacy?', ja: '薬局はどこですか？' },
          { speaker: 'B', en: "It's just next to the hospital.", ja: '病院のすぐ隣にありますよ。' },
          { speaker: 'A', en: 'Is the café opposite the bank?', ja: 'カフェは銀行の向かいですか？' },
          { speaker: 'B', en: 'Yes, it is in front of the library.', ja: 'はい、図書館の前にあります。' },
        ],
      },
    ],
    tip: 'Excuse me で呼びかけてから Do you know the way to ...? や Can you tell me how to get to ...? と尋ねると丁寧です。take the first left のように角の順番を伝え、最後は Thanks for your help! で感謝を伝えます。',
  },
  practice: {
    title: '道順と位置を、英語で確認する',
    instructions: '日本語訳は見ずに、目的地、曲がり方、目印、位置関係の表現を声に重ねます。',
    coreHeading: 'まずは、道を尋ねる一文から。',
    dialogueHeading: '質問、道案内、位置説明の場面で役を切り替える。',
    dialogueDescription: '目的地への道を尋ねる、ステップごとの案内を理解する、目印との位置関係を説明する3つの場面を練習します。',
    finishTitle: '次に道に迷ったとき、目的地への行き方を英語でひとつ尋ねてみましょう。',
    corePhrases: [
      { phrase: 'Do you know the way to the bus station?', context: '道を尋ねる', rate: 0.82 },
      { phrase: "Go straight ahead and it's on your left.", context: 'まっすぐ進むと案内する', rate: 0.78 },
      { phrase: 'Can you tell me how to get to the museum?', context: '行き方を尋ねる', rate: 0.76 },
      { phrase: 'Take the first left at the roundabout.', context: '曲がり方を案内する', rate: 0.76 },
      { phrase: 'Is the bank this way?', context: '方向を確認する', rate: 0.84 },
      { phrase: 'Go past the church.', context: '目印を通り過ぎる', rate: 0.84 },
      { phrase: 'Take the first left.', context: '1つ目の角を左に曲がる', rate: 0.86 },
      { phrase: 'Then cross the road.', context: '道路を渡る', rate: 0.86 },
      { phrase: 'Turn right at the traffic lights.', context: '信号で右に曲がる', rate: 0.78 },
      { phrase: "It's just next to the hospital.", context: '隣の位置を説明する', rate: 0.82 },
      { phrase: 'Thanks for your help!', context: 'お礼を言う', rate: 0.86 },
      { phrase: 'The café is opposite the bank.', context: '向かいの位置を説明する', rate: 0.8 },
    ],
    dialogues: [
      { title: 'Asking for directions', lines: ['Do you know the way to the bus station?', "Go straight ahead and it's on your left.", 'Can you tell me how to get to the museum?', 'Take the first left at the roundabout.'] },
      { title: 'Following directions', lines: ['Is the bank this way?', 'Go past the church and take the first left.', 'Then cross the road and turn right at the traffic lights.', 'Thanks for your help!'] },
      { title: 'Describing a location', lines: ['Where is the pharmacy?', "It's just next to the hospital.", 'Is the café opposite the bank?', 'Yes, it is in front of the library.'] },
    ],
    natural: [
      { full: 'Could you tell me the route to the bus station?', natural: 'Do you know the way to the bus station?' },
      { full: 'Please continue in a straight line; the destination will be on your left.', natural: "Go straight ahead and it's on your left." },
      { full: 'I appreciate your assistance with finding the location.', natural: 'Thanks for your help!' },
    ],
  },
}
