/** Chapter 71 · At the garage. */
export const garageLesson = {
  id: 'garage',
  kind: 'garage',
  number: '71',
  title: '第71章に入る前に：なぜ「整備工場で使う英語」を学ぶのでしょうか？',
  enTitle: 'At the garage',
  ja: '点検の予約、車の不具合の説明、そして修理に必要な基本的な表現を学びます。',
  cando: '点検を予約し、車の症状がどこでいつから起きているかを整備士に具体的に説明できる。',
  learn: {
    intro: [
      '車に問題が起きたとき、自分で原因を直せなくても、どんな症状が出ているのかを説明する必要があります。',
      'どこがおかしいのか、いつから起きているのか、どんな状態なのかをできるだけ具体的に伝えることが大切です。',
      'この章では、点検の予約、車の不具合の説明、そして修理に必要な基本的な表現を学びます。',
    ],
    functions: [
      ['01', '点検と引き取り時間を予約する'],
      ['02', '警告灯やエンジンの症状を伝える'],
      ['03', 'ライト・タイヤ・窓の故障を説明する'],
      ['04', '車のパーツと修理を確認する'],
    ],
    service: {
      title: '車の点検・整備を予約する',
      enTitle: 'Booking a service',
      intro: '整備工場に電話をして点検を予約し、車の仕上がりと引き取り時間を確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'ABC Autos, how can I help?', meaning: 'ABCオートです。どのようなご用件でしょうか？', context: '整備工場で応対する', register: 'polite' },
        { phrase: 'Could I book my car in for a service, please?', meaning: '車の点検・整備を予約したいのですが。', context: '点検を予約する', register: 'polite' },
        { phrase: 'When will my car be ready?', meaning: '私の車はいつ仕上がりますか？', context: '完成時刻を尋ねる', register: 'polite' },
        { phrase: 'It should be ready to pick up at 5.30.', meaning: '5時30分には受け取れるようになっているはずです。', context: '引き取り時間を伝える', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'book my car in', meaning: '車を予約枠に入れる', note: '点検や修理を予約する定番表現です。' },
        { phrase: 'service', meaning: '定期点検・整備', note: '無料サービスではなく車の整備を指します。' },
        { phrase: 'be ready to pick up', meaning: '受け取れる状態になる', note: '車の完成時刻を伝えます。' },
        { phrase: 'at 5.30', meaning: '5時30分に', note: 'イギリス英語では時刻を 5.30 と書くことがあります。' },
      ],
    },
    faults: {
      title: '故障と修理の相談',
      enTitle: 'Faults and repairs',
      intro: '警告灯、オイル、エンジンなどの状態を説明し、整備士に確認をお願いします。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'What does this warning light mean? It keeps flashing...', meaning: 'この警告灯はどういう意味ですか？点滅し続けているのですが。', context: '警告灯を尋ねる', register: 'polite' },
        { phrase: 'Looks like your oil level is too low. Let me check it.', meaning: 'オイルの量が少なすぎるようですね。確認させてください。', context: 'オイルを確認する', register: 'neutral' },
        { phrase: 'So, what seems to be the problem?', meaning: 'それで、どのような問題が起きていますか？', context: '症状を尋ねる', register: 'polite' },
        { phrase: "I think the engine's overheating.", meaning: 'エンジンがオーバーヒートしているのだと思います。', context: 'エンジンの症状を伝える', register: 'neutral' },
        { phrase: "Okay, I'll take a look.", meaning: 'わかりました、見てみましょう。', context: '点検を引き受ける', register: 'friendly' },
      ],
      recognition: [
        { phrase: 'warning light', meaning: '警告灯', note: '車の異常を知らせるランプです。' },
        { phrase: 'keep flashing', meaning: '点滅し続ける', note: '同じ症状が続くことを表します。' },
        { phrase: 'oil level', meaning: 'オイル量', note: 'level が low か確認します。' },
        { phrase: 'overheating', meaning: 'オーバーヒートしている', note: 'エンジンの温度が上がりすぎる状態です。' },
      ],
    },
    problems: {
      title: '車のその他のトラブル',
      enTitle: 'More problems',
      intro: 'ライト、オイル、ハンドル、フロントガラス、タイヤの具体的な不具合を伝えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "The headlight isn't working.", meaning: 'ヘッドライトがつきません。', context: 'ライトの故障を伝える', register: 'neutral' },
        { phrase: 'The oil needs changing.', meaning: 'オイル交換が必要です。', context: 'オイル交換を伝える', register: 'neutral' },
        { phrase: 'The steering wheel is jammed.', meaning: 'ハンドルが動きません。', context: 'ハンドルの故障を伝える', register: 'neutral' },
        { phrase: 'The windscreen is cracked.', meaning: 'フロントガラスにひびが入っています。', context: 'ガラスの状態を伝える', register: 'neutral' },
        { phrase: 'The tyre keeps going down.', meaning: 'タイヤの空気が抜け続けています。', context: 'タイヤの症状を伝える', register: 'neutral' },
      ],
      recognition: [
        { phrase: "isn't working", meaning: '作動しない', note: 'ライトや電装品の故障に使います。' },
        { phrase: 'needs changing', meaning: '交換が必要', note: 'oil needs changing のように使います。' },
        { phrase: 'jammed', meaning: '詰まって動かない・ロックしている', note: 'steering wheel の状態を表します。' },
        { phrase: 'keeps going down', meaning: '空気が抜け続ける', note: 'タイヤの不具合を伝える表現です。' },
      ],
    },
    parts: {
      title: '車のパーツ',
      enTitle: 'Car parts',
      intro: '整備士に部品を伝えたり、修理や交換を依頼したりするための基本語彙です。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'windscreen', meaning: 'フロントガラス', context: '車体', register: 'regional' },
        { phrase: 'bonnet', meaning: 'ボンネット', context: '車体', register: 'regional' },
        { phrase: 'engine', meaning: 'エンジン', context: '動力', register: 'neutral' },
        { phrase: 'radiator', meaning: 'ラジエーター', context: 'エンジン周り', register: 'neutral' },
        { phrase: 'headlight', meaning: 'ヘッドライト', context: '照明', register: 'neutral' },
        { phrase: 'boot', meaning: 'トランク', context: '荷物入れ', register: 'regional' },
        { phrase: 'bumper', meaning: 'バンパー', context: '車体', register: 'neutral' },
        { phrase: 'steering wheel', meaning: 'ハンドル', context: '運転席', register: 'neutral' },
        { phrase: 'wheel', meaning: 'ホイール・車輪', context: '車輪', register: 'neutral' },
        { phrase: 'tyre', meaning: 'タイヤ', context: '車輪', register: 'regional' },
      ],
      recognition: [
        { phrase: 'windscreen', meaning: 'フロントガラス', note: 'アメリカ英語では windshield です。' },
        { phrase: 'bonnet', meaning: 'ボンネット', note: 'アメリカ英語では hood です。' },
        { phrase: 'boot', meaning: 'トランク', note: 'アメリカ英語では trunk です。' },
        { phrase: 'tyre', meaning: 'タイヤ', note: 'アメリカ英語では tire と綴ります。' },
      ],
    },
    dialogues: [
      {
        id: 'service',
        label: 'Pattern A · Booking a service',
        title: '点検を予約して引き取り時刻を確認する',
        lines: [
          { speaker: 'A', en: 'ABC Autos, how can I help?', ja: 'ABCオートです。どのようなご用件でしょうか？' },
          { speaker: 'B', en: 'Could I book my car in for a service, please?', ja: '車の点検を予約したいのですが。' },
          { speaker: 'A', en: 'When will my car be ready?', ja: '私の車はいつ仕上がりますか？' },
          { speaker: 'B', en: 'It should be ready to pick up at 5.30.', ja: '5時30分には受け取れるはずです。' },
        ],
      },
      {
        id: 'faults',
        label: 'Pattern B · Faults and repairs',
        title: '警告灯とエンジンの症状を説明する',
        lines: [
          { speaker: 'A', en: 'What does this warning light mean? It keeps flashing...', ja: 'この警告灯はどういう意味ですか？点滅し続けています。' },
          { speaker: 'B', en: "Looks like your oil level is too low. Let me check it.", ja: 'オイルの量が少なすぎるようですね。確認します。' },
          { speaker: 'A', en: "I think the engine's overheating.", ja: 'エンジンがオーバーヒートしていると思います。' },
          { speaker: 'B', en: "Okay, I'll take a look.", ja: 'わかりました、見てみましょう。' },
        ],
      },
      {
        id: 'problems',
        label: 'Pattern C · More problems',
        title: '車の具体的な不具合を伝える',
        lines: [
          { speaker: 'A', en: "The headlight isn't working.", ja: 'ヘッドライトがつきません。' },
          { speaker: 'B', en: 'The oil needs changing.', ja: 'オイル交換が必要です。' },
          { speaker: 'A', en: 'The windscreen is cracked.', ja: 'フロントガラスにひびが入っています。' },
          { speaker: 'B', en: 'The tyre keeps going down.', ja: 'タイヤの空気が抜け続けています。' },
        ],
      },
    ],
    tip: '車の点検・整備は service、イギリス英語のフロントガラスは windscreen、ボンネットは bonnet、トランクは boot、タイヤは tyre と言います。jammed は詰まって動かない状態、keeps going down はタイヤの空気が抜け続ける状態です。',
  },
  practice: {
    title: '車の症状を、整備工場で具体的に説明する',
    instructions: '日本語訳は見ずに、点検予約、警告灯、エンジン、車のパーツの表現を声に重ねます。',
    coreHeading: 'まずは、点検を予約する一文から。',
    dialogueHeading: '点検予約、故障相談、具体的な不具合で役を切り替える。',
    dialogueDescription: '点検と引き取り時間を確認する、警告灯とエンジンを説明する、ライトやガラスやタイヤの症状を伝える3つの場面を練習します。',
    finishTitle: '次に車の調子が気になったら、症状とパーツを英語でひとつ伝えてみましょう。',
    corePhrases: [
      { phrase: 'Could I book my car in for a service, please?', context: '点検を予約する', rate: 0.74 },
      { phrase: 'When will my car be ready?', context: '完成時刻を尋ねる', rate: 0.82 },
      { phrase: 'What does this warning light mean?', context: '警告灯を尋ねる', rate: 0.78 },
      { phrase: 'It keeps flashing.', context: '点滅を伝える', rate: 0.84 },
      { phrase: "Looks like your oil level is too low.", context: 'オイル量を伝える', rate: 0.74 },
      { phrase: "I think the engine's overheating.", context: 'エンジンの症状を伝える', rate: 0.76 },
      { phrase: "The headlight isn't working.", context: 'ライトの故障を伝える', rate: 0.82 },
      { phrase: 'The oil needs changing.', context: 'オイル交換を伝える', rate: 0.82 },
      { phrase: 'The steering wheel is jammed.', context: 'ハンドルの故障を伝える', rate: 0.78 },
      { phrase: 'The windscreen is cracked.', context: 'ガラスの状態を伝える', rate: 0.8 },
      { phrase: 'The tyre keeps going down.', context: 'タイヤの症状を伝える', rate: 0.76 },
      { phrase: "Okay, I'll take a look.", context: '点検を引き受ける', rate: 0.84 },
    ],
    dialogues: [
      { title: 'Booking a service', lines: ['ABC Autos, how can I help?', 'Could I book my car in for a service, please?', 'When will my car be ready?', 'It should be ready to pick up at 5.30.'] },
      { title: 'Faults and repairs', lines: ['What does this warning light mean? It keeps flashing...', "Looks like your oil level is too low. Let me check it.", "I think the engine's overheating.", "Okay, I'll take a look."] },
      { title: 'More problems', lines: ["The headlight isn't working.", 'The oil needs changing.', 'The windscreen is cracked.', 'The tyre keeps going down.'] },
    ],
    natural: [
      { full: 'Could I arrange a regular maintenance appointment for my car?', natural: 'Could I book my car in for a service, please?' },
      { full: 'What is the meaning of this dashboard warning lamp?', natural: 'What does this warning light mean?' },
      { full: 'The tire is repeatedly losing air pressure.', natural: 'The tyre keeps going down.' },
    ],
  },
}
