/** Chapter 30 · At the gym. */
export const gymLesson = {
  id: 'gym',
  kind: 'gym',
  number: '30',
  title: 'なぜ「ジムで使う英語」を学ぶのでしょうか？',
  enTitle: 'At the gym',
  ja: '入会の条件を確認し、クラスに参加し、ジムでの運動を続けるための英語を学びます。',
  cando: 'ジムの料金や施設について尋ね、クラスに参加し、トレーニングの基本語彙を使える。',
  learn: {
    intro: [
      'ジムに行くことは、ただ運動するだけではありません。入会する前には、料金、会員プラン、クラス、施設、パーソナルトレーニングなどについて確認する必要があります。',
      'また、実際にクラスやトレーニングに参加するときには、インストラクターの指示を理解したり、スタッフや他の利用者とやり取りしたりすることもあります。',
      'この章では、ジムへの入会、便利な質問、フィットネスクラスへの参加、そしてジムでよく使われる基本的な語彙を学びます。',
    ],
    functions: [
      ['01', '条件を確認する'],
      ['02', '施設を見学する'],
      ['03', 'クラスに参加する'],
      ['04', '運動の言葉を使う'],
    ],
    membership: {
      title: 'ジムに入会する・質問する',
      enTitle: 'Joining a gym',
      intro: '料金や会員プランを聞き、施設を見学して、自分に合うサービスを確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'How much does it cost to join?', meaning: '入会するにはいくらかかりますか？', context: '入会料金を尋ねる', register: 'polite' },
        { phrase: "Here's our list of membership options.", meaning: 'こちらが会員プランのリストです。', context: 'プランを案内する', register: 'neutral' },
        { phrase: 'Can I have a tour?', meaning: '施設を見学してもいいですか？', context: '見学をお願いする', register: 'polite' },
        { phrase: "Yes, I'll show you round now.", meaning: 'はい、今からご案内しますね。', context: '施設を案内する', register: 'polite' },
        { phrase: 'So, what do you think?', meaning: 'それで、いかがですか？', context: '見学後の感想を尋ねる', register: 'neutral' },
        { phrase: 'It all looks great. Sign me up!', meaning: 'すべて素晴らしいですね。入会します！', context: '入会を決める', register: 'casual' },
        { phrase: 'What fitness classes do you run?', meaning: 'どんなフィットネスクラスをやっていますか？', context: 'クラスの種類を尋ねる', register: 'neutral' },
        { phrase: 'Would I need to pay extra for yoga classes?', meaning: 'ヨガのクラスには追加料金が必要ですか？', context: '追加料金を確認する', register: 'polite' },
        { phrase: 'Can I book a personal trainer?', meaning: 'パーソナルトレーナーを予約できますか？', context: 'トレーナーを予約する', register: 'polite' },
        { phrase: 'Are there any women-only sessions?', meaning: '女性専用のセッションはありますか？', context: '専用時間を尋ねる', register: 'polite' },
      ],
      recognition: [
        { phrase: 'membership options', meaning: '会員プラン', note: '月額や利用範囲が異なる複数のプランを指します。' },
        { phrase: 'show you round', meaning: '施設を案内する', note: 'show you around と同じ意味の、特にUKでよく聞く表現です。' },
        { phrase: 'sign me up', meaning: '申し込む・登録する', note: '入会やサービスへの登録を前向きに決める言い方です。' },
      ],
    },
    classes: {
      title: 'クラスに参加する',
      enTitle: 'Attending a class',
      intro: 'スタジオで他の参加者やインストラクターに声をかけ、クラスに参加します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Have you been to this fitness class before?', meaning: 'このフィットネスクラスに参加したことはありますか？', context: '初めてのクラスで尋ねる', register: 'neutral' },
        { phrase: "Yes, a few times. It's good fun!", meaning: 'はい、何度か。とても楽しいですよ！', context: '経験を答える', register: 'casual' },
        { phrase: "Hi, I'm here for the spin class.", meaning: 'こんにちは、スピンクラスを受けに来ました。', context: '受付で目的を伝える', register: 'neutral' },
        { phrase: 'Great, grab a free bike and join in!', meaning: '空いているバイクを取って参加してください！', context: 'インストラクターが案内する', register: 'casual' },
        { phrase: 'Could you show me how to adjust the seat?', meaning: 'シートの調整方法を教えていただけますか？', context: '器具の使い方を尋ねる', register: 'polite' },
        { phrase: 'Take a break if you need one.', meaning: '必要なら休憩してください。', context: '運動中の指示を聞く', register: 'neutral' },
        { phrase: 'Are you using this machine?', meaning: 'このマシンを使っていますか？', context: '器具が空いているか尋ねる', register: 'polite' },
        { phrase: 'No, go ahead.', meaning: 'いいえ、どうぞ。', context: '器具を譲る', register: 'casual' },
      ],
      recognition: [
        { phrase: 'spin class', meaning: '固定式バイクのクラス', note: '音楽に合わせて自転車をこぐ有酸素運動です。' },
        { phrase: 'join in', meaning: '参加する', note: 'すでに行われている活動に加わるときに使います。' },
        { phrase: 'go ahead', meaning: 'どうぞ、先に進んで', note: '順番や場所を相手に譲るときの短い返事です。' },
      ],
    },
    vocabulary: {
      title: 'ジムのボキャブラリー',
      enTitle: 'Vocabulary at the gym',
      intro: 'ジムでの運動、クラス、トレーニングの種類を表す基本的な言葉です。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'to work out', meaning: '運動する・トレーニングする', context: 'ジムで運動する', register: 'neutral' },
        { phrase: 'personal trainer', meaning: 'パーソナルトレーナー', context: '個別指導をする人', register: 'neutral' },
        { phrase: 'weight training', meaning: 'ウェイトトレーニング', context: '重りを使う運動', register: 'neutral' },
        { phrase: 'spin class', meaning: 'スピンクラス', context: '固定式バイクのクラス', register: 'neutral' },
        { phrase: 'yoga', meaning: 'ヨガ', context: '柔軟性や呼吸を整えるクラス', register: 'neutral' },
        { phrase: 'Pilates', meaning: 'ピラティス', context: '体幹を整える運動', register: 'neutral' },
        { phrase: 'fitness class', meaning: 'フィットネスクラス', context: '指導付きの運動クラス', register: 'neutral' },
        { phrase: 'HIIT', meaning: '高強度インターバルトレーニング', context: '短い高強度運動を繰り返す方法', register: 'neutral' },
        { phrase: 'dance class', meaning: 'ダンスクラス', context: '音楽に合わせて動くクラス', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'work out', meaning: '運動する', note: 'ジムで運動することには exercise より work out がよく使われます。' },
        { phrase: 'HIIT', meaning: '高強度インターバルトレーニング', note: 'High-Intensity Interval Training の略です。' },
        { phrase: 'Pilates', meaning: 'ピラティス', note: '発音は「ピラティーズ」に近く、最後の s も音にします。' },
      ],
    },
    dialogues: [
      {
        id: 'membership',
        label: 'Pattern A · Joining a gym',
        title: '見学して入会を決める',
        lines: [
          { speaker: 'A', en: 'How much does it cost to join?', ja: '入会するにはいくらかかりますか？' },
          { speaker: 'B', en: "Here's our list of membership options.", ja: 'こちらが会員プランのリストです。' },
          { speaker: 'A', en: 'Can I have a tour?', ja: '施設を見学してもいいですか？' },
          { speaker: 'B', en: "Yes, I'll show you round now.", ja: 'はい、今からご案内しますね。' },
          { speaker: 'A', en: 'It all looks great. Sign me up!', ja: 'すべて素晴らしいですね。入会します！' },
        ],
      },
      {
        id: 'class',
        label: 'Pattern B · At a fitness class',
        title: '初めてのクラスに参加する',
        lines: [
          { speaker: 'A', en: 'Have you been to this fitness class before?', ja: 'このフィットネスクラスに参加したことはありますか？' },
          { speaker: 'B', en: "Yes, a few times. It's good fun!", ja: 'はい、何度か。とても楽しいですよ！' },
          { speaker: 'A', en: "Hi, I'm here for the spin class.", ja: 'こんにちは、スピンクラスを受けに来ました。' },
          { speaker: 'B', en: 'Great, grab a free bike and join in!', ja: '空いているバイクを取って参加してください！' },
        ],
      },
      {
        id: 'floor',
        label: 'Pattern C · On the gym floor',
        title: '器具を譲り合う',
        lines: [
          { speaker: 'A', en: 'Are you using this machine?', ja: 'このマシンを使っていますか？' },
          { speaker: 'B', en: 'No, go ahead.', ja: 'いいえ、どうぞ。' },
          { speaker: 'A', en: 'Thanks. I am going to work out for ten minutes.', ja: 'ありがとう。10分運動します。' },
          { speaker: 'B', en: 'Take a break if you need one.', ja: '必要なら休憩してください。' },
        ],
      },
    ],
    tip: 'work out はジムで運動するという意味で、exercise より会話的です。sign me up は入会を前向きに決める言い方、show you round は施設を案内するUKでよく聞く表現です。',
  },
  practice: {
    title: 'ジムで必要な英語を、自然に声にする',
    instructions: '日本語の説明はここまで。入会、クラス、器具のやり取りを英語だけで声に重ねます。',
    coreHeading: 'まずは、ジムでそのまま使える一文から。',
    dialogueHeading: '見学して、クラスに参加し、器具を譲り合う流れを感じる。',
    dialogueDescription: 'スタッフや他の利用者の声を聞き、自分の目的や希望を短く伝えます。',
    finishTitle: '次にジムへ行ったら、ひとつだけ英語で質問か返事をしてみましょう。',
    corePhrases: [
      { phrase: 'How much does it cost to join?', context: '入会料金を尋ねる', rate: 0.8 },
      { phrase: 'Can I have a tour?', context: '施設を見学する', rate: 0.84 },
      { phrase: 'What fitness classes do you run?', context: 'クラスを尋ねる', rate: 0.78 },
      { phrase: 'Can I book a personal trainer?', context: 'トレーナーを予約する', rate: 0.8 },
      { phrase: "I'm here for the spin class.", context: 'クラスの受付をする', rate: 0.82 },
      { phrase: 'Could you show me how to adjust the seat?', context: '器具の使い方を尋ねる', rate: 0.76 },
      { phrase: 'Are you using this machine?', context: '器具が空いているか尋ねる', rate: 0.82 },
      { phrase: 'No, go ahead.', context: '器具を譲る', rate: 0.9 },
      { phrase: 'I am going to work out for ten minutes.', context: '運動時間を伝える', rate: 0.76 },
      { phrase: 'Take a break if you need one.', context: '休憩を案内する', rate: 0.8 },
    ],
    dialogues: [
      { title: 'Joining a gym', lines: ['How much does it cost to join?', "Here's our list of membership options.", 'Can I have a tour?', 'It all looks great. Sign me up!'] },
      { title: 'At a fitness class', lines: ['Have you been to this fitness class before?', "Yes, a few times. It's good fun!", "I'm here for the spin class.", 'Grab a free bike and join in!'] },
      { title: 'On the gym floor', lines: ['Are you using this machine?', 'No, go ahead.', 'I am going to work out for ten minutes.', 'Take a break if you need one.'] },
    ],
    natural: [
      { full: 'How much does it cost to become a member?', natural: 'How much does it cost to join?' },
      { full: 'I am here to attend the spinning class.', natural: "I'm here for the spin class." },
      { full: 'Please continue and use the machine.', natural: 'No, go ahead.' },
    ],
  },
}
