/** Chapter 80 · Health and medicine. */
export const healthMedicineLesson = {
  id: 'health-medicine',
  kind: 'health-medicine',
  number: '80',
  title: '第80章に入る前に：なぜ「健康や医療で使う英語」を学ぶのでしょうか？',
  enTitle: 'Health and medicine',
  ja: '健康や医療について、症状・痛み・けが・持病を具体的に説明する表現を学びます。',
  cando: '症状、痛み、けが、持病、必要な薬や処置を具体的に伝えられる。',
  learn: {
    intro: [
      '体調が悪いときは、普段よりも正確に自分の状態を伝える必要があります。どこが痛いのか、どんな症状があるのか、いつから続いているのかによって、相手の対応も変わります。',
      '自分の症状や必要な薬・処置を、できるだけ具体的に伝えることが大切です。',
      'この章では、体調不良や痛み、けが、持病など、自分の健康状態を説明するための基本的な表現を学びます。',
    ],
    functions: [
      ['01', '症状と続いている期間を伝える'],
      ['02', '痛みやけがの場所・強さを伝える'],
      ['03', '持病と必要な薬・処置を伝える'],
    ],
    general: {
      title: '体調不良と基本的な症状',
      enTitle: 'Describing general symptoms',
      intro: '風邪や胃腸の不調など、体調の変化を症状ごとに説明します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "I've been feeling sick.", meaning: '吐き気がするんです。／気分が悪いんです。', context: '吐き気や不調を伝える', register: 'polite' },
        { phrase: "I've been having headaches.", meaning: '頭痛が続いているんです。', context: '続いている症状を伝える', register: 'polite' },
        { phrase: "I'm very congested.", meaning: '鼻がとても詰まっているんです。', context: '鼻づまりを伝える', register: 'polite' },
        { phrase: 'My joints are aching.', meaning: '関節が痛むんです。', context: '関節の痛みを伝える', register: 'polite' },
        { phrase: "I've got diarrhoea.", meaning: '下痢をしているんです。', context: 'お腹のトラブルを伝える', register: 'urgent' },
        { phrase: "I'm constipated.", meaning: '便秘なんです。', context: '便秘を伝える', register: 'polite' },
        { phrase: "I've got a lump.", meaning: 'しこり（腫れ物）があるんです。', context: 'しこりを伝える', register: 'polite' },
        { phrase: "I've got a temperature.", meaning: '熱があるんです。', context: '発熱を伝える', register: 'polite' },
        { phrase: "I've got a sore throat.", meaning: 'のどが痛いんです。', context: 'のどの痛みを伝える', register: 'polite' },
        { phrase: 'I have a rash.', meaning: '湿疹（発疹）が出ているんです。', context: '発疹を伝える', register: 'polite' },
      ],
      recognition: [
        { phrase: 'feel sick', meaning: '吐き気がする・気分が悪い', note: '日常会話でよく使う症状の表現です。' },
        { phrase: 'have been -ing', meaning: 'ずっと〜している', note: '症状が過去から現在まで続いていることを伝えます。' },
        { phrase: 'congested', meaning: '鼻が詰まった', note: '風邪などで鼻づまりがひどい状態です。' },
        { phrase: 'ache', meaning: 'ズキズキ痛む', note: '持続的な痛みを表す動詞です。' },
        { phrase: 'diarrhoea / constipated', meaning: '下痢 / 便秘', note: 'お腹の状態を具体的に説明します。' },
      ],
    },
    pain: {
      title: '具体的な痛みや怪我の表現',
      enTitle: 'Specific pain and injuries',
      intro: '痛む場所、腫れ、痛みの強さ、動かしたときの症状を詳しく伝えます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: "I've got a swollen ankle.", meaning: '足首が腫れているんです。', context: '腫れを伝える', register: 'polite' },
        { phrase: "I'm in a lot of pain.", meaning: '強い痛みがあるんです。', context: '痛みの強さを伝える', register: 'urgent' },
        { phrase: "I've got a pain in my back.", meaning: '背中（腰）が痛むんです。', context: '背中や腰の痛みを伝える', register: 'polite' },
        { phrase: "I think I've pulled a muscle in my leg.", meaning: '足の筋肉を痛めた（肉離れした）のだと思います。', context: '筋肉のけがを伝える', register: 'polite' },
        { phrase: "I've got a swollen knee.", meaning: 'ひざが腫れているんです。', context: 'ひざの腫れを伝える', register: 'polite' },
        { phrase: "I've got a pain in my chest.", meaning: '胸が痛むんです。', context: '胸の痛みを伝える', register: 'urgent' },
        { phrase: 'My foot hurts when I walk.', meaning: '歩くと足が痛むんです。', context: '動作中の痛みを伝える', register: 'polite' },
        { phrase: 'I sprained my wrist.', meaning: '手首を捻挫してしまいました。', context: '捻挫を伝える', register: 'polite' },
      ],
      recognition: [
        { phrase: 'swollen', meaning: '腫れた', note: '足首やひざなどの腫れを説明します。' },
        { phrase: 'in a lot of pain', meaning: '強い痛みがある', note: '痛みの強さをはっきり伝える表現です。' },
        { phrase: 'a pain in my ...', meaning: '〜が痛い', note: '痛む体の部位を後ろに続けます。' },
        { phrase: 'pull a muscle', meaning: '筋肉を痛める・肉離れする', note: '運動中などに筋肉を傷めたときに使います。' },
        { phrase: 'sprain', meaning: '捻挫する', note: '関節をひねって靭帯などを傷めた状態です。' },
      ],
    },
    conditions: {
      title: '持病と必要な処置の伝え方',
      enTitle: 'Chronic conditions and treatment',
      intro: '持病や急な症状、必要な薬・器具を、質問と返答の形で伝えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Are you diabetic?', meaning: '糖尿病ですか？', context: '持病を確認する', register: 'polite' },
        { phrase: 'Yes, I am. I need some more insulin.', meaning: 'はい、そうです。インスリンがもう少し必要なんです。', context: '薬の追加が必要だと伝える', register: 'urgent' },
        { phrase: 'Are you okay? You look breathless.', meaning: '大丈夫？ 息が苦しそうだけど。', context: '呼吸の状態を気遣う', register: 'caring' },
        { phrase: "I'm asthmatic. I need another inhaler.", meaning: '喘息なんです。吸入器（インヘラー）が必要です。', context: '喘息と必要な器具を伝える', register: 'urgent' },
      ],
      recognition: [
        { phrase: 'diabetic', meaning: '糖尿病の', note: '糖尿病があることを伝えます。' },
        { phrase: 'insulin', meaning: 'インスリン', note: '糖尿病の治療に使う薬です。' },
        { phrase: 'breathless', meaning: '息苦しい', note: '息が切れている・呼吸が苦しい状態です。' },
        { phrase: 'asthmatic', meaning: '喘息の', note: '喘息があることを伝えます。' },
        { phrase: 'inhaler', meaning: '吸入器', note: '喘息などで薬を吸入する器具です。' },
      ],
    },
    dialogues: [
      {
        id: 'general-symptoms',
        label: 'Pattern A · General symptoms',
        title: '体調不良の症状を伝える',
        lines: [
          { speaker: 'A', en: "I've been feeling sick.", ja: '吐き気がするんです。' },
          { speaker: 'B', en: "I've been having headaches.", ja: '頭痛も続いているんです。' },
          { speaker: 'A', en: "I've got a sore throat.", ja: 'のども痛いんです。' },
          { speaker: 'B', en: "I've got a temperature.", ja: '熱もあるんです。' },
        ],
      },
      {
        id: 'pain-injuries',
        label: 'Pattern B · Pain and injuries',
        title: '痛みやけがの状態を具体的に説明する',
        lines: [
          { speaker: 'A', en: "I've got a swollen ankle.", ja: '足首が腫れているんです。' },
          { speaker: 'B', en: "I'm in a lot of pain.", ja: '強い痛みがあります。' },
          { speaker: 'A', en: "I think I've pulled a muscle in my leg.", ja: '足の筋肉を痛めたのだと思います。' },
          { speaker: 'B', en: 'My foot hurts when I walk.', ja: '歩くと足が痛みます。' },
        ],
      },
      {
        id: 'chronic-conditions',
        label: 'Pattern C · Chronic conditions',
        title: '持病と必要な薬・器具を伝える',
        lines: [
          { speaker: 'A', en: 'Are you diabetic?', ja: '糖尿病ですか？' },
          { speaker: 'B', en: 'Yes, I am. I need some more insulin.', ja: 'はい、インスリンがもう少し必要です。' },
          { speaker: 'A', en: 'Are you okay? You look breathless.', ja: '大丈夫？ 息が苦しそうだけど。' },
          { speaker: 'B', en: "I'm asthmatic. I need another inhaler.", ja: '喘息なんです。別の吸入器が必要です。' },
        ],
      },
    ],
    tip: '症状は「どこが」「どのくらい」「いつから」を具体的に伝えます。have been -ingは続いている症状、acheは持続的な痛み、pull a muscleは筋肉を痛めたときに使います。',
    tips: [
      { title: 'have と have been -ing の使い分け', body: '一時的な症状には I have a headache や I\'ve got a sore throat と言い、数日続いている不調には I\'ve been feeling sick や I\'ve been having headaches と言います。' },
      { title: 'お腹のトラブルを具体的に言う', body: 'diarrhoea（下痢）や constipated（便秘）は少し言いにくくても、診察や健康管理で必要な重要語です。I\'ve got や I\'m の後ろに続けます。' },
      { title: '筋肉を痛めたら pull a muscle', body: '運動中などに筋肉やスジを痛めたときは pull a muscle と言います。I think I\'ve pulled a muscle in my leg. のように、確信がないときもやわらかく伝えられます。' },
    ],
  },
  practice: {
    title: '症状や必要な処置を、英語で具体的に伝える',
    instructions: '日本語訳は見ずに、症状の場所・強さ・経過と必要な薬や器具を声に重ねます。',
    coreHeading: 'まずは、体の状態を伝える一文から。',
    dialogueHeading: '症状、けが、持病の場面で役を切り替える。',
    dialogueDescription: '一般的な症状を説明する、痛みやけがの状態を伝える、持病と必要な薬・器具を相談する3つの場面を練習します。',
    finishTitle: '次に体調が悪くなったとき、症状と必要な対応を英語でひとつ説明してみましょう。',
    corePhrases: [
      { phrase: "I've been feeling sick.", context: '吐き気や不調を伝える', rate: 0.82 },
      { phrase: "I've been having headaches.", context: '続いている症状を伝える', rate: 0.74 },
      { phrase: "I'm very congested.", context: '鼻づまりを伝える', rate: 0.8 },
      { phrase: "I've got a sore throat.", context: 'のどの痛みを伝える', rate: 0.82 },
      { phrase: "I've got a temperature.", context: '熱を伝える', rate: 0.82 },
      { phrase: "I've got a swollen ankle.", context: '腫れを伝える', rate: 0.78 },
      { phrase: "I'm in a lot of pain.", context: '強い痛みを伝える', rate: 0.82 },
      { phrase: "I think I've pulled a muscle in my leg.", context: '筋肉のけがを伝える', rate: 0.72 },
      { phrase: 'My foot hurts when I walk.', context: '歩くときの痛みを伝える', rate: 0.8 },
      { phrase: 'I sprained my wrist.', context: '捻挫を伝える', rate: 0.82 },
      { phrase: 'Yes, I am. I need some more insulin.', context: '必要な薬を伝える', rate: 0.72 },
      { phrase: "I'm asthmatic. I need another inhaler.", context: '持病と器具を伝える', rate: 0.76 },
    ],
    dialogues: [
      { title: 'General symptoms', lines: ["I've been feeling sick.", "I've been having headaches.", "I've got a sore throat.", "I've got a temperature."] },
      { title: 'Pain and injuries', lines: ["I've got a swollen ankle.", "I'm in a lot of pain.", "I think I've pulled a muscle in my leg.", 'My foot hurts when I walk.'] },
      { title: 'Chronic conditions', lines: ['Are you diabetic?', 'Yes, I am. I need some more insulin.', 'Are you okay? You look breathless.', "I'm asthmatic. I need another inhaler."] },
    ],
    natural: [
      { full: 'I have experienced persistent nausea for several days.', natural: "I've been feeling sick." },
      { full: 'I believe I have strained a muscle in my leg.', natural: "I think I've pulled a muscle in my leg." },
      { full: 'I require an additional inhaler because I have asthma.', natural: "I'm asthmatic. I need another inhaler." },
    ],
  },
}
