/** Chapter 33 · Hobbies. */
export const hobbiesLesson = {
  id: 'hobbies',
  kind: 'hobbies',
  number: '33',
  title: '第33章に入る前に：なぜ「趣味」について話すのでしょうか？',
  enTitle: 'Hobbies',
  ja: '新しい趣味を始め、相手の自由時間を尋ね、続けている期間を自然に話します。',
  cando: '新しい趣味を紹介し、相手の趣味を尋ね、for と since を使って経験を伝えられる。',
  learn: {
    intro: [
      '私たちの日常生活には、仕事、勉強、責任など、「しなければならないこと」がたくさんあります。一方、趣味は少し違います。',
      '趣味とは、誰かに求められたからではなく、自分が興味を持ち、楽しみたいと思って、自分で選んで行う活動です。趣味について話すことは、その人が何を楽しみ、自由な時間をどう使っているのかを知ることにもつながります。',
      '趣味は変化します。新しいことを始めたり、試しに挑戦したり、少しずつ上達したり、何年も続けたりすることもあります。この章では、趣味について自然に話す方法を学びます。',
    ],
    functions: [
      ['01', '新しいことを始める'],
      ['02', '趣味を尋ねる'],
      ['03', '自由時間を話す'],
      ['04', '続けた期間を伝える'],
    ],
    starting: {
      title: '新しい趣味を始める',
      enTitle: 'Starting a new hobby',
      intro: '始めたばかりの活動や、試していることを相手に伝え、応援や興味を引き出します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "Guess what? I've just started doing karate!", meaning: 'あのね、空手を始めたばかりなの！', context: '新しい挑戦を伝える', register: 'casual' },
        { phrase: 'No way! Good for you!', meaning: 'まさか！すごいじゃない、よかったね！', context: '相手の挑戦を応援する', register: 'casual' },
        { phrase: "I'm giving knitting a go!", meaning: '編み物に挑戦しているんだ！', context: '試しに始める', register: 'casual' },
        { phrase: "I've taken up pottery recently.", meaning: '最近、陶芸を始めたんだ。', context: '新しい趣味を紹介する', register: 'neutral' },
        { phrase: 'Check this out...', meaning: 'これ見てよ…', context: '作品や活動を見せる', register: 'casual' },
        { phrase: "Wow! Maybe I'll have a go, too!", meaning: 'わあ！私もやってみようかな！', context: '自分も試したいと伝える', register: 'casual' },
        { phrase: 'That sounds fun - I might join you.', meaning: '楽しそうだね、私も混ぜてもらおうかな。', context: '一緒にやる提案をする', register: 'casual' },
      ],
      recognition: [
        { phrase: 'give it a go', meaning: '試しにやってみる', note: '新しい活動を気軽に試すときのカジュアルな表現です。' },
        { phrase: 'take up', meaning: '趣味として始める', note: 'take up pottery のように、新しい趣味を始めることです。' },
        { phrase: 'Good for you!', meaning: 'よかったね・すごいね', note: '相手の前向きな行動を温かく応援します。' },
      ],
    },
    asking: {
      title: '趣味や自由時間の過ごし方について尋ねる',
      enTitle: 'Asking about hobbies',
      intro: '相手の興味や仕事以外の時間の使い方を尋ね、共通点を見つけます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Have you got any hobbies?', meaning: '何か趣味はありますか？', context: '趣味を尋ねる', register: 'neutral' },
        { phrase: "Yeah, I play tennis and I'm learning the guitar.", meaning: 'うん、テニスをしたり、ギターを習ったりしているよ。', context: '趣味を答える', register: 'casual' },
        { phrase: 'So, what do you normally do in your free time?', meaning: '普段、空いた時間に何をしているの？', context: '自由時間について尋ねる', register: 'casual' },
        { phrase: 'I usually go swimming at the weekend. How about you?', meaning: '普段は週末に泳ぎに行っているよ。あなたはどう？', context: '過ごし方を答える', register: 'casual' },
        { phrase: 'What do you do outside of work?', meaning: '仕事以外の時間では何をしているの？', context: '仕事以外の生活を尋ねる', register: 'neutral' },
        { phrase: 'Gaming, mostly.', meaning: 'ほとんどゲームかな。', context: '短く答える', register: 'casual' },
        { phrase: "And I'm writing a blog.", meaning: 'それから、ブログを書いているんだ。', context: '趣味を追加する', register: 'casual' },
      ],
      recognition: [
        { phrase: 'free time', meaning: '自由時間', note: '仕事や勉強以外の、自分で使える時間です。' },
        { phrase: 'outside of work', meaning: '仕事以外で', note: 'プライベートの活動を尋ねる自然な言い方です。' },
        { phrase: 'mostly', meaning: 'ほとんど・主に', note: 'Gaming, mostly. のように短い返事の最後にも置けます。' },
      ],
    },
    talking: {
      title: '継続している期間を伝える',
      enTitle: 'Talking about hobbies',
      intro: '趣味をいつから、どれくらい続けているのかを、for と since で具体的に伝えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'So how long have you all been playing?', meaning: 'みんなはどれくらい弾いているの？', context: '継続期間を尋ねる', register: 'casual' },
        { phrase: "I've been playing the sax for 10 years!", meaning: 'サックスを10年間吹いているよ！', context: '期間の長さを伝える', register: 'casual' },
        { phrase: 'The piano? Since I was 11. How about you?', meaning: 'ピアノ？11歳の頃からずっとだよ。あなたは？', context: '始めた時点を伝える', register: 'casual' },
        { phrase: 'I only started learning the bass guitar three years ago.', meaning: '3年前にベースギターを習い始めたばかりなんだ。', context: '始めた時期を伝える', register: 'neutral' },
        { phrase: "I've been taking photos since I was a child.", meaning: '子どもの頃から写真を撮り続けています。', context: '長い経験を伝える', register: 'neutral' },
        { phrase: 'I have been learning it for six months.', meaning: '6か月間それを習っています。', context: '短い期間を伝える', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'for + a period', meaning: '期間の長さ', note: 'for 10 years、for three months のように使います。' },
        { phrase: 'since + a starting point', meaning: '始めた時点', note: 'since I was 11、since last year のように使います。' },
        { phrase: 'have been ...-ing', meaning: 'ずっと続けている', note: '今も続いている活動の期間を伝える形です。' },
      ],
    },
    vocabulary: {
      title: '趣味について話すための単語',
      enTitle: 'Hobby vocabulary',
      intro: '趣味を動詞で話すときに使いやすい活動の言葉をまとめます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'play tennis', meaning: 'テニスをする', context: 'スポーツの趣味', register: 'neutral' },
        { phrase: 'learn the guitar', meaning: 'ギターを習う', context: '楽器を学ぶ', register: 'neutral' },
        { phrase: 'go swimming', meaning: '泳ぎに行く', context: '定期的な活動', register: 'neutral' },
        { phrase: 'write a blog', meaning: 'ブログを書く', context: '創作活動', register: 'neutral' },
        { phrase: 'do karate', meaning: '空手をする', context: '武道・スポーツ', register: 'neutral' },
        { phrase: 'take photos', meaning: '写真を撮る', context: '写真撮影', register: 'neutral' },
        { phrase: 'make pottery', meaning: '陶芸をする', context: '創作活動', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'My hobby is...', meaning: '私の趣味は…', note: '文法的には正しいですが、普段の会話では動詞で答える方が自然です。' },
        { phrase: 'I play / I like / I go...', meaning: '私は…をする・好き・行く', note: '活動を生き生きと伝える、自然な答えの始め方です。' },
        { phrase: 'give ... a go', meaning: '…を試す', note: 'give knitting a go のように使います。' },
      ],
    },
    dialogues: [
      {
        id: 'new',
        label: 'Pattern A · Starting a new hobby',
        title: '新しい挑戦を紹介する',
        lines: [
          { speaker: 'A', en: "Guess what? I've just started doing karate!", ja: 'あのね、空手を始めたばかりなの！' },
          { speaker: 'B', en: 'No way! Good for you!', ja: 'まさか！すごいじゃない、よかったね！' },
          { speaker: 'A', en: "I'm giving knitting a go!", ja: '編み物に挑戦しているんだ！' },
          { speaker: 'B', en: "That sounds fun - I might join you.", ja: '楽しそうだね、私も混ぜてもらおうかな。' },
        ],
      },
      {
        id: 'asking',
        label: 'Pattern B · Asking about hobbies',
        title: '相手の自由時間を尋ねる',
        lines: [
          { speaker: 'A', en: 'Have you got any hobbies?', ja: '何か趣味はありますか？' },
          { speaker: 'B', en: "Yeah, I play tennis and I'm learning the guitar.", ja: 'うん、テニスをしたり、ギターを習ったりしているよ。' },
          { speaker: 'A', en: 'What do you do outside of work?', ja: '仕事以外の時間では何をしているの？' },
          { speaker: 'B', en: 'Gaming, mostly. And I’m writing a blog.', ja: 'ほとんどゲームかな。それから、ブログを書いているんだ。' },
        ],
      },
      {
        id: 'length',
        label: 'Pattern C · Talking about experience',
        title: '趣味を続けた期間を話す',
        lines: [
          { speaker: 'A', en: 'So how long have you all been playing?', ja: 'みんなはどれくらい弾いているの？' },
          { speaker: 'B', en: "I've been playing the sax for 10 years!", ja: 'サックスを10年間吹いているよ！' },
          { speaker: 'A', en: 'The piano?', ja: 'ピアノ？' },
          { speaker: 'B', en: 'Since I was 11. How about you?', ja: '11歳の頃からずっとだよ。あなたは？' },
        ],
      },
    ],
    tip: '英語では、趣味を答えるときに My hobby is... より I play tennis、I like reading のように動詞で話す方が自然です。for は期間の長さ、since は始めた時点に使います。',
  },
  practice: {
    title: '趣味の話を、自然な英語で声にする',
    instructions: '日本語の説明はここまで。新しい挑戦、自由時間、続けている期間を英語だけで声に重ねます。',
    coreHeading: 'まずは、趣味についてそのまま使える一文から。',
    dialogueHeading: '始めて、尋ねて、続けている期間を話す。',
    dialogueDescription: '活動名だけでなく、始めたことや続けた期間まで自然に伝えます。',
    finishTitle: '次に趣味を聞かれたら、動詞を使ってひとつ答えてみましょう。',
    corePhrases: [
      { phrase: "I've just started doing karate!", context: '新しい趣味を紹介する', rate: 0.8 },
      { phrase: "I'm giving knitting a go!", context: '試しに挑戦する', rate: 0.82 },
      { phrase: "I've taken up pottery recently.", context: '趣味を始めたと伝える', rate: 0.78 },
      { phrase: 'Have you got any hobbies?', context: '趣味を尋ねる', rate: 0.84 },
      { phrase: 'What do you do outside of work?', context: '仕事以外を尋ねる', rate: 0.8 },
      { phrase: 'Gaming, mostly.', context: '短く答える', rate: 0.92 },
      { phrase: "I've been playing the sax for 10 years!", context: '期間の長さを伝える', rate: 0.76 },
      { phrase: 'Since I was 11. How about you?', context: '始めた時点を伝える', rate: 0.82 },
      { phrase: 'I only started learning the bass guitar three years ago.', context: '始めた時期を伝える', rate: 0.74 },
      { phrase: 'I play tennis and I am learning the guitar.', context: '活動を動詞で話す', rate: 0.78 },
    ],
    dialogues: [
      { title: 'Starting a new hobby', lines: ["I've just started doing karate!", 'No way! Good for you!', "I'm giving knitting a go!", 'That sounds fun - I might join you.'] },
      { title: 'Asking about hobbies', lines: ['Have you got any hobbies?', "I play tennis and I'm learning the guitar.", 'What do you do outside of work?', 'Gaming, mostly.'] },
      { title: 'Talking about experience', lines: ['How long have you all been playing?', "I've been playing the sax for 10 years!", 'The piano?', 'Since I was 11. How about you?'] },
    ],
    natural: [
      { full: 'My hobby is karate.', natural: "I've just started doing karate!" },
      { full: 'I am interested in trying knitting.', natural: "I'm giving knitting a go!" },
      { full: 'I have played the saxophone for ten years.', natural: "I've been playing the sax for 10 years!" },
    ],
  },
}
