/** Chapter 79 · Holiday problems. */
export const holidayProblemsLesson = {
  id: 'holiday-problems',
  kind: 'holiday-problems',
  number: '79',
  title: '第79章に入る前に：なぜ「旅行中のトラブルで使う英語」を学ぶのでしょうか？',
  enTitle: 'Holiday problems',
  ja: '紛失や盗難、交通トラブル、病気やけがなど、旅行中の問題に対応するための表現を学びます。',
  cando: '旅行中の紛失・遅延・キャンセル・病気やけがを説明し、必要な助けや対応を求められる。',
  learn: {
    intro: [
      '旅行では、荷物の紛失や遅延、キャンセル、病気など、予定どおりにいかないこともあります。そんなときこそ、落ち着いて状況を説明し、必要な助けを求めることが大切です。',
      '「何が起きたのか」「何に困っているのか」「どんな対応が必要なのか」をできるだけはっきり伝えます。',
      'この章では、紛失や盗難、交通トラブル、病気やけがなど、旅行中の問題に対応するための表現を学びます。',
    ],
    functions: [
      ['01', '紛失・盗難・忘れ物を報告する'],
      ['02', '遅延やキャンセルの情報を確認する'],
      ['03', '超過料金や運休の理由を理解する'],
      ['04', '病気やけがと保険の相談をする'],
    ],
    belongings: {
      title: '荷物の紛失・盗難・忘れ物',
      enTitle: 'Lost belongings',
      intro: '盗難、手荷物の未着、置き忘れなどをスタッフに伝え、必要な情報を確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "My bag's been stolen with my passport inside!", meaning: 'バッグが盗まれました、中にパスポートが入っています！', context: '盗難を報告する', register: 'urgent' },
        { phrase: "Okay, I'll need to take some details.", meaning: 'わかりました。いくつか詳細を伺う必要があります。', context: '情報を確認する', register: 'polite' },
        { phrase: "Excuse me, my suitcase hasn't shown up.", meaning: 'すみません、私のスーツケースが出てきません。', context: '荷物の未着を報告する', register: 'polite' },
        { phrase: 'The airline desk can help you.', meaning: '航空会社のデスクで対応してもらえますよ。', context: '窓口を案内する', register: 'helpful' },
        { phrase: 'Hello, you left your phone behind!', meaning: 'こんにちは、携帯電話を置き忘れていましたよ！', context: '忘れ物を知らせる', register: 'friendly' },
        { phrase: 'Oh gosh, thank you so much!', meaning: 'おや、まあ！本当にありがとうございます！', context: '親切にお礼を言う', register: 'warm' },
      ],
      recognition: [
        { phrase: "has been stolen", meaning: '盗まれた', note: '盗難に遭ったことを伝えます。' },
        { phrase: "hasn't shown up", meaning: '現れていない・出てきていない', note: '荷物がまだ届かないときに使います。' },
        { phrase: 'leave behind', meaning: '置き忘れる', note: '場所に物を残してきたことを表します。' },
        { phrase: 'take some details', meaning: '詳細を聞き取る', note: 'スタッフが必要な情報を確認します。' },
      ],
    },
    delays: {
      title: '遅延とキャンセル',
      enTitle: 'Delays and cancellations',
      intro: 'フライトや電車の運行情報を案内板とスタッフから確認します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: "I'm afraid your flight is delayed.", meaning: 'あいにく、お客様のフライトは遅れております。', context: '遅延を知らせる', register: 'polite' },
        { phrase: "We'll let you know more as soon as we can.", meaning: '分かり次第、すぐに詳細をお知らせします。', context: '続報を約束する', register: 'polite' },
        { phrase: "I can't see our platform number anywhere...", meaning: 'プラットホームの番号がどこにも見当たらないなあ…。', context: '番線を探す', register: 'casual' },
        { phrase: 'Look at the board. Our train has been cancelled!', meaning: '案内板を見て。乗る予定の電車がキャンセル（運休）になってるよ！', context: '運休を知らせる', register: 'urgent' },
      ],
      recognition: [
        { phrase: 'delayed', meaning: '遅延している', note: '予定時刻より遅れている状態です。' },
        { phrase: 'cancelled', meaning: 'キャンセル・運休になった', note: '便や電車が運行されないことです。' },
        { phrase: 'as soon as we can', meaning: 'できるだけ早く・分かり次第', note: '情報を伝える時期をやわらかく示します。' },
        { phrase: 'platform number', meaning: 'プラットホーム番号・番線', note: '電車の発着番線です。' },
      ],
    },
    transport: {
      title: 'その他のトラブルに関する便利な表現',
      enTitle: 'More phrases',
      intro: '超過料金、ゲート閉鎖、ストライキ、乗務員不足など、交通機関で起きる問題を伝えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Your luggage has an excess charge.', meaning: 'お荷物に超過料金がかかります。', context: '追加料金を知らせる', register: 'polite' },
        { phrase: "I'm afraid the gate has closed.", meaning: 'あいにく、搭乗口はすでに閉まっております。', context: 'ゲート閉鎖を知らせる', register: 'polite' },
        { phrase: 'The baggage handlers are on strike.', meaning: '手荷物取扱スタッフがストライキを行っています。', context: 'ストライキを説明する', register: 'neutral' },
        { phrase: 'The train is cancelled due to lack of available train crew.', meaning: '乗務員不足のため、その電車は運休となりました。', context: '運休理由を説明する', register: 'formal' },
      ],
      recognition: [
        { phrase: 'excess charge', meaning: '超過料金', note: '規定量を超えた荷物などにかかる料金です。' },
        { phrase: 'baggage handlers', meaning: '手荷物取扱スタッフ', note: '空港で荷物を扱うスタッフです。' },
        { phrase: 'on strike', meaning: 'ストライキ中で', note: '労働者が業務を停止している状態です。' },
        { phrase: 'lack of available train crew', meaning: '利用できる乗務員の不足', note: '運休理由の説明です。' },
      ],
    },
    illness: {
      title: '病気と怪我',
      enTitle: 'Illness and injury',
      intro: '予定をキャンセルするほどの体調不良や事故について説明し、医師の診断書と保険の対応を確認します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Wanna come hiking tomorrow?', meaning: '明日、ハイキングに行かない？', context: '予定に誘う', register: 'casual' },
        { phrase: "I can't - I've put my back out!", meaning: '無理なんだ、腰を痛めちゃって！', context: 'けがで断る', register: 'casual' },
        { phrase: 'You look awful!', meaning: 'ひどい顔色だよ！', context: '体調を気遣う', register: 'casual' },
        { phrase: "Yeah, I won't make the beach, I've got a tummy bug!", meaning: 'うん、ビーチには行けそうにないや。お腹の風邪にかかっちゃって！', context: '病気で予定を断る', register: 'casual' },
        { phrase: "Hello, I've had an accident on holiday and I can't fly home!", meaning: 'もしもし、休暇中に事故に遭ってしまい、飛行機で家に帰ることができません！', context: '事故と帰国困難を報告する', register: 'urgent' },
        { phrase: "Your insurance should cover you if you get a doctor's note.", meaning: '医師の診断書をもらえば、保険が適用されるはずです。', context: '保険の条件を案内する', register: 'helpful' },
      ],
      recognition: [
        { phrase: 'put my back out', meaning: '腰を痛める・ぎっくり腰になる', note: '急に腰を痛めて動きにくい状態です。' },
        { phrase: 'tummy bug', meaning: 'お腹の風邪・胃腸炎', note: '旅行中の胃腸の不調をカジュアルに表します。' },
        { phrase: "won't make", meaning: '間に合わない・行けない', note: '予定に参加できないときに使います。' },
        { phrase: "doctor's note", meaning: '医師の診断書', note: '保険の請求などに必要になることがあります。' },
      ],
    },
    dialogues: [
      {
        id: 'belongings',
        label: 'Pattern A · Lost belongings',
        title: '荷物の盗難と未着を報告する',
        lines: [
          { speaker: 'A', en: "My bag's been stolen with my passport inside!", ja: 'バッグが盗まれました、中にパスポートが入っています！' },
          { speaker: 'B', en: "Okay, I'll need to take some details.", ja: 'わかりました。いくつか詳細を伺う必要があります。' },
          { speaker: 'A', en: "My suitcase hasn't shown up.", ja: '私のスーツケースが出てきません。' },
          { speaker: 'B', en: 'The airline desk can help you.', ja: '航空会社のデスクで対応してもらえますよ。' },
        ],
      },
      {
        id: 'transport',
        label: 'Pattern B · Delays and cancellations',
        title: '遅延と運休の情報を確認する',
        lines: [
          { speaker: 'A', en: "I'm afraid your flight is delayed.", ja: 'あいにく、お客様のフライトは遅れております。' },
          { speaker: 'B', en: "We'll let you know more as soon as we can.", ja: '分かり次第、すぐに詳細をお知らせします。' },
          { speaker: 'A', en: 'Look at the board. Our train has been cancelled!', ja: '案内板を見て。乗る予定の電車が運休になってるよ！' },
          { speaker: 'B', en: "I can't see our platform number anywhere...", ja: 'プラットホームの番号がどこにも見当たらないなあ…。' },
        ],
      },
      {
        id: 'illness',
        label: 'Pattern C · Illness and injury',
        title: '病気やけがと保険について相談する',
        lines: [
          { speaker: 'A', en: "I can't - I've put my back out!", ja: '無理なんだ、腰を痛めちゃって！' },
          { speaker: 'B', en: "You look awful!", ja: 'ひどい顔色だよ！' },
          { speaker: 'A', en: "I've had an accident on holiday and I can't fly home!", ja: '休暇中に事故に遭って帰国できません！' },
          { speaker: 'B', en: "Your insurance should cover you if you get a doctor's note.", ja: '診断書をもらえば、保険が適用されるはずです。' },
        ],
      },
    ],
    tip: "hasn't shown up は荷物が出てこない、leave behind は置き忘れる、put my back out は腰を痛める、tummy bug はお腹の風邪を表します。トラブルの場所と必要な対応を短く具体的に伝えましょう。",
  },
  practice: {
    title: '旅行中のトラブルを、英語で説明する',
    instructions: '日本語訳は見ずに、紛失、遅延、キャンセル、病気やけがの表現を声に重ねます。',
    coreHeading: 'まずは、困っている状況を伝える一文から。',
    dialogueHeading: '荷物、交通、体調の場面で役を切り替える。',
    dialogueDescription: '紛失や未着を報告する、遅延や運休を確認する、病気やけがと保険を相談する3つの場面を練習します。',
    finishTitle: '次に旅行中の問題が起きたとき、何が起きたかを英語でひとつ説明してみましょう。',
    corePhrases: [
      { phrase: "My bag's been stolen with my passport inside!", context: '盗難を報告する', rate: 0.72 },
      { phrase: "I'll need to take some details.", context: '詳細を確認する', rate: 0.82 },
      { phrase: "My suitcase hasn't shown up.", context: '荷物の未着を伝える', rate: 0.82 },
      { phrase: 'The airline desk can help you.', context: '窓口を案内する', rate: 0.82 },
      { phrase: "I'm afraid your flight is delayed.", context: '遅延を知らせる', rate: 0.8 },
      { phrase: "We'll let you know more as soon as we can.", context: '続報を伝える', rate: 0.7 },
      { phrase: 'Our train has been cancelled!', context: '運休を知らせる', rate: 0.84 },
      { phrase: 'Your luggage has an excess charge.', context: '超過料金を伝える', rate: 0.74 },
      { phrase: 'The baggage handlers are on strike.', context: 'ストライキを説明する', rate: 0.76 },
      { phrase: "I've put my back out!", context: '腰のけがを伝える', rate: 0.8 },
      { phrase: "I've got a tummy bug!", context: '体調不良を伝える', rate: 0.82 },
      { phrase: "Your insurance should cover you if you get a doctor's note.", context: '保険の条件を案内する', rate: 0.66 },
    ],
    dialogues: [
      { title: 'Lost belongings', lines: ["My bag's been stolen with my passport inside!", "I'll need to take some details.", "My suitcase hasn't shown up.", 'The airline desk can help you.'] },
      { title: 'Delays and cancellations', lines: ["I'm afraid your flight is delayed.", "We'll let you know more as soon as we can.", 'Look at the board. Our train has been cancelled!', "I can't see our platform number anywhere..."] },
      { title: 'Illness and injury', lines: ["I've put my back out!", 'You look awful!', "I've got a tummy bug!", "Your insurance should cover you if you get a doctor's note."] },
    ],
    natural: [
      { full: 'I am unable to locate my suitcase on the baggage carousel.', natural: "My suitcase hasn't shown up." },
      { full: 'I cannot attend the planned beach outing because I have a stomach illness.', natural: "I won't make the beach, I've got a tummy bug!" },
      { full: 'The insurer is likely to pay for your costs if you obtain written confirmation from a doctor.', natural: "Your insurance should cover you if you get a doctor's note." },
    ],
  },
}
