/** Chapter 72 · On holiday. */
export const holidayLesson = {
  id: 'holiday',
  kind: 'holiday',
  number: '72',
  title: '第72章に入る前に：なぜ「休暇・旅行に関する英語」を学ぶのでしょうか？',
  enTitle: 'On holiday',
  ja: '宿泊施設、旅行の持ち物、よく使う動詞、旅先でのアクティビティや観光に関する表現を学びます。',
  cando: '宿泊先、持ち物、旅行の予定、アクティビティ、観光名所について希望や情報を伝えられる。',
  learn: {
    intro: [
      '旅行では、どこに泊まるか、何を持っていくか、何をするかなど、普段とは違う選択や行動が増えます。',
      '自分の予定や希望を伝え、必要な情報を理解しながら、安心して旅を楽しむことが大切です。',
      'この章では、宿泊施設、旅行の持ち物、よく使う動詞、そして旅先でのアクティビティや観光に関する表現を学びます。',
    ],
    functions: [
      ['01', '宿泊先と設備を選ぶ'],
      ['02', '持ち物と旅行の準備を確認する'],
      ['03', '予約・滞在・移動の動作を伝える'],
      ['04', '活動と観光の予定を立てる'],
    ],
    accommodation: {
      title: '宿泊施設と旅の必需品',
      enTitle: 'Accommodation & holiday essentials',
      intro: '泊まる場所の種類、設備、旅行に持っていくものを選び、必要な条件を伝えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'hotel', meaning: 'ホテル', context: '宿泊施設', register: 'neutral' },
        { phrase: 'motel', meaning: 'モーテル', context: '宿泊施設', register: 'neutral' },
        { phrase: 'bed and breakfast', meaning: 'B&B・朝食付きの民宿', context: '宿泊施設', register: 'neutral' },
        { phrase: 'hostel', meaning: 'ホステル・簡易宿泊施設', context: '宿泊施設', register: 'neutral' },
        { phrase: 'chalet', meaning: 'シャレー・山小屋風コテージ', context: '宿泊施設', register: 'regional' },
        { phrase: 'cabin', meaning: 'キャビン・丸太小屋', context: '宿泊施設', register: 'neutral' },
        { phrase: 'campsite', meaning: 'キャンプ場', context: '宿泊施設', register: 'neutral' },
        { phrase: 'caravan', meaning: 'キャンピングトレーラー', context: '宿泊施設', register: 'regional' },
        { phrase: 'accessible', meaning: 'バリアフリー対応の', context: '設備・条件', register: 'neutral' },
        { phrase: 'pet-friendly', meaning: 'ペット同伴可の', context: '設備・条件', register: 'neutral' },
        { phrase: 'Wi-Fi', meaning: 'Wi-Fi', context: '設備', register: 'neutral' },
        { phrase: 'swimming pool', meaning: 'スイミングプール', context: '設備', register: 'neutral' },
        { phrase: 'balcony', meaning: 'バルコニー', context: '設備', register: 'neutral' },
        { phrase: 'cot', meaning: '幼児用ベッド・ベビーベッド', context: '設備', register: 'regional' },
        { phrase: 'room service', meaning: 'ルームサービス', context: 'サービス', register: 'neutral' },
        { phrase: 'buffet', meaning: 'ビュッフェ', context: '食事', register: 'neutral' },
        { phrase: 'passport', meaning: 'パスポート', context: '旅の必需品', register: 'neutral' },
        { phrase: 'tickets', meaning: 'チケット・乗車券・入場券', context: '旅の必需品', register: 'neutral' },
        { phrase: 'boarding pass', meaning: '搭乗券', context: '旅の必需品', register: 'neutral' },
        { phrase: 'currency', meaning: '通貨・現地の現金', context: '旅の必需品', register: 'neutral' },
        { phrase: 'travel adaptor', meaning: '変換プラグ・旅行用アダプター', context: '旅の必需品', register: 'regional' },
        { phrase: 'charger', meaning: '充電器', context: '旅の必需品', register: 'neutral' },
        { phrase: 'phrasebook', meaning: '旅行会話集', context: '旅の必需品', register: 'neutral' },
        { phrase: 'sunscreen', meaning: '日焼け止め', context: '旅の必需品', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'bed and breakfast', meaning: '朝食付きの民宿', note: 'B&B と短く呼ぶこともあります。' },
        { phrase: 'accessible', meaning: 'バリアフリー対応', note: '車椅子などに対応した設備を表します。' },
        { phrase: 'pet-friendly', meaning: 'ペット同伴可', note: '宿泊施設や飲食店の条件です。' },
        { phrase: 'cot', meaning: 'ベビーベッド', note: 'アメリカ英語では crib が一般的です。' },
        { phrase: 'travel adaptor', meaning: '旅行用変換プラグ', note: '国ごとのコンセントに合わせます。' },
      ],
    },
    verbs: {
      title: '旅行でよく使う動詞',
      enTitle: 'Verbs',
      intro: 'フライト予約からホテルのチェックアウトまで、旅行の各ステップを表す動詞です。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'to book a flight', meaning: 'フライトを予約する', context: '予約', register: 'neutral' },
        { phrase: 'to make a reservation', meaning: 'ホテルやレストランを予約する', context: '予約', register: 'neutral' },
        { phrase: 'to go on holiday', meaning: '休暇に行く・旅行に出かける', context: '旅行', register: 'regional' },
        { phrase: 'to rent a cottage', meaning: 'コテージを借りる', context: '宿泊', register: 'neutral' },
        { phrase: 'to stay in a hotel', meaning: 'ホテルに滞在する', context: '宿泊', register: 'neutral' },
        { phrase: 'to book a pitch', meaning: 'テント用区画を予約する', context: 'キャンプ', register: 'regional' },
        { phrase: 'to pack (a suitcase)', meaning: 'スーツケースに荷造りする', context: '準備', register: 'neutral' },
        { phrase: 'to change money', meaning: '両替する', context: 'お金', register: 'neutral' },
        { phrase: 'to go abroad', meaning: '海外に行く', context: '旅行', register: 'neutral' },
        { phrase: 'to hire a car', meaning: 'レンタカーを借りる', context: '移動', register: 'regional' },
        { phrase: 'to check in', meaning: 'チェックインする', context: '宿泊・搭乗', register: 'neutral' },
        { phrase: 'to check out', meaning: 'チェックアウトする', context: '宿泊', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'go on holiday', meaning: '休暇に行く', note: 'アメリカ英語では go on vacation です。' },
        { phrase: 'book a pitch', meaning: 'キャンプ区画を予約する', note: 'pitch はテント用の一区画です。' },
        { phrase: 'hire a car', meaning: 'レンタカーを借りる', note: 'イギリス英語でよく使います。' },
        { phrase: 'check in / check out', meaning: 'チェックイン / チェックアウトする', note: '宿泊施設や空港で使います。' },
      ],
    },
    activities: {
      title: '旅先でのアクティビティ',
      enTitle: 'Holiday activities',
      intro: '海、山、雪の中で楽しむスポーツやアウトドア活動について話します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'surfing', meaning: 'サーフィン', context: '水上アクティビティ', register: 'neutral' },
        { phrase: 'water-skiing', meaning: '水上スキー', context: '水上アクティビティ', register: 'neutral' },
        { phrase: 'kayaking', meaning: 'カヤック', context: '水上アクティビティ', register: 'neutral' },
        { phrase: 'windsurfing', meaning: 'ウインドサーフィン', context: '水上アクティビティ', register: 'neutral' },
        { phrase: 'sail', meaning: '帆・セイル', context: '道具', register: 'neutral' },
        { phrase: 'board', meaning: 'ボード・板', context: '道具', register: 'neutral' },
        { phrase: 'life jacket', meaning: '救命胴衣', context: '安全装備', register: 'neutral' },
        { phrase: 'paragliding', meaning: 'パラグライダー', context: '空のアクティビティ', register: 'neutral' },
        { phrase: 'swimming', meaning: '水泳', context: '水中アクティビティ', register: 'neutral' },
        { phrase: 'snorkelling', meaning: 'シュノーケリング', context: '水中アクティビティ', register: 'regional' },
        { phrase: 'scuba diving', meaning: 'スキューバダイビング', context: '水中アクティビティ', register: 'neutral' },
        { phrase: 'hiking', meaning: 'ハイキング', context: '山のアクティビティ', register: 'neutral' },
        { phrase: 'playing golf', meaning: 'ゴルフをすること', context: 'スポーツ', register: 'neutral' },
        { phrase: 'rock climbing', meaning: 'ロッククライミング', context: '山のアクティビティ', register: 'neutral' },
        { phrase: 'snowboarding', meaning: 'スノーボード', context: '雪のアクティビティ', register: 'neutral' },
        { phrase: 'skiing', meaning: 'スキー', context: '雪のアクティビティ', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'life jacket', meaning: '救命胴衣', note: '水上・水中アクティビティの安全装備です。' },
        { phrase: 'snorkelling', meaning: 'シュノーケリング', note: 'アメリカ英語では snorkeling と綴ります。' },
        { phrase: 'scuba diving', meaning: 'スキューバダイビング', note: '水中で呼吸器を使う活動です。' },
        { phrase: 'rock climbing', meaning: 'ロッククライミング', note: '岩壁を登るスポーツです。' },
      ],
    },
    sightseeing: {
      title: '観光とアトラクション',
      enTitle: 'Sightseeing and attractions',
      intro: '観光案内所で情報を集め、地図を見ながら名所やツアーを回ります。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'tourist map', meaning: '観光地図', context: '案内', register: 'neutral' },
        { phrase: 'tourist office', meaning: '観光案内所', context: '案内', register: 'neutral' },
        { phrase: 'guided tour', meaning: 'ガイド付きツアー', context: 'ツアー', register: 'neutral' },
        { phrase: 'museum', meaning: '博物館', context: '名所', register: 'neutral' },
        { phrase: 'art gallery', meaning: '美術館', context: '名所', register: 'neutral' },
        { phrase: 'craft market', meaning: 'クラフトマーケット', context: '買い物・市場', register: 'neutral' },
        { phrase: 'castle', meaning: '城', context: '名所', register: 'neutral' },
        { phrase: 'palace', meaning: '宮殿', context: '名所', register: 'neutral' },
        { phrase: 'church', meaning: '教会', context: '名所', register: 'neutral' },
        { phrase: 'gardens', meaning: '庭園・植物園', context: '名所', register: 'neutral' },
        { phrase: 'water park', meaning: 'ウォーターパーク', context: 'アトラクション', register: 'neutral' },
        { phrase: 'boat trip', meaning: 'ボートツアー・船旅', context: 'アトラクション', register: 'neutral' },
        { phrase: 'wildlife park', meaning: '野生動物公園・サファリパーク', context: 'アトラクション', register: 'neutral' },
        { phrase: 'mountains', meaning: '山・山脈', context: '自然', register: 'neutral' },
        { phrase: 'island', meaning: '島', context: '自然', register: 'neutral' },
        { phrase: 'beach', meaning: 'ビーチ・海岸', context: '自然', register: 'neutral' },
        { phrase: 'lighthouse', meaning: '灯台', context: '名所', register: 'neutral' },
        { phrase: 'pier', meaning: '桟橋・ピア', context: '名所', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'tourist office', meaning: '観光案内所', note: '地図やツアー情報をもらう場所です。' },
        { phrase: 'guided tour', meaning: 'ガイド付きツアー', note: 'ガイドの説明を聞きながら回ります。' },
        { phrase: 'craft market', meaning: 'クラフトマーケット', note: '手芸品や工芸品の市場です。' },
        { phrase: 'pier', meaning: '桟橋', note: '海や湖に突き出した通路・桟橋を指します。' },
      ],
    },
    dialogues: [
      {
        id: 'accommodation',
        label: 'Pattern A · Accommodation',
        title: '宿泊先と設備を選ぶ',
        lines: [
          { speaker: 'A', en: "We'd like to stay in a bed and breakfast.", ja: 'B&Bに泊まりたいです。' },
          { speaker: 'B', en: 'Is it pet-friendly?', ja: 'ペット同伴可ですか？' },
          { speaker: 'A', en: 'Does it have Wi-Fi and a balcony?', ja: 'Wi-Fiとバルコニーはありますか？' },
          { speaker: 'B', en: 'Yes, and there is a swimming pool.', ja: 'はい、スイミングプールもあります。' },
        ],
      },
      {
        id: 'activities',
        label: 'Pattern B · Holiday activities',
        title: '休暇の活動を決める',
        lines: [
          { speaker: 'A', en: "Let's go kayaking tomorrow.", ja: '明日はカヤックに行こう。' },
          { speaker: 'B', en: 'Good idea. I want to try snorkelling, too.', ja: 'いいね。私もシュノーケリングをやってみたい。' },
          { speaker: 'A', en: 'We can pack the sunscreen and life jackets.', ja: '日焼け止めと救命胴衣を荷造りできるよ。' },
          { speaker: 'B', en: 'Great! The beach is nearby.', ja: 'いいね！ビーチは近くだよ。' },
        ],
      },
      {
        id: 'sightseeing',
        label: 'Pattern C · Sightseeing',
        title: '観光名所を回る',
        lines: [
          { speaker: 'A', en: 'Where is the tourist office?', ja: '観光案内所はどこですか？' },
          { speaker: 'B', en: 'Let\'s get a tourist map and book a guided tour.', ja: '観光地図をもらってガイド付きツアーを予約しよう。' },
          { speaker: 'A', en: 'Shall we visit the castle and the gardens?', ja: '城と庭園を見に行かない？' },
          { speaker: 'B', en: 'Yes, then we can walk to the pier.', ja: 'うん、そのあと桟橋まで歩けるね。' },
        ],
      },
    ],
    tip: 'イギリス英語では休暇を holiday、アメリカ英語では vacation と言います。キャンプ場のテント用区画は pitch、ベビーベッドは cot、レンタカーは hire a car と表現します。',
  },
  practice: {
    title: '休暇の予定と希望を、英語で話す',
    instructions: '日本語訳は見ずに、宿泊、荷造り、活動、観光の表現を声に重ねます。',
    coreHeading: 'まずは、どこに泊まり何をするか伝える一文から。',
    dialogueHeading: '宿泊、アクティビティ、観光の場面で役を切り替える。',
    dialogueDescription: '宿泊先と設備を選ぶ、休暇の活動を決める、観光名所を回る3つの場面を練習します。',
    finishTitle: '次に旅行の計画を立てるとき、宿泊か観光の英語をひとつ使ってみましょう。',
    corePhrases: [
      { phrase: "We'd like to stay in a bed and breakfast.", context: '宿泊先を選ぶ', rate: 0.76 },
      { phrase: 'Is it pet-friendly?', context: '宿の条件を尋ねる', rate: 0.84 },
      { phrase: 'Does it have Wi-Fi and a balcony?', context: '設備を尋ねる', rate: 0.78 },
      { phrase: 'I need to pack my passport and boarding pass.', context: '持ち物を準備する', rate: 0.76 },
      { phrase: 'We need to change money.', context: '両替する', rate: 0.82 },
      { phrase: "Let's go kayaking tomorrow.", context: '活動を提案する', rate: 0.82 },
      { phrase: 'I want to try snorkelling, too.', context: '活動の希望を伝える', rate: 0.78 },
      { phrase: 'Where is the tourist office?', context: '観光案内所を尋ねる', rate: 0.84 },
      { phrase: "Let's get a tourist map and book a guided tour.", context: '観光を計画する', rate: 0.72 },
      { phrase: 'Shall we visit the castle and the gardens?', context: '名所を提案する', rate: 0.76 },
      { phrase: 'I would like to book a pitch.', context: 'キャンプ区画を予約する', rate: 0.78 },
      { phrase: 'We are going abroad next month.', context: '海外旅行を伝える', rate: 0.78 },
    ],
    dialogues: [
      { title: 'Accommodation', lines: ["We'd like to stay in a bed and breakfast.", 'Is it pet-friendly?', 'Does it have Wi-Fi and a balcony?', 'Yes, and there is a swimming pool.'] },
      { title: 'Holiday activities', lines: ["Let's go kayaking tomorrow.", 'Good idea. I want to try snorkelling, too.', 'We can pack the sunscreen and life jackets.', 'Great! The beach is nearby.'] },
      { title: 'Sightseeing', lines: ['Where is the tourist office?', "Let's get a tourist map and book a guided tour.", 'Shall we visit the castle and the gardens?', 'Yes, then we can walk to the pier.'] },
    ],
    natural: [
      { full: 'We would prefer to spend our stay at a small bed-and-breakfast.', natural: "We'd like to stay in a bed and breakfast." },
      { full: 'Could you tell me the location of the local visitor information centre?', natural: 'Where is the tourist office?' },
      { full: 'Would you like to go kayaking on the following day?', natural: "Let's go kayaking tomorrow." },
    ],
  },
}
