/** Chapter 61 · Home improvements. */
export const homeImprovementsLesson = {
  id: 'home-improvements',
  kind: 'home-improvements',
  number: '61',
  title: '第61章に入る前に：なぜ「住宅のリフォームで使う英語」を学ぶのでしょうか？',
  enTitle: 'Home improvements',
  ja: 'DIYの作業、専門業者への依頼、見積もりについて話す英語を学びます。',
  cando: '住宅のリフォーム内容を説明し、進捗、見積もり、材料について確認できる。',
  learn: {
    intro: [
      '家をより快適にするためには、自分で修理や模様替えをすることもあれば、専門の業者にお願いすることもあります。',
      'そのときは、何をしたいのか、どこまで作業が進んでいるのか、そして費用や条件をはっきり確認することが大切です。',
      'DIYの進み具合を共有し、難しい作業は専門家に相談することで、リフォームの計画を安心して進められます。',
      'この章では、DIYの作業について話す表現や、専門業者への依頼、見積もりについてのやり取りを学びます。',
    ],
    functions: [
      ['01', 'DIYの進み具合を伝える'],
      ['02', '必要な作業を説明する'],
      ['03', '業者に見積もりを頼む'],
      ['04', '費用と材料を確認する'],
    ],
    diy: {
      title: 'DIYでのリフォーム',
      enTitle: 'DIY decorating',
      intro: '作業の進捗、残っている工程、仕上がりについて、家族や友人と確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'How are you getting on?', meaning: '進み具合はどうですか？', context: '作業の進捗を尋ねる', register: 'casual' },
        { phrase: "The tiles are all up. Just the grouting to go and I'm done!", meaning: 'タイルはすべて貼り終わりました。あとは目地を詰めるだけで終わりです！', context: '残りの作業を伝える', register: 'casual' },
        { phrase: "I've finished stripping the walls.", meaning: '壁紙を剥がし終えました。', context: '作業の完了を伝える', register: 'neutral' },
        { phrase: "Great! Let's hang this new wallpaper, then.", meaning: '素晴らしい！じゃあ、この新しい壁紙を貼りましょう。', context: '次の作業を提案する', register: 'casual' },
        { phrase: "It's looking good!", meaning: 'いい感じになってきたね！', context: '仕上がりを褒める', register: 'casual' },
        { phrase: 'Thank you, one more coat of paint should do it, I reckon.', meaning: 'ありがとう、あと1回ペンキを重ね塗りすれば大丈夫だと思うよ。', context: '残りの塗装を見積もる', register: 'casual' },
      ],
      recognition: [
        { phrase: 'get on', meaning: '進む・進み具合がどうか', note: 'How are you getting on? で「順調？」と尋ねます。' },
        { phrase: 'all up', meaning: 'すべて取り付け・貼り付け済み', note: 'タイルや棚などが設置し終わった状態です。' },
        { phrase: 'grouting', meaning: '目地を詰める作業', note: 'tile の間を grout で埋める工程です。' },
        { phrase: 'one more coat', meaning: 'もう1回の塗り重ね', note: 'paint を重ねる回数を伝える表現です。' },
      ],
    },
    professional: {
      title: '専門業者への依頼',
      enTitle: 'Hiring a professional',
      intro: '必要な作業を説明し、訪問日と見積もりを依頼する電話の流れです。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'ABC Decorators, how can I help?', meaning: 'ABCデコレーターズです。どのようなご用件でしょうか？', context: '業者の電話応対', register: 'polite' },
        { phrase: 'Hi, we need someone to put up some shelves.', meaning: '棚を取り付けてくれる人を探しています。', context: '依頼したい作業を説明する', register: 'polite' },
        { phrase: 'Sure, we can do that for you.', meaning: 'かしこまりました、対応可能です。', context: '対応できると伝える', register: 'polite' },
        { phrase: 'Are you able to come round and give us a quote?', meaning: 'こちらの家に来て、見積もりを出していただけますか？', context: '訪問見積もりを頼む', register: 'polite' },
        { phrase: 'I could come over on Thursday.', meaning: '木曜日なら伺うことができます。', context: '訪問日を提案する', register: 'neutral' },
        { phrase: 'Could you put up this wardrobe?', meaning: 'このワードローブを組み立てて設置していただけますか？', context: '家具の設置を頼む', register: 'polite' },
        { phrase: 'Can you give us a quote for fixing our fence?', meaning: 'フェンスの修理に見積もりをいただけますか？', context: '修理の見積もりを頼む', register: 'polite' },
        { phrase: 'We need someone to paint our kitchen walls.', meaning: 'キッチンの壁にペンキを塗ってくれる人を探しています。', context: '依頼内容を具体化する', register: 'neutral' },
        { phrase: "I'd like a quote for fitting a carpet.", meaning: 'カーペットを敷くための見積もりをいただきたいです。', context: '施工の見積もりを頼む', register: 'polite' },
        { phrase: 'Is that your best quote?', meaning: 'これが最安の見積もりですか？', context: '提示額を確認する', register: 'polite' },
        { phrase: 'Will you supply the materials?', meaning: '材料はそちらで用意していただけますか？', context: '材料の負担を確認する', register: 'polite' },
      ],
      recognition: [
        { phrase: 'put up shelves', meaning: '棚を取り付ける', note: '壁などに棚を設置する動作です。' },
        { phrase: 'come round', meaning: 'こちらへ訪ねて来る', note: '業者が家に来るときのイギリス英語です。' },
        { phrase: 'give us a quote', meaning: '私たちに見積もりを出す', note: 'サービス業者への依頼でよく使います。' },
        { phrase: 'supply the materials', meaning: '材料を用意する', note: '費用に材料費が含まれるか確認できます。' },
      ],
    },
    vocabulary: {
      title: 'リフォームのボキャブラリー',
      enTitle: 'Vocabulary · Home improvements',
      intro: '作業、施工、価格を表す言葉を、実際の依頼や見積もりと結びつけます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'quote', meaning: '見積もり・提示額', context: '費用', register: 'neutral' },
        { phrase: 'estimate', meaning: '見積もり・概算', context: '費用', register: 'neutral' },
        { phrase: 'put up', meaning: '取り付ける・設置する', context: '施工', register: 'neutral' },
        { phrase: 'fit', meaning: 'ぴったり合わせて敷く・取り付ける', context: '施工', register: 'neutral' },
        { phrase: 'grout', meaning: '目地材・目地を詰める', context: 'タイル', register: 'neutral' },
        { phrase: 'strip the walls', meaning: '壁紙を剥がす', context: '下準備', register: 'neutral' },
        { phrase: 'coat of paint', meaning: 'ペンキのひと塗り', context: '塗装', register: 'neutral' },
        { phrase: 'I reckon', meaning: '〜だと思う・〜だと見積もる', context: '判断', register: 'regional' },
      ],
      recognition: [
        { phrase: 'quote vs estimate', meaning: '確定に近い見積もりと概算', note: '日常のサービス業では quote がよく使われます。' },
        { phrase: 'put up', meaning: '壁などに取り付ける', note: '棚やワードローブの設置に使います。' },
        { phrase: 'fit', meaning: '空間に合わせて敷く・取り付ける', note: 'カーペットや床材などに使います。' },
        { phrase: 'I reckon', meaning: '〜だと思う', note: 'I think / I guess に近いイギリス口語です。' },
      ],
    },
    dialogues: [
      {
        id: 'diy',
        label: 'Pattern A · DIY decorating',
        title: 'DIYの進み具合を話す',
        lines: [
          { speaker: 'A', en: 'How are you getting on?', ja: '進み具合はどうですか？' },
          { speaker: 'B', en: "The tiles are all up. Just the grouting to go and I'm done!", ja: 'タイルはすべて貼り終わりました。あとは目地を詰めるだけで終わりです！' },
          { speaker: 'A', en: "It's looking good!", ja: 'いい感じになってきたね！' },
          { speaker: 'B', en: 'Thank you, one more coat of paint should do it, I reckon.', ja: 'ありがとう、あと1回ペンキを重ね塗りすれば大丈夫だと思うよ。' },
        ],
      },
      {
        id: 'professional',
        label: 'Pattern B · Hiring a professional',
        title: '業者に訪問見積もりを頼む',
        lines: [
          { speaker: 'A', en: 'ABC Decorators, how can I help?', ja: 'ABCデコレーターズです。どのようなご用件でしょうか？' },
          { speaker: 'B', en: 'Hi, we need someone to put up some shelves.', ja: '棚を取り付けてくれる人を探しています。' },
          { speaker: 'A', en: 'Are you able to come round and give us a quote?', ja: 'こちらの家に来て、見積もりを出していただけますか？' },
          { speaker: 'B', en: 'I could come over on Thursday.', ja: '木曜日なら伺うことができます。' },
        ],
      },
      {
        id: 'quote',
        label: 'Pattern C · Checking a quote',
        title: '見積もりと材料を確認する',
        lines: [
          { speaker: 'A', en: 'Can you give us a quote for fixing our fence?', ja: 'フェンスの修理に見積もりをいただけますか？' },
          { speaker: 'B', en: 'Of course. Will you supply the materials?', ja: 'もちろんです。材料はそちらで用意していただけますか？' },
          { speaker: 'A', en: 'No, we can supply them.', ja: 'いいえ、こちらで用意できます。' },
          { speaker: 'B', en: 'Is that your best quote?', ja: 'これが最安の見積もりですか？' },
        ],
      },
    ],
    tip: '見積もりには quote が日常のサービス業でよく使われ、estimate は概算を表します。put up は棚や家具を取り付ける動作、fit はカーペットなどを空間に合わせて敷く動作です。How are you getting on? は作業や勉強の進捗を尋ねる自然な表現で、I reckon は I think に近いイギリス口語です。',
  },
  practice: {
    title: 'リフォームの希望と見積もりを、英語で具体的に伝える',
    instructions: '日本語訳は見ずに、DIYの進捗、業者への依頼、見積もり確認の表現を声に重ねます。',
    coreHeading: 'まずは、作業の進み具合を尋ねる一文から。',
    dialogueHeading: 'DIY、業者への電話、見積もり確認の場面で役を切り替える。',
    dialogueDescription: '作業の残りを伝える、訪問見積もりを頼む、費用と材料を確認する3つの場面を練習します。',
    finishTitle: '次にリフォームの相談をするとき、作業か見積もりの表現をひとつ使ってみましょう。',
    corePhrases: [
      { phrase: 'How are you getting on?', context: '進み具合を尋ねる', rate: 0.82 },
      { phrase: "The tiles are all up. Just the grouting to go and I'm done!", context: '残りの作業を伝える', rate: 0.76 },
      { phrase: "I've finished stripping the walls.", context: '作業の完了を伝える', rate: 0.8 },
      { phrase: "Let's hang this new wallpaper, then.", context: '次の作業を提案する', rate: 0.8 },
      { phrase: "It's looking good!", context: '仕上がりを褒める', rate: 0.86 },
      { phrase: 'One more coat of paint should do it, I reckon.', context: '塗装の残りを見積もる', rate: 0.76 },
      { phrase: 'We need someone to put up some shelves.', context: '業者を探す', rate: 0.8 },
      { phrase: 'Are you able to come round and give us a quote?', context: '訪問見積もりを頼む', rate: 0.74 },
      { phrase: 'I could come over on Thursday.', context: '訪問日を提案する', rate: 0.82 },
      { phrase: 'Can you give us a quote for fixing our fence?', context: '修理の見積もりを頼む', rate: 0.74 },
      { phrase: 'Is that your best quote?', context: '提示額を確認する', rate: 0.82 },
      { phrase: 'Will you supply the materials?', context: '材料を確認する', rate: 0.82 },
    ],
    dialogues: [
      { title: 'DIY decorating', lines: ['How are you getting on?', "The tiles are all up. Just the grouting to go and I'm done!", "It's looking good!", 'One more coat of paint should do it, I reckon.'] },
      { title: 'Hiring a professional', lines: ['ABC Decorators, how can I help?', 'Hi, we need someone to put up some shelves.', 'Are you able to come round and give us a quote?', 'I could come over on Thursday.'] },
      { title: 'Checking a quote', lines: ['Can you give us a quote for fixing our fence?', 'Will you supply the materials?', 'No, we can supply them.', 'Is that your best quote?'] },
    ],
    natural: [
      { full: 'How is the home improvement project progressing?', natural: 'How are you getting on?' },
      { full: 'Can you provide us with a price estimate for repairing our fence?', natural: 'Can you give us a quote for fixing our fence?' },
      { full: 'Will your company provide the required materials?', natural: 'Will you supply the materials?' },
    ],
  },
}
