/** Chapter 56 · The home. */
export const homeLesson = {
  id: 'home',
  kind: 'home',
  number: '56',
  title: '第56章に入る前に：なぜ「家に関する英語」を学ぶのでしょうか？',
  enTitle: 'The home',
  ja: '住宅の種類、部屋、家具、家電、家の修繕について話す英語を学びます。',
  cando: '自分の住まいや部屋、家のもの、修繕の予定を分かりやすく説明できる。',
  learn: {
    intro: [
      '家は、私たちの日常生活の中で最も身近なものの一つです。どんな家に住んでいるのか、どんな部屋や物があるのかを話すとき、家に関する言葉が必要になります。',
      '家の中を案内したり、家具や家電の場所を説明したり、近所の様子を伝えたりすると、相手は私たちの暮らしを具体的にイメージできます。',
      'また、壁を塗ったり、棚を取り付けたり、配線を直したりするときにも、作業と道具を正確に伝えることが大切です。',
      'この章では、住宅の種類、部屋や場所、家具や家電、そして家の修繕に関する表現を学びます。',
    ],
    functions: [
      ['01', '住まいのタイプを説明する'],
      ['02', '部屋と場所を案内する'],
      ['03', '家具と家電を言う'],
      ['04', '修繕やリフォームを相談する'],
    ],
    homes: {
      title: '住宅の種類と近所',
      enTitle: 'Homes and neighbourhoods',
      intro: '住んでいる家のタイプや、海外でよく聞く住宅の形を具体的に説明します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'I live in a flat.', meaning: '私はアパートの1戸に住んでいます。', context: '住まいを言う', register: 'neutral' },
        { phrase: 'It is in a block of flats.', meaning: 'それはマンション・アパートの建物の中にあります。', context: '建物を説明する', register: 'neutral' },
        { phrase: 'They live in a detached house.', meaning: '彼らは独立した一戸建てに住んでいます。', context: '一戸建てを説明する', register: 'neutral' },
        { phrase: 'We bought a semi-detached house.', meaning: '私たちは2軒が壁を共有する家を買いました。', context: '住宅形態を説明する', register: 'neutral' },
        { phrase: 'She grew up in a terraced house.', meaning: '彼女は連結住宅で育ちました。', context: '育った家を話す', register: 'neutral' },
        { phrase: 'The cottage is in the countryside.', meaning: 'そのコテージは田舎にあります。', context: '場所と家を説明する', register: 'neutral' },
        { phrase: 'We are looking for a bungalow.', meaning: '私たちは平屋住宅を探しています。', context: '住まいを探す', register: 'neutral' },
        { phrase: 'The top-floor flat is a penthouse.', meaning: '最上階の住戸はペントハウスです。', context: '特別な住戸を説明する', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'townhouse', meaning: 'タウンハウス', note: '都市部の連続した住宅を指します。' },
        { phrase: 'cabin', meaning: '丸太小屋・キャビン', note: '森や山などの小さな家に使います。' },
        { phrase: 'mobile home', meaning: '移動式住宅', note: 'トレーラーハウスのような住居です。' },
        { phrase: 'maisonette / duplex', meaning: 'メゾネット・2階層の住戸', note: '1戸の中に上下2つの階がある住まいです。' },
      ],
    },
    rooms: {
      title: '部屋と家の中のエリア',
      enTitle: 'Rooms and home areas',
      intro: '部屋の名前だけでなく、上下の階、廊下、庭、車庫などの場所も案内できるようにします。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'The bedrooms are upstairs.', meaning: '寝室は上の階にあります。', context: '階を案内する', register: 'neutral' },
        { phrase: 'The living room is downstairs.', meaning: 'リビングは下の階にあります。', context: '部屋の場所を言う', register: 'neutral' },
        { phrase: 'There is a small study next to the hallway.', meaning: '廊下の隣に小さな書斎があります。', context: '部屋を案内する', register: 'neutral' },
        { phrase: 'The kitchen opens onto the dining room.', meaning: 'キッチンはダイニングルームにつながっています。', context: '部屋のつながりを説明する', register: 'neutral' },
        { phrase: 'The bathroom is at the top of the stairs.', meaning: '浴室は階段の上にあります。', context: '場所を説明する', register: 'neutral' },
        { phrase: 'We have a balcony overlooking the garden.', meaning: '庭を見渡せるバルコニーがあります。', context: '屋外スペースを説明する', register: 'neutral' },
        { phrase: 'The garage is behind the house.', meaning: '車庫は家の裏にあります。', context: '敷地を案内する', register: 'neutral' },
        { phrase: 'The fence needs painting and the roof needs checking.', meaning: 'フェンスは塗装が必要で、屋根は点検が必要です。', context: '家の状態を伝える', register: 'polite' },
      ],
      recognition: [
        { phrase: 'loft', meaning: 'ロフト・屋根裏部屋', note: '屋根の下の収納や部屋を指します。' },
        { phrase: 'hallway', meaning: '廊下・玄関ホール', note: '部屋と部屋をつなぐ通路です。' },
        { phrase: 'upstairs / downstairs', meaning: '上の階 / 下の階', note: 'イギリス英語の日常会話でよく使います。' },
        { phrase: 'stairs / roof', meaning: '階段 / 屋根', note: '家の構造や場所を説明する基本語彙です。' },
      ],
    },
    improvements: {
      title: '家の修繕とリフォーム',
      enTitle: 'Home improvements',
      intro: '何を直すのか、どんな作業をするのかを具体的に伝え、DIYや業者への相談につなげます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'I am going to paint the door.', meaning: 'ドアにペンキを塗る予定です。', context: '塗装を話す', register: 'neutral' },
        { phrase: 'We need to grout the bathroom tiles.', meaning: '浴室のタイルに目地を詰める必要があります。', context: 'タイルを直す', register: 'neutral' },
        { phrase: 'They are stripping the walls.', meaning: '彼らは壁紙を剥がしています。', context: '壁を改修する', register: 'neutral' },
        { phrase: 'Could you fill this crack?', meaning: 'このひび割れを埋めてもらえますか？', context: '補修を頼む', register: 'polite' },
        { phrase: 'The electrician will rewire the house.', meaning: '電気工事士が家の配線を引き直します。', context: '配線工事を説明する', register: 'neutral' },
        { phrase: 'We need to fix the fence and put up shelves.', meaning: 'フェンスを直して、棚を取り付ける必要があります。', context: '作業をまとめる', register: 'neutral' },
        { phrase: 'We are fitting a new carpet.', meaning: '新しいカーペットを敷いています。', context: '床を変える', register: 'neutral' },
        { phrase: 'They are building an extension.', meaning: '彼らは増築しています。', context: 'リフォームを説明する', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'make curtains', meaning: 'カーテンを作る', note: '手作りやオーダーメイドのカーテンに使います。' },
        { phrase: 'rewire the house', meaning: '家の配線を引き直す', note: '電気工事の大きな改修を表します。' },
        { phrase: 'fit a carpet', meaning: 'カーペットを敷く', note: '床にカーペットを取り付ける表現です。' },
        { phrase: 'build an extension', meaning: '増築する', note: '家に新しい部屋や部分を付け足します。' },
      ],
    },
    vocabulary: {
      title: '家電と家具',
      enTitle: 'Appliances & furniture',
      intro: '家の中にあるものを言えると、場所の説明や故障の相談が具体的になります。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'The fridge-freezer is in the kitchen.', meaning: '冷蔵冷凍庫はキッチンにあります。', context: '家電の場所', register: 'neutral' },
        { phrase: 'The oven is not working properly.', meaning: 'オーブンがきちんと動いていません。', context: '家電の不具合', register: 'polite' },
        { phrase: 'The washing machine is beside the sink.', meaning: '洗濯機はシンクの隣にあります。', context: '家電の位置', register: 'neutral' },
        { phrase: 'There is a dishwasher under the worktop.', meaning: '作業台の下に食洗機があります。', context: '家電を説明する', register: 'neutral' },
        { phrase: 'My wardrobe is full of winter coats.', meaning: '私の洋服だんすは冬のコートでいっぱいです。', context: '収納を話す', register: 'neutral' },
        { phrase: 'The chest of drawers is in the bedroom.', meaning: 'チェストは寝室にあります。', context: '家具の場所', register: 'neutral' },
        { phrase: 'We keep the dishes in the sideboard.', meaning: '食器はサイドボードに入れています。', context: '収納を説明する', register: 'neutral' },
        { phrase: 'The baby sleeps in a cot.', meaning: '赤ちゃんはベビーベッドで寝ます。', context: '英米語の違いを知る', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'cot', meaning: 'ベビーベッド', note: 'イギリス英語で、アメリカ英語の crib にあたります。' },
        { phrase: 'wardrobe', meaning: '洋服だんす', note: 'アメリカ英語では closet がよく使われます。' },
        { phrase: 'chest of drawers', meaning: '引き出し付きの収納家具', note: '衣類などをしまうチェストです。' },
        { phrase: 'sideboard', meaning: 'サイドボード・低い収納棚', note: 'ダイニングで食器をしまう家具です。' },
      ],
    },
    dialogues: [
      {
        id: 'home-type',
        label: 'Pattern A · Describing a home',
        title: '住んでいる家を説明する',
        lines: [
          { speaker: 'A', en: 'What sort of home do you live in?', ja: 'どんな家に住んでいますか？' },
          { speaker: 'B', en: 'I live in a flat in a block of flats.', ja: 'マンションの1戸に住んでいます。' },
          { speaker: 'A', en: 'Is it near the town centre?', ja: '街の中心部の近くですか？' },
          { speaker: 'B', en: 'Yes, and we have a balcony overlooking the garden.', ja: 'はい、庭を見渡せるバルコニーもあります。' },
        ],
      },
      {
        id: 'rooms',
        label: 'Pattern B · Showing someone around',
        title: '家の中を案内する',
        lines: [
          { speaker: 'A', en: 'Come in. The living room is downstairs.', ja: 'どうぞ。リビングは下の階です。' },
          { speaker: 'B', en: 'And where is the study?', ja: '書斎はどこですか？' },
          { speaker: 'A', en: 'It is next to the hallway, opposite the kitchen.', ja: '廊下の隣で、キッチンの向かいです。' },
          { speaker: 'B', en: 'Great. I can see the garden from here.', ja: 'すてきですね。ここから庭が見えます。' },
        ],
      },
      {
        id: 'improvements',
        label: 'Pattern C · Home improvements',
        title: '修繕の予定を相談する',
        lines: [
          { speaker: 'A', en: 'What are you doing this weekend?', ja: '今週末は何をする予定ですか？' },
          { speaker: 'B', en: 'We are going to paint the door and fix the fence.', ja: 'ドアを塗って、フェンスを直す予定です。' },
          { speaker: 'A', en: 'Do you need help putting up the shelves?', ja: '棚を取り付けるのを手伝いましょうか？' },
          { speaker: 'B', en: 'That would be great. The wall also has a crack to fill.', ja: '助かります。壁には埋める必要のあるひび割れもあります。' },
        ],
      },
    ],
    tip: 'flat はイギリス英語の「アパートの1戸」、建物全体は block of flats と言います。semi-detached house は2軒が壁を共有する家、terraced house は複数の家が横につながる家、detached house は独立した一戸建てです。また、幼児用ベッドはイギリス英語で cot、洋服だんすは wardrobe と呼びます。',
  },
  practice: {
    title: '家と暮らしを、英語で具体的に説明する',
    instructions: '日本語訳は見ずに、住まい、部屋、家電、修繕の表現を声に重ねます。',
    coreHeading: 'まずは、自分の家を説明する一文から。',
    dialogueHeading: '住まい、案内、修繕の場面で役を切り替える。',
    dialogueDescription: 'どんな家に住んでいるか話す、家の中を案内する、修繕を相談する3つの場面を練習します。',
    finishTitle: '次に家について話すとき、部屋か修繕の表現をひとつ使ってみましょう。',
    corePhrases: [
      { phrase: 'I live in a flat.', context: '住まいを言う', rate: 0.84 },
      { phrase: 'They live in a detached house.', context: '一戸建てを説明する', rate: 0.8 },
      { phrase: 'The bedrooms are upstairs.', context: '階を案内する', rate: 0.82 },
      { phrase: 'The living room is downstairs.', context: '部屋の場所を言う', rate: 0.82 },
      { phrase: 'There is a small study next to the hallway.', context: '部屋を案内する', rate: 0.76 },
      { phrase: 'We have a balcony overlooking the garden.', context: '屋外スペースを説明する', rate: 0.76 },
      { phrase: 'The fridge-freezer is in the kitchen.', context: '家電の場所を言う', rate: 0.8 },
      { phrase: 'The oven is not working properly.', context: '家電の不具合を伝える', rate: 0.76 },
      { phrase: 'I am going to paint the door.', context: '塗装を話す', rate: 0.8 },
      { phrase: 'Could you fill this crack?', context: '補修を頼む', rate: 0.82 },
      { phrase: 'We need to fix the fence and put up shelves.', context: '作業をまとめる', rate: 0.74 },
      { phrase: 'They are building an extension.', context: '増築を説明する', rate: 0.8 },
    ],
    dialogues: [
      { title: 'Describing a home', lines: ['What sort of home do you live in?', 'I live in a flat in a block of flats.', 'Is it near the town centre?', 'Yes, and we have a balcony overlooking the garden.'] },
      { title: 'Showing someone around', lines: ['Come in. The living room is downstairs.', 'And where is the study?', 'It is next to the hallway, opposite the kitchen.', 'Great. I can see the garden from here.'] },
      { title: 'Home improvements', lines: ['What are you doing this weekend?', 'We are going to paint the door and fix the fence.', 'Do you need help putting up the shelves?', 'That would be great. The wall also has a crack to fill.'] },
    ],
    natural: [
      { full: 'I live in an apartment in an apartment building.', natural: 'I live in a flat in a block of flats.' },
      { full: 'The rooms for sleeping are on the upper floor.', natural: 'The bedrooms are upstairs.' },
      { full: 'We need to repair the fence and install shelves.', natural: 'We need to fix the fence and put up shelves.' },
    ],
  },
}
