/** Chapter 63 · Home emergencies. */
export const homeEmergenciesLesson = {
  id: 'home-emergencies',
  kind: 'home-emergencies',
  number: '63',
  title: '第63章に入る前に：なぜ「家の緊急トラブルで使う英語」を学ぶのでしょうか？',
  enTitle: 'Home emergencies',
  ja: '停電、水漏れ、設備の故障など、家の緊急トラブルを説明する英語を学びます。',
  cando: '家のトラブルの場所や状態を説明し、必要な修理や出張対応を依頼できる。',
  learn: {
    intro: [
      '家では、停電や水漏れ、設備の故障など、突然のトラブルが起こることがあります。',
      'そんなときは、何が起きているのかを確認し、必要であれば専門の人に助けを求める必要があります。',
      'この章では、電気や水道などのトラブルを説明する表現や、修理業者に相談するときの英語を学びます。',
    ],
    functions: [
      ['01', '起きていることを確認する'],
      ['02', '電気の状態を説明する'],
      ['03', '業者に症状を伝える'],
      ['04', '費用と対応時間を確認する'],
    ],
    power: {
      title: '電気のトラブル',
      enTitle: 'Power problems',
      intro: '停電やブレーカーの状態を確認し、電気が戻ったかを家の人と伝え合います。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "What's happening?", meaning: '何が起きているの？', context: '状況を確認する', register: 'casual' },
        { phrase: "The power has gone off. I'll check the fuse box.", meaning: '停電しちゃった。ブレーカーを見てみるよ。', context: '停電と確認作業を伝える', register: 'neutral' },
        { phrase: "A switch has flipped. Let's see if I can get it working...", meaning: 'スイッチが落ちているね。動くかどうかやってみよう……', context: 'ブレーカーを確認する', register: 'casual' },
        { phrase: 'Try turning the lights on now...', meaning: '今、電気をつけてみて……', context: '復旧を確認する', register: 'neutral' },
        { phrase: 'The power is back on!', meaning: '電気が戻ったよ！', context: '復旧を伝える', register: 'casual' },
        { phrase: 'A switch has flipped.', meaning: 'スイッチが落ちています。', context: '原因を説明する', register: 'neutral' },
        { phrase: "Let's see if I can get it working...", meaning: '動くかどうかやってみよう……', context: '復旧を試みる', register: 'casual' },
      ],
      recognition: [
        { phrase: 'go off', meaning: '電気などが切れる', note: 'The power has gone off. のように使います。' },
        { phrase: 'fuse box', meaning: 'ヒューズボックス・分電盤', note: 'ブレーカーを確認する場所です。' },
        { phrase: 'switch has flipped', meaning: 'スイッチが切り替わった・落ちた', note: 'ブレーカーが落ちたときにも使います。' },
        { phrase: 'back on', meaning: '再びついて・復旧して', note: '電気や暖房が戻った状態を表します。' },
      ],
    },
    professional: {
      title: '専門業者への依頼',
      enTitle: 'Professional help',
      intro: '水漏れや給湯器の故障を説明し、業者の到着時間と出張料を確認します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: "My dishwasher's leaking...", meaning: '食洗機が水漏れしているのですが……', context: '水漏れを伝える', register: 'neutral' },
        { phrase: 'I can be there in an hour. My callout charge is £80.', meaning: '1時間以内にそちらに行けます。基本出張料は80ポンドです。', context: '到着時間と料金を伝える', register: 'polite' },
        { phrase: 'Right, so what seems to be the problem?', meaning: 'なるほど、それでどのような問題が起きていますか？', context: '症状を詳しく尋ねる', register: 'neutral' },
        { phrase: 'The tap has been dripping for days.', meaning: '蛇口から何日も水が垂れ続けています。', context: '継続する水漏れを伝える', register: 'neutral' },
        { phrase: 'My shower keeps going cold!', meaning: 'シャワーが途中で冷たくなってしまうんです！', context: '繰り返す故障を伝える', register: 'casual' },
        { phrase: 'When was the boiler last serviced?', meaning: '最後にボイラーの点検を受けたのはいつですか？', context: '点検時期を尋ねる', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'callout charge', meaning: '基本出張料', note: '作業前に訪問だけで発生する料金です。' },
        { phrase: 'dripping for days', meaning: '何日もポタポタ垂れている', note: '現在完了進行形で継続を伝えます。' },
        { phrase: 'keeps going cold', meaning: '何度も冷たくなる', note: '繰り返す不具合への不満を表します。' },
        { phrase: 'serviced', meaning: '点検・整備を受けた', note: 'boiler や車などの定期点検に使います。' },
      ],
    },
    emergencies: {
      title: 'その他の緊急トラブル',
      enTitle: 'More problems & vocabulary',
      intro: '水回り、屋根、暖房、窓など、家のどこに問題があるかを具体的に伝えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'I have a leaking roof.', meaning: '雨漏りがしています。', context: '屋根の問題を伝える', register: 'neutral' },
        { phrase: 'My toilet is overflowing.', meaning: 'トイレの水があふれています。', context: 'トイレの問題を伝える', register: 'neutral' },
        { phrase: "There's no hot water.", meaning: 'お湯が出ません。', context: '給湯の問題を伝える', register: 'neutral' },
        { phrase: "The heating won't come on.", meaning: '暖房がつきません。', context: '暖房の問題を伝える', register: 'neutral' },
        { phrase: 'The window is broken.', meaning: '窓が割れています。', context: '窓の破損を伝える', register: 'neutral' },
        { phrase: 'The sink is blocked.', meaning: 'シンクが詰まっています。', context: '排水の問題を伝える', register: 'neutral' },
        { phrase: 'There has been a power cut.', meaning: '停電がありました。', context: '停電を名詞で伝える', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'broken window', meaning: '割れた窓', note: '家の破損箇所を短く伝えます。' },
        { phrase: 'burst pipe', meaning: '破裂した配管', note: '大きな水漏れにつながるトラブルです。' },
        { phrase: 'broken-down boiler', meaning: '故障したボイラー', note: '給湯・暖房設備の故障を表します。' },
        { phrase: 'overflowing toilet', meaning: 'あふれているトイレ', note: 'overflow の -ing 形です。' },
        { phrase: 'leaking roof', meaning: '雨漏りしている屋根', note: '屋根からの水漏れです。' },
        { phrase: 'blocked sink', meaning: '詰まったシンク', note: '排水口の詰まりを表します。' },
        { phrase: 'dripping tap', meaning: '水が垂れている蛇口', note: 'tap から水がポタポタ落ちる状態です。' },
        { phrase: 'power cut', meaning: '停電', note: 'イギリス英語でよく使う名詞です。' },
      ],
    },
    vocabulary: {
      title: '家の緊急トラブルの単語',
      enTitle: 'Vocabulary · Home emergencies',
      intro: 'トラブルの場所、状態、原因を表す言葉を、修理依頼のフレーズと一緒に覚えます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'broken window', meaning: '割れた窓', context: '窓', register: 'neutral' },
        { phrase: 'burst pipe', meaning: '破裂した配管', context: '水道', register: 'neutral' },
        { phrase: 'broken-down boiler', meaning: '故障したボイラー', context: '給湯・暖房', register: 'neutral' },
        { phrase: 'overflowing toilet', meaning: 'あふれているトイレ', context: '水回り', register: 'neutral' },
        { phrase: 'leaking roof', meaning: '雨漏りしている屋根', context: '屋根', register: 'neutral' },
        { phrase: 'blocked sink', meaning: '詰まったシンク', context: '排水', register: 'neutral' },
        { phrase: 'dripping tap', meaning: '水がポタポタ垂れている蛇口', context: '水道', register: 'neutral' },
        { phrase: 'power cut', meaning: '停電', context: '電気', register: 'regional' },
      ],
      recognition: [
        { phrase: 'power has gone off', meaning: '電気が切れた', note: '突然の停電を伝える表現です。' },
        { phrase: 'power cut', meaning: '停電', note: 'アメリカ英語の power outage にあたります。' },
        { phrase: 'callout charge', meaning: '出張料', note: '業者を呼ぶときの基本料金です。' },
        { phrase: 'keeps going', meaning: '何度も〜になる', note: '繰り返す不具合を強調します。' },
      ],
    },
    dialogues: [
      {
        id: 'power',
        label: 'Pattern A · Power problems',
        title: '停電を確認して復旧する',
        lines: [
          { speaker: 'A', en: "What's happening?", ja: '何が起きているの？' },
          { speaker: 'B', en: "The power has gone off. I'll check the fuse box.", ja: '停電しちゃった。ブレーカーを見てみるよ。' },
          { speaker: 'A', en: 'Try turning the lights on now...', ja: '今、電気をつけてみて……' },
          { speaker: 'B', en: 'The power is back on!', ja: '電気が戻ったよ！' },
        ],
      },
      {
        id: 'professional',
        label: 'Pattern B · Professional help',
        title: '水漏れの修理を依頼する',
        lines: [
          { speaker: 'A', en: "My dishwasher's leaking...", ja: '食洗機が水漏れしているのですが……' },
          { speaker: 'B', en: 'Right, so what seems to be the problem?', ja: 'なるほど、それでどのような問題が起きていますか？' },
          { speaker: 'A', en: 'The tap has been dripping for days.', ja: '蛇口から何日も水が垂れ続けています。' },
          { speaker: 'B', en: 'I can be there in an hour. My callout charge is £80.', ja: '1時間以内に伺えます。基本出張料は80ポンドです。' },
        ],
      },
      {
        id: 'emergencies',
        label: 'Pattern C · More problems',
        title: '家の別のトラブルを伝える',
        lines: [
          { speaker: 'A', en: "There's no hot water.", ja: 'お湯が出ません。' },
          { speaker: 'B', en: "The heating won't come on, either.", ja: '暖房もつきません。' },
          { speaker: 'A', en: 'When was the boiler last serviced?', ja: '最後にボイラーの点検を受けたのはいつですか？' },
          { speaker: 'B', en: 'I have a leaking roof as well.', ja: '屋根の雨漏りもあります。' },
        ],
      },
    ],
    tip: '停電は The power has gone off. と言い、名詞ではイギリス英語の power cut を使います。callout charge は業者の基本出張料です。keeps going cold のような keep + -ing は繰り返す故障、has been dripping は過去から今まで続く不具合を表します。',
  },
  practice: {
    title: '家の緊急トラブルを、英語で分かりやすく伝える',
    instructions: '日本語訳は見ずに、停電、水漏れ、給湯・暖房のトラブルを声に重ねます。',
    coreHeading: 'まずは、何が起きているかを尋ねる一文から。',
    dialogueHeading: '停電、修理依頼、設備トラブルの場面で役を切り替える。',
    dialogueDescription: '電気を確認する、水漏れの業者を呼ぶ、給湯や暖房の問題を伝える3つの場面を練習します。',
    finishTitle: '次に家のトラブルを説明するとき、場所と状態を英語でひとつ伝えてみましょう。',
    corePhrases: [
      { phrase: "What's happening?", context: '状況を確認する', rate: 0.86 },
      { phrase: "The power has gone off. I'll check the fuse box.", context: '停電と確認作業を伝える', rate: 0.76 },
      { phrase: 'A switch has flipped.', context: '原因を説明する', rate: 0.84 },
      { phrase: 'Try turning the lights on now...', context: '復旧を確認する', rate: 0.78 },
      { phrase: 'The power is back on!', context: '復旧を伝える', rate: 0.86 },
      { phrase: "My dishwasher's leaking...", context: '水漏れを伝える', rate: 0.8 },
      { phrase: 'The tap has been dripping for days.', context: '継続する水漏れを伝える', rate: 0.76 },
      { phrase: 'My shower keeps going cold!', context: '繰り返す故障を伝える', rate: 0.78 },
      { phrase: 'I can be there in an hour. My callout charge is £80.', context: '時間と料金を伝える', rate: 0.74 },
      { phrase: "There's no hot water.", context: '給湯の問題を伝える', rate: 0.84 },
      { phrase: "The heating won't come on.", context: '暖房の問題を伝える', rate: 0.8 },
      { phrase: 'When was the boiler last serviced?', context: '点検時期を尋ねる', rate: 0.76 },
    ],
    dialogues: [
      { title: 'Power problems', lines: ["What's happening?", "The power has gone off. I'll check the fuse box.", 'Try turning the lights on now...', 'The power is back on!'] },
      { title: 'Professional help', lines: ["My dishwasher's leaking...", 'Right, so what seems to be the problem?', 'The tap has been dripping for days.', 'I can be there in an hour. My callout charge is £80.'] },
      { title: 'More problems', lines: ["There's no hot water.", "The heating won't come on, either.", 'When was the boiler last serviced?', 'I have a leaking roof as well.'] },
    ],
    natural: [
      { full: 'There is a problem with the electricity supply.', natural: 'The power has gone off.' },
      { full: 'The tap has continued to release drops of water for several days.', natural: 'The tap has been dripping for days.' },
      { full: 'The shower repeatedly becomes cold.', natural: 'My shower keeps going cold!' },
    ],
  },
}
