/** Chapter 64 · Home entertainment. */
export const homeEntertainmentLesson = {
  id: 'home-entertainment',
  kind: 'home-entertainment',
  number: '64',
  title: '第64章に入る前に：なぜ「ホームエンターテインメントで使う英語」を学ぶのでしょうか？',
  enTitle: 'Home entertainment',
  ja: 'テレビや動画、ゲームについて話し、機器を操作したりトラブルに対応したりする英語を学びます。',
  cando: '家で見るものを相談し、ゲーム中の反応や機器の操作・不具合を自然に伝えられる。',
  learn: {
    intro: [
      '家でテレビや動画を見たり、ゲームをしたりするときも、私たちは自然に人とやり取りをしています。',
      '何を見るか相談したり、感想を言ったり、音量や字幕など機器の操作をお願いしたりする場面があります。',
      'この章では、テレビや動画、ゲームについて話す表現や、機器の操作・トラブルに関する英語を学びます。',
    ],
    functions: [
      ['01', '見るものを相談する'],
      ['02', '番組の感想を伝える'],
      ['03', 'ゲーム中に反応する'],
      ['04', '機器の操作を頼む'],
    ],
    watching: {
      title: 'テレビ・動画を見る',
      enTitle: 'Watching TV',
      intro: '番組を選び、次のエピソードや別のスポーツ番組を提案しながら見るものを決めます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'What shall we watch tonight?', meaning: '今夜は何を見ようか？', context: '見るものを相談する', register: 'casual' },
        { phrase: 'We could try this new detective series.', meaning: 'この新しい刑事ドラマシリーズを見てみるのもいいかもね。', context: '番組を提案する', register: 'casual' },
        { phrase: 'That was great - shall we check out the next episode?', meaning: 'すごく面白かったね。次のエピソードも見てみない？', context: '続きを提案する', register: 'casual' },
        { phrase: "It's not streaming yet. How about some sport?", meaning: 'まだ配信されていないよ。スポーツ番組はどう？', context: '代わりの番組を提案する', register: 'casual' },
        { phrase: "Have you got the remote? I can't hear anything.", meaning: 'リモコン持ってる？何も聞こえないよ。', context: '音量を頼む', register: 'casual' },
        { phrase: "Yes, here it is. I'll turn it up.", meaning: 'うん、ここにあるよ。音量を上げるね。', context: '操作を引き受ける', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'detective series', meaning: '刑事ドラマシリーズ', note: 'series は連続番組・シリーズ作品です。' },
        { phrase: 'check out', meaning: '見てみる・確認する', note: '次のエピソードを見る提案に使います。' },
        { phrase: 'streaming', meaning: '配信・ストリーミング', note: '番組がオンラインで見られる状態です。' },
        { phrase: 'turn it up', meaning: '音量を上げる', note: 'remote と一緒によく使います。' },
      ],
    },
    gaming: {
      title: 'ゲームを楽しむ',
      enTitle: 'Gaming',
      intro: '勝負中の意気込みや悔しさ、画面を見る時間のルール、次のステージへの誘いを練習します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: "I'm so gonna win this!", meaning: '絶対勝つぞ！', context: '勝負への意気込み', register: 'casual' },
        { phrase: 'Damn! You got me again!', meaning: 'ちくしょう！またやられた！', context: '負けたときの反応', register: 'casual' },
        { phrase: "Your screen time's up now.", meaning: '画面を見る時間はもうおしまいだよ。', context: '時間のルールを伝える', register: 'casual' },
        { phrase: 'But I really want to finish this game! Just five more minutes...', meaning: 'でも、どうしてもこのゲームを終わらせたいんだ！あと5分だけ……', context: 'もう少し続けたいと頼む', register: 'casual' },
        { phrase: 'Shall we play the next level?', meaning: '次のレベルをやろうか？', context: '次のステージに誘う', register: 'casual' },
        { phrase: "I'm just grabbing a bite to eat - be right back!", meaning: 'ちょっと軽いものを食べてくるよ。すぐ戻るね！', context: '一時中断を伝える', register: 'casual' },
      ],
      recognition: [
        { phrase: 'so gonna', meaning: '絶対に〜するぞ', note: 'gonna に so を加えたフランクな強調です。' },
        { phrase: 'get me', meaning: '私を倒す・やっつける', note: 'ゲームで相手に負けたときの表現です。' },
        { phrase: 'screen time', meaning: '画面を見る時間', note: 'ゲーム、テレビ、スマホなどを含みます。' },
        { phrase: 'grab a bite to eat', meaning: '軽く食べる', note: '短い食事のためにその場を離れるときに使います。' },
      ],
    },
    controls: {
      title: '機器の操作とトラブル',
      enTitle: 'More phrases',
      intro: '字幕、コントローラー、タブレット、ゲーム機について、お願いや確認をします。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Can you turn on the subtitles?', meaning: '字幕をつけてくれる？', context: '字幕を頼む', register: 'casual' },
        { phrase: 'Have you got another controller?', meaning: 'コントローラーはもう1つある？', context: '道具を尋ねる', register: 'casual' },
        { phrase: 'My tablet has frozen!', meaning: 'タブレットがフリーズしちゃった！', context: '機器の不具合を伝える', register: 'casual' },
        { phrase: 'Is the console plugged in?', meaning: 'ゲーム機はコンセントにつながっている？', context: '接続を確認する', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'turn on', meaning: '電源を入れる', note: 'subtitles などの設定にも使います。' },
        { phrase: 'frozen', meaning: 'フリーズした・固まった', note: '画面が操作できない状態です。' },
        { phrase: 'plugged in', meaning: 'コンセントにつながっている', note: 'console や機器の電源接続を確認します。' },
        { phrase: 'controller', meaning: 'ゲームのコントローラー', note: 'ゲーム機を操作する道具です。' },
      ],
    },
    vocabulary: {
      title: 'ホームエンターテインメントの語彙',
      enTitle: 'Vocabulary · Home entertainment',
      intro: 'テレビ、音声、ゲーム、スマート機器を表す基本語彙を会話と一緒に覚えます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'smart TV', meaning: 'スマートテレビ', context: 'テレビ', register: 'neutral' },
        { phrase: 'remote', meaning: 'リモコン', context: 'テレビ操作', register: 'neutral' },
        { phrase: 'subtitles', meaning: '字幕', context: '動画設定', register: 'neutral' },
        { phrase: 'headphones', meaning: 'ヘッドホン', context: '音声', register: 'neutral' },
        { phrase: 'console', meaning: 'ゲーム機', context: 'ゲーム', register: 'neutral' },
        { phrase: 'smart speakers', meaning: 'スマートスピーカー', context: '音声機器', register: 'neutral' },
        { phrase: 'controller', meaning: 'コントローラー', context: 'ゲーム操作', register: 'neutral' },
        { phrase: 'tablet', meaning: 'タブレット', context: '携帯機器', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'streaming service', meaning: '配信サービス', note: '動画をオンラインで見るサービスです。' },
        { phrase: 'next episode', meaning: '次のエピソード', note: 'シリーズ作品の続きを指します。' },
        { phrase: 'level', meaning: 'レベル・ステージ', note: 'ゲームの進行単位です。' },
        { phrase: 'screen time', meaning: '画面を見る時間', note: '家族でルールを決めるときにも使います。' },
      ],
    },
    dialogues: [
      {
        id: 'watching',
        label: 'Pattern A · Watching TV',
        title: '見る番組と音量を決める',
        lines: [
          { speaker: 'A', en: 'What shall we watch tonight?', ja: '今夜は何を見ようか？' },
          { speaker: 'B', en: 'We could try this new detective series.', ja: 'この新しい刑事ドラマシリーズを見てみるのもいいかもね。' },
          { speaker: 'A', en: "Have you got the remote? I can't hear anything.", ja: 'リモコン持ってる？何も聞こえないよ。' },
          { speaker: 'B', en: "Yes, here it is. I'll turn it up.", ja: 'うん、ここにあるよ。音量を上げるね。' },
        ],
      },
      {
        id: 'gaming',
        label: 'Pattern B · Gaming',
        title: 'ゲームの勝負と休憩を話す',
        lines: [
          { speaker: 'A', en: "I'm so gonna win this!", ja: '絶対勝つぞ！' },
          { speaker: 'B', en: 'Damn! You got me again!', ja: 'ちくしょう！またやられた！' },
          { speaker: 'A', en: "Your screen time's up now.", ja: '画面を見る時間はもうおしまいだよ。' },
          { speaker: 'B', en: 'But I really want to finish this game! Just five more minutes...', ja: 'でも、どうしてもこのゲームを終わらせたいんだ！あと5分だけ……' },
        ],
      },
      {
        id: 'controls',
        label: 'Pattern C · Controls & problems',
        title: '機器の操作とトラブルを伝える',
        lines: [
          { speaker: 'A', en: 'Can you turn on the subtitles?', ja: '字幕をつけてくれる？' },
          { speaker: 'B', en: 'Have you got another controller?', ja: 'コントローラーはもう1つある？' },
          { speaker: 'A', en: 'My tablet has frozen!', ja: 'タブレットがフリーズしちゃった！' },
          { speaker: 'B', en: 'Is the console plugged in?', ja: 'ゲーム機はコンセントにつながっている？' },
        ],
      },
    ],
    tip: 'so gonna はゲームなどで「絶対に〜するぞ」と意気込むカジュアルな表現です。機器が固まったら frozen、軽く食べるなら grab a bite to eat、画面を見る時間は screen time と言います。',
  },
  practice: {
    title: '家のエンタメ時間を、英語で自然に楽しむ',
    instructions: '日本語訳は見ずに、番組選び、ゲームの反応、機器の操作を声に重ねます。',
    coreHeading: 'まずは、何を見るかを相談する一文から。',
    dialogueHeading: 'テレビ、ゲーム、機器トラブルの場面で役を切り替える。',
    dialogueDescription: '番組と音量を決める、ゲームの勝負と休憩を話す、字幕や機器を確認する3つの場面を練習します。',
    finishTitle: '次に家で見るものを相談するとき、今日のフレーズをひとつ使ってみましょう。',
    corePhrases: [
      { phrase: 'What shall we watch tonight?', context: '見るものを相談する', rate: 0.82 },
      { phrase: 'We could try this new detective series.', context: '番組を提案する', rate: 0.78 },
      { phrase: 'That was great - shall we check out the next episode?', context: '続きを提案する', rate: 0.74 },
      { phrase: "Have you got the remote? I can't hear anything.", context: '音量を頼む', rate: 0.76 },
      { phrase: "I'm so gonna win this!", context: '勝負への意気込み', rate: 0.82 },
      { phrase: 'Damn! You got me again!', context: '負けたときの反応', rate: 0.8 },
      { phrase: "Your screen time's up now.", context: '時間のルールを伝える', rate: 0.8 },
      { phrase: 'Just five more minutes...', context: 'もう少し続けたいと頼む', rate: 0.82 },
      { phrase: "I'm just grabbing a bite to eat - be right back!", context: '一時中断を伝える', rate: 0.76 },
      { phrase: 'Can you turn on the subtitles?', context: '字幕を頼む', rate: 0.8 },
      { phrase: 'My tablet has frozen!', context: '機器の不具合を伝える', rate: 0.82 },
      { phrase: 'Is the console plugged in?', context: '接続を確認する', rate: 0.78 },
    ],
    dialogues: [
      { title: 'Watching TV', lines: ['What shall we watch tonight?', 'We could try this new detective series.', "Have you got the remote? I can't hear anything.", "Yes, here it is. I'll turn it up."] },
      { title: 'Gaming', lines: ["I'm so gonna win this!", 'Damn! You got me again!', "Your screen time's up now.", 'But I really want to finish this game! Just five more minutes...'] },
      { title: 'Controls & problems', lines: ['Can you turn on the subtitles?', 'Have you got another controller?', 'My tablet has frozen!', 'Is the console plugged in?'] },
    ],
    natural: [
      { full: 'Which television programme should we watch this evening?', natural: 'What shall we watch tonight?' },
      { full: 'I will definitely win this game.', natural: "I'm so gonna win this!" },
      { full: 'Please turn on the text displayed at the bottom of the screen.', natural: 'Can you turn on the subtitles?' },
    ],
  },
}
