/** Chapter 74 · Staying in a hotel. */
export const hotelLesson = {
  id: 'staying-hotel',
  kind: 'staying-hotel',
  number: '74',
  title: '第74章に入る前に：なぜ「ホテルで使う英語」を学ぶのでしょうか？',
  enTitle: 'Staying in a hotel',
  ja: 'チェックインからチェックアウトまで、ホテルでの滞在とリクエストに関する表現を学びます。',
  cando: 'ホテルで予約を確認し、必要なサービスを頼み、設備の不具合や滞在の感想を伝えられる。',
  learn: {
    intro: [
      'ホテルでは、チェックインからチェックアウトまで、確認したり、お願いしたり、問題を伝えたりする場面がたくさんあります。',
      '自分が必要としていることや困っていることを、相手に分かりやすく伝えることが大切です。',
      'この章では、チェックイン、滞在中のリクエストやトラブル、朝食、そしてチェックアウトで使う表現を学びます。',
    ],
    functions: [
      ['01', '予約と部屋の情報を確認する'],
      ['02', 'アメニティやサービスを頼む'],
      ['03', '設備のトラブルを伝える'],
      ['04', '朝食とチェックアウトを進める'],
    ],
    checkin: {
      title: '到着とチェックイン',
      enTitle: 'Arrival and check-in',
      intro: '予約名、宿泊日数、必要書類、部屋や朝食の時間をフロントで確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Welcome to Paradise Hotel. Do you have a reservation?', meaning: 'パラダイスホテルへようこそ。ご予約はございますか？', context: '予約を確認する', register: 'polite' },
        { phrase: 'Yes, we booked online for two nights, under the name Patel.', meaning: 'はい、ネットで2泊予約しています。パテルという名前です。', context: '予約名と日数を伝える', register: 'polite' },
        { phrase: 'Could you fill in this registration form?', meaning: 'こちらの宿泊カードにご記入いただけますか？', context: '書類への記入を頼む', register: 'polite' },
        { phrase: 'Of course. Could I borrow a pen?', meaning: 'もちろん。ペンをお借りできますか？', context: '筆記具を借りる', register: 'polite' },
        { phrase: 'Can I see your passport, please?', meaning: 'パスポートを拝見できますか？', context: '身分証を提示してもらう', register: 'polite' },
        { phrase: 'Here you go.', meaning: 'はい、どうぞ。', context: '物を渡す', register: 'friendly' },
        { phrase: 'Is the room ready?', meaning: '部屋の準備はできていますか？', context: '入室できるか尋ねる', register: 'polite' },
        { phrase: "Yes, here's the key card.", meaning: 'はい、こちらがカードキーです。', context: '鍵を渡す', register: 'friendly' },
        { phrase: 'What time is check-out?', meaning: 'チェックアウトは何時ですか？', context: '退室時刻を尋ねる', register: 'polite' },
        { phrase: "It's at 11am.", meaning: '午前11時です。', context: '時刻を伝える', register: 'neutral' },
        { phrase: 'I paid in advance on the booking site.', meaning: '予約サイトで事前に支払いを済ませています。', context: '事前決済を伝える', register: 'polite' },
        { phrase: 'Do you have a double room available?', meaning: 'ダブルの部屋は空いていますか？', context: '部屋の空きを尋ねる', register: 'polite' },
        { phrase: "We'd like a room with twin beds, please.", meaning: 'ツインの部屋をお願いします。', context: '部屋のタイプを希望する', register: 'polite' },
        { phrase: 'The restaurant serves dinner until 10pm.', meaning: 'レストランは夜10時まで夕食を提供しています。', context: '館内施設の時間を案内する', register: 'neutral' },
        { phrase: 'The swimming pool opens again at 6am.', meaning: 'プールは朝6時に再びオープンします。', context: '施設の時間を案内する', register: 'neutral' },
        { phrase: 'Your room is on the second floor.', meaning: 'お部屋は2階（イギリスでの3階）にあります。', context: '部屋の場所を案内する', register: 'neutral' },
        { phrase: 'Breakfast is from 7.30am to 10am.', meaning: '朝食は午前7時半から10時までです。', context: '朝食時間を案内する', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'under the name', meaning: '〜の名前で', note: '予約名を伝えるときに使います。' },
        { phrase: 'registration form', meaning: '宿泊カード・登録用紙', note: 'チェックイン時に記入する書類です。' },
        { phrase: 'key card', meaning: 'カードキー', note: '部屋の鍵になるカードです。' },
        { phrase: 'twin beds', meaning: 'ツインベッド', note: 'ベッドが2台ある部屋です。' },
      ],
    },
    requests: {
      title: 'リクエストとサービスを頼む',
      enTitle: 'Asking for things',
      intro: 'タオル、アメニティ、ルームサービス、枕、モーニングコールなどを丁寧に頼みます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Could I have some fresh towels, please?', meaning: '新しいタオルをいくつかいただけますか？', context: 'タオルを頼む', register: 'polite' },
        { phrase: "Yes, I'll have some sent up right away.", meaning: 'はい、すぐにお届けさせます。', context: '部屋へ届けると答える', register: 'polite' },
        { phrase: "I'd like a hairdryer brought to my room.", meaning: 'ドライヤーを部屋に持ってきてほしいのですが。', context: '備品を頼む', register: 'polite' },
        { phrase: "I'd like a club sandwich sent up, please.", meaning: 'クラブサンドイッチを部屋に届けてほしいのですが。', context: 'ルームサービスを頼む', register: 'polite' },
        { phrase: "I'd like two extra pillows.", meaning: '枕を余分に2つお願いします。', context: '枕を頼む', register: 'polite' },
        { phrase: "I'd like a 7am wake-up call.", meaning: '朝7時にモーニングコールをお願いします。', context: 'モーニングコールを頼む', register: 'polite' },
      ],
      recognition: [
        { phrase: 'fresh towels', meaning: '新しいタオル', note: '交換用の清潔なタオルです。' },
        { phrase: 'sent up', meaning: '上の階の部屋へ届ける', note: 'ルームサービスでよく使います。' },
        { phrase: 'brought to my room', meaning: '私の部屋に持ってくる', note: '備品を部屋まで運んでもらう表現です。' },
        { phrase: 'wake-up call', meaning: 'モーニングコール', note: '指定時刻に電話で起こしてもらいます。' },
      ],
    },
    problems: {
      title: 'トラブルを説明する',
      enTitle: 'Describing problems',
      intro: '設備が動かない、壊れている、暑すぎるなど、部屋の状態をフロントに具体的に伝えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "The TV won't switch on.", meaning: 'テレビの電源が入りません。', context: '機械が作動しない', register: 'polite' },
        { phrase: 'Okay, let me take a look.', meaning: 'わかりました、確認しに伺います。', context: '確認すると答える', register: 'friendly' },
        { phrase: 'The Wi-Fi password is wrong.', meaning: 'Wi-Fiのパスワードが違っています。', context: '接続情報の問題を伝える', register: 'polite' },
        { phrase: 'The lamp is broken.', meaning: 'ランプが壊れています。', context: '物理的な故障を伝える', register: 'polite' },
        { phrase: 'The room is too hot.', meaning: '部屋が暑すぎます。', context: '室温の問題を伝える', register: 'polite' },
        { phrase: "My window doesn't close properly.", meaning: '窓がしっかりと閉まりません。', context: '設備の不具合を伝える', register: 'polite' },
        { phrase: 'The shower is leaking.', meaning: 'シャワーから水が漏れています。', context: '水漏れを伝える', register: 'polite' },
        { phrase: "My key card isn't working.", meaning: 'カードキーが使えません。', context: '鍵の不具合を伝える', register: 'polite' },
      ],
      recognition: [
        { phrase: "won't switch on", meaning: 'どうしても電源が入らない', note: '機械が作動しないときの自然な表現です。' },
        { phrase: 'broken', meaning: '壊れている', note: '物理的な破損や故障を表します。' },
        { phrase: 'doesn’t close properly', meaning: 'きちんと閉まらない', note: '設備の動作が不完全だと伝えます。' },
        { phrase: 'leaking', meaning: '水漏れしている', note: 'シャワーや水道などに使います。' },
      ],
    },
    breakfast: {
      title: '朝食時の会話',
      enTitle: 'At breakfast',
      intro: '朝食会場で時間、席、ビュッフェ、飲み物について確認します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Am I too late for breakfast?', meaning: '朝食の時間に遅すぎましたか？', context: '朝食に間に合うか尋ねる', register: 'polite' },
        { phrase: "No, you're just in time.", meaning: 'いいえ、ちょうど間に合いましたよ。', context: '時間を案内する', register: 'friendly' },
        { phrase: 'Can I take your room number?', meaning: 'お部屋番号を伺ってもよろしいですか？', context: '宿泊情報を確認する', register: 'polite' },
        { phrase: 'Can we sit anywhere we like?', meaning: '好きな席に座ってもいいですか？', context: '席を尋ねる', register: 'polite' },
        { phrase: 'Yes, and do help yourselves at the buffet.', meaning: 'はい、ビュッフェをどうぞご自由にお取りください。', context: '自由に取ってよいと案内する', register: 'friendly' },
        { phrase: 'Could I have some more coffee?', meaning: 'コーヒーをもう少しいただけますか？', context: '飲み物を頼む', register: 'polite' },
        { phrase: "Sure, I'll bring it to your table.", meaning: 'かしこまりました、テーブルまでお持ちします。', context: '席へ届けると答える', register: 'polite' },
      ],
      recognition: [
        { phrase: 'just in time', meaning: 'ちょうど間に合って', note: '締め切りや終了時刻の直前に間に合ったときに使います。' },
        { phrase: 'help yourselves', meaning: 'ご自由にお取りください', note: 'ビュッフェなどで相手に勧める表現です。' },
        { phrase: 'room number', meaning: '部屋番号', note: '朝食会場の利用確認で尋ねられます。' },
      ],
    },
    checkout: {
      title: 'チェックアウト',
      enTitle: 'Checking out',
      intro: '滞在の感想、請求書、支払い、荷物やタクシーの手配を確認して退館します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Did you enjoy your stay?', meaning: 'ご滞在は楽しめましたか？', context: '滞在の感想を尋ねる', register: 'polite' },
        { phrase: 'It was lovely, thanks. The room was a bit noisy.', meaning: 'とても素敵でした。部屋は少しうるさかったですけれど。', context: '感想と穏やかな不満を伝える', register: 'polite' },
        { phrase: "Here's your bill if you'd like to check it.", meaning: 'こちらが請求書ですので、ご確認ください。', context: '請求書を渡す', register: 'polite' },
        { phrase: 'That all looks fine.', meaning: 'すべて問題ありません。', context: '請求内容を確認する', register: 'neutral' },
        { phrase: 'Are you paying by card?', meaning: 'お支払いはカードですか？', context: '支払い方法を尋ねる', register: 'polite' },
        { phrase: 'Dinner was delicious.', meaning: '夕食はとても美味しかったです。', context: 'サービスを褒める', register: 'friendly' },
        { phrase: 'Our breakfast was a bit cold.', meaning: '朝食が少し冷めていました。', context: '穏やかに不満を伝える', register: 'polite' },
        { phrase: 'The bed was a little bit hard.', meaning: 'ベッドが少し硬かったです。', context: '穏やかに感想を伝える', register: 'polite' },
        { phrase: 'Is it possible to stay an extra night?', meaning: 'もう1泊延泊することは可能ですか？', context: '延泊を尋ねる', register: 'polite' },
        { phrase: 'Can I leave my luggage here?', meaning: 'ここに荷物を預かってもらえますか？', context: '荷物を預ける', register: 'polite' },
        { phrase: 'Could you call me a taxi, please?', meaning: 'タクシーを呼んでいただけますか？', context: '移動を手配する', register: 'polite' },
      ],
      recognition: [
        { phrase: 'a bit / a little bit', meaning: '少し・ちょっと', note: '不満をやわらかく伝えます。' },
        { phrase: 'bill', meaning: '請求書', note: 'チェックアウト時に内容を確認します。' },
        { phrase: 'stay an extra night', meaning: 'もう1泊滞在する', note: '延泊の希望を伝える表現です。' },
        { phrase: 'leave my luggage', meaning: '荷物を預ける', note: '退館後に荷物を保管してもらうときに使います。' },
      ],
    },
    dialogues: [
      {
        id: 'checkin',
        label: 'Pattern A · Arrival and check-in',
        title: '予約を確認して部屋に入る',
        lines: [
          { speaker: 'A', en: 'Welcome to Paradise Hotel. Do you have a reservation?', ja: 'パラダイスホテルへようこそ。ご予約はございますか？' },
          { speaker: 'B', en: 'Yes, we booked online for two nights, under the name Patel.', ja: 'はい、ネットで2泊予約しています。パテルという名前です。' },
          { speaker: 'A', en: 'Could you fill in this registration form?', ja: 'こちらの宿泊カードにご記入いただけますか？' },
          { speaker: 'B', en: "Of course. Could I borrow a pen?", ja: 'もちろん。ペンをお借りできますか？' },
        ],
      },
      {
        id: 'requests-problems',
        label: 'Pattern B · Requests and problems',
        title: '必要なものを頼み、トラブルを伝える',
        lines: [
          { speaker: 'A', en: 'Could I have some fresh towels, please?', ja: '新しいタオルをいくつかいただけますか？' },
          { speaker: 'B', en: "I'll have some sent up right away.", ja: 'すぐにお届けさせます。' },
          { speaker: 'A', en: "The TV won't switch on.", ja: 'テレビの電源が入りません。' },
          { speaker: 'B', en: 'Okay, let me take a look.', ja: 'わかりました、確認しに伺います。' },
        ],
      },
      {
        id: 'breakfast-checkout',
        label: 'Pattern C · Breakfast and checkout',
        title: '朝食とチェックアウトを進める',
        lines: [
          { speaker: 'A', en: 'Can we sit anywhere we like?', ja: '好きな席に座ってもいいですか？' },
          { speaker: 'B', en: 'Yes, and do help yourselves at the buffet.', ja: 'はい、ビュッフェをどうぞご自由にお取りください。' },
          { speaker: 'A', en: 'It was lovely, thanks. The room was a bit noisy.', ja: 'とても素敵でした。部屋は少しうるさかったですけれど。' },
          { speaker: 'B', en: "Here's your bill if you'd like to check it.", ja: 'こちらが請求書ですので、ご確認ください。' },
        ],
      },
    ],
    tip: 'a bit / a little bit を使うと、不満をやわらかく伝えられます。部屋へ届けるときは sent up や brought to my room、機械が作動しないときは won’t + 動詞、物理的に壊れているときは broken を使い分けます。',
  },
  practice: {
    title: 'ホテルで必要なことを、英語で伝える',
    instructions: '日本語訳は見ずに、チェックイン、リクエスト、トラブル、朝食、チェックアウトの表現を声に重ねます。',
    coreHeading: 'まずは、ホテルでよく使う一文から。',
    dialogueHeading: '到着、滞在中、退館の場面で役を切り替える。',
    dialogueDescription: 'チェックインする、サービスとトラブルを伝える、朝食とチェックアウトを進める3つの場面を練習します。',
    finishTitle: '次にホテルへ泊まるとき、必要なリクエストを英語でひとつ伝えてみましょう。',
    corePhrases: [
      { phrase: 'Do you have a reservation?', context: '予約を確認する', rate: 0.82 },
      { phrase: 'We booked online for two nights, under the name Patel.', context: '予約名と日数を伝える', rate: 0.72 },
      { phrase: 'Could you fill in this registration form?', context: '書類への記入を頼む', rate: 0.72 },
      { phrase: 'What time is check-out?', context: '退室時刻を尋ねる', rate: 0.84 },
      { phrase: 'Could I have some fresh towels, please?', context: 'タオルを頼む', rate: 0.76 },
      { phrase: "I'd like a 7am wake-up call.", context: 'モーニングコールを頼む', rate: 0.78 },
      { phrase: "The TV won't switch on.", context: '機械の不具合を伝える', rate: 0.82 },
      { phrase: 'My key card isn\'t working.', context: 'カードキーの不具合を伝える', rate: 0.82 },
      { phrase: 'Am I too late for breakfast?', context: '朝食に間に合うか尋ねる', rate: 0.78 },
      { phrase: 'Could I have some more coffee?', context: '飲み物を頼む', rate: 0.82 },
      { phrase: "Here's your bill if you'd like to check it.", context: '請求書を確認する', rate: 0.7 },
      { phrase: 'Could you call me a taxi, please?', context: 'タクシーを頼む', rate: 0.78 },
    ],
    dialogues: [
      { title: 'Arrival and check-in', lines: ['Welcome to Paradise Hotel. Do you have a reservation?', 'Yes, we booked online for two nights, under the name Patel.', 'Could you fill in this registration form?', 'Of course. Could I borrow a pen?'] },
      { title: 'Requests and problems', lines: ['Could I have some fresh towels, please?', "I'll have some sent up right away.", "The TV won't switch on.", 'Okay, let me take a look.'] },
      { title: 'Breakfast and checkout', lines: ['Can we sit anywhere we like?', 'Yes, and do help yourselves at the buffet.', 'It was lovely, thanks. The room was a bit noisy.', "Here's your bill if you'd like to check it."] },
    ],
    natural: [
      { full: 'Could you please arrange for some clean towels to be delivered to my room?', natural: 'Could I have some fresh towels, please?' },
      { full: 'The television does not turn on despite my trying to use it.', natural: "The TV won't switch on." },
      { full: 'Would it be possible for you to arrange a taxi for me?', natural: 'Could you call me a taxi, please?' },
    ],
  },
}
