/** Chapter 50 · Job interviews. */
export const jobInterviewsLesson = {
  id: 'job-interviews',
  kind: 'job-interviews',
  number: '50',
  title: '第50章に入る前に：なぜ「面接で使う英語」を学ぶのでしょうか？',
  enTitle: 'Job interviews',
  ja: '面接で志望動機、経験、強み、貢献できることを伝える英語を学びます。',
  cando: '面接で自分の経験や強み、会社への貢献を具体的に説明できる。',
  learn: {
    intro: [
      '就職面接は、単に質問に正しく答えるためのテストではありません。仕事をする人として自分がどのような人物なのか、何ができるのかを伝える機会です。',
      '面接官も、その人が仕事の内容やチーム、会社に合っているかを確認しています。そのため、英語力だけでなく、経験、能力、意欲を具体的に伝えることが大切です。',
      'この章では、面接でよく聞かれる質問への答え方、自分の強みや経験の伝え方、そして会社にどのように貢献できるかを説明する表現を学びます。',
    ],
    functions: [
      ['01', '志望動機を答える'],
      ['02', '会社への貢献を伝える'],
      ['03', '強みと経験を説明する'],
      ['04', '将来の希望を話す'],
    ],
    motivation: {
      title: '面接官の質問と効果的な回答',
      enTitle: "Interviewers' questions",
      intro: '志望動機、ポジションとの適性、会社に提供できることを自信を持って答えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Why are you right for this position?', meaning: 'なぜあなたはこの職種にふさわしいのですか？', context: '適性を尋ねる', register: 'polite' },
        { phrase: "I've got the qualifications and experience you're looking for.", meaning: '御社が求める資格と経験があります。', context: '資格と経験を答える', register: 'polite' },
        { phrase: 'What can you bring to our company?', meaning: '当社にどのように貢献できますか？', context: '貢献を尋ねる', register: 'polite' },
        { phrase: 'Enthusiasm, energy, and lots of ideas.', meaning: '熱意、活力、そしてたくさんのアイデアです。', context: '貢献できることを答える', register: 'neutral' },
        { phrase: 'Why did you apply for this job?', meaning: 'なぜこの仕事に応募したのですか？', context: '志望動機を尋ねる', register: 'polite' },
        { phrase: "I'm really keen to use my planning skills.", meaning: '企画スキルをぜひ活かしたいからです。', context: '意欲を伝える', register: 'polite' },
      ],
      recognition: [
        { phrase: 'be right for a position', meaning: '職種にふさわしい', note: '経験や性格が仕事に合っていることを表します。' },
        { phrase: 'bring to our company', meaning: '会社にもたらす・貢献する', note: '能力、経験、アイデアなどを伝える表現です。' },
        { phrase: 'be keen to', meaning: 'ぜひ〜したい', note: '強い意欲を前向きに伝えます。' },
      ],
    },
    strengths: {
      title: '自己アピールをする',
      enTitle: 'Talking about yourself',
      intro: '自分の長所や働き方を、短く具体的な英語で説明します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Tell me about yourself.', meaning: 'あなた自身について教えてください。', context: '自己紹介を促す', register: 'polite' },
        { phrase: "I'm reliable and organized.", meaning: '私は信頼でき、計画的です。', context: '長所を伝える', register: 'neutral' },
        { phrase: 'I work well in a team.', meaning: 'チームでうまく仕事ができます。', context: '協調性を伝える', register: 'neutral' },
        { phrase: "I'm good with customers.", meaning: '顧客対応が得意です。', context: '対人スキルを伝える', register: 'neutral' },
        { phrase: "I'm used to working under pressure.", meaning: 'プレッシャーの下で働くことに慣れています。', context: '対応力を伝える', register: 'neutral' },
        { phrase: 'I can adapt to new situations.', meaning: '新しい状況に適応できます。', context: '適応力を伝える', register: 'neutral' },
        { phrase: "I'm a quick learner.", meaning: '物覚えが早いです。', context: '学習の速さを伝える', register: 'neutral' },
        { phrase: "I'm self-motivated.", meaning: '自発的に行動できます。', context: '主体性を伝える', register: 'neutral' },
        { phrase: 'I have an excellent track record.', meaning: '素晴らしい実績があります。', context: '実績を伝える', register: 'polite' },
        { phrase: 'I enjoy solving problems.', meaning: '問題を解決するのが好きです。', context: '仕事への姿勢を伝える', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'reliable', meaning: '信頼できる', note: '任せた仕事を責任を持って行う人を表します。' },
        { phrase: 'organized', meaning: '計画的な・几帳面な', note: '仕事や時間を整理して進められることです。' },
        { phrase: 'self-motivated', meaning: '自発的な', note: '指示を待たず、自分から動けることです。' },
        { phrase: 'track record', meaning: '実績', note: 'これまでの成功や成果の記録を指します。' },
      ],
    },
    moreQuestions: {
      title: '面接でよく聞かれるその他の質問',
      enTitle: 'More questions you may hear',
      intro: '経験、強み、仕事以外の関心、将来の目標、給与、開始時期について準備します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'What experience do you have in...?', meaning: '〜についてどのような経験がありますか？', context: '専門経験を尋ねる', register: 'polite' },
        { phrase: 'What are your strengths?', meaning: 'あなたの強みは何ですか？', context: '強みを尋ねる', register: 'polite' },
        { phrase: 'What do you enjoy doing outside work?', meaning: '仕事以外では何をするのが好きですか？', context: '仕事外の関心を尋ねる', register: 'polite' },
        { phrase: 'What are your goals for the future?', meaning: '将来の目標は何ですか？', context: '将来の目標を尋ねる', register: 'polite' },
        { phrase: 'Why do you want to leave your current job?', meaning: 'なぜ現在の仕事を辞めたいのですか？', context: '転職理由を尋ねる', register: 'polite' },
        { phrase: 'What salary are you expecting?', meaning: 'どのくらいの給与を希望していますか？', context: '希望給与を尋ねる', register: 'polite' },
        { phrase: "What's the notice period in your current job?", meaning: '現在の仕事の退職予告期間はどのくらいですか？', context: '入社可能時期を確認する', register: 'polite' },
        { phrase: 'How soon could you start?', meaning: 'いつから働き始められますか？', context: '開始時期を尋ねる', register: 'polite' },
      ],
      recognition: [
        { phrase: 'notice period', meaning: '退職予告期間', note: '退職を申し出てから実際に辞めるまでの期間です。' },
        { phrase: 'salary expectations', meaning: '希望給与', note: 'What salary are you expecting? のように尋ねます。' },
        { phrase: 'start date', meaning: '勤務開始日', note: 'How soon could you start? と関連する表現です。' },
      ],
    },
    vocabulary: {
      title: '面接のボキャブラリー',
      enTitle: 'Vocabulary · Job interviews',
      intro: '面接官の質問と自己アピールでよく使う言葉を整理します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'position', meaning: '職種・ポジション', context: '応募する仕事', register: 'neutral' },
        { phrase: 'qualifications', meaning: '資格・能力', context: '応募条件', register: 'neutral' },
        { phrase: 'experience', meaning: '経験', context: 'これまでの仕事', register: 'neutral' },
        { phrase: 'enthusiasm', meaning: '熱意', context: '仕事への意欲', register: 'neutral' },
        { phrase: 'planning skills', meaning: '企画・計画のスキル', context: '活かせる能力', register: 'neutral' },
        { phrase: 'reliable', meaning: '信頼できる', context: '自分の強み', register: 'neutral' },
        { phrase: 'organized', meaning: '計画的な・几帳面な', context: '自分の強み', register: 'neutral' },
        { phrase: 'track record', meaning: '実績', context: 'これまでの成果', register: 'neutral' },
        { phrase: 'notice period', meaning: '退職予告期間', context: '勤務開始時期', register: 'neutral' },
        { phrase: 'salary', meaning: '給与', context: '希望条件', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'team player', meaning: 'チームで協力できる人', note: 'I work well in a team. と同じ強みを伝えます。' },
        { phrase: 'adapt to new situations', meaning: '新しい状況に適応する', note: '変化への対応力を表します。' },
        { phrase: 'solve problems', meaning: '問題を解決する', note: 'Enjoy solving problems. の動詞句です。' },
      ],
    },
    dialogues: [
      {
        id: 'motivation',
        label: 'Pattern A · Motivation and contribution',
        title: '志望動機と会社への貢献を答える',
        lines: [
          { speaker: 'A', en: 'Why are you right for this position?', ja: 'なぜあなたはこの職種にふさわしいのですか？' },
          { speaker: 'B', en: "I've got the qualifications and experience you're looking for.", ja: '御社が求める資格と経験があります。' },
          { speaker: 'A', en: 'What can you bring to our company?', ja: '当社にどのように貢献できますか？' },
          { speaker: 'B', en: 'Enthusiasm, energy, and lots of ideas.', ja: '熱意、活力、そしてたくさんのアイデアです。' },
        ],
      },
      {
        id: 'strengths',
        label: 'Pattern B · Talking about yourself',
        title: '自分の強みと働き方を説明する',
        lines: [
          { speaker: 'A', en: 'Tell me about yourself.', ja: 'あなた自身について教えてください。' },
          { speaker: 'B', en: "I'm reliable and organized.", ja: '私は信頼でき、計画的です。' },
          { speaker: 'A', en: 'How do you work with other people?', ja: 'ほかの人とはどのように働きますか？' },
          { speaker: 'B', en: 'I work well in a team and I enjoy solving problems.', ja: 'チームでうまく働き、問題解決を楽しみます。' },
        ],
      },
      {
        id: 'practical',
        label: 'Pattern C · Practical questions',
        title: '給与と勤務開始時期を確認する',
        lines: [
          { speaker: 'A', en: 'What salary are you expecting?', ja: 'どのくらいの給与を希望していますか？' },
          { speaker: 'B', en: "I'm open to discussing the salary.", ja: '給与については相談できます。' },
          { speaker: 'A', en: 'How soon could you start?', ja: 'いつから働き始められますか？' },
          { speaker: 'B', en: 'I could start after my notice period.', ja: '退職予告期間のあとに始められます。' },
        ],
      },
    ],
    tip: '英語の面接では、謙遜しすぎず、自分の長所を I am... や I have... でストレートに伝えます。reliable、organized、self-motivated のような形容詞や、I have an excellent track record. のような実績の表現を使うと、強みを具体的にアピールできます。',
  },
  practice: {
    title: '面接で、自分の強みを具体的に伝える',
    instructions: '日本語訳は見ずに、志望動機、貢献、強み、経験、給与、開始時期について声に重ねます。',
    coreHeading: 'まずは、面接でそのまま使える一文から。',
    dialogueHeading: '志望動機、自己アピール、実務条件の場面で役を切り替える。',
    dialogueDescription: '会社への貢献を答える、自分の強みを話す、給与と開始時期を確認する3つの場面を練習します。',
    finishTitle: '次の面接準備では、自分の強みを英語でひとつ具体的に説明してみましょう。',
    corePhrases: [
      { phrase: 'Why are you right for this position?', context: '適性を尋ねる', rate: 0.78 },
      { phrase: "I've got the qualifications and experience you're looking for.", context: '資格と経験を答える', rate: 0.74 },
      { phrase: 'What can you bring to our company?', context: '貢献を尋ねる', rate: 0.78 },
      { phrase: 'Enthusiasm, energy, and lots of ideas.', context: '貢献できることを答える', rate: 0.8 },
      { phrase: 'Why did you apply for this job?', context: '志望動機を尋ねる', rate: 0.78 },
      { phrase: "I'm really keen to use my planning skills.", context: '意欲を伝える', rate: 0.76 },
      { phrase: 'Tell me about yourself.', context: '自己紹介を促す', rate: 0.82 },
      { phrase: "I'm reliable and organized.", context: '長所を伝える', rate: 0.82 },
      { phrase: 'I work well in a team.', context: '協調性を伝える', rate: 0.82 },
      { phrase: "I'm used to working under pressure.", context: '対応力を伝える', rate: 0.76 },
      { phrase: 'I have an excellent track record.', context: '実績を伝える', rate: 0.78 },
      { phrase: 'What are your strengths?', context: '強みを尋ねる', rate: 0.82 },
      { phrase: 'What salary are you expecting?', context: '希望給与を尋ねる', rate: 0.78 },
      { phrase: 'How soon could you start?', context: '開始時期を尋ねる', rate: 0.82 },
    ],
    dialogues: [
      { title: 'Motivation and contribution', lines: ['Why are you right for this position?', "I've got the qualifications and experience you're looking for.", 'What can you bring to our company?', 'Enthusiasm, energy, and lots of ideas.'] },
      { title: 'Talking about yourself', lines: ['Tell me about yourself.', "I'm reliable and organized.", 'How do you work with other people?', 'I work well in a team and I enjoy solving problems.'] },
      { title: 'Practical questions', lines: ['What salary are you expecting?', "I'm open to discussing the salary.", 'How soon could you start?', 'I could start after my notice period.'] },
    ],
    natural: [
      { full: 'I possess the qualifications and experience that you want.', natural: "I've got the qualifications and experience you're looking for." },
      { full: 'I am very eager to use my planning abilities.', natural: "I'm really keen to use my planning skills." },
      { full: 'I have a very strong history of successful work.', natural: 'I have an excellent track record.' },
    ],
  },
}
