/** Chapter 44 · At the library. */
export const libraryLesson = {
  id: 'library',
  kind: 'library',
  number: '44',
  title: '第44章に入る前に：なぜ「図書館で使う英語」を学ぶのでしょうか？',
  enTitle: 'At the library',
  ja: '図書館への登録、本の貸出・返却、設備の利用を尋ねる英語を学びます。',
  cando: '図書館に登録し、本を借りたり返したり、館内設備やおすすめの本を尋ねられる。',
  learn: {
    intro: [
      '図書館は、本が置いてあるだけの場所ではありません。本や資料を借りたり、勉強したり、パソコンを使ったり、情報を探したりできる公共の場所です。',
      '図書館を自分で利用するためには、登録の仕方、資料の借り方・返し方、そして必要なときに助けを求める表現を知っておくことが大切です。',
      'この章では、図書館への登録、本の貸出・返却・延長、おすすめの本の尋ね方、そして館内設備の利用に必要な表現を学びます。',
    ],
    functions: [
      ['01', '利用登録をする'],
      ['02', '本と資料を借りる'],
      ['03', '設備を利用する'],
      ['04', '返却・延長・検索を尋ねる'],
    ],
    joining: {
      title: '図書館の利用登録と質問',
      enTitle: 'Joining the library',
      intro: '初めて利用するときの登録手続きと、館内で開催される講座について尋ねます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Hi there. How do I join the library?', meaning: 'こんにちは。図書館にはどうやって登録すればいいですか？', context: '利用登録をする', register: 'polite' },
        { phrase: "I'll just need some ID and proof of your address.", meaning: '身分証明書と住所証明が必要になります。', context: '必要書類を確認する', register: 'polite' },
        { phrase: 'Do you run computing courses here?', meaning: 'ここではコンピューターの講座を開催していますか？', context: '講座について尋ねる', register: 'polite' },
        { phrase: "Yes, here's a list of all our classes.", meaning: 'はい、こちらがすべてのクラスのリストです。', context: '講座を案内する', register: 'neutral' },
        { phrase: 'Is proof of address required to join?', meaning: '登録には住所証明が必要ですか？', context: '登録条件を確認する', register: 'polite' },
      ],
      recognition: [
        { phrase: 'proof of your address', meaning: '住所証明', note: '公共料金の請求書などが使われることがあります。' },
        { phrase: 'computing course', meaning: 'コンピューター講座', note: '図書館の地域向け講座でよく使われます。' },
        { phrase: 'join the library', meaning: '図書館に登録する', note: '会員登録して利用できる状態にすることです。' },
      ],
    },
    using: {
      title: '本を借りる・館内を利用する',
      enTitle: 'Using the library',
      intro: '本やオーディオブックを借り、自習スペースやパソコンを利用します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: "I'd like to take these books out.", meaning: 'これらの本を借りたいのですが。', context: '本を借りる', register: 'polite' },
        { phrase: "If you've got your library card, you can use this scanner.", meaning: '図書カードがあれば、こちらのスキャナーを使えます。', context: 'セルフ貸出を案内する', register: 'neutral' },
        { phrase: 'Have you got this as an audiobook?', meaning: 'これのオーディオブックはありますか？', context: '音声資料を探す', register: 'polite' },
        { phrase: "Yes, we do. I'll show you how to download it.", meaning: 'はい、あります。ダウンロード方法をお見せします。', context: 'ダウンロードを案内する', register: 'neutral' },
        { phrase: 'Can we use a computer for our school project?', meaning: '学校の課題のためにパソコンを使ってもいいですか？', context: 'パソコンを頼む', register: 'polite' },
        { phrase: "Of course. I'll book you one in the study space.", meaning: 'もちろんです。自習スペースのものを予約します。', context: '設備を予約する', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'take these books out', meaning: 'これらの本を借りる', note: '図書館の外へ持ち出すニュアンスです。' },
        { phrase: 'library card', meaning: '図書カード', note: '貸出やセルフスキャナーで使います。' },
        { phrase: 'study space', meaning: '自習スペース', note: '勉強や課題に使う場所です。' },
      ],
    },
    more: {
      title: '窓口で役立つその他のフレーズ',
      enTitle: 'More phrases',
      intro: '貸出期間の延長、本の返却、目的の本や資料を探すときの表現です。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'I need to renew these books, please.', meaning: 'これらの本の貸出期間を延長したいのですが。', context: '貸出期間を延長する', register: 'polite' },
        { phrase: 'Where do I return these books?', meaning: 'これらの本はどこに返却すればいいですか？', context: '返却場所を尋ねる', register: 'polite' },
        { phrase: 'Can you help me find a book, please?', meaning: '本を探すのを手伝っていただけますか？', context: '本を探す', register: 'polite' },
        { phrase: "Where is the children's section?", meaning: '児童書コーナーはどこですか？', context: '場所を尋ねる', register: 'polite' },
        { phrase: 'Could you recommend a good thriller?', meaning: 'おすすめの面白いスリラー本を教えていただけますか？', context: 'おすすめを聞く', register: 'polite' },
        { phrase: 'Can I see your newspaper archive?', meaning: '新聞のアーカイブを見てもいいですか？', context: '資料を閲覧する', register: 'polite' },
        { phrase: 'When are these books due back?', meaning: 'これらの本の返却期限はいつですか？', context: '返却期限を尋ねる', register: 'polite' },
      ],
      recognition: [
        { phrase: 'renew', meaning: '貸出期間を延長する', note: '本や免許証などの期限を更新するときにも使います。' },
        { phrase: 'children\'s section', meaning: '児童書コーナー', note: '図書館内の場所を尋ねる表現です。' },
        { phrase: 'newspaper archive', meaning: '新聞アーカイブ', note: '過去の新聞を保存した資料です。' },
      ],
    },
    vocabulary: {
      title: '図書館のボキャブラリー',
      enTitle: 'Vocabulary · Library services',
      intro: '図書館の案内やスタッフとの会話でよく見る単語を整理します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'library card', meaning: '図書カード', context: '貸出に使うカード', register: 'neutral' },
        { phrase: 'scanner', meaning: 'スキャナー', context: 'セルフ貸出の機械', register: 'neutral' },
        { phrase: 'audiobook', meaning: 'オーディオブック', context: '音声で聞く本', register: 'neutral' },
        { phrase: 'study space', meaning: '自習スペース', context: '勉強する場所', register: 'neutral' },
        { phrase: 'renew', meaning: '延長する・更新する', context: '貸出期間を延ばす', register: 'neutral' },
        { phrase: 'return', meaning: '返却する', context: '借りた本を戻す', register: 'neutral' },
        { phrase: 'children\'s section', meaning: '児童書コーナー', context: '子ども向けの本の場所', register: 'neutral' },
        { phrase: 'thriller', meaning: 'スリラー', context: '本のジャンル', register: 'neutral' },
        { phrase: 'newspaper archive', meaning: '新聞アーカイブ', context: '過去の新聞資料', register: 'neutral' },
        { phrase: 'due back', meaning: '返却期限である', context: 'いつ返すかを表す', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'take out', meaning: '（図書館から）借りる', note: 'check out と同じように使えます。' },
        { phrase: 'renew', meaning: '貸出期間を延長する', note: 'borrowed item の期限を延ばします。' },
        { phrase: 'due back', meaning: '返却期限が来る', note: 'When are these books due back? の形で使います。' },
        { phrase: 'archive', meaning: '保存資料・アーカイブ', note: '過去の新聞や記録を指します。' },
      ],
    },
    dialogues: [
      {
        id: 'joining',
        label: 'Pattern A · Joining the library',
        title: '登録に必要なものと講座を尋ねる',
        lines: [
          { speaker: 'A', en: 'Hi there. How do I join the library?', ja: '図書館にはどうやって登録すればいいですか？' },
          { speaker: 'B', en: "I'll just need some ID and proof of your address.", ja: '身分証明書と住所証明が必要です。' },
          { speaker: 'A', en: 'Do you run computing courses here?', ja: 'ここではコンピューター講座を開催していますか？' },
          { speaker: 'B', en: "Yes, here's a list of all our classes.", ja: 'はい、こちらがクラスのリストです。' },
        ],
      },
      {
        id: 'borrowing',
        label: 'Pattern B · Borrowing books',
        title: '本を借り、オーディオブックを探す',
        lines: [
          { speaker: 'A', en: "I'd like to take these books out.", ja: 'これらの本を借りたいのですが。' },
          { speaker: 'B', en: "If you've got your library card, you can use this scanner.", ja: '図書カードがあれば、このスキャナーを使えます。' },
          { speaker: 'A', en: 'Have you got this as an audiobook?', ja: 'これのオーディオブックはありますか？' },
          { speaker: 'B', en: "Yes, we do. I'll show you how to download it.", ja: 'はい、あります。ダウンロード方法をお見せします。' },
        ],
      },
      {
        id: 'renewing',
        label: 'Pattern C · Renewing and finding books',
        title: '延長し、おすすめの本を尋ねる',
        lines: [
          { speaker: 'A', en: 'I need to renew these books, please.', ja: 'これらの本の貸出期間を延長したいのですが。' },
          { speaker: 'B', en: 'Of course. When are they due back?', ja: 'もちろんです。返却期限はいつですか？' },
          { speaker: 'A', en: 'Could you recommend a good thriller?', ja: 'おすすめのスリラー本を教えていただけますか？' },
          { speaker: 'B', en: "I'll help you find one.", ja: '一冊探すお手伝いをします。' },
        ],
      },
    ],
    tip: '図書館で本を「借りる」ときは borrow だけでなく take out や check out をよく使います。貸出期間を延長する動詞は renew です。proof of your address は住所証明、due back は返却期限を表します。',
  },
  practice: {
    title: '図書館を、英語で自分で利用する',
    instructions: '日本語訳は見ずに、登録、貸出、設備の利用、返却と延長を声に重ねます。',
    coreHeading: 'まずは、図書館の窓口でそのまま使える一文から。',
    dialogueHeading: '登録、貸出、延長の場面で役を切り替える。',
    dialogueDescription: '利用登録、本を借りる、返却期限を延長する3つの場面で会話を練習します。',
    finishTitle: '次に図書館へ行くとき、借りたい資料や使いたい設備を英語でひとつ尋ねてみましょう。',
    corePhrases: [
      { phrase: 'Hi there. How do I join the library?', context: '利用登録をする', rate: 0.8 },
      { phrase: "I'll just need some ID and proof of your address.", context: '必要書類を確認する', rate: 0.72 },
      { phrase: 'Do you run computing courses here?', context: '講座を尋ねる', rate: 0.8 },
      { phrase: "I'd like to take these books out.", context: '本を借りる', rate: 0.82 },
      { phrase: 'Have you got this as an audiobook?', context: '音声資料を探す', rate: 0.8 },
      { phrase: 'Can we use a computer for our school project?', context: 'パソコンを利用する', rate: 0.72 },
      { phrase: 'I need to renew these books, please.', context: '貸出を延長する', rate: 0.78 },
      { phrase: 'Where do I return these books?', context: '本を返却する', rate: 0.84 },
      { phrase: 'Can you help me find a book, please?', context: '本を探す', rate: 0.78 },
      { phrase: "Where is the children's section?", context: '場所を尋ねる', rate: 0.82 },
      { phrase: 'Could you recommend a good thriller?', context: 'おすすめを聞く', rate: 0.76 },
      { phrase: 'Can I see your newspaper archive?', context: '資料を閲覧する', rate: 0.78 },
    ],
    dialogues: [
      { title: 'Joining the library', lines: ['Hi there. How do I join the library?', "I'll just need some ID and proof of your address.", 'Do you run computing courses here?', "Yes, here's a list of all our classes."] },
      { title: 'Borrowing books', lines: ["I'd like to take these books out.", "If you've got your library card, you can use this scanner.", 'Have you got this as an audiobook?', "Yes, we do. I'll show you how to download it."] },
      { title: 'Renewing and finding books', lines: ['I need to renew these books, please.', 'Of course. When are they due back?', 'Could you recommend a good thriller?', "I'll help you find one."] },
    ],
    natural: [
      { full: 'How can I become a member of the library?', natural: 'How do I join the library?' },
      { full: 'I would like to borrow these books.', natural: "I'd like to take these books out." },
      { full: 'Can you extend the loan period?', natural: 'I need to renew these books, please.' },
    ],
  },
}
