/** Chapter 48 · Looking for work. */
export const lookingForWorkLesson = {
  id: 'looking-for-work',
  kind: 'looking-for-work',
  number: '48',
  title: '第48章に入る前に：なぜ「仕事探しの英語」を学ぶのでしょうか？',
  enTitle: 'Looking for work',
  ja: '求人の条件、職歴、スキル、勤務時間、給与について話す英語を学びます。',
  cando: '求人を探し、自分の経験やスキル、希望する勤務条件を明確に伝えられる。',
  learn: {
    intro: [
      '仕事を探すということは、単に求人を見つけることではありません。会社がどのような人を求めているのかを理解し、自分のスキルや経験、働ける時間、希望する条件が合っているかを考えます。',
      '同時に、自分が何ができるのか、どのような経験があるのか、どんな仕事を探しているのかを相手に明確に伝えることも大切です。',
      'この章では、求人の探し方、勤務条件の尋ね方、自分の経験やスキルの伝え方、そして仕事探しでよく聞かれる質問への答え方を学びます。',
    ],
    functions: [
      ['01', '求人の条件を読む'],
      ['02', '職業紹介所で相談する'],
      ['03', '経験とスキルを伝える'],
      ['04', '希望条件を答える'],
    ],
    searching: {
      title: '求人を探す',
      enTitle: 'Job searching',
      intro: '求人広告を読み、求人サイトや店頭の募集について問い合わせます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'This job looks interesting...', meaning: 'この仕事、面白そうだな…', context: '求人に興味を持つ', register: 'casual' },
        { phrase: 'flexible hours', meaning: 'フレキシブルな勤務時間', context: '求人条件を読む', register: 'neutral' },
        { phrase: 'no experience needed', meaning: '経験不問・未経験歓迎', context: '求人条件を読む', register: 'neutral' },
        { phrase: 'Sounds ideal!', meaning: '理想的に思える・ぴったりだ！', context: '条件に納得する', register: 'casual' },
        { phrase: 'Have you used this job search website?', meaning: 'この求人検索サイトを使ったことある？', context: '求人サイトを尋ねる', register: 'casual' },
        { phrase: 'Yes, I found my current job on there.', meaning: 'うん、今の仕事はそこで見つけたんだ。', context: '求人サイトを説明する', register: 'casual' },
        { phrase: 'Is the job in the window still vacant?', meaning: '店頭に出ている求人はまだ募集していますか？', context: '店頭求人を尋ねる', register: 'polite' },
        { phrase: 'Yes, could you email us your CV?', meaning: 'はい、履歴書をメールで送っていただけますか？', context: '応募書類を頼む', register: 'polite' },
      ],
      recognition: [
        { phrase: 'flexible hours', meaning: '融通の利く勤務時間', note: '勤務時間を調整できる求人条件です。' },
        { phrase: 'no experience needed', meaning: '経験不要', note: '未経験者も応募できるという意味です。' },
        { phrase: 'vacant', meaning: '空いている・募集中の', note: '求人の名詞は vacancy です。' },
      ],
    },
    agency: {
      title: '職業紹介所での相談',
      enTitle: 'At the employment agency',
      intro: '紹介所で希望する職種を伝え、これまでの仕事について説明します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'How can I help?', meaning: 'どのようなご用件でしょうか？', context: '相談を始める', register: 'polite' },
        { phrase: "I'm looking for a part-time sales job.", meaning: 'パートタイムの販売職を探しています。', context: '希望職種を伝える', register: 'polite' },
        { phrase: 'Okay, let me take some details about you.', meaning: 'あなたの詳細を少しお伺いしますね。', context: '経歴を確認する', register: 'polite' },
        { phrase: 'Have you worked in a restaurant before?', meaning: '以前にレストランで働いたことはありますか？', context: '職歴を尋ねる', register: 'polite' },
        { phrase: 'I worked as a server last summer.', meaning: '去年の夏、サーバーとして働きました。', context: '職歴を伝える', register: 'neutral' },
        { phrase: 'I can work evenings and weekends.', meaning: '夕方と週末に働けます。', context: '勤務可能時間を伝える', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'take some details', meaning: '詳細を聞き取る', note: '応募者の経歴や連絡先を確認する表現です。' },
        { phrase: 'part-time sales job', meaning: 'パートの販売職', note: '希望する雇用形態と職種を組み合わせています。' },
        { phrase: 'server', meaning: '飲食店の接客係', note: 'waiter / waitress に代わる表現です。' },
      ],
    },
    questions: {
      title: 'よく聞かれる質問',
      enTitle: 'Questions you may hear',
      intro: '応募、面接、紹介所でよく聞かれる質問に、経験や条件を具体的に答えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'What skills have you got?', meaning: 'どのようなスキルを持っていますか？', context: 'スキルを尋ねる', register: 'polite' },
        { phrase: 'What hours can you work?', meaning: 'どの時間帯に働けますか？', context: '勤務可能時間を尋ねる', register: 'polite' },
        { phrase: 'What experience have you got?', meaning: 'どのような経験がありますか？', context: '経験を尋ねる', register: 'polite' },
        { phrase: 'What salary are you looking for?', meaning: 'どのくらいの給与を希望していますか？', context: '希望給与を尋ねる', register: 'polite' },
        { phrase: 'Why did you leave your last job?', meaning: 'なぜ前の仕事を辞めたのですか？', context: '退職理由を尋ねる', register: 'polite' },
        { phrase: 'I have good customer service skills.', meaning: '接客のスキルがあります。', context: 'スキルを答える', register: 'neutral' },
        { phrase: 'I am available three days a week.', meaning: '週3日働けます。', context: '勤務可能日数を答える', register: 'neutral' },
        { phrase: 'I am looking for a salary of around £30,000.', meaning: '3万ポンド程度の給与を希望しています。', context: '希望給与を答える', register: 'polite' },
      ],
      recognition: [
        { phrase: 'What experience have you got?', meaning: 'どのような経験がありますか？', note: 'Have you got はイギリス英語でよく使われます。' },
        { phrase: 'customer service skills', meaning: '接客スキル', note: '販売、飲食、受付など幅広い職種で役立つ表現です。' },
        { phrase: 'available', meaning: '勤務できる・空いている', note: '働ける曜日や時間を伝えるときに使います。' },
      ],
    },
    vocabulary: {
      title: '仕事探しのボキャブラリー',
      enTitle: 'Vocabulary · Looking for work',
      intro: '求人広告、履歴書、紹介所、面談でよく見る単語を整理します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'job search website', meaning: '求人検索サイト', context: '求人を探す場所', register: 'neutral' },
        { phrase: 'vacant', meaning: '募集中の・空いている', context: '求人の状態', register: 'neutral' },
        { phrase: 'vacancy', meaning: '空き・欠員・求人', context: '募集ポジション', register: 'neutral' },
        { phrase: 'CV', meaning: '履歴書', context: 'イギリス英語', register: 'neutral' },
        { phrase: 'resume', meaning: '履歴書', context: 'アメリカ英語', register: 'neutral' },
        { phrase: 'employment agency', meaning: '職業紹介所', context: '求人を紹介する場所', register: 'neutral' },
        { phrase: 'skills', meaning: 'スキル・技能', context: 'できること', register: 'neutral' },
        { phrase: 'experience', meaning: '経験', context: 'これまでの仕事', register: 'neutral' },
        { phrase: 'salary', meaning: '給与', context: '希望条件', register: 'neutral' },
        { phrase: 'flexible hours', meaning: '柔軟な勤務時間', context: '求人条件', register: 'neutral' },
        { phrase: 'no experience needed', meaning: '経験不要', context: '求人条件', register: 'neutral' },
        { phrase: 'server', meaning: '接客係', context: '飲食店の仕事', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'CV', meaning: '履歴書', note: 'イギリス英語。アメリカ英語では resume が一般的です。' },
        { phrase: 'vacancy', meaning: '求人・欠員', note: 'Staff Vacancy のように看板で見かけます。' },
        { phrase: 'current job', meaning: '現在の仕事', note: '今働いている仕事を指します。' },
        { phrase: 'email us your CV', meaning: '履歴書をメールで送る', note: '応募書類の提出を頼む自然な表現です。' },
      ],
    },
    dialogues: [
      {
        id: 'window',
        label: 'Pattern A · Asking about a vacancy',
        title: '店頭の求人について問い合わせる',
        lines: [
          { speaker: 'A', en: 'Is the job in the window still vacant?', ja: '窓に貼ってある求人はまだ募集中ですか？' },
          { speaker: 'B', en: 'Yes, could you email us your CV?', ja: 'はい、履歴書をメールで送っていただけますか？' },
          { speaker: 'A', en: 'What hours can you work?', ja: 'どの時間帯に働けますか？' },
          { speaker: 'B', en: 'I can work evenings and weekends.', ja: '夕方と週末に働けます。' },
        ],
      },
      {
        id: 'agency',
        label: 'Pattern B · Employment agency',
        title: '紹介所で希望職種と職歴を伝える',
        lines: [
          { speaker: 'A', en: 'How can I help?', ja: 'どのようなご用件でしょうか？' },
          { speaker: 'B', en: "I'm looking for a part-time sales job.", ja: 'パートタイムの販売職を探しています。' },
          { speaker: 'A', en: 'Have you worked in a restaurant before?', ja: '以前にレストランで働いたことはありますか？' },
          { speaker: 'B', en: 'I worked as a server last summer.', ja: '去年の夏、接客係として働きました。' },
        ],
      },
      {
        id: 'questions',
        label: 'Pattern C · Job questions',
        title: 'スキルと希望条件を答える',
        lines: [
          { speaker: 'A', en: 'What skills have you got?', ja: 'どのようなスキルを持っていますか？' },
          { speaker: 'B', en: 'I have good customer service skills.', ja: '接客のスキルがあります。' },
          { speaker: 'A', en: 'What salary are you looking for?', ja: 'どのくらいの給与を希望していますか？' },
          { speaker: 'B', en: 'I am looking for a salary of around £30,000.', ja: '3万ポンド程度の給与を希望しています。' },
        ],
      },
    ],
    tip: 'イギリス英語では履歴書を CV、アメリカ英語では resume と呼びます。求人の「空き」は vacant、名詞は vacancy です。server は waiter / waitress に代わる性別を問わない接客係の表現です。',
  },
  practice: {
    title: '仕事探しを、英語で前に進める',
    instructions: '日本語訳は見ずに、求人条件、職歴、スキル、勤務時間、希望給与を声に重ねます。',
    coreHeading: 'まずは、仕事探しでそのまま使える一文から。',
    dialogueHeading: '求人、紹介所、面談の場面で役を切り替える。',
    dialogueDescription: '店頭の求人を尋ねる、職業紹介所で相談する、面接の質問に答える3つの場面を練習します。',
    finishTitle: '次に求人を見るとき、条件か自分のスキルを英語でひとつ説明してみましょう。',
    corePhrases: [
      { phrase: 'This job looks interesting...', context: '求人に興味を持つ', rate: 0.86 },
      { phrase: 'Have you used this job search website?', context: '求人サイトを尋ねる', rate: 0.78 },
      { phrase: 'Is the job in the window still vacant?', context: '店頭求人を尋ねる', rate: 0.72 },
      { phrase: 'Could you email us your CV?', context: 'CVを頼む', rate: 0.8 },
      { phrase: "I'm looking for a part-time sales job.", context: '希望職種を伝える', rate: 0.76 },
      { phrase: 'Have you worked in a restaurant before?', context: '職歴を尋ねる', rate: 0.76 },
      { phrase: 'I worked as a server last summer.', context: '職歴を伝える', rate: 0.8 },
      { phrase: 'What skills have you got?', context: 'スキルを尋ねる', rate: 0.82 },
      { phrase: 'What hours can you work?', context: '勤務可能時間を尋ねる', rate: 0.82 },
      { phrase: 'What experience have you got?', context: '経験を尋ねる', rate: 0.78 },
      { phrase: 'What salary are you looking for?', context: '希望給与を尋ねる', rate: 0.76 },
      { phrase: 'I have good customer service skills.', context: 'スキルを答える', rate: 0.78 },
    ],
    dialogues: [
      { title: 'Asking about a vacancy', lines: ['Is the job in the window still vacant?', 'Yes, could you email us your CV?', 'What hours can you work?', 'I can work evenings and weekends.'] },
      { title: 'Employment agency', lines: ['How can I help?', "I'm looking for a part-time sales job.", 'Have you worked in a restaurant before?', 'I worked as a server last summer.'] },
      { title: 'Job questions', lines: ['What skills have you got?', 'I have good customer service skills.', 'What salary are you looking for?', 'I am looking for a salary of around £30,000.'] },
    ],
    natural: [
      { full: 'I am searching for a sales job with fewer hours.', natural: "I'm looking for a part-time sales job." },
      { full: 'Is the position advertised in the window still available?', natural: 'Is the job in the window still vacant?' },
      { full: 'What times are you able to work?', natural: 'What hours can you work?' },
    ],
  },
}
