/** Chapter 35 · At the market. */
export const marketLesson = {
  id: 'market',
  kind: 'market',
  number: '35',
  title: '第35章に入る前に：なぜ「市場で使う英語」を学ぶのでしょうか？',
  enTitle: 'At the market',
  ja: '値段、量、商品の状態を確認し、丁寧に交渉する英語を学びます。',
  cando: '市場で値段や量を尋ね、丁寧に交渉し、食材を必要な単位で注文できる。',
  learn: {
    intro: [
      '市場では、普通のお店よりも、店員とのやり取りが直接的で会話的になることがあります。値段を聞いたり、量を指定したり、商品の状態について尋ねたり、場合によっては価格を交渉したりすることもあります。',
      'そのため、市場で必要なのは、「何を買いたいか」だけでなく、「どのくらい欲しいのか」「いくらなら買いたいのか」を伝える英語です。',
      'この章では、値段の尋ね方、丁寧な交渉の仕方、生鮮食品の買い方、そして量や容器を表す基本的な表現を学びます。',
    ],
    functions: [
      ['01', '値段を確認する'],
      ['02', '丁寧に交渉する'],
      ['03', '量と単位を指定する'],
      ['04', '注文を決める'],
    ],
    bargain: {
      title: '値段の交渉・値切り',
      enTitle: 'Getting a bargain',
      intro: 'フリーマーケットや市場で、少し安くしてもらえないか丁寧に交渉するときの表現です。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "What's your best price for this?", meaning: 'これ、一番安くていくらになりますか？', context: '一番安い価格を尋ねる', register: 'polite' },
        { phrase: "I can't go any lower than £12.", meaning: '12ポンドより安くはできません。', context: 'これ以上下げられないと伝える', register: 'neutral' },
        { phrase: "I've only got £10.", meaning: '10ポンドしか持っていないんです。', context: '持っている金額を伝える', register: 'casual' },
        { phrase: "You've got a deal!", meaning: 'それで手を打ちましょう！', context: '交渉を成立させる', register: 'casual' },
        { phrase: 'Is that your best price?', meaning: 'それが限界の価格ですか？', context: '最後の価格か確認する', register: 'neutral' },
        { phrase: "That's my final offer.", meaning: 'これが最終的な提示額です。', context: '最後の提示額を伝える', register: 'neutral' },
        { phrase: "I can't spend that much.", meaning: 'そこまでは出せません。', context: '予算を伝える', register: 'polite' },
        { phrase: 'Can I get two for £15?', meaning: '2つで15ポンドにしてもらえませんか？', context: 'まとめ買いを交渉する', register: 'polite' },
        { phrase: "I'll take it!", meaning: 'それを買います！', context: '購入を決める', register: 'casual' },
      ],
      recognition: [
        { phrase: 'best price', meaning: '一番安い価格・限界の価格', note: '値段交渉を始めるときの自然な言い方です。' },
        { phrase: 'go any lower', meaning: 'さらに安くする', note: 'I can’t go any lower than ... の形で使います。' },
        { phrase: 'You’ve got a deal!', meaning: '交渉成立です', note: '条件に合意したときの決まり文句です。' },
      ],
    },
    produce: {
      title: '新鮮な食材を買う・量り売り',
      enTitle: 'Buying fresh produce',
      intro: '量り売りで値段を聞いたり、個数や量を指定して注文したりする表現です。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'How much is this cheese?', meaning: 'このチーズはいくらですか？', context: '食材の値段を尋ねる', register: 'neutral' },
        { phrase: "It's £3.99 per kilo.", meaning: '1キロあたり3.99ポンドです。', context: '単位あたりの価格を答える', register: 'neutral' },
        { phrase: 'Could I have a box of eggs?', meaning: '卵を1箱いただけますか？', context: '容器単位で注文する', register: 'polite' },
        { phrase: 'Would you like six or 12?', meaning: '6個入りですか、それとも12個入りですか？', context: '個数を確認する', register: 'polite' },
        { phrase: "I'd like a loaf of bread, please.", meaning: 'パンを1斤お願いします。', context: 'パンを単位で注文する', register: 'polite' },
        { phrase: "Here you go. That'll be £2.50.", meaning: 'はい、どうぞ。2.50ポンドになります。', context: '商品と合計金額を渡す', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'per kilo', meaning: '1キロあたり', note: '量り売りの価格を伝える単位です。' },
        { phrase: 'a loaf of bread', meaning: 'パン1斤・1塊', note: 'bread を数えるときの単位です。' },
        { phrase: 'a box of eggs', meaning: '卵1箱', note: '容器ごと注文するときに使います。' },
      ],
    },
    units: {
      title: '食べ物の数え方・単位',
      enTitle: 'Vocabulary · Food market',
      intro: '食材の形や入れ物によって変わる数え方を、買い物の場面で使える形にします。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'a bunch of grapes', meaning: 'ぶどう1房', context: '房で数える', register: 'neutral' },
        { phrase: 'a loaf of bread', meaning: 'パン1斤・1塊', context: '塊で数える', register: 'neutral' },
        { phrase: 'a punnet of strawberries', meaning: 'イチゴ1パック', context: '小さな容器で数える', register: 'neutral' },
        { phrase: 'a block of cheese', meaning: 'チーズ1塊', context: '塊で数える', register: 'neutral' },
        { phrase: 'a box of eggs', meaning: '卵1箱', context: '箱で数える', register: 'neutral' },
        { phrase: 'a bag of apples', meaning: 'りんご1袋', context: '袋で数える', register: 'neutral' },
        { phrase: 'a kilo of potatoes', meaning: 'じゃがいも1キロ', context: '重さで数える', register: 'neutral' },
        { phrase: 'a jar of honey', meaning: 'ハチミツ1瓶', context: '瓶で数える', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'punnet', meaning: '小さな果物用パック', note: 'イチゴなどが入った容器を指すイギリス英語です。' },
        { phrase: 'a bunch of', meaning: 'ひと房・ひと束', note: 'ぶどうやバナナなどに使います。' },
        { phrase: 'a jar of', meaning: 'ひと瓶の', note: 'honey や jam など、瓶に入ったものに使います。' },
      ],
    },
    dialogues: [
      {
        id: 'bargain',
        label: 'Pattern A · Getting a bargain',
        title: '値段を交渉して、条件を決める',
        lines: [
          { speaker: 'A', en: "What's your best price for this?", ja: 'これ、一番安くていくらになりますか？' },
          { speaker: 'B', en: "I can't go any lower than £12.", ja: '12ポンドより安くはできないね。' },
          { speaker: 'A', en: "I've only got £10.", ja: '10ポンドしか持っていないんです。' },
          { speaker: 'B', en: "You've got a deal!", ja: 'それで手を打ちましょう！' },
        ],
      },
      {
        id: 'produce',
        label: 'Pattern B · Buying fresh produce',
        title: '食材の値段と個数を確認する',
        lines: [
          { speaker: 'A', en: 'How much is this cheese?', ja: 'このチーズはいくらですか？' },
          { speaker: 'B', en: "It's £3.99 per kilo.", ja: '1キロあたり3.99ポンドです。' },
          { speaker: 'A', en: 'Could I have a box of eggs?', ja: '卵を1箱いただけますか？' },
          { speaker: 'B', en: 'Would you like six or 12?', ja: '6個入りですか、それとも12個入りですか？' },
        ],
      },
      {
        id: 'units',
        label: 'Pattern C · Choosing a quantity',
        title: '単位を使って注文を決める',
        lines: [
          { speaker: 'A', en: "I'd like a loaf of bread, please.", ja: 'パンを1斤お願いします。' },
          { speaker: 'B', en: "Here you go. That'll be £2.50.", ja: 'はい、どうぞ。2.50ポンドになります。' },
          { speaker: 'A', en: 'Can I get two for £15?', ja: '2つで15ポンドにしてもらえませんか？' },
          { speaker: 'B', en: "You've got a deal!", ja: 'それで手を打ちましょう！' },
        ],
      },
    ],
    tip: '市場で注文するときは Can I...、Could I...、または I’d like... で始め、最後に please をつけると丁寧に聞こえます。Could I...? は Can I...? より少し丁寧です。punnet はイチゴなどの小さなパック、loaf はパンの塊、a kilo of は重さの単位です。',
  },
  practice: {
    title: '市場で、値段と量を英語で相談する',
    instructions: '日本語の説明はここまで。値段を尋ね、量を選び、必要なら丁寧に交渉する英語を声に重ねます。',
    coreHeading: 'まずは、市場でそのまま使える一文から。',
    dialogueHeading: '値段を聞き、量を選び、買うと決める。',
    dialogueDescription: '交渉の声、食材を注文する声、単位と価格を確認する声を切り替えます。',
    finishTitle: '次に市場へ行ったとき、ひとつだけ英語で値段か量を確認してみましょう。',
    corePhrases: [
      { phrase: "What's your best price for this?", context: '一番安い価格を尋ねる', rate: 0.8 },
      { phrase: "I've only got £10.", context: '予算を伝える', rate: 0.84 },
      { phrase: "You've got a deal!", context: '交渉を成立させる', rate: 0.94 },
      { phrase: 'How much is this cheese?', context: '食材の値段を尋ねる', rate: 0.84 },
      { phrase: "It's £3.99 per kilo.", context: '単位あたりの価格を答える', rate: 0.82 },
      { phrase: 'Could I have a box of eggs?', context: '容器単位で注文する', rate: 0.78 },
      { phrase: 'Would you like six or 12?', context: '個数を確認する', rate: 0.82 },
      { phrase: "I'd like a loaf of bread, please.", context: 'パンを注文する', rate: 0.8 },
      { phrase: 'Can I get two for £15?', context: 'まとめ買いを交渉する', rate: 0.8 },
      { phrase: "I'll take it!", context: '購入を決める', rate: 0.96 },
    ],
    dialogues: [
      { title: 'Getting a bargain', lines: ["What's your best price for this?", "I can't go any lower than £12.", "I've only got £10.", "You've got a deal!"] },
      { title: 'Buying fresh produce', lines: ['How much is this cheese?', "It's £3.99 per kilo.", 'Could I have a box of eggs?', 'Would you like six or 12?'] },
      { title: 'Choosing a quantity', lines: ["I'd like a loaf of bread, please.", "Here you go. That'll be £2.50.", 'Can I get two for £15?', "You've got a deal!"] },
    ],
    natural: [
      { full: 'What is the lowest price you can give me?', natural: "What's your best price for this?" },
      { full: 'I have only ten pounds with me.', natural: "I've only got £10." },
      { full: 'I would like one loaf of bread, please.', natural: "I'd like a loaf of bread, please." },
    ],
  },
}
