/** Chapter 58 · Moving house. */
export const movingHouseLesson = {
  id: 'moving-house',
  kind: 'moving-house',
  number: '58',
  title: '第58章に入る前に：なぜ「引っ越しで使う英語」を学ぶのでしょうか？',
  enTitle: 'Moving house',
  ja: '荷造り、引っ越し当日、鍵の受け取り、作業の指示、荷解きについて話す英語を学びます。',
  cando: '引っ越しの準備や当日の作業を説明し、必要な手伝いや指示を英語で伝えられる。',
  learn: {
    intro: [
      '引っ越しは、ただ荷物を運ぶだけではありません。荷造りをし、予定を確認し、人に手伝いを頼み、どこに何を運ぶかを伝えるなど、多くのやり取りが必要になります。',
      '準備中は、箱を集めたり、部屋ごとに荷物をまとめたり、引っ越し日を共有したりします。当日は、鍵を受け取り、トラックに荷物を積み、作業の順番を指示します。',
      '新居では、どの箱をどの部屋に運ぶかを伝え、荷解きが終わったことを確認します。疲れた人に声をかけることも、引っ越しをうまく進める大切なコミュニケーションです。',
      'この章では、荷造りや荷物の積み込み、鍵の受け取り、作業の指示、そして荷解きに関する表現を学びます。',
    ],
    functions: [
      ['01', '箱を集めて荷造りする'],
      ['02', '引っ越し日と準備を確認する'],
      ['03', '荷物を積み、作業を指示する'],
      ['04', '鍵を受け取り、荷解きを終える'],
    ],
    packing: {
      title: '荷造りと準備',
      enTitle: 'Packing up',
      intro: '箱を集め、荷造りの進み具合と、トラックに積み込む準備を確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "I'm moving house! Do you have any spare boxes?", meaning: '引っ越しをするんだ！予備の箱は何かある？', context: '箱を頼む', register: 'casual' },
        { phrase: 'There are lots in the back. Help yourself!', meaning: '奥にたくさんあるよ。ご自由にどうぞ！', context: '箱をすすめる', register: 'casual' },
        { phrase: 'Is everything packed and ready?', meaning: '荷造りは全部終わって準備万端？', context: '準備を確認する', register: 'neutral' },
        { phrase: "Yes, we're done. Let's load the van!", meaning: 'うん、終わったよ。バンに荷物を積もう！', context: '積み込みを始める', register: 'casual' },
        { phrase: "I've told everyone our moving date.", meaning: 'みんなに引っ越し日を伝えたよ。', context: '予定を共有する', register: 'neutral' },
        { phrase: "I've packed up the bedroom.", meaning: '寝室の荷造りは終わったよ。', context: '部屋の準備を報告する', register: 'neutral' },
        { phrase: 'We have to move out by the weekend.', meaning: '週末までに退去しなければなりません。', context: '退去期限を伝える', register: 'neutral' },
        { phrase: "Let's load the removal van!", meaning: '引っ越しトラックに荷物を積もう！', context: '作業を促す', register: 'casual' },
      ],
      recognition: [
        { phrase: 'spare boxes', meaning: '余分な箱・予備の段ボール', note: '使っていない箱を頼むときの表現です。' },
        { phrase: 'Help yourself!', meaning: 'ご自由にどうぞ！', note: '相手に遠慮なく取ってよいと伝えます。' },
        { phrase: 'pack up', meaning: '荷造りする・まとめる', note: '部屋や持ち物を箱に詰める動作です。' },
        { phrase: 'removal van', meaning: '引っ越し用の大型バン', note: 'イギリス英語で moving truck にあたります。' },
      ],
    },
    movingDay: {
      title: '引っ越し当日',
      enTitle: 'Moving day',
      intro: '鍵を受け取り、どの荷物をどこへ運ぶかを伝え、作業の順番を調整します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: "I'm here to pick up the keys to my flat.", meaning: 'フラットの鍵を受け取りに来ました。', context: '鍵を受け取る', register: 'polite' },
        { phrase: 'Here you are. Hope the move goes well!', meaning: 'はい、どうぞ。引っ越しがうまくいくといいですね！', context: '鍵を渡す', register: 'friendly' },
        { phrase: 'Where do you want us to start?', meaning: 'どこから作業を始めましょうか？', context: '作業の順番を尋ねる', register: 'polite' },
        { phrase: 'Can you take the boxes in the kitchen first?', meaning: 'キッチンの箱を先に運んでもらえますか？', context: '運ぶ場所を指示する', register: 'polite' },
        { phrase: 'Put the fragile boxes in the living room, please.', meaning: '壊れやすい箱はリビングに置いてください。', context: '置き場所を指示する', register: 'polite' },
        { phrase: 'Mind the stairs!', meaning: '階段に気をつけて！', context: '安全を知らせる', register: 'casual' },
        { phrase: 'We have to move out by the weekend.', meaning: '週末までに退去しなければなりません。', context: '期限を共有する', register: 'neutral' },
        { phrase: 'The keys are on the hall table.', meaning: '鍵は玄関ホールのテーブルにあります。', context: '鍵の場所を伝える', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'pick up the keys', meaning: '鍵を受け取る', note: '予約したものや新居の鍵を取りに行く表現です。' },
        { phrase: 'load the van', meaning: 'バンに積み込む', note: '荷物を車両へ載せる動作です。' },
        { phrase: 'fragile', meaning: '壊れやすい', note: '箱に貼る表示や作業の指示に使います。' },
        { phrase: 'Mind ...!', meaning: '〜に気をつけて！', note: 'イギリス英語で危険を知らせる短い表現です。' },
      ],
    },
    unpacking: {
      title: '荷解きと新居での一息',
      enTitle: 'Unpacking & settling in',
      intro: '荷物を新しい部屋へ運び終えたことを確認し、作業をねぎらって次の予定を話します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "That's the unpacking done!", meaning: 'これで荷解きは終わり！', context: '作業の完了を伝える', register: 'casual' },
        { phrase: 'Nice work! Now, you sit down and have a cup of tea.', meaning: 'お疲れ様！さあ、座ってお茶でも飲んで。', context: '相手をねぎらう', register: 'friendly' },
        { phrase: 'We can unpack in the morning.', meaning: '午前中に荷解きができます。', context: '作業の予定を話す', register: 'neutral' },
        { phrase: 'The bedroom boxes can wait until tomorrow.', meaning: '寝室の箱は明日まで後回しにできます。', context: '優先順位を決める', register: 'neutral' },
        { phrase: 'Let us take a break before we unpack the kitchen.', meaning: 'キッチンの荷解きの前に休憩しましょう。', context: '休憩を提案する', register: 'neutral' },
        { phrase: 'We are finally moved in!', meaning: 'やっと引っ越しが完了して入居できたね！', context: '入居を喜ぶ', register: 'casual' },
      ],
      recognition: [
        { phrase: 'unpack', meaning: '荷解きをする', note: '箱から荷物を出して新居にしまうことです。' },
        { phrase: 'move in', meaning: '入居する・引っ越して来る', note: '新しい家に入ることを表します。' },
        { phrase: 'settle in', meaning: '新居で落ち着く', note: '新しい環境に慣れて生活を始める表現です。' },
        { phrase: 'Nice work!', meaning: 'お疲れ様・よくやったね', note: '作業を終えた人をねぎらう短い一言です。' },
      ],
    },
    vocabulary: {
      title: '引っ越しのボキャブラリー',
      enTitle: 'Vocabulary · Moving house',
      intro: '引っ越しの予定、荷物、車両、入居と退去に関する基本語彙を整理します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'moving date', meaning: '引っ越し日', context: '予定', register: 'neutral' },
        { phrase: 'move out', meaning: '退去する', context: '今の家を出る', register: 'neutral' },
        { phrase: 'move in', meaning: '入居する', context: '新しい家に入る', register: 'neutral' },
        { phrase: 'keys', meaning: '鍵', context: '新居の受け取り', register: 'neutral' },
        { phrase: 'pack', meaning: '荷造りする', context: '箱に詰める', register: 'neutral' },
        { phrase: 'unpack', meaning: '荷解きをする', context: '箱から出す', register: 'neutral' },
        { phrase: 'boxes', meaning: '箱・段ボール箱', context: '荷物を入れるもの', register: 'neutral' },
        { phrase: 'load', meaning: '積み込む', context: '車両へ載せる', register: 'neutral' },
        { phrase: 'removal van', meaning: '引っ越し用のトラック・大型バン', context: '車両', register: 'neutral' },
        { phrase: 'moving company', meaning: '引っ越し業者', context: 'サービス', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'move house', meaning: '引っ越しをする', note: 'イギリス英語でよく使うフレーズです。' },
        { phrase: 'by the weekend', meaning: '週末までに', note: '退去などの締め切りを伝えます。' },
        { phrase: 'removals', meaning: '引っ越し業・引っ越し作業', note: 'イギリス英語で removal van と関連します。' },
        { phrase: 'removal van', meaning: '引っ越しトラック', note: 'アメリカ英語では moving truck が一般的です。' },
      ],
    },
    dialogues: [
      {
        id: 'packing',
        label: 'Pattern A · Packing up',
        title: '箱を集めて荷造りする',
        lines: [
          { speaker: 'A', en: "I'm moving house! Do you have any spare boxes?", ja: '引っ越しをするんだ！予備の箱は何かある？' },
          { speaker: 'B', en: 'There are lots in the back. Help yourself!', ja: '奥にたくさんあるよ。ご自由にどうぞ！' },
          { speaker: 'A', en: 'Is everything packed and ready?', ja: '荷造りは全部終わって準備万端？' },
          { speaker: 'B', en: "Yes, we're done. Let's load the van!", ja: 'うん、終わったよ。バンに荷物を積もう！' },
        ],
      },
      {
        id: 'moving-day',
        label: 'Pattern B · Moving day',
        title: '鍵を受け取り作業を指示する',
        lines: [
          { speaker: 'A', en: "I'm here to pick up the keys to my flat.", ja: 'フラットの鍵を受け取りに来ました。' },
          { speaker: 'B', en: 'Here you are. Hope the move goes well!', ja: 'はい、どうぞ。引っ越しがうまくいくといいですね！' },
          { speaker: 'A', en: 'Where do you want us to start?', ja: 'どこから作業を始めましょうか？' },
          { speaker: 'B', en: 'Can you take the boxes in the kitchen first?', ja: 'キッチンの箱を先に運んでもらえますか？' },
        ],
      },
      {
        id: 'unpacking',
        label: 'Pattern C · Unpacking',
        title: '荷解きを終えて一息つく',
        lines: [
          { speaker: 'A', en: "That's the unpacking done!", ja: 'これで荷解きは終わり！' },
          { speaker: 'B', en: 'Nice work! Now, you sit down and have a cup of tea.', ja: 'お疲れ様！さあ、座ってお茶でも飲んで。' },
          { speaker: 'A', en: 'We can unpack in the morning.', ja: '午前中に荷解きができるよ。' },
          { speaker: 'B', en: 'We are finally moved in!', ja: 'やっと引っ越しが完了して入居できたね！' },
        ],
      },
    ],
    tip: 'イギリス英語では、引っ越しをすることを move house とよく言います。新居に入るのは move in、今の家を出るのは move out です。引っ越し用のトラックは removal van と呼ばれ、アメリカ英語の moving truck にあたります。by the weekend のように by と期限を組み合わせると、退去や準備の締め切りを伝えられます。',
  },
  practice: {
    title: '引っ越しの作業を、英語で分かりやすく進める',
    instructions: '日本語訳は見ずに、荷造り、当日の指示、荷解きの表現を声に重ねます。',
    coreHeading: 'まずは、引っ越しの進み具合を伝える一文から。',
    dialogueHeading: '準備、引っ越し当日、荷解きの場面で役を切り替える。',
    dialogueDescription: '箱を集めて積み込む、鍵を受け取って作業を指示する、荷解きを終えて休む3つの場面を練習します。',
    finishTitle: '次に引っ越しの準備をするとき、作業の進み具合をひとつ英語で伝えてみましょう。',
    corePhrases: [
      { phrase: "I'm moving house! Do you have any spare boxes?", context: '箱を頼む', rate: 0.74 },
      { phrase: 'There are lots in the back. Help yourself!', context: '箱をすすめる', rate: 0.8 },
      { phrase: 'Is everything packed and ready?', context: '準備を確認する', rate: 0.82 },
      { phrase: "Yes, we're done. Let's load the van!", context: '積み込みを始める', rate: 0.78 },
      { phrase: "Let's load the removal van!", context: '引っ越しトラックに積む', rate: 0.78 },
      { phrase: "I've told everyone our moving date.", context: '予定を共有する', rate: 0.78 },
      { phrase: "I'm here to pick up the keys to my flat.", context: '鍵を受け取る', rate: 0.74 },
      { phrase: 'Where do you want us to start?', context: '作業の順番を尋ねる', rate: 0.78 },
      { phrase: 'Can you take the boxes in the kitchen first?', context: '運ぶ場所を指示する', rate: 0.74 },
      { phrase: "That's the unpacking done!", context: '作業の完了を伝える', rate: 0.82 },
      { phrase: 'Nice work! Now, you sit down and have a cup of tea.', context: '相手をねぎらう', rate: 0.74 },
      { phrase: 'We have to move out by the weekend.', context: '退去期限を伝える', rate: 0.78 },
      { phrase: 'We are finally moved in!', context: '入居を喜ぶ', rate: 0.8 },
    ],
    dialogues: [
      { title: 'Packing up', lines: ["I'm moving house! Do you have any spare boxes?", 'There are lots in the back. Help yourself!', 'Is everything packed and ready?', "Yes, we're done. Let's load the van!"] },
      { title: 'Moving day', lines: ["I'm here to pick up the keys to my flat.", 'Here you are. Hope the move goes well!', 'Where do you want us to start?', 'Can you take the boxes in the kitchen first?'] },
      { title: 'Unpacking', lines: ["That's the unpacking done!", 'Nice work! Now, you sit down and have a cup of tea.', 'We can unpack in the morning.', 'We are finally moved in!'] },
    ],
    natural: [
      { full: 'I am changing my house.', natural: "I'm moving house!" },
      { full: 'Please begin with the boxes from the kitchen.', natural: 'Can you take the boxes in the kitchen first?' },
      { full: 'We have completed unpacking everything.', natural: "That's the unpacking done!" },
    ],
  },
}
