/** Chapter 55 · Online meetings. */
export const onlineMeetingsLesson = {
  id: 'online-meetings',
  kind: 'online-meetings',
  number: '55',
  title: '第55章に入る前に：なぜ「オンライン会議で使う英語」を学ぶのでしょうか？',
  enTitle: 'Online meetings',
  ja: 'オンライン会議の始め方、接続トラブルへの対応、次回の予定調整を学びます。',
  cando: '音声や画面の状態を確認し、接続トラブルに対応しながら会議を進められる。',
  learn: {
    intro: [
      'オンライン会議は、対面の会議とよく似ていますが、同時にテクノロジーにも対応する必要があります。',
      '音声が聞こえているか確認したり、画面を共有したり、接続トラブルに対応したりしながら、全員が話についてこられるようにすることが大切です。',
      '大切なのは、何を話すかだけではありません。技術的な問題があっても、コミュニケーションを分かりやすく保つことです。',
      'この章では、オンライン会議の始め方、接続トラブルへの対応、そして次回の会議を調整する表現を学びます。',
    ],
    functions: [
      ['01', '会議を立ち上げる'],
      ['02', '音声と画面を確認する'],
      ['03', '接続トラブルに対応する'],
      ['04', '次回の予定を調整する'],
    ],
    start: {
      title: 'オンライン会議を始める',
      enTitle: 'Getting started',
      intro: '挨拶、画面共有、音声確認、参加者の確認をして、会議をスムーズに立ち上げます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: "Let's get going, shall we?", meaning: '始めましょうか？', context: '会議を始める', register: 'casual' },
        { phrase: "I'll share the presentation on my screen.", meaning: '私の画面でプレゼンテーションを共有しますね。', context: '画面を共有する', register: 'neutral' },
        { phrase: 'Can you hear me?', meaning: '私の声が聞こえますか？', context: '音声を確認する', register: 'neutral' },
        { phrase: "I think you're on mute.", meaning: 'マイクがミュートになっているようです。', context: 'ミュートを知らせる', register: 'casual' },
        { phrase: "That's everyone now.", meaning: 'これで全員揃いましたね。', context: '参加者を確認する', register: 'neutral' },
        { phrase: "Right, I'll run through the key points.", meaning: 'では、要点をざっと説明しますね。', context: '要点を説明する', register: 'neutral' },
        { phrase: 'Would you like to speak first?', meaning: '最初に発言しますか？', context: '発言を促す', register: 'polite' },
        { phrase: 'Could you repeat that, please?', meaning: 'もう一度言っていただけますか？', context: '聞き返す', register: 'polite' },
        { phrase: 'Can you enlarge it on your screen?', meaning: '画面を拡大していただけますか？', context: '表示を見やすくする', register: 'polite' },
        { phrase: 'Sorry for interrupting, please carry on.', meaning: '遮ってしまってすみません、続けてください。', context: '割り込み後に促す', register: 'polite' },
      ],
      recognition: [
        { phrase: 'on mute', meaning: 'ミュートになって', note: 'オンライン会議で頻繁に使う定番表現です。' },
        { phrase: 'share my screen', meaning: '画面共有する', note: '資料を参加者に見せるときに使います。' },
        { phrase: 'run through', meaning: 'ざっと説明する・おさらいする', note: '要点を短く確認するときの句動詞です。' },
      ],
    },
    connection: {
      title: '接続トラブルへ対応する',
      enTitle: 'Connection problems',
      intro: '音声が途切れる、画面が固まる、参加者が切断されるなどの状態を短く伝えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "I think we've lost Sam.", meaning: 'サムさんの接続が切れてしまったようです。', context: '参加者の接続切れを知らせる', register: 'neutral' },
        { phrase: 'My connection keeps dropping out.', meaning: '接続が途切れがちです。', context: '自分の接続不良を伝える', register: 'neutral' },
        { phrase: "Sorry everyone, my Wi-Fi's slow.", meaning: '皆さんすみません、Wi-Fiの速度が遅いです。', context: '通信速度を伝える', register: 'casual' },
        { phrase: 'Sorry, my screen has frozen.', meaning: 'すみません、画面が固まってしまいました。', context: '画面フリーズを伝える', register: 'polite' },
        { phrase: "We can hear you, but we can't see you.", meaning: '声は聞こえますが、映像が見えません。', context: '音声と映像の状態を伝える', register: 'neutral' },
        { phrase: 'Try leaving the meeting and joining again.', meaning: '一度退室して、もう一度入り直してみてください。', context: '再接続を提案する', register: 'neutral' },
        { phrase: "You're dropping out.", meaning: '声が途切れています。', context: '相手の音声を知らせる', register: 'casual' },
      ],
      recognition: [
        { phrase: 'drop out', meaning: '接続が途切れる', note: 'keep dropping out で何度も途切れる状態です。' },
        { phrase: 'lose someone', meaning: '相手の接続が切れる', note: '通話中に聞こえなくなることを表します。' },
        { phrase: 'frozen', meaning: '画面が固まった', note: '動かなくなった画面やアプリに使います。' },
      ],
    },
    next: {
      title: '次回のミーティングを調整する',
      enTitle: 'The next meeting',
      intro: '会議の最後に、次回の予定を組み、招待やリンクを送る役割を確認します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Shall we put in another meeting?', meaning: 'もう一度ミーティングの予定を入れましょうか？', context: '次回を提案する', register: 'neutral' },
        { phrase: "Good idea. I'll send you an invite.", meaning: 'いいですね。招待（リンク）を送ります。', context: '招待を送る', register: 'neutral' },
        { phrase: "Let's put a follow-up in the calendar for next Tuesday.", meaning: '次の火曜日にフォローアップをカレンダーに入れましょう。', context: '日時を決める', register: 'neutral' },
        { phrase: 'Does that time work for everyone?', meaning: 'その時間は皆さん都合がよいですか？', context: '参加者の都合を確認する', register: 'polite' },
      ],
      recognition: [
        { phrase: 'put in a meeting', meaning: '会議の予定を組む', note: 'カレンダーに予定を差し込むイメージです。' },
        { phrase: 'invite', meaning: '招待・会議リンク', note: 'オンライン会議の招待メールやリンクを指します。' },
        { phrase: 'follow-up', meaning: 'フォローアップ', note: '次回の確認や続きの会議を表します。' },
      ],
    },
    vocabulary: {
      title: 'オンライン会議のボキャブラリー',
      enTitle: 'Vocabulary · Online meetings',
      intro: '音声、映像、接続、画面共有、予定調整に関する基本語彙を整理します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'mute', meaning: 'ミュート・消音', context: 'マイクの状態', register: 'neutral' },
        { phrase: 'screen share', meaning: '画面共有', context: '資料を見せる機能', register: 'neutral' },
        { phrase: 'connection', meaning: '接続', context: '通信の状態', register: 'neutral' },
        { phrase: 'Wi-Fi', meaning: 'Wi-Fi・無線通信', context: 'ネットワーク', register: 'neutral' },
        { phrase: 'frozen', meaning: '固まった・フリーズした', context: '画面やアプリの状態', register: 'neutral' },
        { phrase: 'drop out', meaning: '途切れる', context: '音声や接続', register: 'neutral' },
        { phrase: 'rejoin', meaning: '入り直す', context: '会議へ再接続', register: 'neutral' },
        { phrase: 'invite', meaning: '招待・会議リンク', context: '次回会議の案内', register: 'neutral' },
        { phrase: 'key points', meaning: '要点', context: '会議の中心内容', register: 'neutral' },
        { phrase: 'run through', meaning: 'ざっと説明する', context: '要点を確認する', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'on mute', meaning: 'ミュート中', note: 'I think you\'re on mute. の一部です。' },
        { phrase: 'drop out', meaning: '途切れる', note: '通信や音声が不安定なときに使います。' },
        { phrase: 'put in', meaning: '予定を入れる', note: 'カレンダーに会議を組む表現です。' },
      ],
    },
    dialogues: [
      {
        id: 'start',
        label: 'Pattern A · Getting started',
        title: '音声と参加者を確認して始める',
        lines: [
          { speaker: 'A', en: "Let's get going, shall we?", ja: '始めましょうか？' },
          { speaker: 'B', en: 'Can you hear me?', ja: '私の声が聞こえますか？' },
          { speaker: 'A', en: "I think you're on mute.", ja: 'マイクがミュートになっているようです。' },
          { speaker: 'B', en: "That's everyone now. Right, I'll run through the key points.", ja: 'これで全員揃いましたね。では、要点をざっと説明します。' },
        ],
      },
      {
        id: 'connection',
        label: 'Pattern B · Connection problems',
        title: '接続不良を伝えて再接続する',
        lines: [
          { speaker: 'A', en: "I think we've lost Sam.", ja: 'サムさんの接続が切れたようです。' },
          { speaker: 'B', en: 'My connection keeps dropping out.', ja: '接続が途切れがちです。' },
          { speaker: 'A', en: "We can hear you, but we can't see you.", ja: '声は聞こえますが、映像が見えません。' },
          { speaker: 'B', en: 'Try leaving the meeting and joining again.', ja: '一度退室して、もう一度入り直してみてください。' },
        ],
      },
      {
        id: 'next',
        label: 'Pattern C · The next meeting',
        title: '次回の予定を決める',
        lines: [
          { speaker: 'A', en: 'Shall we put in another meeting?', ja: 'もう一度ミーティングの予定を入れましょうか？' },
          { speaker: 'B', en: "Good idea. I'll send you an invite.", ja: 'いいですね。招待を送ります。' },
          { speaker: 'A', en: "Let's put a follow-up in the calendar for next Tuesday.", ja: '次の火曜日にフォローアップをカレンダーに入れましょう。' },
          { speaker: 'B', en: 'Does that time work for everyone?', ja: 'その時間は皆さん都合がよいですか？' },
        ],
      },
    ],
    tip: 'オンライン会議では、I think you\'re on mute.、You\'re dropping out.、My screen has frozen. のように、技術的な状態を短く伝えることが大切です。drop out は声や接続が途切れること、lose someone は通話中に相手が聞こえなくなることを表します。次回の予定は put in a meeting で組み、招待やリンクを send an invite で共有します。',
  },
  practice: {
    title: 'オンライン会議を、英語で止めずに進める',
    instructions: '日本語訳は見ずに、開始、音声確認、接続トラブル、次回予定の表現を声に重ねます。',
    coreHeading: 'まずは、オンライン会議を立ち上げる一文から。',
    dialogueHeading: '開始、接続トラブル、次回調整で役を切り替える。',
    dialogueDescription: '音声と参加者を確認して始める、接続不良に対応する、次回の予定を組む3つの場面を練習します。',
    finishTitle: '次のオンライン会議で、技術的な問題をひとつ英語で分かりやすく伝えてみましょう。',
    corePhrases: [
      { phrase: "Let's get going, shall we?", context: '会議を始める', rate: 0.82 },
      { phrase: "I'll share the presentation on my screen.", context: '画面を共有する', rate: 0.76 },
      { phrase: 'Can you hear me?', context: '音声を確認する', rate: 0.84 },
      { phrase: "I think you're on mute.", context: 'ミュートを知らせる', rate: 0.82 },
      { phrase: "That's everyone now.", context: '参加者を確認する', rate: 0.84 },
      { phrase: "Right, I'll run through the key points.", context: '要点を説明する', rate: 0.76 },
      { phrase: "I think we've lost Sam.", context: '接続切れを知らせる', rate: 0.78 },
      { phrase: 'My connection keeps dropping out.', context: '接続不良を伝える', rate: 0.74 },
      { phrase: "Sorry everyone, my Wi-Fi's slow.", context: 'Wi-Fiの遅さを伝える', rate: 0.76 },
      { phrase: 'Sorry, my screen has frozen.', context: '画面フリーズを伝える', rate: 0.78 },
      { phrase: "We can hear you, but we can't see you.", context: '映像の不具合を伝える', rate: 0.74 },
      { phrase: 'Try leaving the meeting and joining again.', context: '再接続を提案する', rate: 0.72 },
      { phrase: 'Shall we put in another meeting?', context: '次回を提案する', rate: 0.8 },
      { phrase: "Good idea. I'll send you an invite.", context: '招待を送る', rate: 0.8 },
    ],
    dialogues: [
      { title: 'Getting started', lines: ["Let's get going, shall we?", 'Can you hear me?', "I think you're on mute.", "That's everyone now. Right, I'll run through the key points."] },
      { title: 'Connection problems', lines: ["I think we've lost Sam.", 'My connection keeps dropping out.', "We can hear you, but we can't see you.", 'Try leaving the meeting and joining again.'] },
      { title: 'The next meeting', lines: ['Shall we put in another meeting?', "Good idea. I'll send you an invite.", "Let's put a follow-up in the calendar for next Tuesday.", 'Does that time work for everyone?'] },
    ],
    natural: [
      { full: 'Your microphone is turned off.', natural: "I think you're on mute." },
      { full: 'The internet connection keeps disconnecting.', natural: 'My connection keeps dropping out.' },
      { full: 'Leave the call and enter it again.', natural: 'Try leaving the meeting and joining again.' },
    ],
  },
}
