/** Chapter 62 · Pets. */
export const petsLesson = {
  id: 'pets',
  kind: 'pets',
  number: '62',
  title: '第62章に入る前に：なぜ「ペットに関する英語」を学ぶのでしょうか？',
  enTitle: 'Pets',
  ja: 'ペットを迎える会話、体調や症状の伝え方、日常のケアについて話す英語を学びます。',
  cando: 'ペットの性格や生活環境、症状、必要なケアを正確に説明できる。',
  learn: {
    intro: [
      'ペットと暮らすということは、かわいがるだけでなく、健康や安全について責任を持つことでもあります。',
      '体調の変化に気づいたり、必要なケアをしたり、場合によっては動物病院で状況を説明したりする必要があります。',
      'この章では、ペットを迎えるときの会話、体調や症状の伝え方、そして日常のケアに関する表現を学びます。',
    ],
    functions: [
      ['01', 'ペットを迎える希望を伝える'],
      ['02', '家庭環境との相性を尋ねる'],
      ['03', '症状を具体的に説明する'],
      ['04', 'ケアと手続きを確認する'],
    ],
    adopting: {
      title: '保護動物の引き取り',
      enTitle: 'Adopting a rescue animal',
      intro: 'シェルターのスタッフに、迎えたい動物や家庭環境との相性を尋ねます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "Hi, I'd like to adopt a cat.", meaning: 'こんにちは、猫を引き取りたいのですが。', context: '里親になりたいと伝える', register: 'polite' },
        { phrase: "I'm looking to home one of your dogs.", meaning: 'そちらの犬の1匹を家族に迎えたいと思っています。', context: '保護犬を迎える希望を伝える', register: 'neutral' },
        { phrase: 'Does she like other cats?', meaning: 'この子は他の猫と仲良くできますか？', context: '他の動物との相性を尋ねる', register: 'casual' },
        { phrase: 'Is she good with children?', meaning: 'この子は子どもと仲良くできますか？', context: '子どもとの相性を尋ねる', register: 'neutral' },
        { phrase: 'Is anyone home during the day?', meaning: '日中、誰か家にいますか？', context: '留守番環境を確認する', register: 'neutral' },
        { phrase: 'Yes, I work from home.', meaning: 'はい、在宅ワークをしています。', context: '家庭環境を説明する', register: 'neutral' },
        { phrase: 'Are you after a particular breed?', meaning: '特定の犬種をお探しですか？', context: '希望の種類を尋ねる', register: 'casual' },
      ],
      recognition: [
        { phrase: 'rescue animal', meaning: '保護動物', note: 'シェルターなどから迎える動物です。' },
        { phrase: 'home a dog', meaning: '犬を家族に迎える', note: '保護動物の新しい家を見つける表現です。' },
        { phrase: 'good with children', meaning: '子どもに対しておとなしい・相性がよい', note: '動物と人の相性を尋ねる定番表現です。' },
        { phrase: 'be after', meaning: '探している・求めている', note: 'particular breed などと使います。' },
      ],
    },
    vet: {
      title: '動物病院での診察',
      enTitle: 'Seeing the vet',
      intro: '動物病院で、体重、食欲、けが、繰り返す症状などを具体的に伝えます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'What seems to be the problem?', meaning: 'どうされましたか？', context: '獣医師が症状を尋ねる', register: 'polite' },
        { phrase: "She's lost weight and gone off her food.", meaning: '体重が減って、餌を食べないんです。', context: '体重と食欲の変化を伝える', register: 'neutral' },
        { phrase: "I think he's got a broken leg.", meaning: '足を骨折しているのだと思います。', context: 'けがの可能性を伝える', register: 'neutral' },
        { phrase: "Yes, we'll need to do an X-ray.", meaning: 'そうですね、レントゲンを撮る必要があります。', context: '検査の必要を説明する', register: 'neutral' },
        { phrase: 'My dog has hurt his paw.', meaning: 'うちの犬が肉球・足先を怪我しました。', context: 'けがの場所を伝える', register: 'neutral' },
        { phrase: 'My cat keeps being sick.', meaning: 'うちの猫が何度も吐いてしまいます。', context: '繰り返す症状を伝える', register: 'neutral' },
        { phrase: 'My rabbit is losing her fur.', meaning: 'うちのウサギの毛が抜けてきています。', context: '毛の変化を伝える', register: 'neutral' },
        { phrase: 'My puppy is very quiet.', meaning: 'うちの子犬はとても静かで、いつもより元気がありません。', context: '元気がない様子を伝える', register: 'neutral' },
        { phrase: "She's always thirsty.", meaning: 'この子はいつも喉を渇かしています。', context: '水を飲む量の変化を伝える', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'go off her food', meaning: '餌を食べなくなる', note: '食欲がなくなったことを表す口語です。' },
        { phrase: 'be sick', meaning: '吐く・体調が悪い', note: 'vomit より日常的な言い方です。' },
        { phrase: 'keeps being sick', meaning: '何度も吐く', note: 'keep + -ing で繰り返しを伝えます。' },
        { phrase: 'paw', meaning: '肉球のある足先', note: '犬や猫の足先を指します。' },
      ],
    },
    care: {
      title: 'ペットのお世話とヘルスケア',
      enTitle: 'Pet care & looking after your pet',
      intro: '予防接種やノミ駆除、マイクロチップ、海外移動に必要な手続きを確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'vaccination', meaning: '予防接種', context: '健康管理', register: 'neutral' },
        { phrase: 'flea treatment', meaning: 'ノミ駆除・ノミ駆除薬', context: '健康管理', register: 'neutral' },
        { phrase: 'eye drops', meaning: '目薬', context: 'ケア用品', register: 'neutral' },
        { phrase: 'grooming', meaning: 'グルーミング・トリミング', context: '身だしなみ', register: 'neutral' },
        { phrase: 'microchip', meaning: 'マイクロチップ', context: '身元確認', register: 'neutral' },
        { phrase: 'pet passport', meaning: 'ペット用パスポート', context: '海外移動', register: 'neutral' },
        { phrase: 'So, we have to get him microchipped...', meaning: 'それで、この子にマイクロチップを装着しなければなりません。', context: '手続きを確認する', register: 'neutral' },
        { phrase: '...give him his flea treatment...', meaning: 'ノミ駆除薬を与えて……', context: 'ケアの手順を続ける', register: 'neutral' },
        { phrase: '...get him a passport...', meaning: 'パスポートを取得して……', context: '渡航準備を続ける', register: 'neutral' },
        { phrase: '...and book his vaccinations!', meaning: 'それから予防接種の予約をしなければなりません！', context: '最後の手続きを伝える', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'get him microchipped', meaning: 'マイクロチップを装着してもらう', note: 'get + object + past participle の依頼・手配です。' },
        { phrase: 'flea treatment', meaning: 'ノミ駆除薬', note: '定期的な予防ケアに使います。' },
        { phrase: 'book vaccinations', meaning: '予防接種を予約する', note: '動物病院の予約に使います。' },
        { phrase: 'pet passport', meaning: 'ペット用パスポート', note: '海外へ移動するときの書類です。' },
      ],
    },
    vocabulary: {
      title: 'ペットとケアのボキャブラリー',
      enTitle: 'Vocabulary · Pets & healthcare',
      intro: '動物の状態、症状、日常のケアを表す言葉を会話と一緒に覚えます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'vet', meaning: '獣医・獣医師', context: '動物病院', register: 'neutral' },
        { phrase: 'broken leg', meaning: '骨折した足', context: 'けが', register: 'neutral' },
        { phrase: 'lost weight', meaning: '体重が減った', context: '症状', register: 'neutral' },
        { phrase: 'go off food', meaning: '餌を食べなくなる', context: '食欲', register: 'neutral' },
        { phrase: 'be sick', meaning: '吐く・体調が悪い', context: '症状', register: 'neutral' },
        { phrase: 'lose fur', meaning: '毛が抜ける', context: '症状', register: 'neutral' },
        { phrase: 'thirsty', meaning: '喉が渇いている', context: '症状', register: 'neutral' },
        { phrase: 'work from home', meaning: '在宅勤務をする', context: '家庭環境', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'he / she', meaning: 'ペットを指す人称代名詞', note: '家族の一員として it ではなく he / she を使います。' },
        { phrase: 'X-ray', meaning: 'レントゲン', note: '検査を表す日常語です。' },
        { phrase: 'grooming', meaning: 'グルーミング・トリミング', note: '毛や爪などの手入れです。' },
        { phrase: 'microchip', meaning: 'マイクロチップ', note: 'ペットの身元確認に使います。' },
      ],
    },
    dialogues: [
      {
        id: 'adopting',
        label: 'Pattern A · Adopting a rescue animal',
        title: '保護動物との相性を尋ねる',
        lines: [
          { speaker: 'A', en: "Hi, I'd like to adopt a cat.", ja: 'こんにちは、猫を引き取りたいのですが。' },
          { speaker: 'B', en: 'Does she like other cats?', ja: 'この子は他の猫と仲良くできますか？' },
          { speaker: 'A', en: 'Is she good with children?', ja: 'この子は子どもと仲良くできますか？' },
          { speaker: 'B', en: 'Yes, and she would suit a family who works from home.', ja: 'はい、在宅勤務の家族にも合うと思います。' },
        ],
      },
      {
        id: 'vet',
        label: 'Pattern B · Seeing the vet',
        title: '症状を獣医師に説明する',
        lines: [
          { speaker: 'A', en: 'What seems to be the problem?', ja: 'どうされましたか？' },
          { speaker: 'B', en: "She's lost weight and gone off her food.", ja: '体重が減って、餌を食べないんです。' },
          { speaker: 'A', en: 'My cat keeps being sick.', ja: 'うちの猫が何度も吐いてしまいます。' },
          { speaker: 'B', en: "We'll need to do an X-ray.", ja: 'レントゲンを撮る必要があります。' },
        ],
      },
      {
        id: 'care',
        label: 'Pattern C · Pet care',
        title: 'ケアと渡航手続きを確認する',
        lines: [
          { speaker: 'A', en: 'So, we have to get him microchipped...', ja: 'それで、この子にマイクロチップを装着しなければなりません。' },
          { speaker: 'B', en: '...give him his flea treatment...', ja: 'ノミ駆除薬を与えて……' },
          { speaker: 'A', en: '...get him a passport...', ja: 'パスポートを取得して……' },
          { speaker: 'B', en: '...and book his vaccinations!', ja: 'それから予防接種の予約をしなければなりません！' },
        ],
      },
    ],
    tip: '自分のペットや性別が分かっている動物は he / she と呼ぶのが温かい自然な英語です。be sick は日常の「吐く」、keeps being sick は「何度も吐く」を表します。go off one\'s food は餌を食べなくなること、be after は何かを探していることです。',
  },
  practice: {
    title: 'ペットの状態とケアを、英語で正確に伝える',
    instructions: '日本語訳は見ずに、動物を迎える会話、症状説明、ケアの手続きを声に重ねます。',
    coreHeading: 'まずは、ペットの様子を伝える一文から。',
    dialogueHeading: '里親相談、動物病院、日常ケアの場面で役を切り替える。',
    dialogueDescription: '相性を尋ねる、症状を説明する、必要なケアを確認する3つの場面を練習します。',
    finishTitle: '次にペットの様子を説明するとき、症状かケアの表現をひとつ使ってみましょう。',
    corePhrases: [
      { phrase: "Hi, I'd like to adopt a cat.", context: '里親になりたいと伝える', rate: 0.82 },
      { phrase: "I'm looking to home one of your dogs.", context: '保護犬を迎える希望を伝える', rate: 0.78 },
      { phrase: 'Does she like other cats?', context: '相性を尋ねる', rate: 0.84 },
      { phrase: 'Is she good with children?', context: '子どもとの相性を尋ねる', rate: 0.84 },
      { phrase: "She's lost weight and gone off her food.", context: '体重と食欲の変化を伝える', rate: 0.76 },
      { phrase: "I think he's got a broken leg.", context: 'けがの可能性を伝える', rate: 0.8 },
      { phrase: 'My dog has hurt his paw.', context: 'けがの場所を伝える', rate: 0.8 },
      { phrase: 'My cat keeps being sick.', context: '繰り返す症状を伝える', rate: 0.8 },
      { phrase: 'My puppy is very quiet.', context: '元気がない様子を伝える', rate: 0.82 },
      { phrase: 'So, we have to get him microchipped...', context: '手続きを確認する', rate: 0.76 },
      { phrase: '...give him his flea treatment...', context: 'ケアの手順を続ける', rate: 0.76 },
      { phrase: '...and book his vaccinations!', context: '予防接種を予約する', rate: 0.78 },
    ],
    dialogues: [
      { title: 'Adopting a rescue animal', lines: ["Hi, I'd like to adopt a cat.", 'Does she like other cats?', 'Is she good with children?', 'Yes, and she would suit a family who works from home.'] },
      { title: 'Seeing the vet', lines: ['What seems to be the problem?', "She's lost weight and gone off her food.", 'My cat keeps being sick.', "We'll need to do an X-ray."] },
      { title: 'Pet care', lines: ['So, we have to get him microchipped...', '...give him his flea treatment...', '...get him a passport...', '...and book his vaccinations!'] },
    ],
    natural: [
      { full: 'My cat has repeatedly vomited.', natural: 'My cat keeps being sick.' },
      { full: 'She has stopped being interested in her food.', natural: "She's gone off her food." },
      { full: 'Is this animal comfortable around children?', natural: 'Is she good with children?' },
    ],
  },
}
