/** Chapter 81 · At the pharmacy. */
export const pharmacyLesson = {
  id: 'pharmacy',
  kind: 'pharmacy',
  number: '81',
  title: '第81章に入る前に：なぜ「薬局で使う英語」を学ぶのでしょうか？',
  enTitle: 'At the pharmacy',
  ja: '処方箋、症状、市販薬、服用方法について相談する表現を学びます。',
  cando: '処方箋を受け取り、症状やアレルギーを説明し、薬の飲み方を確認できる。',
  learn: {
    intro: [
      '薬局では、薬を受け取るだけでなく、自分の症状やアレルギー、服用している薬について伝えたり、飲み方や副作用を確認したりすることがあります。',
      '自分の体の状態と薬に関する情報を正確に伝え、分からないことをきちんと確認することが大切です。',
      'この章では、処方箋の受け取り、症状の相談、市販薬の購入、そして薬の使い方についての基本的な表現を学びます。',
    ],
    functions: [
      ['01', '処方箋と服用中の薬を伝える'],
      ['02', '症状を説明して市販薬を相談する'],
      ['03', '飲み方・副作用・併用を確認する'],
    ],
    prescription: {
      title: '処方箋の受け取りと薬の相談',
      enTitle: 'Picking up a prescription',
      intro: '処方箋を渡し、アレルギーや他の薬、飲み方について薬剤師と確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'I have a prescription to get filled, please.', meaning: '処方箋の調剤をお願いしたいのですが。', context: '処方箋を提出する', register: 'polite' },
        { phrase: 'Do you have any allergies?', meaning: 'アレルギーはありますか？', context: 'アレルギーを確認する', register: 'polite' },
        { phrase: 'Are you taking any other medication?', meaning: '何か他の薬を服用していますか？', context: '服用中の薬を確認する', register: 'polite' },
        { phrase: 'Are there any side effects?', meaning: '副作用はありますか？', context: '副作用を尋ねる', register: 'polite' },
        { phrase: "I'm here to pick up a prescription.", meaning: '処方箋の薬を受け取りに来ました。', context: '薬を受け取りに来たと伝える', register: 'polite' },
        { phrase: 'How often should I take it?', meaning: 'どのくらいの頻度で服用すればよいですか？', context: '服用頻度を確認する', register: 'polite' },
        { phrase: 'Should I take it before or after meals?', meaning: '食前と食後のどちらに服用すればよいですか？', context: '食事とのタイミングを確認する', register: 'polite' },
        { phrase: 'Is it safe to take with painkillers?', meaning: '痛み止めと一緒に服用しても大丈夫ですか？', context: '薬の併用を確認する', register: 'urgent' },
      ],
      recognition: [
        { phrase: 'get a prescription filled', meaning: '処方箋を調剤してもらう', note: '処方箋を薬にしてもらうときの表現です。' },
        { phrase: 'pick up a prescription', meaning: '処方箋の薬を受け取る', note: '薬局へ受け取りに来たことを伝えます。' },
        { phrase: 'medication', meaning: '薬・薬剤', note: '服用している薬全般を表します。' },
        { phrase: 'side effects', meaning: '副作用', note: '薬で起こる望ましくない反応です。' },
        { phrase: 'before or after meals', meaning: '食前または食後', note: '服用するタイミングを確認します。' },
      ],
    },
    symptoms: {
      title: '症状の相談と市販薬の購入',
      enTitle: 'Symptoms and over-the-counter medicine',
      intro: '湿疹、かゆみ、のどの痛みなどを伝え、自分に合う市販薬を相談します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'I have an itchy rash on my arm.', meaning: '腕にかゆい湿疹（発疹）が出ているんです。', context: '症状と場所を伝える', register: 'polite' },
        { phrase: 'I have a really sore throat.', meaning: 'のどが本当にヒリヒリ痛むんです。', context: 'のどの痛みを伝える', register: 'polite' },
        { phrase: 'How long have you had symptoms?', meaning: 'その症状はどのくらい続いていますか？', context: '症状の期間を尋ねる', register: 'polite' },
        { phrase: 'Do you have any other symptoms?', meaning: '他に何か症状はありますか？', context: '他の症状を確認する', register: 'polite' },
        { phrase: 'This cough syrup should do the trick.', meaning: 'この咳止めシロップが効くはずですよ。', context: '薬を提案する', register: 'helpful' },
      ],
      recognition: [
        { phrase: 'itchy rash', meaning: 'かゆい発疹', note: '症状の種類と感覚を一緒に伝えます。' },
        { phrase: 'sore throat', meaning: '痛い・ヒリヒリするのど', note: '炎症や疲労による表面的な痛みを表します。' },
        { phrase: 'How long have you had ...?', meaning: 'どのくらい〜が続いていますか？', note: '症状が始まった時期を尋ねます。' },
        { phrase: 'over-the-counter medicine', meaning: '市販薬', note: '処方箋なしで買える薬です。' },
        { phrase: 'do the trick', meaning: '効く・うまくいく', note: '目的を果たして効果があるという口語表現です。' },
      ],
    },
    vocabulary: {
      title: '薬局で役立つボキャブラリー',
      enTitle: 'Pharmacy vocabulary',
      intro: '薬局や薬の説明でよく見かける基本語を整理します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'pharmacist', meaning: '薬剤師', context: '薬について相談する相手', register: 'neutral' },
        { phrase: 'prescription', meaning: '処方箋', context: '医師から出される薬の指示書', register: 'neutral' },
        { phrase: 'medication', meaning: '薬・薬剤', context: '服用する薬全般', register: 'neutral' },
        { phrase: 'cough syrup', meaning: '咳止めシロップ', context: '咳のための液体の薬', register: 'neutral' },
        { phrase: 'side effects', meaning: '副作用', context: '薬による望ましくない反応', register: 'neutral' },
        { phrase: 'antiseptic', meaning: '消毒薬・殺菌剤', context: '傷などに使う薬', register: 'neutral' },
        { phrase: 'vitamins', meaning: 'ビタミン剤', context: 'ビタミンの補給に使うもの', register: 'neutral' },
        { phrase: 'sunscreen', meaning: '日焼け止め', context: '紫外線から肌を守るもの', register: 'neutral' },
      ],
      recognition: [
        { phrase: "chemist's", meaning: '薬局（イギリス英語）', note: 'イギリスでは薬局を chemist\'s と呼ぶことがあります。' },
        { phrase: 'pharmacy / drugstore', meaning: '薬局（アメリカ英語）', note: 'pharmacyやdrugstoreが一般的です。' },
        { phrase: 'over-the-counter', meaning: '処方箋なしで買える', note: '市販薬を表す重要な語です。' },
      ],
    },
    dialogues: [
      {
        id: 'prescription',
        label: 'Pattern A · Prescription',
        title: '処方箋と服用方法を確認する',
        lines: [
          { speaker: 'A', en: 'I have a prescription to get filled, please.', ja: '処方箋の調剤をお願いしたいのですが。' },
          { speaker: 'B', en: 'Do you have any allergies?', ja: 'アレルギーはありますか？' },
          { speaker: 'A', en: 'Are you taking any other medication?', ja: '何か他の薬を服用していますか？' },
          { speaker: 'B', en: 'Are there any side effects?', ja: '副作用はありますか？' },
        ],
      },
      {
        id: 'symptoms',
        label: 'Pattern B · Symptoms',
        title: '症状を伝えて市販薬を相談する',
        lines: [
          { speaker: 'A', en: 'I have an itchy rash on my arm.', ja: '腕にかゆい湿疹が出ています。' },
          { speaker: 'B', en: 'How long have you had symptoms?', ja: 'その症状はどのくらい続いていますか？' },
          { speaker: 'A', en: 'Do you have any other symptoms?', ja: '他に何か症状はありますか？' },
          { speaker: 'B', en: 'This cough syrup should do the trick.', ja: 'この咳止めシロップが効くはずですよ。' },
        ],
      },
      {
        id: 'medicine-use',
        label: 'Pattern C · Medicine use',
        title: '薬の飲み方と併用を確認する',
        lines: [
          { speaker: 'A', en: "I'm here to pick up a prescription.", ja: '処方箋の薬を受け取りに来ました。' },
          { speaker: 'B', en: 'How often should I take it?', ja: 'どのくらいの頻度で服用すればよいですか？' },
          { speaker: 'A', en: 'Should I take it before or after meals?', ja: '食前と食後のどちらに服用すればよいですか？' },
          { speaker: 'B', en: 'Is it safe to take with painkillers?', ja: '痛み止めと一緒に服用しても大丈夫ですか？' },
        ],
      },
    ],
    tip: '薬局では、症状の場所や期間、アレルギー、服用中の薬を具体的に伝えます。do the trickは「効く」、soreはヒリヒリ・ずきずきする痛みを表します。',
    tips: [
      { title: 'do the trick は「効く」', body: 'This cough syrup should do the trick. の do the trick は、薬や解決策が「効果を発揮する、うまくいく」という便利な口語表現です。' },
      { title: 'sore の痛みのニュアンス', body: 'sore throat の sore は、炎症や疲労などでヒリヒリ、ずきずき、触ると痛い状態を表します。' },
      { title: "chemist's と pharmacy", body: "イギリス英語では薬局を chemist's と呼ぶことがあります。アメリカ英語では pharmacy や drugstore が一般的です。" },
    ],
  },
  practice: {
    title: '薬局で症状と薬の情報を、英語で確認する',
    instructions: '日本語訳は見ずに、処方箋、症状、飲み方、副作用の表現を声に重ねます。',
    coreHeading: 'まずは、症状や薬について尋ねる一文から。',
    dialogueHeading: '処方箋、症状、市販薬の場面で役を切り替える。',
    dialogueDescription: '処方箋を受け取る、症状に合う市販薬を相談する、薬の飲み方や併用を確認する3つの場面を練習します。',
    finishTitle: '次に薬局へ行ったとき、症状か薬の疑問を英語でひとつ確認してみましょう。',
    corePhrases: [
      { phrase: 'I have a prescription to get filled, please.', context: '処方箋を提出する', rate: 0.72 },
      { phrase: "I'm here to pick up a prescription.", context: '薬を受け取りに来たと伝える', rate: 0.8 },
      { phrase: 'Do you have any allergies?', context: 'アレルギーを確認する', rate: 0.82 },
      { phrase: 'Are you taking any other medication?', context: '服用中の薬を確認する', rate: 0.7 },
      { phrase: 'How often should I take it?', context: '服用頻度を確認する', rate: 0.82 },
      { phrase: 'Should I take it before or after meals?', context: '食事とのタイミングを確認する', rate: 0.74 },
      { phrase: 'Is it safe to take with painkillers?', context: '薬の併用を確認する', rate: 0.72 },
      { phrase: 'I have an itchy rash on my arm.', context: '症状と場所を伝える', rate: 0.78 },
      { phrase: 'I have a really sore throat.', context: 'のどの痛みを伝える', rate: 0.82 },
      { phrase: 'How long have you had symptoms?', context: '症状の期間を尋ねる', rate: 0.78 },
      { phrase: 'Do you have any other symptoms?', context: '他の症状を確認する', rate: 0.82 },
      { phrase: 'This cough syrup should do the trick.', context: '薬の効果を伝える', rate: 0.72 },
    ],
    dialogues: [
      { title: 'Prescription', lines: ['I have a prescription to get filled, please.', 'Do you have any allergies?', 'Are you taking any other medication?', 'Are there any side effects?'] },
      { title: 'Symptoms', lines: ['I have an itchy rash on my arm.', 'How long have you had symptoms?', 'Do you have any other symptoms?', 'This cough syrup should do the trick.'] },
      { title: 'Medicine use', lines: ["I'm here to pick up a prescription.", 'How often should I take it?', 'Should I take it before or after meals?', 'Is it safe to take with painkillers?'] },
    ],
    natural: [
      { full: 'I need to collect medication that was prescribed by my doctor.', natural: "I'm here to pick up a prescription." },
      { full: 'How frequently am I supposed to take this medicine?', natural: 'How often should I take it?' },
      { full: 'This cough medicine should be effective.', natural: 'This cough syrup should do the trick.' },
    ],
  },
}
