/** Chapter 53 · Giving a presentation. */
export const presentationLesson = {
  id: 'presentation',
  kind: 'presentation',
  number: '53',
  title: '第53章に入る前に：なぜ「プレゼンテーションで使う英語」を学ぶのでしょうか？',
  enTitle: 'Giving a presentation',
  ja: 'プレゼンテーションの始め方、話題の切り替え方、要約と質問での締め方を学びます。',
  cando: 'プレゼンの流れを示し、聞き手を迷わせずに要点を伝えられる。',
  learn: {
    intro: [
      'プレゼンテーションは、ただ人前で話すことではありません。自分の考えを分かりやすく伝え、聞き手が最初から最後まで話についてこられるようにすることが大切です。',
      '良いプレゼンでは、最初にテーマを示し、話題が変わるときにはそれを伝え、最後には話が終わることをはっきり示します。',
      '大切なのは、難しい英語を使うことではありません。聞き手を迷わせず、自分の考えを分かりやすく案内することです。',
      'この章では、プレゼンテーションの始め方、話題の切り替え方、そして要約や質問で締めくくるための表現を学びます。',
    ],
    functions: [
      ['01', 'テーマを示す'],
      ['02', '発表の焦点を伝える'],
      ['03', '話題を切り替える'],
      ['04', '要約と質問で締める'],
    ],
    start: {
      title: 'プレゼンテーションを始める',
      enTitle: 'Getting started',
      intro: '冒頭でテーマと目的を示し、聞き手に発表の地図を渡します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "Today, I'm going to talk about...", meaning: '今日は、〜についてお話しします。', context: 'テーマを示す', register: 'neutral' },
        { phrase: "You're all here because...", meaning: '皆様にお集まりいただいたのは、〜のためです。', context: '発表の意義を示す', register: 'polite' },
        { phrase: "Firstly, I'd like to begin by saying...", meaning: 'まず初めに、〜ということから始めたいと思います。', context: '丁寧に始める', register: 'polite' },
        { phrase: 'The focus of my presentation is...', meaning: '私のプレゼンテーションの焦点は、〜です。', context: '発表の焦点を伝える', register: 'polite' },
        { phrase: "First I'm going to tell you about...", meaning: '最初に、〜についてお伝えします。', context: '最初の項目を予告する', register: 'neutral' },
        { phrase: 'To kick things off...', meaning: 'まず手始めに／皮切りとして…', context: '勢いよく始める', register: 'casual' },
      ],
      recognition: [
        { phrase: 'focus', meaning: '焦点・テーマ', note: '発表で中心となる内容を指します。' },
        { phrase: 'kick things off', meaning: '始める', note: '少しカジュアルに、発表をスタートする表現です。' },
        { phrase: 'audience', meaning: '聞き手・観客', note: 'プレゼンを聞く人たちをまとめて指します。' },
      ],
    },
    transitions: {
      title: '話題を変える・切り替える',
      enTitle: 'Changing the subject',
      intro: 'スライドやトピックが変わることを言葉で知らせ、聞き手を次の話へ案内します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: "Now let's turn to the subject of...", meaning: 'それでは、〜という話題に移りましょう。', context: '次の話題へ移る', register: 'neutral' },
        { phrase: "Now I'd like to talk about...", meaning: 'それでは、〜についてお話ししたいと思います。', context: '次の項目を紹介する', register: 'polite' },
        { phrase: 'Moving on to...', meaning: '〜に移りまして…', context: '短く話題を転換する', register: 'neutral' },
        { phrase: "The next thing I'd like to bring to your attention is...", meaning: '次に皆様にご注目いただきたいのは、〜です。', context: '重要点を示す', register: 'polite' },
        { phrase: 'This brings me on to...', meaning: 'これで話は〜へとつながります。', context: '前の話からつなぐ', register: 'neutral' },
        { phrase: 'This leads me on to...', meaning: 'ここから〜の話に入ります。', context: '論理的に先へ進む', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'moving on to', meaning: '〜に移る', note: 'プレゼンで最も使いやすい短いサインポストです。' },
        { phrase: 'bring to your attention', meaning: '注目してもらう', note: '聞き手の注意を重要点へ向けます。' },
        { phrase: 'lead me on to', meaning: '〜へ話を導く', note: '話の流れが自然につながることを示します。' },
      ],
    },
    finish: {
      title: 'プレゼンテーションを締めくくる',
      enTitle: 'Finishing up',
      intro: '要点をまとめ、終わりを知らせ、聞き手が質問しやすい場を作ります。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "Lastly, I'd like to finish by saying...", meaning: '最後に、〜と申し上げて締めくくりたいと思います。', context: '最後のメッセージを伝える', register: 'polite' },
        { phrase: "I think I've covered everything. Any questions?", meaning: 'これで一通り説明できたかと思います。何かご質問はありますか？', context: '質疑応答へ移る', register: 'neutral' },
        { phrase: 'Finally, I want to let you know that...', meaning: '最後に、皆様に〜ということをお伝えしておきます。', context: '最後の情報を伝える', register: 'neutral' },
        { phrase: 'Does anyone have anything to add?', meaning: 'どなたか付け加えることはありますか？', context: '追加意見を募る', register: 'polite' },
        { phrase: "So, to sum up, I'd say...", meaning: 'それでは、要約しますと、〜と言えます。', context: '要約して終える', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'to sum up', meaning: '要約すると', note: '発表全体のまとめに入る定番表現です。' },
        { phrase: 'cover everything', meaning: '一通り説明し終える', note: '話すべき内容を扱ったことを示します。' },
        { phrase: 'Q&A', meaning: '質疑応答', note: 'Questions and Answers の略です。' },
      ],
    },
    vocabulary: {
      title: 'プレゼンテーションのボキャブラリー',
      enTitle: 'Vocabulary · Presentations',
      intro: '発表の構成、聞き手、スライド、話題の流れに関する基本語彙を整理します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'presentation', meaning: 'プレゼンテーション・発表', context: '発表全体', register: 'neutral' },
        { phrase: 'audience', meaning: '聞き手・観客', context: '発表を聞く人', register: 'neutral' },
        { phrase: 'focus', meaning: '焦点・中心テーマ', context: '発表の中心', register: 'neutral' },
        { phrase: 'subject', meaning: '話題・テーマ', context: '扱う話題', register: 'neutral' },
        { phrase: 'slide', meaning: 'スライド', context: '画面・資料', register: 'neutral' },
        { phrase: 'signpost', meaning: '道標・流れを示す表現', context: '話題転換の合図', register: 'neutral' },
        { phrase: 'summary', meaning: '要約', context: '最後のまとめ', register: 'neutral' },
        { phrase: 'Q&A', meaning: '質疑応答', context: '質問の時間', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'topic', meaning: '話題', note: 'subject と同じように使えます。' },
        { phrase: 'attention', meaning: '注意・注目', note: 'bring to your attention の一部です。' },
        { phrase: 'lastly', meaning: '最後に', note: '締めくくりのサインポストです。' },
      ],
    },
    dialogues: [
      {
        id: 'opening',
        label: 'Pattern A · Opening',
        title: 'テーマと目的を示して始める',
        lines: [
          { speaker: 'A', en: "Today, I'm going to talk about customer feedback.", ja: '今日は、顧客からのフィードバックについてお話しします。' },
          { speaker: 'A', en: 'The focus of my presentation is our new support plan.', ja: '私のプレゼンテーションの焦点は、新しいサポート計画です。' },
          { speaker: 'A', en: "First I'm going to tell you about the main findings.", ja: '最初に、主な調査結果についてお伝えします。' },
        ],
      },
      {
        id: 'transition',
        label: 'Pattern B · Signposting',
        title: '聞き手を次の話題へ案内する',
        lines: [
          { speaker: 'A', en: 'Moving on to the second point, let’s look at the timeline.', ja: '2つ目のポイントに移り、タイムラインを見てみましょう。' },
          { speaker: 'A', en: "The next thing I'd like to bring to your attention is the budget.", ja: '次にご注目いただきたいのは予算です。' },
          { speaker: 'A', en: 'This leads me on to our next step.', ja: 'ここから次のステップの話に入ります。' },
        ],
      },
      {
        id: 'closing',
        label: 'Pattern C · Closing',
        title: '要約して質問を受ける',
        lines: [
          { speaker: 'A', en: "So, to sum up, I'd say the plan is ready.", ja: '要約しますと、計画は準備できたと言えます。' },
          { speaker: 'A', en: "I think I've covered everything. Any questions?", ja: 'これで一通り説明できたかと思います。ご質問はありますか？' },
          { speaker: 'A', en: 'Does anyone have anything to add?', ja: 'どなたか付け加えることはありますか？' },
        ],
      },
    ],
    tip: 'プレゼンテーションでは、話が今どこにあるのかを示すサインポストが大切です。Moving on to... や This leads me on to... を使うと、聞き手はスライドやトピックの移行を迷わず追えます。To kick things off... は少しカジュアルに始める表現、Firstly... や The focus of my presentation is... はフォーマルな場で使いやすい表現です。最後は I think I\'ve covered everything. Any questions? と添えると、質問しやすい雰囲気を作れます。',
  },
  practice: {
    title: 'プレゼンの流れを、英語で案内する',
    instructions: '日本語訳は見ずに、始める・切り替える・締めるサインポストを声に重ねます。',
    coreHeading: 'まずは、聞き手を迷わせない一文から。',
    dialogueHeading: '始まり、話題転換、締めくくりで役を切り替える。',
    dialogueDescription: '発表のテーマを示す、次の話題へ移る、要約して質問を受ける3つの場面を練習します。',
    finishTitle: '次の発表で、聞き手を案内するサインポストをひとつ使ってみましょう。',
    corePhrases: [
      { phrase: "Today, I'm going to talk about...", context: 'テーマを示す', rate: 0.78 },
      { phrase: "You're all here because...", context: '発表の意義を示す', rate: 0.8 },
      { phrase: "Firstly, I'd like to begin by saying...", context: '丁寧に始める', rate: 0.74 },
      { phrase: 'The focus of my presentation is...', context: '焦点を伝える', rate: 0.76 },
      { phrase: 'To kick things off...', context: '勢いよく始める', rate: 0.82 },
      { phrase: "Now let's turn to the subject of...", context: '次の話題へ移る', rate: 0.76 },
      { phrase: 'Moving on to...', context: '短く切り替える', rate: 0.84 },
      { phrase: "The next thing I'd like to bring to your attention is...", context: '重要点を示す', rate: 0.7 },
      { phrase: 'This leads me on to...', context: '話の流れをつなぐ', rate: 0.8 },
      { phrase: "Lastly, I'd like to finish by saying...", context: '最後のメッセージ', rate: 0.72 },
      { phrase: "So, to sum up, I'd say...", context: '要約する', rate: 0.8 },
      { phrase: "I think I've covered everything. Any questions?", context: '質疑応答へ移る', rate: 0.76 },
      { phrase: 'Does anyone have anything to add?', context: '追加意見を募る', rate: 0.78 },
    ],
    dialogues: [
      { title: 'Opening', lines: ["Today, I'm going to talk about customer feedback.", 'The focus of my presentation is our new support plan.', "First I'm going to tell you about the main findings."] },
      { title: 'Signposting', lines: ['Moving on to the second point, let’s look at the timeline.', "The next thing I'd like to bring to your attention is the budget.", 'This leads me on to our next step.'] },
      { title: 'Closing', lines: ["So, to sum up, I'd say the plan is ready.", "I think I've covered everything. Any questions?", 'Does anyone have anything to add?'] },
    ],
    natural: [
      { full: 'I want to talk about the main issue today.', natural: "Today, I'm going to talk about..." },
      { full: "Let's talk about the next topic now.", natural: 'Moving on to...' },
      { full: "Let's summarize and then ask for questions.", natural: "So, to sum up, I'd say..." },
    ],
  },
}
