/** Chapter 40 · Returning goods. */
export const returnsLesson = {
  id: 'returns-goods',
  kind: 'returns-goods',
  number: '40',
  title: '第40章に入る前に：なぜ「商品の返品で使う英語」を学ぶのでしょうか？',
  enTitle: 'Returning goods',
  ja: '商品の問題を説明し、返金や交換を丁寧にお願いする英語を学びます。',
  cando: '商品の不具合やサイズ違いを説明し、返金・交換・商品券について尋ねられる。',
  learn: {
    intro: [
      '買い物では、いつもすべてが予定どおりにいくとは限りません。サイズが合わなかったり、商品が壊れていたり、別の商品に交換したくなったりすることがあります。',
      'そのようなときに大切なのは、何が問題なのかを明確に説明し、自分がどのような対応を希望しているのかを伝えることです。状況によって、返金、交換、あるいは別の対応をお願いすることがあります。',
      'この章では、商品の問題を説明する表現、返金や交換をお願いする表現、そして返品のやり取りを丁寧かつ明確に進める方法を学びます。',
    ],
    functions: [
      ['01', '返品窓口を探す'],
      ['02', '問題を説明する'],
      ['03', '返金をお願いする'],
      ['04', '交換や商品券を確認する'],
    ],
    problem: {
      title: '返品窓口を探す・問題を説明する',
      enTitle: 'Explaining the problem',
      intro: '返品したい商品と、その理由を短くはっきり伝えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Where can I return this bag?', meaning: 'このバッグはどこで返品できますか？', context: '返品窓口を尋ねる', register: 'polite' },
        { phrase: 'Our returns desk is on the second floor.', meaning: '返品窓口は2階にあります。', context: '返品窓口を案内する', register: 'neutral' },
        { phrase: 'I need to return these trousers.', meaning: 'このズボンを返品したいのですが。', context: '返品を切り出す', register: 'neutral' },
        { phrase: 'Can I ask what the problem is?', meaning: 'どのような問題があるかお伺いできますか？', context: '返品理由を尋ねる', register: 'polite' },
        { phrase: 'I bought the wrong colour.', meaning: '間違った色を買ってしまいました。', context: '色違いを説明する', register: 'neutral' },
        { phrase: 'I bought the wrong size.', meaning: '間違ったサイズを買ってしまいました。', context: 'サイズ違いを説明する', register: 'neutral' },
        { phrase: "They're too big.", meaning: '大きすぎます。', context: 'サイズの問題を伝える', register: 'neutral' },
        { phrase: 'The shoes are too tight.', meaning: '靴がきつすぎます。', context: '靴の問題を伝える', register: 'neutral' },
        { phrase: "This dress is too small.", meaning: 'このドレスは小さすぎます。', context: '服の問題を伝える', register: 'neutral' },
        { phrase: "The dress doesn't fit properly.", meaning: 'ドレスのサイズが合いません。', context: 'フィット感を説明する', register: 'neutral' },
        { phrase: "The lamp isn't working properly.", meaning: 'ランプがきちんと動きません。', context: '不具合を説明する', register: 'neutral' },
        { phrase: 'The vase is broken.', meaning: '花瓶が割れています。', context: '破損を説明する', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'returns desk', meaning: '返品窓口', note: '返品や交換を受け付けるカウンターです。' },
        { phrase: 'fit properly', meaning: 'きちんと合う', note: '服や靴のサイズ感を説明するときに使います。' },
        { phrase: 'working properly', meaning: '正常に作動する', note: '家電やランプなどの不具合に使います。' },
      ],
    },
    refund: {
      title: '返金と交換のやり取り',
      enTitle: 'Refunds and exchanges',
      intro: '返金、交換、レシートがない場合の対応をカウンターで確認します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'I bought this online. Can I get a refund?', meaning: 'これ、ネットで買ったんです。返金してもらえますか？', context: '返金をお願いする', register: 'polite' },
        { phrase: 'Yes, I just need your order number.', meaning: 'はい、注文番号だけ必要になります。', context: '注文番号を確認する', register: 'neutral' },
        { phrase: 'I have to return this, but I lost my receipt.', meaning: 'これを返品したいのですが、レシートをなくしてしまいました。', context: 'レシートがないと伝える', register: 'neutral' },
        { phrase: "Without a receipt, we can only offer an exchange, I'm afraid.", meaning: 'レシートがない場合は交換のみの対応となります。', context: '交換のみと説明する', register: 'polite' },
        { phrase: "I'm returning this hat. I just don't like it!", meaning: 'この帽子を返品します。ただ気に入らなかったんです！', context: '気に入らなかったと伝える', register: 'casual' },
        { phrase: 'Do you have a receipt?', meaning: 'レシートはお持ちですか？', context: 'レシートを確認する', register: 'polite' },
        { phrase: 'No, it was a gift.', meaning: 'いいえ、贈り物だったんです。', context: 'ギフトだと伝える', register: 'neutral' },
        { phrase: "Don't worry, I'll give you a voucher.", meaning: 'ご心配なく、商品券をお渡ししますね。', context: '商品券を提案する', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'get a refund', meaning: '返金してもらう', note: 'Can I get a refund? のように使います。' },
        { phrase: 'without a receipt', meaning: 'レシートなしで', note: 'レシートがない場合の条件を説明するときに使います。' },
        { phrase: 'voucher', meaning: '商品券・引換券', note: '現金の代わりに店で使える券です。' },
      ],
    },
    vocabulary: {
      title: '返品と交換のボキャブラリー',
      enTitle: 'Vocabulary · Returns',
      intro: '返品カウンターで何を希望しているかを伝える基本語を整理します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'return', meaning: '返品・返品する', context: '商品を店に返すこと', register: 'neutral' },
        { phrase: 'refund', meaning: '返金・払い戻し', context: '支払ったお金を戻すこと', register: 'neutral' },
        { phrase: 'exchange', meaning: '交換', context: '別の商品に替えること', register: 'neutral' },
        { phrase: 'receipt', meaning: 'レシート・領収書', context: '購入を証明するもの', register: 'neutral' },
        { phrase: 'order number', meaning: '注文番号', context: 'オンライン購入の番号', register: 'neutral' },
        { phrase: 'voucher', meaning: '商品券・引換券', context: '店で使える券', register: 'neutral' },
        { phrase: 'wrong colour', meaning: '間違った色', context: '色を選び間違えた場合', register: 'neutral' },
        { phrase: 'wrong size', meaning: '間違ったサイズ', context: 'サイズを選び間違えた場合', register: 'neutral' },
        { phrase: 'too tight', meaning: 'きつすぎる', context: '服や靴のフィット感', register: 'neutral' },
        { phrase: 'broken', meaning: '壊れている・割れている', context: '商品が破損している状態', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'return', meaning: '返品', note: 'I need to return this. と希望を伝えます。' },
        { phrase: 'refund', meaning: '返金', note: 'Can I get a refund? と尋ねます。' },
        { phrase: 'exchange', meaning: '交換', note: '別の商品やサイズに替える対応です。' },
      ],
    },
    dialogues: [
      {
        id: 'problem',
        label: 'Pattern A · Explaining the problem',
        title: '返品理由を説明する',
        lines: [
          { speaker: 'A', en: 'I need to return these trousers.', ja: 'このズボンを返品したいのですが。' },
          { speaker: 'B', en: 'Can I ask what the problem is?', ja: 'どのような問題があるかお伺いできますか？' },
          { speaker: 'A', en: 'I bought the wrong size. They\'re too big.', ja: '間違ったサイズを買いました。大きすぎます。' },
          { speaker: 'B', en: "Of course. Let's see what we can do.", ja: 'もちろんです。対応を確認しましょう。' },
        ],
      },
      {
        id: 'refund',
        label: 'Pattern B · Asking for a refund',
        title: '返金と注文番号を確認する',
        lines: [
          { speaker: 'A', en: 'I bought this online. Can I get a refund?', ja: 'これ、ネットで買ったんです。返金してもらえますか？' },
          { speaker: 'B', en: 'Yes, I just need your order number.', ja: 'はい、注文番号だけ必要になります。' },
          { speaker: 'A', en: 'Here it is. The lamp is not working properly.', ja: 'こちらです。ランプがきちんと動きません。' },
          { speaker: 'B', en: "I'm sorry about that. I'll process the refund.", ja: '申し訳ありません。返金を処理します。' },
        ],
      },
      {
        id: 'receipt',
        label: 'Pattern C · No receipt',
        title: 'レシートがないギフトを交換する',
        lines: [
          { speaker: 'A', en: 'I have to return this, but I lost my receipt.', ja: 'これを返品したいのですが、レシートをなくしてしまいました。' },
          { speaker: 'B', en: "Without a receipt, we can only offer an exchange, I'm afraid.", ja: 'レシートがない場合は交換のみの対応となります。' },
          { speaker: 'A', en: 'No, it was a gift.', ja: 'いいえ、贈り物だったんです。' },
          { speaker: 'B', en: "Don't worry, I'll give you a voucher.", ja: 'ご心配なく、商品券をお渡ししますね。' },
        ],
      },
    ],
    tip: '返品、返金、交換はそれぞれ return、refund、exchange と言います。レシートがない場合やギフトを返品する場合は、現金の代わりに voucher を渡されることがあります。まず問題を短く説明し、そのあと希望する対応を尋ねましょう。',
  },
  practice: {
    title: '返品カウンターで、問題と希望を英語で伝える',
    instructions: '日本語の説明はここまで。返品理由を説明し、返金・交換・商品券について尋ねる英語を声に重ねます。',
    coreHeading: 'まずは、返品でそのまま使える一文から。',
    dialogueHeading: '問題を説明し、返金・交換の方法を確認する。',
    dialogueDescription: '返品理由を伝える声、返金をお願いする声、レシートがない場合の声を切り替えます。',
    finishTitle: '次に返品が必要になったとき、問題と希望する対応をひとつ英語で説明してみましょう。',
    corePhrases: [
      { phrase: 'Where can I return this bag?', context: '返品窓口を尋ねる', rate: 0.82 },
      { phrase: 'I need to return these trousers.', context: '返品を切り出す', rate: 0.8 },
      { phrase: 'I bought the wrong size.', context: 'サイズ違いを説明する', rate: 0.84 },
      { phrase: 'The shoes are too tight.', context: '靴の問題を伝える', rate: 0.84 },
      { phrase: "The dress doesn't fit properly.", context: 'フィット感を説明する', rate: 0.78 },
      { phrase: 'The vase is broken.', context: '破損を説明する', rate: 0.86 },
      { phrase: 'I bought this online. Can I get a refund?', context: '返金をお願いする', rate: 0.76 },
      { phrase: 'I have to return this, but I lost my receipt.', context: 'レシートがないと伝える', rate: 0.74 },
      { phrase: 'Without a receipt, we can only offer an exchange.', context: '交換条件を説明する', rate: 0.72 },
      { phrase: "Don't worry, I'll give you a voucher.", context: '商品券を提案する', rate: 0.78 },
    ],
    dialogues: [
      { title: 'Explaining the problem', lines: ['I need to return these trousers.', 'Can I ask what the problem is?', "I bought the wrong size. They're too big.", "Of course. Let's see what we can do."] },
      { title: 'Asking for a refund', lines: ['I bought this online. Can I get a refund?', 'Yes, I just need your order number.', 'Here it is. The lamp is not working properly.', "I'm sorry about that. I'll process the refund."] },
      { title: 'No receipt', lines: ['I have to return this, but I lost my receipt.', "Without a receipt, we can only offer an exchange, I'm afraid.", 'No, it was a gift.', "Don't worry, I'll give you a voucher."] },
    ],
    natural: [
      { full: 'I want to return this.', natural: 'I need to return this.' },
      { full: 'Can I have my money back?', natural: 'Can I get a refund?' },
      { full: 'I do not have the receipt.', natural: 'I lost my receipt.' },
    ],
  },
}
