/** Chapter 46 · At school. */
export const schoolLesson = {
  id: 'school',
  kind: 'school',
  number: '46',
  title: '第46章に入る前に：なぜ「学校で使う英語」を学ぶのでしょうか？',
  enTitle: 'At school',
  ja: '学校の仕組み、授業、宿題、初登校、保護者面談について尋ねる英語を学びます。',
  cando: '学校のカリキュラムやルールを尋ね、初登校や保護者面談で学習状況を話せる。',
  learn: {
    intro: [
      '学校は、子どもが勉強するだけの場所ではありません。生徒、先生、そして保護者がコミュニケーションを取りながら、子どもの成長を支える場所でもあります。',
      '保護者は、授業、宿題、学校のルール、放課後の活動などについて質問することがあります。また、子どもが学校に馴染んでいるか、学習が順調に進んでいるかを先生に確認することもあります。',
      'この章では、学校について質問する表現、初登校でのやり取り、そして先生と子どもの学習状況について話す表現を学びます。',
    ],
    functions: [
      ['01', '学校の仕組みを尋ねる'],
      ['02', '授業と活動を確認する'],
      ['03', '初登校を支える'],
      ['04', '学習状況を話す'],
    ],
    schoolInfo: {
      title: '学校を選ぶ・質問する',
      enTitle: 'Choosing a school · More questions',
      intro: '学校見学や説明会で、カリキュラム、授業、クラス、宿題、活動について確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'We offer a wide range of subjects.', meaning: '当校では幅広い科目を提供しています。', context: '学校側の説明', register: 'neutral' },
        { phrase: 'The children have maths every day.', meaning: '子どもたちは毎日数学の授業があります。', context: '授業を説明する', register: 'neutral' },
        { phrase: 'Is music part of the curriculum?', meaning: '音楽はカリキュラムに含まれていますか？', context: 'カリキュラムを尋ねる', register: 'polite' },
        { phrase: 'How often do they have science lessons?', meaning: '理科の授業はどのくらいの頻度でありますか？', context: '授業頻度を尋ねる', register: 'polite' },
        { phrase: 'How many children are in each class?', meaning: '1クラスに子どもは何人いますか？', context: 'クラス人数を尋ねる', register: 'polite' },
        { phrase: 'How much homework is there?', meaning: '宿題はどのくらい出ますか？', context: '宿題を尋ねる', register: 'polite' },
        { phrase: 'What clubs do you offer?', meaning: 'どのようなクラブ活動がありますか？', context: '課外活動を尋ねる', register: 'polite' },
        { phrase: 'Do you have a school uniform?', meaning: '制服はありますか？', context: '学校のルールを尋ねる', register: 'polite' },
        { phrase: 'Is there an after-school club?', meaning: '放課後のクラブはありますか？', context: '放課後の活動を尋ねる', register: 'polite' },
      ],
      recognition: [
        { phrase: 'a wide range of subjects', meaning: '幅広い科目', note: '学校のカリキュラムを紹介するときに使います。' },
        { phrase: 'part of the curriculum', meaning: 'カリキュラムの一部', note: 'ある科目が必修・選択かを尋ねる表現です。' },
        { phrase: 'after-school club', meaning: '放課後のクラブ', note: '学校後の活動や学童の場面で使います。' },
      ],
    },
    firstDay: {
      title: '入学初日と保護者面談',
      enTitle: "Starting school · Parents' evening",
      intro: '初登校の不安をやわらげ、保護者面談で学校への適応や学習の進み具合を確認します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'You must be our new student. Welcome!', meaning: 'あなたが新しい生徒さんですね。ようこそ！', context: '初登校で迎える', register: 'polite' },
        { phrase: "Yes, this is Tom. He's a bit nervous for his first day!", meaning: 'はい、トムです。初日で少し緊張しています！', context: '子どもの様子を伝える', register: 'casual' },
        { phrase: "There's no need to worry, Tom.", meaning: '心配する必要はありませんよ、トム。', context: '子どもを安心させる', register: 'polite' },
        { phrase: "Let's go and meet your new class.", meaning: '新しいクラスのみんなに会いに行きましょう。', context: '教室へ案内する', register: 'casual' },
        { phrase: 'Zia is settling in very well.', meaning: 'ジアは学校にとてもよく馴染んでいますよ。', context: '学校への適応を伝える', register: 'polite' },
        { phrase: "Oh, good. How is she getting on with English?", meaning: 'ああ、よかった。英語の進み具合はどうですか？', context: '学習状況を尋ねる', register: 'polite' },
        { phrase: "She's making really good progress.", meaning: 'とても順調に進歩していますよ。', context: '進歩を伝える', register: 'polite' },
      ],
      recognition: [
        { phrase: 'settle in', meaning: '新しい環境に馴染む', note: '転校、引っ越し、転職のあとにも使います。' },
        { phrase: 'get on with', meaning: '〜の調子がよい・うまくやる', note: '人や科目との相性・進み具合を尋ねます。' },
        { phrase: 'make progress', meaning: '進歩する', note: '学習や技能の伸びを伝える表現です。' },
      ],
    },
    subjects: {
      title: '学校の科目',
      enTitle: 'Vocabulary · School subjects',
      intro: '時間割や学校の案内によく出てくる科目の名前を確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'English', meaning: '英語・英語圏での国語', context: '科目', register: 'neutral' },
        { phrase: 'maths', meaning: '算数・数学', context: '科目', register: 'neutral' },
        { phrase: 'science', meaning: '理科・科学', context: '科目', register: 'neutral' },
        { phrase: 'history', meaning: '歴史', context: '科目', register: 'neutral' },
        { phrase: 'geography', meaning: '地理', context: '科目', register: 'neutral' },
        { phrase: 'computing', meaning: 'コンピューター・情報', context: '科目', register: 'neutral' },
        { phrase: 'languages', meaning: '語学・外国語', context: '科目', register: 'neutral' },
        { phrase: 'physical education (PE)', meaning: '体育', context: '科目', register: 'neutral' },
        { phrase: 'art', meaning: '美術', context: '科目', register: 'neutral' },
        { phrase: 'music', meaning: '音楽', context: '科目', register: 'neutral' },
        { phrase: 'drama', meaning: '演劇', context: '科目', register: 'neutral' },
        { phrase: 'religious studies', meaning: '宗教学', context: '科目', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'maths', meaning: '算数・数学', note: 'イギリス英語。アメリカ英語では math です。' },
        { phrase: 'physical education (PE)', meaning: '体育', note: '学校では PE と短く呼ぶことが多いです。' },
        { phrase: 'religious studies', meaning: '宗教学', note: '学校の科目名として使われます。' },
      ],
    },
    vocabulary: {
      title: '学校のボキャブラリー',
      enTitle: 'Vocabulary · At school',
      intro: '学校の案内、先生との会話、保護者面談でよく見る単語を整理します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'curriculum', meaning: 'カリキュラム・教育課程', context: '学校の学習内容', register: 'neutral' },
        { phrase: 'homework', meaning: '宿題', context: '家庭で行う課題', register: 'neutral' },
        { phrase: 'school uniform', meaning: '制服', context: '学校のルール', register: 'neutral' },
        { phrase: 'after-school club', meaning: '放課後のクラブ', context: '課外活動', register: 'neutral' },
        { phrase: 'class', meaning: 'クラス・授業', context: '学習集団や授業', register: 'neutral' },
        { phrase: 'student', meaning: '生徒・学生', context: '学ぶ子ども', register: 'neutral' },
        { phrase: 'parents\' evening', meaning: '保護者面談', context: '先生と保護者の面談', register: 'neutral' },
        { phrase: 'settle in', meaning: '学校に馴染む', context: '新しい環境への適応', register: 'neutral' },
        { phrase: 'get on with', meaning: '〜の調子がよい', context: '学習や人間関係', register: 'neutral' },
        { phrase: 'make progress', meaning: '進歩する', context: '学習の上達', register: 'neutral' },
      ],
      recognition: [
        { phrase: "Parents' evening", meaning: '保護者面談', note: 'アメリカ英語では parent-teacher conference が一般的です。' },
        { phrase: 'settle in', meaning: '馴染む', note: '新しい学校や職場で落ち着くことです。' },
        { phrase: 'get on with English', meaning: '英語の調子がよい', note: '学習の進み具合を尋ねる自然な表現です。' },
        { phrase: 'make good progress', meaning: '順調に進歩する', note: '先生が学習状況を伝えるときに使います。' },
      ],
    },
    dialogues: [
      {
        id: 'school-questions',
        label: 'Pattern A · Choosing a school',
        title: 'カリキュラムと学校の活動を尋ねる',
        lines: [
          { speaker: 'A', en: 'Is music part of the curriculum?', ja: '音楽はカリキュラムに含まれていますか？' },
          { speaker: 'B', en: 'We offer a wide range of subjects.', ja: '幅広い科目を提供しています。' },
          { speaker: 'A', en: 'How much homework is there?', ja: '宿題はどのくらい出ますか？' },
          { speaker: 'B', en: 'The children have homework every evening.', ja: '子どもたちは毎晩宿題があります。' },
        ],
      },
      {
        id: 'first-day',
        label: 'Pattern B · Starting school',
        title: '初登校の子どもを迎える',
        lines: [
          { speaker: 'A', en: 'You must be our new student. Welcome!', ja: 'あなたが新しい生徒さんですね。ようこそ！' },
          { speaker: 'B', en: "Yes, this is Tom. He's a bit nervous for his first day!", ja: 'はい、トムです。初日で少し緊張しています！' },
          { speaker: 'A', en: "There's no need to worry, Tom.", ja: '心配する必要はありませんよ、トム。' },
          { speaker: 'B', en: "Let's go and meet your new class.", ja: '新しいクラスのみんなに会いに行きましょう。' },
        ],
      },
      {
        id: 'parents-evening',
        label: "Pattern C · Parents' evening",
        title: '学校への適応と英語の進歩を確認する',
        lines: [
          { speaker: 'A', en: 'Zia is settling in very well.', ja: 'ジアは学校にとてもよく馴染んでいます。' },
          { speaker: 'B', en: "Oh, good. How is she getting on with English?", ja: 'ああ、よかった。英語の進み具合はどうですか？' },
          { speaker: 'A', en: "She's making really good progress.", ja: 'とても順調に進歩しています。' },
          { speaker: 'B', en: "That's wonderful to hear.", ja: 'それを聞けてうれしいです。' },
        ],
      },
    ],
    tip: "イギリス英語では maths、Parents' evening と言い、アメリカ英語では math、parent-teacher conference が一般的です。settle in は新しい環境に馴染む、get on with は学習や人間関係の調子がよい、make progress は進歩するという意味です。",
  },
  practice: {
    title: '学校でのことを、英語で尋ねて説明する',
    instructions: '日本語訳は見ずに、学校の仕組み、初登校、授業、学習状況を声に重ねます。',
    coreHeading: 'まずは、学校でそのまま使える一文から。',
    dialogueHeading: '学校選び、初登校、保護者面談の場面で役を切り替える。',
    dialogueDescription: '学校の質問、子どもを迎える会話、学習の進み具合を確認する3つの場面を練習します。',
    finishTitle: '次に学校について話すとき、授業か活動について英語でひとつ尋ねてみましょう。',
    corePhrases: [
      { phrase: 'Is music part of the curriculum?', context: 'カリキュラムを尋ねる', rate: 0.8 },
      { phrase: 'How often do they have science lessons?', context: '授業頻度を尋ねる', rate: 0.74 },
      { phrase: 'How many children are in each class?', context: 'クラス人数を尋ねる', rate: 0.72 },
      { phrase: 'How much homework is there?', context: '宿題を尋ねる', rate: 0.84 },
      { phrase: 'What clubs do you offer?', context: 'クラブ活動を尋ねる', rate: 0.84 },
      { phrase: 'Do you have a school uniform?', context: '制服を尋ねる', rate: 0.82 },
      { phrase: 'You must be our new student. Welcome!', context: '初登校で迎える', rate: 0.76 },
      { phrase: "There's no need to worry, Tom.", context: '子どもを安心させる', rate: 0.8 },
      { phrase: 'Zia is settling in very well.', context: '適応を伝える', rate: 0.78 },
      { phrase: "How is she getting on with English?", context: '学習状況を尋ねる', rate: 0.76 },
      { phrase: "She's making really good progress.", context: '進歩を伝える', rate: 0.8 },
      { phrase: 'The children have maths every day.', context: '授業を説明する', rate: 0.8 },
    ],
    dialogues: [
      { title: 'Choosing a school', lines: ['Is music part of the curriculum?', 'We offer a wide range of subjects.', 'How much homework is there?', 'The children have homework every evening.'] },
      { title: 'Starting school', lines: ['You must be our new student. Welcome!', "Yes, this is Tom. He's a bit nervous for his first day!", "There's no need to worry, Tom.", "Let's go and meet your new class."] },
      { title: "Parents' evening", lines: ['Zia is settling in very well.', "Oh, good. How is she getting on with English?", "She's making really good progress.", "That's wonderful to hear."] },
    ],
    natural: [
      { full: 'How many pupils are in one classroom?', natural: 'How many children are in each class?' },
      { full: 'She is becoming comfortable in the new school.', natural: 'She is settling in very well.' },
      { full: 'How is her English going?', natural: 'How is she getting on with English?' },
    ],
  },
}
