/*
 * Source-book vocabulary that was present in the printed pages but was
 * previously hidden inside a grouped/illustrative entry in the older lesson
 * files.  Every item below was checked against the corresponding OCR page
 * text in sourceBookCorpus.js.  This is deliberately limited to source-book
 * vocabulary; it is not a place for new examples.
 */

const v = (phrase, meaning, audio) => ({ phrase, meaning, context: '原書の語彙', register: 'neutral', audio })

export const sourceBookSupplements = {
  11: {
    dates: [
      v('month', '月'),
      v('year', '年'),
      v('calendar', 'カレンダー'),
      v('day', '日', 'ee_11_1_day_us.mp3'),
      v('weekday', '平日'),
      v('week', '週'),
      v('date', '日付'),
      v('yesterday', '昨日'),
      v('today', '今日'),
      v('tomorrow', '明日'),
      v('weekend', '週末'),
      v('Monday', '月曜日'),
      v('Tuesday', '火曜日'),
      v('Wednesday', '水曜日'),
      v('Thursday', '木曜日'),
      v('Friday', '金曜日'),
      v('Saturday', '土曜日'),
      v('Sunday', '日曜日'),
      v('1st', '1日・1番目'),
      v('2nd', '2日・2番目'),
      v('3rd', '3日・3番目', 'ee_11_1_third_us.mp3'),
      v('4th', '4日・4番目'),
      v('5th', '5日・5番目'),
      v('6th', '6日・6番目'),
      v('7th', '7日・7番目'),
      v('8th', '8日・8番目'),
      v('9th', '9日・9番目'),
      v('10th', '10日・10番目'),
      v('20th', '20日・20番目'),
      v('21st', '21日・21番目'),
      v('first', '1番目'),
      v('second', '2番目'),
      v('third', '3番目', 'ee_11_1_third_us.mp3'),
      v('fourth', '4番目'),
      v('fifth', '5番目'),
      v('sixth', '6番目'),
      v('seventh', '7番目'),
      v('eighth', '8番目'),
      v('ninth', '9番目'),
      v('tenth', '10番目'),
      v('twentieth', '20番目'),
      v('twenty-first', '21番目'),
      v('once a week', '週に1回'),
      v('twice a week', '週に2回'),
      v('three times a week', '週に3回'),
      v('every day', '毎日'),
      v('every week', '毎週'),
      v('every month', '毎月'),
      v('1900', '1900年', 'ee_11_1_nineteenhundred_us.mp3'),
      v('1901', '1901年', 'ee_11_1_nineteenohone_us.mp3'),
      v('1910', '1910年', 'ee_11_1_nineteenten_us.mp3'),
      v('2000', '2000年', 'ee_11_1_twothousand_us.mp3'),
      v('2001', '2001年', 'ee_11_1_twothousandandone_us.mp3'),
      v('2033', '2033年', 'ee_11_1_twentythirtythree_us.mp3'),
      v('nineteen hundred', '1900年'),
      v('nineteen oh-one', '1901年'),
      v('nineteen ten', '1910年'),
      v('two thousand', '2000年'),
      v('two thousand and one', '2001年'),
      v('twenty thirty-three', '2033年'),
    ],
    time: [
      v("one o'clock", '1時', 'ee_11_2_oneoclock_us.mp3'),
      v('1pm', '午後1時', 'ee_11_2_oneoclock_us.mp3'),
      v('five past one', '1時5分'),
      v('ten past one', '1時10分'),
      v('quarter past one', '1時15分'),
      v('twenty past one', '1時20分'),
      v('twenty-five past one', '1時25分'),
      v('one thirty', '1時30分'),
      v('half past one', '1時30分'),
      v('twenty-five to two', '2時25分前'),
      v('twenty to two', '2時20分前'),
      v('quarter to two', '2時15分前'),
      v('ten to two', '2時10分前'),
      v('five to two', '2時5分前'),
      v('second', '秒'),
      v('minute', '分'),
      v('half hour', '30分'),
      v('hour', '1時間'),
      v('What time does it start?', '何時に始まりますか？'),
      v('At 6pm.', '午後6時です。'),
    ],
    weather: [
      v('sunny', '晴れ'),
      v('cloudy', '曇り'),
      v('overcast', '一面の曇り'),
      v('warm', '暖かい'),
      v('boiling', 'うだるように暑い'),
      v('freezing', '凍えるほど寒い'),
      v('icy', '氷のように寒い'),
      v('windy', '風が強い'),
      v('snowy', '雪が降っている'),
      v('pouring', '土砂降り'),
      v('misty', '霧がかかった'),
      v('foggy', '霧の深い'),
      v('storm', '嵐'),
      v('flood', '洪水'),
      v('heatwave', '熱波'),
      v('drought', '干ばつ'),
      v('hurricane', 'ハリケーン'),
      v('blizzard', '猛吹雪'),
    ],
  },

  20: {
    drinks: [
      v('black coffee', 'ブラックコーヒー'),
      v('white coffee', 'ミルク入りコーヒー'),
      v('espresso', 'エスプレッソ'),
      v('cappuccino', 'カプチーノ'),
      v('latte', 'ラテ'),
      v('iced coffee', 'アイスコーヒー'),
      v('tea', '紅茶'),
      v('herbal tea', 'ハーブティー'),
      v('iced tea', 'アイスティー'),
      v('hot chocolate', 'ホットチョコレート'),
      v('milkshake', 'ミルクセーキ'),
      v('orange juice', 'オレンジジュース'),
      v('oat milk', 'オーツミルク'),
      v('skimmed milk', '低脂肪乳'),
      v('soya milk', '豆乳'),
      v('cola', 'コーラ'),
      v('sparkling water', '炭酸水'),
      v('mineral water', 'ミネラルウォーター'),
      v('whole milk', '全乳'),
      v('almond milk', 'アーモンドミルク'),
      v('reusable cup', '繰り返し使えるカップ'),
      v('sugar', '砂糖'),
    ],
    verbs: [
      v('to peel', '皮をむく'),
      v('to pour', '注ぐ'),
      v('to whisk', '泡立てる'),
      v('to burn', '焦がす'),
      v('to grate', 'すりおろす'),
      v('to mix', '混ぜる'),
      v('to chop', '刻む'),
      v('to stir', 'かき混ぜる'),
      v('to roll out', '（生地を）伸ばす'),
      v('to weigh', '重さを量る'),
      v('to slice', '薄切りにする'),
    ],
    equipment: [
      v('blender', 'ブレンダー'),
      v('kitchen knives', 'キッチンナイフ'),
      v('scales', 'はかり'),
      v('measuring jug', '計量カップ'),
      v('saucepan', '片手鍋'),
      v('colander', 'ざる'),
      v('grater', 'おろし金'),
      v('frying pan', 'フライパン'),
      v('mixing bowl', 'ミキシングボウル'),
      v('mixer', 'ミキサー'),
      v('sieve', 'ふるい'),
      v('casserole dish', 'キャセロール皿'),
      v('microwave', '電子レンジ'),
      v('cafetiere', 'フレンチプレス式コーヒーメーカー'),
      v('toaster', 'トースター'),
    ],
    preparation: [
      v('fried', '揚げた・炒めた'),
      v('stir-fried', '炒めた'),
      v('deep-fried', '油で揚げた'),
      v('starter', '前菜'),
      v('main course', 'メイン料理'),
      v('side order', 'サイドメニュー'),
      v('poached', 'ポーチド（湯煎）した'),
      v('boiled', 'ゆでた'),
      v('stewed', '煮込んだ'),
      v('dessert', 'デザート'),
      v('pudding', 'デザート・プディング'),
      v('to book a table', 'テーブルを予約する'),
      v('to order', '注文する'),
      v('roasted', 'ローストした'),
      v('baked', '焼いた'),
      v('grilled', '網焼きにした'),
      v('bill', '会計・請求書'),
      v('to split the bill', '会計を割り勘にする'),
      v('gluten-free', 'グルテンフリーの'),
      v('marinated', '漬け込んだ'),
      v('steamed', '蒸した'),
      v('smoked', '燻製にした'),
      v('vegan', 'ビーガンの'),
      v('vegetarian', 'ベジタリアンの'),
      v('dairy-free', '乳製品不使用の'),
    ],
  },

  14: {
    family: [
      v('grandfather', '祖父'), v('grandmother', '祖母'), v('grandparents', '祖父母'),
      v('father-in-law', '義父'), v('mother-in-law', '義母'), v('uncle', 'おじ'),
      v('mother', '母'), v('mum', 'お母さん'), v('father', '父'), v('dad', 'お父さん'),
      v('aunt', 'おば'), v('sister-in-law', '義姉・義妹'), v('wife', '妻'), v('me', '私'),
      v('brother', '兄弟・兄・弟'), v('sister', '姉妹・姉・妹'), v('brother-in-law', '義兄・義弟'),
      v('married', '結婚している'), v('daughter-in-law', '義理の娘'), v('son', '息子'),
      v('daughter', '娘'), v('son-in-law', '義理の息子'), v('nephew', '甥'), v('niece', '姪'), v('cousin', 'いとこ'),
      v('divorced', '離婚した'), v('children', '子どもたち'), v('grandson', '孫息子'),
      v('granddaughter', '孫娘'), v('grandchildren', '孫たち'), v('non-blood relative', '血縁のない親族'),
    ],
    inlaws: [
      v('ex-husband', '元夫'), v('stepmother', '継母'), v('stepmum', '継母'),
      v('father', '父'), v('dad', 'お父さん'), v('mother', '母'), v('mum', 'お母さん'),
      v('stepfather', '継父'), v('stepdad', '継父'), v('ex-wife', '元妻'),
      v('stepbrother', '義理の兄弟'), v('stepsister', '義理の姉妹'), v('me', '私'),
      v('half-brother', '異父・異母兄弟'), v('half-sister', '異父・異母姉妹'),
    ],
    relationships: [
      v('siblings', '兄弟姉妹'), v('twins', '双子'), v('only child', '一人っ子'),
      v('oldest child', '一番上の子'), v('middle child', '真ん中の子'), v('youngest child', '末っ子'),
      v('parents', '両親'), v('single parent', 'ひとり親'), v('partner', 'パートナー'),
      v('engaged', '婚約している'), v('married', '結婚している'), v('husband', '夫'), v('wife', '妻'),
      v('single', '独身'), v('divorced', '離婚した'), v('ex-husband', '元夫'), v('ex-wife', '元妻'),
      v('colleague', '同僚'), v('friend', '友人'), v('neighbour', '近所の人'),
    ],
    lifeEvents: [
      v('birth', '出生'), v('birthday', '誕生日'), v('graduation', '卒業'), v('first job', '最初の仕事'),
      v('promotion', '昇進'), v('falling in love', '恋に落ちること'), v('wedding', '結婚式'), v('holiday', '休暇'),
      v('divorce', '離婚'), v('new home', '新居'), v('retirement', '退職'), v('funeral', '葬儀'),
    ],
    growingUp: [
      v('baby', '赤ちゃん'), v('toddler', 'よちよち歩きの幼児'), v('children', '子どもたち'),
      v('girl', '女の子'), v('boy', '男の子'), v('teenagers', '10代の人々'), v('woman', '女性'),
      v('man', '男性'), v('adults', '大人'), v('senior citizens', '高齢者'),
    ],
  },

  23: {
    vocabulary: [
      v('on tap', '樽から注ぐ・生の'), v('spirits', '蒸留酒'), v('sparkling wine', 'スパークリングワイン'),
      v('wine', 'ワイン'), v('lager', 'ラガー'), v('mocktail', 'ノンアルコールカクテル'),
      v('gin and tonic', 'ジントニック'), v('cocktail', 'カクテル'), v('ice and lemon', '氷とレモン'),
      v('soft drinks', 'ソフトドリンク'), v('alcohol-free lager', 'ノンアルコールラガー'), v('beer', 'ビール'),
    ],
  },

  22: {
    vocabulary: [
      v('curry', 'カレー'), v('noodles', '麺類'), v('pizza', 'ピザ'), v('sushi', '寿司'),
      v('tacos', 'タコス'), v('kebab', 'ケバブ'), v('burgers', 'ハンバーガー'), v('fried chicken', 'フライドチキン'),
      v('fries', 'フライドポテト'), v('nachos', 'ナチョス'), v('takeaway', '持ち帰り料理'), v('delivery', '配達'),
    ],
  },

  24: {
    vocabulary: [
      v('menu', 'メニュー'),
      v('fork', 'フォーク'),
      v('wine list', 'ワインリスト'),
      v('table number', 'テーブル番号'),
      v('wine glass', 'ワイングラス'),
      v('jug of water', '水差し一杯の水'),
      v('dessert spoon', 'デザートスプーン'),
      v('white wine', '白ワイン'),
      v('black pepper', '黒こしょう'),
      v('ice bucket', 'アイスペール'),
      v('salt', '塩'),
      v('side plate', '取り皿'),
      v('bread basket', 'パンかご'),
      v('napkin', 'ナプキン'),
      v('plate', '皿'),
      v('knife', 'ナイフ'),
      v('soup spoon', 'スープスプーン'),
    ],
  },

  26: {
    outdoor: [
      v('running', 'ランニング'), v('cycling', 'サイクリング'), v('going to the funfair', '移動遊園地に行くこと'),
      v('tai chi', '太極拳'), v('skateboarding', 'スケートボード'), v('walking', 'ウォーキング'),
      v('going to the playground', '遊び場に行くこと'), v('yoga', 'ヨガ'), v('flying a kite', '凧揚げ'),
      v('having a picnic', 'ピクニックをすること'), v('playing football', 'サッカーをすること'), v('skipping', '縄跳び'),
      v('snowboarding', 'スノーボード'), v('climbing', 'クライミング'), v('sailing', 'セーリング'), v('swimming', '水泳'),
      v('fishing', '釣り'), v('skiing', 'スキー'), v('mountain biking', 'マウンテンバイク'), v('quad biking', '四輪バギー'),
      v('hiking', 'ハイキング'), v('foraging', '採集'), v('orienteering', 'オリエンテーリング'),
      v('camping', 'キャンプ'), v('horse riding', '乗馬'), v('birdwatching', 'バードウォッチング'),
    ],
    games: [
      v('darts', 'ダーツ'), v('board game', 'ボードゲーム'), v('jigsaw puzzle', 'ジグソーパズル'),
      v('cards', 'カードゲーム'), v('gaming', 'ゲームをすること'), v('dominoes', 'ドミノ'), v('chess', 'チェス'),
      v('chess pieces', 'チェスの駒'), v('chessboard', 'チェス盤'),
    ],
    entertainment: [
      v('theatre', '劇場'), v('cinema', '映画館'), v('nightclub', 'ナイトクラブ'), v('ballet', 'バレエ'),
      v('concert', 'コンサート'), v('festival', 'フェスティバル'), v('band', 'バンド'), v('orchestra', 'オーケストラ'),
      v('choir', '合唱団'),
    ],
    musicGenres: [
      v('pop', 'ポップ'), v('rock', 'ロック'), v('country', 'カントリー'), v('hip-hop', 'ヒップホップ'),
      v('dance', 'ダンス音楽'), v('bhangra', 'バングラ'), v('jazz', 'ジャズ'), v('classical', 'クラシック'), v('opera', 'オペラ'),
    ],
  },

  36: {
    vocabulary: [
      v('bakery', 'パン・ベーカリー用品'),
      v('fruit', '果物'),
      v('vegetables', '野菜'),
      v('dairy products', '乳製品'),
      v('meat and poultry', '肉と鶏肉'),
      v('frozen food', '冷凍食品'),
      v('gluten-free products', 'グルテンフリー商品'),
      v('cereals', 'シリアル'),
      v('household products', '家庭用品'),
      v('pet food', 'ペットフード'),
      v('health and beauty', 'ヘルス・ビューティー用品'),
      v('baby products', 'ベビー用品'),
      v('deli', 'デリ'),
      v('checkout', 'レジ'),
      v('self-checkout', 'セルフレジ'),
    ],
  },

  37: {
    vocabulary: [
      v('herb garden', 'ハーブ園'), v('houseplant', '観葉植物'), v('outdoor plants', '屋外植物'),
      v('seeds', '種'), v('bulbs', '球根'), v('compost', '園芸用堆肥'), v('wheelbarrow', '手押し車'),
      v('spade', '園芸用シャベル'), v('watering can', 'じょうろ'), v('trowel', '移植ごて'), v('shears', '剪定ばさみ'),
      v('fork', '園芸用フォーク'),
    ],
  },

  38: {
    vocabulary: [
      v('hammer', 'ハンマー'), v('nail', 'くぎ'), v('screwdriver', 'ドライバー'), v('screw', 'ねじ'), v('drill', '電動ドリル'),
      v('saw', 'のこぎり'), v('to paint', 'ペンキを塗る'), v('to plaster', 'しっくいを塗る'),
      v('to sand', 'やすりをかける'), v('to tile', 'タイルを張る'), v('to fill', '埋める'), v('to hang', '掛ける'),
    ],
  },

  31: {
    vocabulary: [
      v('American football', 'アメリカンフットボール'), v('badminton', 'バドミントン'), v('baseball', '野球'),
      v('cricket', 'クリケット'), v('football (soccer)', 'サッカー'), v('golf', 'ゴルフ'), v('athletics', '陸上競技'),
      v('ice hockey', 'アイスホッケー'), v('rugby', 'ラグビー'), v('swimming', '水泳'), v('tennis', 'テニス'), v('boxing', 'ボクシング'),
    ],
  },

  34: {
    city: [
      v('petrol station', 'ガソリンスタンド'), v('supermarket', 'スーパーマーケット'), v('garden centre', '園芸店'),
      v('DIY store', 'DIY用品店'), v('gym', 'ジム'), v('cinema', '映画館'), v('theatre', '劇場'), v('café', 'カフェ'),
      v('library', '図書館'), v('post office', '郵便局'), v('bank', '銀行'), v('restaurant', 'レストラン'), v('hotel', 'ホテル'),
      v('shopping centre', 'ショッピングセンター'), v('shop', '店'), v('school', '学校'), v('ambulance', '救急車'),
      v('market', '市場'), v('pharmacy', '薬局'), v('hospital', '病院'), v('police car', 'パトカー'),
      v('fire engine', '消防車'), v('customer', '顧客'), v('queue', '列'), v('police station', '警察署'), v('fire station', '消防署'),
    ],
    types: [
      v('bakery', 'パン屋'), v('butcher', '肉屋'), v('fishmonger', '魚屋'), v('greengrocer', '青果店'),
      v('boutique', 'ブティック'), v('shoe shop', '靴店'), v('antiques shop', '骨董品店'), v('florist', '花屋'),
      v('optician', '眼鏡店・眼鏡技師'), v('hair salon', '美容室'), v('barber', '理髪店'), v('newsagent', '新聞販売店'),
      v('bookshop', '書店'),
    ],
    money: [
      v('banknotes', '紙幣'), v('coins', '硬貨'), v('debit card', 'デビットカード'), v('loyalty card', 'ポイントカード'),
      v('contactless payment', 'タッチ決済'), v('cash machine', '現金自動預払機'), v('sale', 'セール'), v('reduced', '値下げされた'),
      v('receipt', 'レシート'), v('pay for something', '何かの代金を支払う'), v('return goods', '商品を返品する'),
      v('exchange', '交換'), v('refund', '返金'),
    ],
  },

  35: {
    units: [
      v('a bunch of grapes', 'ぶどう1房'), v('a loaf of bread', 'パン1斤'), v('a punnet of strawberries', 'イチゴ1パック'),
      v('a block of cheese', 'チーズ1個'), v('a box of eggs', '卵1箱'), v('a bag of apples', 'リンゴ1袋'),
      v('a kilo of potatoes', 'ジャガイモ1キロ'), v('a jar of honey', '蜂蜜1瓶'),
    ],
  },

  43: {
    vocabulary: [
      v('cash', '現金'),
      v('ID', '身分証明書'),
      v('self-service machine', 'セルフサービス機'),
      v('debit card', 'デビットカード'),
      v('credit card', 'クレジットカード'),
      v('currency', '通貨'),
      v('bank statement', '銀行取引明細書'),
      v('mobile banking', 'モバイルバンキング'),
      v('online banking', 'オンラインバンキング'),
      v('to pay money into', '（口座に）お金を入金する'),
      v('to withdraw money', 'お金を引き出す'),
      v('to transfer money', 'お金を送金する'),
    ],
  },

  41: {
    vocabulary: [
      v('hairdresser', '美容師'),
      v('barber', '理髪師'),
      v('beautician', '美容スタッフ'),
      v('beard trim', 'ひげのトリミング'),
      v('cut', 'カット'),
      v('blow-dry', 'ブロー'),
      v('highlights', 'ハイライトカラー'),
      v('fringe', '前髪'),
      v('facial', 'フェイシャル'),
      v('manicure', 'マニキュア'),
      v('pedicure', 'ペディキュア'),
      v('waxing', 'ワックス脱毛'),
    ],
  },

  45: {
    work: [
      v('employer', '雇用主'), v('employee', '従業員'), v('freelancer', 'フリーランサー'),
      v('office worker', 'オフィスワーカー'), v('site worker', '現場作業員'), v('permanent job', '正社員・無期雇用の仕事'),
      v('temporary job', '派遣・有期雇用の仕事'), v('full-time job', 'フルタイムの仕事'), v('part-time job', 'パートタイムの仕事'),
      v('shift', 'シフト'), v('overtime', '残業'), v('flexitime', 'フレックスタイム制'),
      v('to go on maternity leave', '産休に入る'), v('to resign', '辞職する'), v('to retire', '退職する'),
      v('wages', '賃金'), v('salary', '給料'), v('hourly rate', '時給'), v('payslip', '給与明細'),
      v('benefits', '福利厚生'), v('pay rise', '昇給'), v('pay cut', '減給'), v('bonus', '賞与'),
      v('annual leave', '年次有給休暇'), v('sick leave', '病気休暇'),
    ],
  },

  46: {
    subjects: [
      v('English', '英語・国語'), v('maths', '算数・数学'), v('science', '理科'), v('history', '歴史'),
      v('geography', '地理'), v('computing', 'コンピューター・情報'), v('languages', '外国語'), v('physical education (PE)', '体育'),
      v('art', '美術'), v('music', '音楽'), v('drama', '演劇'), v('religious studies', '宗教学'),
    ],
  },

  47: {
    vocabulary: [
      v('humanities', '人文科学'), v('social sciences', '社会科学'), v('chemistry', '化学'), v('physics', '物理学'),
      v('biology', '生物学'), v('medicine', '医学'), v('law', '法律学'), v('engineering', '工学'),
      v('art and design', '美術とデザイン'), v('business', 'ビジネス'), v('economics', '経済学'), v('politics', '政治学'),
    ],
  },

  52: {
    vocabulary: [
      v('meeting', '会議'),
      v('lunch break', '昼休み'),
      v('tea break', 'お茶休憩・小休憩'),
      v('morning shift', '朝のシフト'),
      v('afternoon shift', '午後のシフト'),
      v('evening shift', '夜のシフト'),
      v('manager', 'マネージャー'),
      v('supervisor', '監督者'),
      v('colleague', '同僚'),
      v('team', 'チーム'),
      v('to clock in', '出勤を打刻する'),
      v('to clock out', '退勤を打刻する'),
      v('locker', 'ロッカー'),
    ],
  },

  56: {
    homes: [
      v('penthouse', '最上階の高級住戸'),
      v('detached house', '独立した一戸建て'),
      v('semi-detached house', '2軒が壁を共有する住宅'),
      v('terraced house', '連結住宅'),
      v('flat', 'アパート・マンションの1戸'),
      v('second floor', '2階（英語の階数）'),
      v('first floor', '1階（英語の階数）'),
      v('cottage', '田舎の小さな家'),
      v('cabin', '小屋・キャビン'),
      v('mobile home', '移動式住宅'),
      v('ground floor', '地上階'),
      v('basement', '地下室'),
      v('block of flats', 'マンション・アパートの建物'),
      v('maisonette', 'メゾネット住戸'),
      v('duplex', '2階層の住戸'),
      v('townhouse', 'タウンハウス'),
      v('bungalow', '平屋住宅'),
    ],
    rooms: [
      v('roof', '屋根'),
      v('upstairs', '上の階'),
      v('downstairs', '下の階'),
      v('loft', 'ロフト・屋根裏部屋'),
      v('balcony', 'バルコニー'),
      v('study', '書斎・勉強部屋'),
      v('bathroom', '浴室'),
      v('bedroom', '寝室'),
      v('garden', '庭'),
      v('kitchen', '台所・キッチン'),
      v('living room', '居間・リビング'),
      v('dining room', '食堂・ダイニング'),
      v('stairs', '階段'),
      v('hallway', '廊下・玄関ホール'),
      v('garage', '車庫'),
      v('fence', 'フェンス・柵'),
    ],
    improvements: [
      v('to paint a door', 'ドアにペンキを塗る'),
      v('to grout tiles', 'タイルに目地を詰める'),
      v('to strip the walls', '壁紙を剥がす'),
      v('to fill a crack', 'ひび割れを埋める'),
      v('to rewire the house', '家の配線を引き直す'),
      v('to fix a fence', 'フェンスを修理する'),
      v('to put up shelves', '棚を取り付ける'),
      v('to fit a carpet', 'カーペットを敷く'),
      v('to make curtains', 'カーテンを作る'),
      v('to build an extension', '増築する'),
    ],
    vocabulary: [
      v('fridge-freezer', '冷蔵冷凍庫'),
      v('oven', 'オーブン'),
      v('washing machine', '洗濯機'),
      v('dishwasher', '食器洗い機'),
      v('sink', '流し台・シンク'),
      v('bath', '浴槽'),
      v('shower', 'シャワー'),
      v('toilet', 'トイレ'),
      v('wash basin', '洗面台'),
      v('mirror', '鏡'),
      v('bed', 'ベッド'),
      v('cot', 'ベビーベッド'),
      v('wardrobe', '洋服だんす'),
      v('bedside table', 'ベッドサイドテーブル'),
      v('chest of drawers', 'チェスト・たんす'),
      v('sofa', 'ソファ'),
      v('armchair', '肘掛け椅子'),
      v('coffee table', 'コーヒーテーブル'),
      v('ottoman', 'オットマン'),
      v('toy box', 'おもちゃ箱'),
      v('shelf', '棚'),
      v('bookcase', '本棚'),
      v('dining table', 'ダイニングテーブル'),
      v('dining chair', 'ダイニングチェア'),
      v('television', 'テレビ'),
      v('TV', 'テレビ'),
      v('sideboard', 'サイドボード'),
    ],
  },

  57: {
    vocabulary: [
      v('landlord', '大家（男性）'), v('landlady', '大家（女性）'), v('tenant', '賃借人'), v('flatmate', '同居人'),
      v('rent', '家賃'), v('deposit', '保証金'), v('tenancy agreement', '賃貸契約書'), v('furnished', '家具付き'),
      v('unfurnished', '家具なし'), v('utility bills', '光熱費'),
    ],
  },

  58: {
    vocabulary: [
      v('moving date', '引っ越し日'), v('to move out', '退去する'), v('to move in', '入居する'), v('keys', '鍵'),
      v('to pack', '荷造りする'), v('to unpack', '荷解きをする'), v('boxes', '段ボール箱'), v('to load', '積み込む'),
      v('removal van', '引っ越し用バン'),
    ],
  },

  60: {
    vocabulary: [
      v('to do the laundry', '洗濯をする'), v('to do the washing-up', '皿洗いをする'), v('to do the vacuuming', '掃除機をかける'),
      v('to empty the dishwasher', '食洗機を空にする'), v('to clean the bath', '浴槽を掃除する'), v('to sweep the floor', '床を掃く'),
      v('to put the rubbish out', 'ゴミを出す'), v('to tidy up', '片付ける'), v('to make the bed', 'ベッドを整える'),
    ],
  },

  62: {
    vocabulary: [
      v('vaccination', '予防接種'), v('flea treatment', 'ノミ駆除薬'), v('eye drops', '目薬'), v('grooming', 'グルーミング'),
      v('microchip', 'マイクロチップ'), v('pet passport', 'ペット用パスポート'),
    ],
  },

  63: {
    vocabulary: [
      v('broken window', '割れた窓'), v('burst pipe', '破裂した配管'), v('broken-down boiler', '故障したボイラー'),
      v('overflowing toilet', 'あふれているトイレ'), v('leaking roof', '雨漏りしている屋根'), v('blocked sink', '詰まったシンク'),
      v('dripping tap', '水が垂れている蛇口'), v('power cut', '停電'),
    ],
  },

  64: {
    vocabulary: [
      v('smart TV', 'スマートテレビ'), v('remote', 'リモコン'), v('subtitles', '字幕'), v('headphones', 'ヘッドホン'),
      v('console', 'ゲーム機'), v('smart speakers', 'スマートスピーカー'), v('controller', 'コントローラー'), v('tablet', 'タブレット'),
    ],
  },

  65: {
    transport: [
      v('car', '車'), v('van', 'バン'), v('lorry', 'トラック'), v('taxi', 'タクシー'), v('taxi rank', 'タクシー乗り場'),
      v('bicycle', '自転車'), v('bike', '自転車'), v('scooter', 'スクーター'), v('moped', 'モペッド'), v('motorbike', 'オートバイ'),
      v('garage', '整備工場'), v('ferry', 'フェリー'), v('boat', 'ボート'), v('yacht', 'ヨット'), v('port', '港'),
      v('helicopter', 'ヘリコプター'), v('cable car', 'ロープウェイ'), v('aeroplane', '飛行機'), v('airport', '空港'),
      v('runway', '滑走路'), v('airport bus', '空港バス'), v('car park', '駐車場'), v('coach', '長距離バス'),
      v('bus station', 'バスターミナル'), v('bus', '路線バス'), v('bus stop', 'バス停'), v('tram', '路面電車'),
      v('metro station', '地下鉄駅'), v('train station', '鉄道駅'), v('platform number', 'プラットホーム番号'), v('passengers', '乗客'),
      v('platform', 'プラットホーム'), v('train', '電車'),
    ],
    verbs: [
      v('to board a plane', '飛行機に搭乗する'), v('to take off', '離陸する'), v('to land', '着陸する'), v('to tap in', '入場時にタッチする'),
      v('to tap out', '出場時にタッチする'), v('to wait for a bus', 'バスを待つ'), v('to get on a bus', 'バスに乗る'),
      v('to drive a car', '車を運転する'), v('to give someone a lift', '車に乗せて送る'), v('to book a taxi', 'タクシーを予約する'),
    ],
    essentials: [
      v('single ticket', '片道切符'), v('return ticket', '往復切符'), v('e-ticket', '電子チケット'), v('railcard', '鉄道割引カード'),
      v('driving licence', '運転免許証'), v('departure times', '出発時刻'), v('departure board', '出発案内板'), v('destinations', '目的地'),
      v('On Time', '定刻通り'), v('delayed', '遅延'), v('cancelled', '運休'),
    ],
  },

  67: {
    vocabulary: [
      v('train', '電車'), v('information display', '情報表示板'), v('ticket office', '切符売り場'), v('departure board', '出発案内板'),
      v('seat', '座席'), v('ticket machine', '券売機'), v('platform', 'プラットホーム'), v('passenger', '乗客'),
      v('waiting room', '待合室'), v('luggage storage', '荷物預かり所'), v('ticket inspector', '検札係'), v('ticket barrier', '自動改札口'),
    ],
  },

  68: {
    vocabulary: [
      v('overhead locker', '頭上ロッカー'), v('reading light', '読書灯'), v('window', '窓'), v('row', '座席列'), v('row number', '座席列番号'),
      v('life jacket', '救命胴衣'), v('tray table', 'トレイテーブル'), v('seat belt', 'シートベルト'), v('window seat', '窓側の席'), v('aisle seat', '通路側の席'),
    ],
  },

  69: {
    parts: [
      v('saddle', 'サドル'), v('handlebars', 'ハンドルバー'), v('helmet', 'ヘルメット'), v('frame', 'フレーム'), v('brake', 'ブレーキ'),
      v('light', 'ライト'), v('pedal', 'ペダル'), v('tyre', 'タイヤ'), v('gears', 'ギア'), v('wheel', '車輪'), v('spokes', 'スポーク'),
      v('chain', 'チェーン'), v('to repair', '修理する'),
    ],
  },

  71: {
    parts: [
      v('boot', 'トランク'), v('windscreen', 'フロントガラス'), v('bonnet', 'ボンネット'), v('bumper', 'バンパー'), v('engine', 'エンジン'),
      v('steering wheel', 'ハンドル'), v('radiator', 'ラジエーター'), v('wheel', '車輪'), v('headlight', 'ヘッドライト'), v('tyre', 'タイヤ'),
    ],
  },

  72: {
    accommodation: [
      v('hotel', 'ホテル'), v('motel', 'モーテル'), v('bed and breakfast', 'B&B・朝食付き民宿'), v('hostel', 'ホステル'),
      v('chalet', 'シャレー'), v('cabin', '山小屋・キャビン'), v('campsite', 'キャンプ場'), v('caravan', 'キャンピングトレーラー'),
      v('accessible', 'バリアフリー対応の'), v('pet-friendly', 'ペット同伴可の'), v('Wi-Fi', 'Wi-Fi'), v('swimming pool', 'プール'),
      v('balcony', 'バルコニー'), v('cot', 'ベビーベッド'), v('room service', 'ルームサービス'), v('buffet', 'ビュッフェ'),
    ],
    essentials: [
      v('passport', 'パスポート'), v('tickets', 'チケット'), v('boarding pass', '搭乗券'), v('currency', '通貨・外貨'),
      v('travel adaptor', '旅行用変換プラグ'), v('charger', '充電器'), v('phrasebook', '旅行会話集'), v('sunscreen', '日焼け止め'),
    ],
    verbs: [
      v('to book a flight', 'フライトを予約する'), v('to make a reservation', '予約する'), v('to go on holiday', '休暇に行く'),
      v('to rent a cottage', 'コテージを借りる'), v('to stay in a hotel', 'ホテルに滞在する'), v('to book a pitch', 'テント区画を予約する'),
      v('to pack (a suitcase)', 'スーツケースに荷造りする'), v('to change money', '両替する'), v('to go abroad', '海外に行く'),
      v('to hire a car', 'レンタカーを借りる'), v('to check in', 'チェックインする'), v('to check out', 'チェックアウトする'),
    ],
    activities: [
      v('surfing', 'サーフィン'), v('water-skiing', '水上スキー'), v('kayaking', 'カヤック'), v('windsurfing', 'ウインドサーフィン'),
      v('sail', '帆'), v('board', 'ボード'), v('life jacket', '救命胴衣'), v('paragliding', 'パラグライダー'), v('swimming', '水泳'),
      v('snorkelling', 'シュノーケリング'), v('scuba diving', 'スキューバダイビング'), v('hiking', 'ハイキング'), v('playing golf', 'ゴルフをすること'),
      v('rock climbing', 'ロッククライミング'), v('snowboarding', 'スノーボード'), v('skiing', 'スキー'),
    ],
    sightseeing: [
      v('tourist map', '観光地図'), v('tourist office', '観光案内所'),
      v('guided tour', 'ガイド付きツアー'), v('museum', '博物館'), v('art gallery', '美術館'), v('craft market', '工芸品市場'),
      v('castle', '城'), v('palace', '宮殿'), v('church', '教会'),
      v('gardens', '庭園'), v('water park', 'ウォーターパーク'), v('boat trip', 'ボートツアー'), v('wildlife park', '野生動物公園'),
      v('mountains', '山・山脈'), v('island', '島'), v('beach', 'ビーチ'), v('lighthouse', '灯台'), v('pier', '桟橋'),
    ],
  },

  73: {
    types: [
      v('beach holiday', 'ビーチ休暇'), v('city break', '都市への短期旅行'), v('spa break', 'スパ休暇'),
      v('winter sports holiday', 'ウィンタースポーツ休暇'), v('camper van holiday', 'キャンピングカー旅行'), v('camping trip', 'キャンプ旅行'),
      v('hiking tour', 'ハイキングツアー'), v('cruise', 'クルーズ'), v('safari', 'サファリ'), v('all-inclusive', 'オールインクルーシブ'),
    ],
  },

  74: {
    vocabulary: [
      v('registration form', '宿泊登録カード'),
      v('double room', 'ダブルルーム'),
      v('twin beds', 'ツインベッド'),
      v('club sandwich', 'クラブサンドイッチ'),
      v('shower', 'シャワー'),
      v('key card', 'カードキー'),
      v('luggage', '荷物'),
      v('pillows', '枕'),
      v('lamp', 'ランプ'),
      v('towels', 'タオル'),
      v('hairdryer', 'ドライヤー'),
    ],
  },
}
