/** Chapter 32 · Sports events. */
export const sportsEventsLesson = {
  id: 'sports-events',
  kind: 'sports-events',
  number: '32',
  title: 'なぜ「スポーツイベントで使う英語」を学ぶのでしょうか？',
  enTitle: 'Sports events',
  ja: 'チケットや放送を確認し、試合を見ながら自然に応援するための英語を学びます。',
  cando: 'スポーツイベントのチケットや放送について尋ね、試合中に応援や反応を短く伝えられる。',
  learn: {
    intro: [
      'スポーツ観戦は、ただ試合を見るだけではありません。チケットを買ったり、試合の時間を確認したり、どこで放送されるのかを尋ねたりすることがあります。',
      'そして試合が始まると、応援したり、驚いたり、喜んだりしながら、周りの人たちとその瞬間を共有します。',
      'この章では、チケットや放送についての表現と、試合を見ながら自然に応援する表現を学びます。',
    ],
    functions: [
      ['01', 'チケットを確認する'],
      ['02', '放送を尋ねる'],
      ['03', '応援する'],
      ['04', '感情を共有する'],
    ],
    tickets: {
      title: 'チケットを買う・質問する',
      enTitle: 'Buying tickets',
      intro: '試合を見に行く計画を立て、発売日や残席、割引、座席について確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Fancy going to watch the golf tournament?', meaning: 'ゴルフトーナメントを見に行かない？', context: '観戦に誘う', register: 'casual' },
        { phrase: 'Yes! When do tickets go on sale?', meaning: 'うん！チケットはいつ発売されるの？', context: '発売日を尋ねる', register: 'casual' },
        { phrase: "Tonight. I think they'll sell out fast!", meaning: '今夜だよ。すぐに売り切れると思う！', context: '売り切れを予想する', register: 'casual' },
        { phrase: 'Any seats left for the tennis final today?', meaning: '今日のテニスの決勝戦、まだ席は残っていますか？', context: '残席を確認する', register: 'polite' },
        { phrase: "Yes, there are a few. You're just in time!", meaning: 'はい、少しありますよ。ちょうど間に合いましたね！', context: '残席を答える', register: 'neutral' },
        { phrase: 'Have all the tickets sold out?', meaning: 'チケットはすべて売り切れましたか？', context: '売り切れを尋ねる', register: 'neutral' },
        { phrase: 'Can I buy a season ticket?', meaning: 'シーズンチケットは買えますか？', context: '年間・シーズン券を尋ねる', register: 'polite' },
        { phrase: 'Is there a student discount?', meaning: '学生割引はありますか？', context: '割引を確認する', register: 'polite' },
        { phrase: 'Do you have seats for disabled spectators?', meaning: '障害のある観客用の席はありますか？', context: 'アクセシブルな席を尋ねる', register: 'polite' },
      ],
      recognition: [
        { phrase: 'go on sale', meaning: '発売される', note: 'チケットや商品が販売開始になることです。' },
        { phrase: 'sell out', meaning: '売り切れる', note: 'tickets sell out のように、チケットがなくなることを表します。' },
        { phrase: 'season ticket', meaning: 'シーズンチケット', note: 'シーズン中の複数の試合を観戦できる券です。' },
      ],
    },
    watching: {
      title: 'スポーツ観戦と応援のフレーズ',
      enTitle: 'Watching sport',
      intro: '放送時間を確認し、試合中は短く力強いフレーズで選手を応援します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Are you showing the football here?', meaning: 'ここでサッカーの試合は放送していますか？', context: 'スポーツバーで放送を尋ねる', register: 'polite' },
        { phrase: 'Yes, we are. Tonight at 8.', meaning: 'はい、放送しますよ。今夜8時です。', context: '放送時間を答える', register: 'neutral' },
        { phrase: 'Are you watching the athletics?', meaning: '陸上競技を見ているの？', context: '観戦しているか尋ねる', register: 'casual' },
        { phrase: 'You bet! It starts in half an hour.', meaning: 'もちろん！あと30分で始まるよ。', context: '強く同意して時間を伝える', register: 'casual' },
        { phrase: 'Come on, guys!', meaning: 'さあ、みんな！', context: 'チームを応援する', register: 'casual' },
        { phrase: 'You can do it!', meaning: '君たちならできる！', context: '選手を励ます', register: 'casual' },
        { phrase: 'Go, Tigers!', meaning: '行け、タイガース！', context: 'チーム名で応援する', register: 'casual' },
        { phrase: 'Keep going!', meaning: 'そのまま行け！がんばれ！', context: '動きを続けるよう励ます', register: 'casual' },
        { phrase: 'Keep it up!', meaning: 'その調子だ！', context: '良いプレイをほめる', register: 'casual' },
      ],
      recognition: [
        { phrase: 'showing the football', meaning: 'サッカーを放送している', note: 'show はテレビやスクリーンで試合を流す意味でも使います。' },
        { phrase: 'You bet!', meaning: 'もちろん・当然', note: '確実な同意を表す、カジュアルで力強い返事です。' },
        { phrase: 'Keep it up!', meaning: 'その調子で続けて', note: '良い状態を保つように励ます表現です。' },
      ],
    },
    vocabulary: {
      title: 'スポーツイベントのボキャブラリー',
      enTitle: 'Vocabulary at a sports event',
      intro: 'チケット、放送、観客、応援に関する基本語彙をまとめます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'tournament', meaning: 'トーナメント・大会', context: '勝ち抜き形式などの大会', register: 'neutral' },
        { phrase: 'final', meaning: '決勝戦', context: '大会の最後の試合', register: 'neutral' },
        { phrase: 'spectator', meaning: '観客', context: '試合を見に来た人', register: 'neutral' },
        { phrase: 'season ticket', meaning: 'シーズンチケット', context: '複数試合の観戦券', register: 'neutral' },
        { phrase: 'student discount', meaning: '学生割引', context: '学生向けの安い料金', register: 'neutral' },
        { phrase: 'sell out', meaning: '売り切れる', context: 'チケットがなくなる', register: 'neutral' },
        { phrase: 'half an hour', meaning: '30分・半時間', context: '試合開始までの時間', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'spectator', meaning: '観客', note: 'stadium や会場で試合を見る人です。' },
        { phrase: 'final', meaning: '決勝', note: 'the final のように、最後の重要な試合を指します。' },
        { phrase: 'half an hour', meaning: '30分', note: '時間を自然に伝える日常的な表現です。' },
      ],
    },
    dialogues: [
      {
        id: 'tickets',
        label: 'Pattern A · Buying tickets',
        title: '観戦に誘って発売日を確認する',
        lines: [
          { speaker: 'A', en: 'Fancy going to watch the golf tournament?', ja: 'ゴルフトーナメントを見に行かない？' },
          { speaker: 'B', en: 'Yes! When do tickets go on sale?', ja: 'うん！チケットはいつ発売されるの？' },
          { speaker: 'A', en: "Tonight. I think they'll sell out fast!", ja: '今夜だよ。すぐに売り切れると思う！' },
          { speaker: 'B', en: 'I will set a reminder.', ja: 'リマインダーを設定するね。' },
        ],
      },
      {
        id: 'broadcast',
        label: 'Pattern B · Watching sport',
        title: '放送と開始時間を確認する',
        lines: [
          { speaker: 'A', en: 'Are you showing the football here?', ja: 'ここでサッカーの試合は放送していますか？' },
          { speaker: 'B', en: 'Yes, we are. Tonight at 8.', ja: 'はい、放送しますよ。今夜8時です。' },
          { speaker: 'A', en: 'Are you watching the athletics?', ja: '陸上競技を見ているの？' },
          { speaker: 'B', en: 'You bet! It starts in half an hour.', ja: 'もちろん！あと30分で始まるよ。' },
        ],
      },
      {
        id: 'cheering',
        label: 'Pattern C · Cheering',
        title: '試合中にチームを応援する',
        lines: [
          { speaker: 'A', en: 'Come on, guys!', ja: 'さあ、みんな！' },
          { speaker: 'B', en: 'You can do it!', ja: '君たちならできる！' },
          { speaker: 'A', en: 'Go, Tigers!', ja: '行け、タイガース！' },
          { speaker: 'B', en: 'Keep it up!', ja: 'その調子だ！' },
        ],
      },
    ],
    tip: 'You bet! は「もちろん、当然」と強く同意する返事です。sell out はチケットなどが売り切れること、go on sale は発売開始を表します。',
  },
  practice: {
    title: 'スポーツ観戦の英語を、声に出して応援する',
    instructions: '日本語の説明はここまで。チケット、放送、応援の短い英語を、試合の流れに合わせて声に重ねます。',
    coreHeading: 'まずは、観戦の場でそのまま使える一文から。',
    dialogueHeading: 'チケットを取り、放送を見つけ、チームを応援する。',
    dialogueDescription: '情報を尋ねる声と、試合中の短い掛け声を切り替えます。',
    finishTitle: '次に試合を観るとき、ひとつだけ英語で応援か反応をしてみましょう。',
    corePhrases: [
      { phrase: 'Fancy going to watch the golf tournament?', context: '観戦に誘う', rate: 0.78 },
      { phrase: 'When do tickets go on sale?', context: '発売日を尋ねる', rate: 0.82 },
      { phrase: "I think they'll sell out fast!", context: '売り切れを予想する', rate: 0.8 },
      { phrase: 'Any seats left for the tennis final today?', context: '残席を尋ねる', rate: 0.78 },
      { phrase: 'Are you showing the football here?', context: '放送を確認する', rate: 0.8 },
      { phrase: 'You bet!', context: '強く同意する', rate: 0.96 },
      { phrase: 'Come on, guys!', context: 'チームを応援する', rate: 0.96 },
      { phrase: 'You can do it!', context: '選手を励ます', rate: 0.94 },
      { phrase: 'Go, Tigers!', context: 'チーム名で応援する', rate: 0.98 },
      { phrase: 'Keep it up!', context: 'その調子と伝える', rate: 0.96 },
    ],
    dialogues: [
      { title: 'Buying tickets', lines: ['Fancy going to watch the golf tournament?', 'When do tickets go on sale?', "I think they'll sell out fast!", 'I will set a reminder.'] },
      { title: 'Watching sport', lines: ['Are you showing the football here?', 'Yes, we are. Tonight at 8.', 'Are you watching the athletics?', 'You bet! It starts in half an hour.'] },
      { title: 'Cheering', lines: ['Come on, guys!', 'You can do it!', 'Go, Tigers!', 'Keep it up!'] },
    ],
    natural: [
      { full: 'Would you like to go and watch the golf tournament?', natural: 'Fancy going to watch the golf tournament?' },
      { full: 'Are you going to show the football match here?', natural: 'Are you showing the football here?' },
      { full: 'They will probably be sold out quickly.', natural: "I think they'll sell out fast!" },
    ],
  },
}
