/** Chapter 51 · Starting a new job. */
export const startingNewJobLesson = {
  id: 'starting-new-job',
  kind: 'starting-new-job',
  number: '51',
  title: '第51章に入る前に：なぜ「新しい職場で使う英語」を学ぶのでしょうか？',
  enTitle: 'Starting a new job',
  ja: '初日の挨拶、仕事の準備、同僚とのやり取り、安全ルールについて話す英語を学びます。',
  cando: '新しい職場で挨拶をし、必要な質問をしながら仕事の流れとルールを確認できる。',
  learn: {
    intro: [
      '新しい仕事を始めるということは、新しい人、新しい仕組み、そして新しいルールのある環境に入ることです。初日に覚えるのは、仕事内容だけではありません。',
      '職場の流れ、パソコンなどのシステム、安全上のルール、そして同僚とのコミュニケーションについても少しずつ理解する必要があります。',
      '最初からすべてを知っている必要はありません。分からないときに、適切に質問し、必要な助けを求めることも大切な仕事のスキルです。',
    ],
    functions: [
      ['01', '初日の挨拶をする'],
      ['02', '仕事の準備をする'],
      ['03', '同僚に声をかける'],
      ['04', 'ルールと安全を確認する'],
    ],
    settingUp: {
      title: '初日の挨拶と準備',
      enTitle: 'Setting up',
      intro: '受付や上司に初日の挨拶をし、入館証、ロッカー、メールアカウントを確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "Hello, I'm Christina. It's my first day.", meaning: 'こんにちは、クリスティーナです。今日が初日です。', context: '初日の挨拶', register: 'polite' },
        { phrase: "Welcome! Here's your pass. I'll let the manager know you're here.", meaning: 'ようこそ！これが入館証です。マネージャーに来たことを伝えますね。', context: '新人を迎える', register: 'polite' },
        { phrase: 'Your supervisor will show you where everything is.', meaning: '上司がどこに何があるか案内します。', context: '職場を案内する', register: 'neutral' },
        { phrase: "Let's find you a locker.", meaning: 'あなたのロッカーを見つけましょう。', context: '仕事の準備', register: 'casual' },
        { phrase: "I've set up your email account. Can you type in a password?", meaning: 'メールアカウントを設定しました。パスワードを入力してもらえますか？', context: 'アカウントを設定する', register: 'polite' },
        { phrase: 'Okay. How long does it have to be?', meaning: 'わかりました。パスワードはどのくらいの長さが必要ですか？', context: '設定について質問する', register: 'polite' },
      ],
      recognition: [
        { phrase: 'pass', meaning: '入館証・通行証', note: '職場に入るためのカードや証明証です。' },
        { phrase: 'supervisor', meaning: '上司・監督者', note: '仕事を指示し、サポートする人です。' },
        { phrase: 'locker', meaning: 'ロッカー', note: '荷物や制服を保管する個人用の収納です。' },
        { phrase: 'type in', meaning: '入力する', note: 'パスワードや情報をキーボードで入力するときに使います。' },
      ],
    },
    colleagues: {
      title: '同僚との会話・声かけ',
      enTitle: 'Meeting colleagues',
      intro: '新しい同僚に調子を尋ね、助けを求めたり、ランチに誘ったりします。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: "How's it going so far?", meaning: 'ここまでの調子はどうですか？', context: '新人の様子を尋ねる', register: 'casual' },
        { phrase: "There's lots to remember, but I'm getting there!", meaning: '覚えることがたくさんありますが、なんとかやっています！', context: '慣れてきたと伝える', register: 'casual' },
        { phrase: 'Let me know if you get stuck.', meaning: '行き詰まったら教えてくださいね。', context: '助けを申し出る', register: 'casual' },
        { phrase: "How's your morning been?", meaning: '午前中の調子はどうでしたか？', context: '近況を尋ねる', register: 'casual' },
        { phrase: "It's great to have you on the team.", meaning: 'あなたをチームに迎えられて嬉しいです。', context: '歓迎する', register: 'casual' },
        { phrase: 'Anything you need, just ask.', meaning: '必要なものがあったら、何でも聞いてください。', context: '気遣いを伝える', register: 'casual' },
        { phrase: 'Have you got everything you need?', meaning: '必要なものはすべて揃っていますか？', context: '準備を確認する', register: 'casual' },
        { phrase: 'Have you met everybody now?', meaning: 'もうみんなには会いましたか？', context: '同僚を紹介する', register: 'casual' },
        { phrase: 'Shall we grab some lunch?', meaning: '一緒にお昼を食べに行きませんか？', context: 'ランチに誘う', register: 'casual' },
      ],
      recognition: [
        { phrase: "I'm getting there!", meaning: 'なんとかやっています・慣れてきました', note: '少しずつ進歩しているポジティブな返事です。' },
        { phrase: 'get stuck', meaning: '行き詰まる・わからなくなる', note: '作業が止まって助けが必要な状態です。' },
        { phrase: 'on the team', meaning: 'チームの一員として', note: '新しいメンバーを歓迎するときに使います。' },
      ],
    },
    routines: {
      title: '職場のルールと安全',
      enTitle: 'Health & Safety · Workplace routines',
      intro: '休憩、シフト、退勤の打刻、安全規則を確認して、安心して仕事を始めます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Your first break is at 12.30.', meaning: '最初の休憩は12時30分です。', context: '休憩時間を伝える', register: 'neutral' },
        { phrase: "You'll need to clock out at the end of your shift.", meaning: 'シフトの終わりには退勤を打刻する必要があります。', context: '退勤のルール', register: 'neutral' },
        { phrase: 'You need to read these safety rules carefully.', meaning: 'これらの安全規則を注意深く読む必要があります。', context: '安全規則を確認する', register: 'polite' },
        { phrase: 'And always wear your hard hat!', meaning: 'そして、常にヘルメットを着用してください！', context: '安全装備を指示する', register: 'polite' },
        { phrase: "I'm stuck. Could you show me what to do?", meaning: '行き詰まってしまいました。どうすればよいか教えていただけますか？', context: '助けを求める', register: 'polite' },
      ],
      recognition: [
        { phrase: 'clock in / clock out', meaning: '出勤・退勤を打刻する', note: '勤務の開始と終了を記録します。' },
        { phrase: 'shift', meaning: '勤務シフト', note: '交代制の勤務時間や、その時間帯を指します。' },
        { phrase: 'hard hat', meaning: 'ヘルメット・安全帽', note: '工事現場などで頭を守る安全装備です。' },
      ],
    },
    vocabulary: {
      title: '新しい職場のボキャブラリー',
      enTitle: 'Vocabulary · Starting a new job',
      intro: '初日の案内、仕事の設定、同僚との会話、ルールで使う基本語彙を整理します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'pass', meaning: '入館証・通行証', context: '職場への入館', register: 'neutral' },
        { phrase: 'supervisor', meaning: '上司・監督者', context: '仕事の案内役', register: 'neutral' },
        { phrase: 'locker', meaning: 'ロッカー', context: '荷物を置く場所', register: 'neutral' },
        { phrase: 'email account', meaning: 'メールアカウント', context: '仕事のシステム', register: 'neutral' },
        { phrase: 'break', meaning: '休憩', context: '勤務中の休み', register: 'neutral' },
        { phrase: 'shift', meaning: 'シフト', context: '勤務時間', register: 'neutral' },
        { phrase: 'safety rules', meaning: '安全規則', context: '職場のルール', register: 'neutral' },
        { phrase: 'hard hat', meaning: 'ヘルメット', context: '安全装備', register: 'neutral' },
        { phrase: 'get stuck', meaning: '行き詰まる', context: '助けが必要な状態', register: 'friendly' },
        { phrase: 'clock out', meaning: '退勤を打刻する', context: 'シフトの終了', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'getting there', meaning: '少しずつ慣れている', note: "I'm getting there! の一部として覚えます。" },
        { phrase: 'type in a password', meaning: 'パスワードを入力する', note: '新しいアカウントを設定するときの表現です。' },
        { phrase: 'grab some lunch', meaning: '軽くランチを食べる', note: '同僚を気軽に誘う表現です。' },
      ],
    },
    dialogues: [
      {
        id: 'first-day',
        label: 'Pattern A · First day',
        title: '初日に挨拶をして職場を案内してもらう',
        lines: [
          { speaker: 'A', en: "Hello, I'm Christina. It's my first day.", ja: 'こんにちは、クリスティーナです。今日が初日です。' },
          { speaker: 'B', en: "Welcome! Here's your pass. I'll let the manager know you're here.", ja: 'ようこそ！これが入館証です。マネージャーに伝えますね。' },
          { speaker: 'A', en: 'Your supervisor will show you where everything is.', ja: '上司がどこに何があるか案内します。' },
          { speaker: 'B', en: "Let's find you a locker.", ja: 'あなたのロッカーを見つけましょう。' },
        ],
      },
      {
        id: 'colleagues',
        label: 'Pattern B · Meeting colleagues',
        title: '同僚に声をかけてランチに誘う',
        lines: [
          { speaker: 'A', en: "How's it going so far?", ja: 'ここまでの調子はどうですか？' },
          { speaker: 'B', en: "There's lots to remember, but I'm getting there!", ja: '覚えることがたくさんありますが、なんとかやっています！' },
          { speaker: 'A', en: 'Let me know if you get stuck.', ja: '行き詰まったら教えてくださいね。' },
          { speaker: 'B', en: 'Shall we grab some lunch?', ja: '一緒にお昼を食べに行きませんか？' },
        ],
      },
      {
        id: 'safety',
        label: 'Pattern C · Routines and safety',
        title: '勤務ルールと安全規則を確認する',
        lines: [
          { speaker: 'A', en: 'Your first break is at 12.30.', ja: '最初の休憩は12時30分です。' },
          { speaker: 'B', en: "You'll need to clock out at the end of your shift.", ja: 'シフトの終わりには退勤を打刻する必要があります。' },
          { speaker: 'A', en: 'You need to read these safety rules carefully.', ja: 'これらの安全規則を注意深く読む必要があります。' },
          { speaker: 'B', en: 'And always wear your hard hat!', ja: 'そして、常にヘルメットを着用してください！' },
        ],
      },
    ],
    tip: "I'm getting there! は、新しい仕事を覚えている途中で「少しずつ慣れてきました」と伝える前向きな表現です。get stuck は「行き詰まる」、clock in / clock out は出退勤を打刻するという意味です。わからないときは、I'm stuck. と言って助けを求めましょう。",
  },
  practice: {
    title: '新しい職場で、質問しながら慣れていく',
    instructions: '日本語訳は見ずに、初日の挨拶、同僚への声かけ、助けの求め方、安全ルールを声に重ねます。',
    coreHeading: 'まずは、新しい職場でそのまま使える一文から。',
    dialogueHeading: '初日、同僚、ルール確認の場面で役を切り替える。',
    dialogueDescription: '初日に挨拶をする、同僚と話す、安全と勤務ルールを確認する3つの場面を練習します。',
    finishTitle: '次に新しい環境へ入るとき、分からないことを英語でひとつ質問してみましょう。',
    corePhrases: [
      { phrase: "Hello, I'm Christina. It's my first day.", context: '初日の挨拶', rate: 0.8 },
      { phrase: "Welcome! Here's your pass.", context: '新人を迎える', rate: 0.82 },
      { phrase: 'Your supervisor will show you where everything is.', context: '職場を案内する', rate: 0.76 },
      { phrase: "I've set up your email account. Can you type in a password?", context: 'アカウントを設定する', rate: 0.74 },
      { phrase: 'How long does it have to be?', context: '設定について質問する', rate: 0.82 },
      { phrase: "How's it going so far?", context: '新人の様子を尋ねる', rate: 0.82 },
      { phrase: "There's lots to remember, but I'm getting there!", context: '慣れてきたと伝える', rate: 0.76 },
      { phrase: 'Let me know if you get stuck.', context: '助けを申し出る', rate: 0.82 },
      { phrase: "It's great to have you on the team.", context: '歓迎する', rate: 0.8 },
      { phrase: 'Shall we grab some lunch?', context: 'ランチに誘う', rate: 0.84 },
      { phrase: "You'll need to clock out at the end of your shift.", context: '退勤のルール', rate: 0.74 },
      { phrase: 'You need to read these safety rules carefully.', context: '安全規則を確認する', rate: 0.76 },
      { phrase: 'And always wear your hard hat!', context: '安全装備を指示する', rate: 0.82 },
      { phrase: "I'm stuck. Could you show me what to do?", context: '助けを求める', rate: 0.78 },
    ],
    dialogues: [
      { title: 'First day', lines: ["Hello, I'm Christina. It's my first day.", "Welcome! Here's your pass. I'll let the manager know you're here.", 'Your supervisor will show you where everything is.', "Let's find you a locker."] },
      { title: 'Meeting colleagues', lines: ["How's it going so far?", "There's lots to remember, but I'm getting there!", 'Let me know if you get stuck.', 'Shall we grab some lunch?'] },
      { title: 'Routines and safety', lines: ['Your first break is at 12.30.', "You'll need to clock out at the end of your shift.", 'You need to read these safety rules carefully.', 'And always wear your hard hat!'] },
    ],
    natural: [
      { full: 'I am gradually understanding everything.', natural: "I'm getting there!" },
      { full: 'Tell me if you become unable to continue.', natural: 'Let me know if you get stuck.' },
      { full: 'Shall we go and eat a quick lunch?', natural: 'Shall we grab some lunch?' },
    ],
  },
}
