/** Chapter 36 · At the supermarket. */
export const supermarketLesson = {
  id: 'supermarket',
  kind: 'supermarket',
  number: '36',
  title: '第36章に入る前に：なぜ「スーパーマーケットで使う英語」を学ぶのでしょうか？',
  enTitle: 'At the supermarket',
  ja: '商品を探し、レジやセルフレジでやり取りし、買い物中の問題に対応する英語を学びます。',
  cando: 'スーパーで商品や売り場を尋ね、レジで支払い、トラブルが起きたときに助けを求められる。',
  learn: {
    intro: [
      'スーパーマーケットはとても身近な場所ですが、実際には小さなコミュニケーションがたくさんあります。商品を探したり、在庫があるか尋ねたり、カウンターで注文したり、レジでの質問に答えたり、問題が起きたときに助けを求めたりすることがあります。',
      '使う英語はそれほど難しくありませんが、こうした表現を身につけることで、日常生活の中で自分の力で行動できる場面が増えていきます。',
      'この章では、商品の尋ね方、レジでのやり取り、セルフレジの使い方、そして買い物中によくあるトラブルへの対応を学びます。',
    ],
    functions: [
      ['01', '商品を見つける'],
      ['02', '在庫を確認する'],
      ['03', 'レジで支払う'],
      ['04', '問題を伝える'],
    ],
    asking: {
      title: '商品の場所を尋ねる・お願いする',
      enTitle: 'Asking for things',
      intro: '探している商品が見つからないときや、デリ・カウンターで注文するときに使います。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'Excuse me, where are the cereals?', meaning: 'すみません、シリアルはどこですか？', context: '商品の場所を聞く', register: 'polite' },
        { phrase: "You'll find them in aisle 10.", meaning: '10番通路にありますよ。', context: '売り場を案内する', register: 'neutral' },
        { phrase: "I can't find the pet food.", meaning: 'ペットフードが見つかりません。', context: '商品を探していると伝える', register: 'neutral' },
        { phrase: "It's right here, at the end of this aisle.", meaning: 'すぐここ、この通路の突き当たりにあります。', context: '場所を詳しく案内する', register: 'neutral' },
        { phrase: 'Do you stock oat milk here?', meaning: 'ここにオーツミルクは置いてありますか？', context: '商品を扱っているか尋ねる', register: 'polite' },
        { phrase: "Yes, it's in that fridge just over there.", meaning: 'はい、あそこの冷蔵庫にあります。', context: '在庫の場所を案内する', register: 'neutral' },
        { phrase: 'How many slices of ham?', meaning: 'ハムは何枚にしますか？', context: 'カウンターで量を確認する', register: 'neutral' },
        { phrase: "I'd like eight, please.", meaning: '8枚お願いします。', context: '枚数を注文する', register: 'polite' },
        { phrase: 'Do you have any more baguettes?', meaning: 'バゲットはもっとありますか？', context: '追加の在庫を尋ねる', register: 'polite' },
        { phrase: "Just a moment, I'll get some for you.", meaning: '少々お待ちください、取ってきますね。', context: '在庫を取りに行く', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'aisle', meaning: '通路・売り場', note: '発音は「アイル」。s は発音しません。' },
        { phrase: 'stock', meaning: '在庫として置く・扱う', note: 'Do you stock ...? で「〜は置いてありますか？」です。' },
        { phrase: 'deli', meaning: 'デリ・惣菜売り場', note: 'delicatessen の短い形です。' },
      ],
    },
    checkout: {
      title: 'レジでのやり取り・セルフレジ',
      enTitle: 'At the checkout',
      intro: '有人レジ、セルフレジ、カード端末で聞こえる表現を一つの流れで練習します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Do you need a bag?', meaning: '袋はいりますか？', context: 'レジで袋を確認する', register: 'neutral' },
        { phrase: "No, I've brought my own, thanks.", meaning: 'いいえ、マイバッグを持ってきました。', context: '袋を断る', register: 'polite' },
        { phrase: "That's £45.20. Have you got a loyalty card?", meaning: '45ポンド20ペンスです。ポイントカードはお持ちですか？', context: '合計とカードを確認する', register: 'neutral' },
        { phrase: 'Yes, just a second...', meaning: 'はい、ちょっと待ってください…。', context: 'カードを探す', register: 'neutral' },
        { phrase: "That's all gone through. Would you like a receipt?", meaning: '決済が完了しました。レシートはいりますか？', context: '支払い完了とレシートを確認する', register: 'neutral' },
        { phrase: "No, that's fine, thanks.", meaning: 'いいえ、結構です。ありがとう。', context: 'レシートを断る', register: 'polite' },
        { phrase: 'Would you like to use the self-checkout?', meaning: 'セルフレジをご利用になりますか？', context: 'セルフレジを案内する', register: 'polite' },
        { phrase: "No, thanks. I'm happy to wait.", meaning: 'いいえ、結構です。このまま待ちます。', context: '有人レジを選ぶ', register: 'polite' },
        { phrase: 'Please tap or insert your card into the payment device.', meaning: '支払い端末にカードをタッチするか、挿入してください。', context: 'カード端末の案内', register: 'neutral' },
        { phrase: 'Do you accept cash?', meaning: '現金は使えますか？', context: '支払い方法を尋ねる', register: 'polite' },
        { phrase: 'How much is it for a bag?', meaning: '袋はいくらですか？', context: '袋の値段を尋ねる', register: 'polite' },
        { phrase: 'Can I use these vouchers?', meaning: 'これらの割引券は使えますか？', context: 'バウチャーを使えるか尋ねる', register: 'polite' },
      ],
      recognition: [
        { phrase: 'checkout', meaning: 'レジ', note: 'スーパーで支払いをする場所を指します。' },
        { phrase: 'self-checkout', meaning: 'セルフレジ', note: '自分で商品をスキャンして支払うレジです。' },
        { phrase: 'go through', meaning: '決済が完了する', note: 'That’s all gone through. のように使います。' },
      ],
    },
    vocabulary: {
      title: '売り場のボキャブラリー',
      enTitle: 'Vocabulary · Aisles',
      intro: 'スーパーの売り場案内や通路の看板によく書かれている単語です。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'bakery', meaning: 'パン売り場', context: 'パンや焼き菓子', register: 'neutral' },
        { phrase: 'fruit', meaning: 'フルーツ', context: '果物売り場', register: 'neutral' },
        { phrase: 'vegetables', meaning: '野菜', context: '野菜売り場', register: 'neutral' },
        { phrase: 'dairy products', meaning: '乳製品', context: '牛乳やチーズなど', register: 'neutral' },
        { phrase: 'meat and poultry', meaning: '精肉と家禽肉', context: '肉や鶏肉の売り場', register: 'neutral' },
        { phrase: 'frozen food', meaning: '冷凍食品', context: '冷凍品の売り場', register: 'neutral' },
        { phrase: 'cereals', meaning: 'シリアル', context: '朝食用シリアル', register: 'neutral' },
        { phrase: 'household products', meaning: '日用品・家庭用品', context: '洗剤などの売り場', register: 'neutral' },
        { phrase: 'health and beauty', meaning: '健康・美容用品', context: '薬や美容用品', register: 'neutral' },
        { phrase: 'deli / delicatessen', meaning: 'デリ・惣菜売り場', context: '調理済み食品の売り場', register: 'neutral' },
        { phrase: 'checkout', meaning: 'レジ', context: '支払いをする場所', register: 'neutral' },
        { phrase: 'self-checkout', meaning: 'セルフレジ', context: '自分で操作するレジ', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'aisle 10', meaning: '10番通路', note: 'aisle は「アイル」と発音します。' },
        { phrase: 'dairy products', meaning: '乳製品', note: 'dairy は dairy farm のように「乳製品の」を表します。' },
        { phrase: 'poultry', meaning: '家禽肉・鶏肉', note: '肉売り場の案内で見かける単語です。' },
      ],
    },
    dialogues: [
      {
        id: 'find',
        label: 'Pattern A · Asking for things',
        title: '売り場と在庫を尋ねる',
        lines: [
          { speaker: 'A', en: 'Excuse me, where are the cereals?', ja: 'すみません、シリアルはどこですか？' },
          { speaker: 'B', en: "You'll find them in aisle 10.", ja: '10番通路にありますよ。' },
          { speaker: 'A', en: 'Do you stock oat milk here?', ja: 'ここにオーツミルクは置いてありますか？' },
          { speaker: 'B', en: "Yes, it's in that fridge just over there.", ja: 'はい、あそこの冷蔵庫にあります。' },
        ],
      },
      {
        id: 'checkout',
        label: 'Pattern B · At the checkout',
        title: 'レジで袋とポイントカードに答える',
        lines: [
          { speaker: 'A', en: 'Do you need a bag?', ja: '袋はいりますか？' },
          { speaker: 'B', en: "No, I've brought my own, thanks.", ja: 'いいえ、マイバッグを持ってきました。' },
          { speaker: 'A', en: "That's £45.20. Have you got a loyalty card?", ja: '45ポンド20ペンスです。ポイントカードはお持ちですか？' },
          { speaker: 'B', en: 'Yes, just a second...', ja: 'はい、ちょっと待ってください…。' },
        ],
      },
      {
        id: 'problem',
        label: 'Pattern C · Fixing a problem',
        title: '商品やバーコードの問題を伝える',
        lines: [
          { speaker: 'A', en: 'Excuse me, this milk carton is leaking.', ja: 'すみません、この牛乳パックは漏れています。' },
          { speaker: 'B', en: "No problem, I'll go and get another one.", ja: '問題ありません、別のものを取ってきますね。' },
          { speaker: 'A', en: "This barcode won't scan.", ja: 'このバーコードが読み取れません。' },
          { speaker: 'B', en: "Here, I'll give it a try.", ja: '貸してください、私がやってみます。' },
        ],
      },
    ],
    tip: 'aisle はスペルに s があっても「アイル」と発音します。スーパーで支払いをする場所は register より checkout と呼ぶのが一般的です。self-checkout はセルフレジ、cash register はレジの機械そのものを指します。',
  },
  practice: {
    title: 'スーパーで、必要なことを英語で伝える',
    instructions: '日本語の説明はここまで。商品を探し、レジで答え、トラブルがあれば助けを求める英語を声に重ねます。',
    coreHeading: 'まずは、スーパーでそのまま使える一文から。',
    dialogueHeading: '商品を見つけ、レジを通り、問題を解決する。',
    dialogueDescription: '売り場を尋ねる声、レジで答える声、店員に問題を知らせる声を切り替えます。',
    finishTitle: '次にスーパーへ行ったとき、ひとつだけ英語で場所か支払いを確認してみましょう。',
    corePhrases: [
      { phrase: 'Excuse me, where are the cereals?', context: '売り場を尋ねる', rate: 0.8 },
      { phrase: "You'll find them in aisle 10.", context: '通路を案内する', rate: 0.82 },
      { phrase: 'Do you stock oat milk here?', context: '在庫を尋ねる', rate: 0.8 },
      { phrase: 'How many slices of ham?', context: '枚数を確認する', rate: 0.86 },
      { phrase: 'Do you need a bag?', context: '袋を確認する', rate: 0.9 },
      { phrase: "No, I've brought my own, thanks.", context: 'マイバッグを伝える', rate: 0.8 },
      { phrase: 'Would you like to use the self-checkout?', context: 'セルフレジを案内する', rate: 0.76 },
      { phrase: 'Do you accept cash?', context: '現金を使えるか尋ねる', rate: 0.86 },
      { phrase: 'This barcode won’t scan.', context: 'バーコードの問題を伝える', rate: 0.84 },
      { phrase: 'Please tap or insert your card.', context: '端末の案内を聞く', rate: 0.78 },
    ],
    dialogues: [
      { title: 'Asking for things', lines: ['Excuse me, where are the cereals?', "You'll find them in aisle 10.", 'Do you stock oat milk here?', "Yes, it's in that fridge just over there."] },
      { title: 'At the checkout', lines: ['Do you need a bag?', "No, I've brought my own, thanks.", "That's £45.20. Have you got a loyalty card?", 'Yes, just a second...'] },
      { title: 'Fixing a problem', lines: ['Excuse me, this milk carton is leaking.', "No problem, I'll go and get another one.", "This barcode won't scan.", "Here, I'll give it a try."] },
    ],
    natural: [
      { full: 'Where can I find the cereal?', natural: 'Excuse me, where are the cereals?' },
      { full: 'The barcode does not scan.', natural: "This barcode won't scan." },
      { full: 'Would you like to use the self-service checkout?', natural: 'Would you like to use the self-checkout?' },
    ],
  },
}
