/** Chapter 70 · Taxis. */
export const taxisLesson = {
  id: 'taxis',
  kind: 'taxis',
  number: '70',
  title: '第70章に入る前に：なぜ「タクシーで使う英語」を学ぶのでしょうか？',
  enTitle: 'Taxis',
  ja: 'タクシーの乗り方や予約、乗車中のお願い、支払いに関する表現を学びます。',
  cando: '行き先、乗車・降車場所、人数、荷物、支払い方法をタクシーで正確に伝えられる。',
  learn: {
    intro: [
      'タクシーでは、短い会話の中で、行き先、時間、荷物、支払いなど必要な情報を正確に伝えることが大切です。',
      '特に知らない土地では、どこへ行きたいのか、どこで降りたいのか、どんな希望があるのかを簡単にはっきり伝えられると安心です。',
      'この章では、タクシーの乗り方や予約、乗車中のお願い、支払いに関する表現を学びます。',
    ],
    functions: [
      ['01', '行き先と降車場所を伝える'],
      ['02', '人数・時間・荷物を予約する'],
      ['03', '途中の要望や忘れ物を伝える'],
      ['04', '支払いとチップを確認する'],
    ],
    taking: {
      title: 'タクシーに乗る・拾う',
      enTitle: 'Taking a taxi',
      intro: 'タクシー乗り場を探し、住所を見せ、荷物を預け、降りる場所と料金を確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "Where's the nearest taxi rank?", meaning: '最寄りのタクシー乗り場はどこですか？', context: '乗り場を尋ねる', register: 'polite' },
        { phrase: 'The cabs wait just there, across the street.', meaning: 'タクシーならすぐそこ、道路を渡ったところで待っていますよ。', context: '乗り場を案内する', register: 'neutral' },
        { phrase: 'Can you take me to this address?', meaning: 'この住所まで行っていただけますか？', context: '行き先を伝える', register: 'polite' },
        { phrase: "No problem. Let me put your case in the boot.", meaning: '問題ありません。荷物をトランクに入れましょう。', context: '荷物を積む', register: 'friendly' },
        { phrase: 'Can you drop me here, please?', meaning: 'ここで降ろしていただけますか？', context: '降車場所を伝える', register: 'polite' },
        { phrase: 'Sure, that will be £19.10.', meaning: 'わかりました。19ポンド10ペンスになります。', context: '料金を伝える', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'taxi rank', meaning: 'タクシー乗り場', note: 'イギリス英語でよく使います。' },
        { phrase: 'cab', meaning: 'タクシー', note: 'taxi と同じ意味の口語です。' },
        { phrase: 'drop me', meaning: '私を降ろす', note: 'drop me here で「ここで降ろして」です。' },
        { phrase: 'boot', meaning: '車のトランク', note: 'アメリカ英語の trunk にあたります。' },
      ],
    },
    booking: {
      title: '事前予約をする',
      enTitle: 'Booking in advance',
      intro: '空港やホテルからの予約で、人数、時間、行き先、荷物の数を伝えます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Hello, can I book a taxi from the airport?', meaning: 'こんにちは、空港からのタクシーを予約できますか？', context: 'タクシーを予約する', register: 'polite' },
        { phrase: 'For how many people and when do you need it?', meaning: '何名様で、いつ必要ですか？', context: '人数と時間を尋ねる', register: 'polite' },
        { phrase: 'Tomorrow at 11am. There are four of us.', meaning: '明日の午前11時です。4人います。', context: '日時と人数に答える', register: 'neutral' },
        { phrase: 'Where are you travelling to?', meaning: 'どちらまで行かれますか？', context: '行き先を尋ねる', register: 'polite' },
        { phrase: 'To Evergreen Avenue.', meaning: 'エバーグリーン・アベニューまでです。', context: '行き先に答える', register: 'neutral' },
        { phrase: 'How many pieces of luggage have you got?', meaning: 'お荷物はいくつありますか？', context: '荷物の数を尋ねる', register: 'polite' },
        { phrase: 'One small suitcase and one large one.', meaning: '小さなスーツケースが1つと、大きなものが1つです。', context: '荷物の数に答える', register: 'neutral' },
        { phrase: "Okay. That's all booked for you.", meaning: 'わかりました。これで予約は完了です。', context: '予約完了を伝える', register: 'friendly' },
      ],
      recognition: [
        { phrase: 'book a taxi', meaning: 'タクシーを予約する', note: '電話やホテルで使います。' },
        { phrase: 'There are four of us', meaning: '私たちは4人です', note: '同行者の人数を伝えます。' },
        { phrase: 'pieces of luggage', meaning: '荷物の個数', note: 'スーツケースやバッグの数を数えます。' },
        { phrase: 'all booked', meaning: '予約完了', note: '予約が確定したことを伝えます。' },
      ],
    },
    extras: {
      title: '乗車中の追加フレーズ',
      enTitle: 'More phrases',
      intro: '所要時間、途中の立ち寄り、支払い、配車アプリ、忘れ物、補助犬について伝えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'How long will it take to get there?', meaning: 'そこに着くまでどのくらい時間がかかりますか？', context: '所要時間を尋ねる', register: 'polite' },
        { phrase: 'Can we make an extra stop?', meaning: '途中で1箇所、寄っていただけますか？', context: '途中の立ち寄りを頼む', register: 'polite' },
        { phrase: 'Keep the change.', meaning: 'お釣りは取っておいてください。', context: 'チップを渡す', register: 'friendly' },
        { phrase: 'Can I pay with contactless?', meaning: 'タッチ決済で支払えますか？', context: '支払い方法を尋ねる', register: 'polite' },
        { phrase: 'How soon will the cab be here?', meaning: 'タクシーはあとどのくらいでここに来ますか？', context: '到着時間を尋ねる', register: 'polite' },
        { phrase: "I'll book a ride-share via the app.", meaning: 'アプリでライドシェアを予約するよ。', context: '配車アプリを使う', register: 'casual' },
        { phrase: 'I left my laptop in one of your taxis.', meaning: 'お宅のタクシーの1台にノートパソコンを置き忘れてしまいました。', context: '忘れ物を伝える', register: 'polite' },
        { phrase: "I'm travelling with my assistance dog.", meaning: 'ほじょ犬と一緒に乗車します。', context: '補助犬を伝える', register: 'polite' },
      ],
      recognition: [
        { phrase: 'extra stop', meaning: '追加の立ち寄り', note: '途中で別の場所に寄るときに使います。' },
        { phrase: 'keep the change', meaning: 'お釣りは取っておいて', note: 'チップを渡す定番表現です。' },
        { phrase: 'contactless', meaning: 'タッチ決済', note: 'カードやスマホをかざす支払いです。' },
        { phrase: 'assistance dog', meaning: '補助犬', note: '介助犬・盲導犬などを表します。' },
      ],
    },
    vocabulary: {
      title: 'タクシーのボキャブラリー',
      enTitle: 'Vocabulary · Taxis',
      intro: '乗り場、車内、荷物、支払い、配車に関する単語を整理します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'taxi', meaning: 'タクシー', context: '乗り物', register: 'neutral' },
        { phrase: 'cab', meaning: 'タクシー', context: '乗り物', register: 'casual' },
        { phrase: 'taxi rank', meaning: 'タクシー乗り場', context: '場所', register: 'regional' },
        { phrase: 'address', meaning: '住所', context: '行き先', register: 'neutral' },
        { phrase: 'boot', meaning: 'トランク', context: '車の設備', register: 'regional' },
        { phrase: 'case', meaning: 'スーツケース・荷物', context: '荷物', register: 'neutral' },
        { phrase: 'luggage', meaning: '手荷物・荷物', context: '荷物', register: 'neutral' },
        { phrase: 'fare', meaning: '運賃', context: '支払い', register: 'neutral' },
        { phrase: 'contactless', meaning: 'タッチ決済', context: '支払い', register: 'regional' },
        { phrase: 'ride-share', meaning: 'ライドシェア・配車サービス', context: '配車', register: 'neutral' },
        { phrase: 'assistance dog', meaning: '補助犬', context: '乗車サポート', register: 'neutral' },
        { phrase: 'change', meaning: 'お釣り', context: '支払い', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'taxi / cab', meaning: 'タクシー', note: 'cab は親しみのある口語です。' },
        { phrase: 'boot', meaning: 'トランク', note: 'イギリス英語の表現です。' },
        { phrase: 'fare', meaning: '運賃', note: '料金を確認するときに使います。' },
        { phrase: 'ride-share', meaning: '配車サービス', note: 'アプリで車を呼ぶサービスです。' },
      ],
    },
    dialogues: [
      {
        id: 'taking',
        label: 'Pattern A · Taking a taxi',
        title: '住所を見せて乗車する',
        lines: [
          { speaker: 'A', en: 'Can you take me to this address?', ja: 'この住所まで行っていただけますか？' },
          { speaker: 'B', en: "No problem. Let me put your case in the boot.", ja: '問題ありません。荷物をトランクに入れましょう。' },
          { speaker: 'A', en: 'How long will it take to get there?', ja: 'そこに着くまでどのくらいかかりますか？' },
          { speaker: 'B', en: 'Sure, that will be £19.10.', ja: 'わかりました。19ポンド10ペンスになります。' },
        ],
      },
      {
        id: 'booking',
        label: 'Pattern B · Booking in advance',
        title: '人数と荷物を伝えて予約する',
        lines: [
          { speaker: 'A', en: 'Hello, can I book a taxi from the airport?', ja: 'こんにちは、空港からのタクシーを予約できますか？' },
          { speaker: 'B', en: 'For how many people and when do you need it?', ja: '何名様で、いつ必要ですか？' },
          { speaker: 'A', en: 'Tomorrow at 11am. There are four of us.', ja: '明日の午前11時です。4人います。' },
          { speaker: 'B', en: "Okay. That's all booked for you.", ja: 'わかりました。これで予約は完了です。' },
        ],
      },
      {
        id: 'extras',
        label: 'Pattern C · More phrases',
        title: '支払いと乗車中の希望を伝える',
        lines: [
          { speaker: 'A', en: 'Can we make an extra stop?', ja: '途中で1箇所、寄っていただけますか？' },
          { speaker: 'B', en: 'Of course.', ja: 'もちろんです。' },
          { speaker: 'A', en: 'Can I pay with contactless?', ja: 'タッチ決済で支払えますか？' },
          { speaker: 'B', en: 'Keep the change.', ja: 'お釣りは取っておいてください。' },
        ],
      },
    ],
    tip: 'taxi と cab はどちらもタクシーですが、cab は口語でよく使います。イギリス英語のトランクは boot、チップとしてお釣りを渡すときは Keep the change、タッチ決済は contactless と言います。',
  },
  practice: {
    title: 'タクシーの行き先と希望を、英語で伝える',
    instructions: '日本語訳は見ずに、行き先、予約、荷物、支払い、乗車中のお願いを声に重ねます。',
    coreHeading: 'まずは、住所まで行けるか尋ねる一文から。',
    dialogueHeading: '乗車、事前予約、追加のお願いで役を切り替える。',
    dialogueDescription: '住所と所要時間を確認する、人数と荷物を伝えて予約する、支払いと途中の要望を伝える3つの場面を練習します。',
    finishTitle: '次にタクシーに乗るとき、行き先か支払いの英語をひとつ使ってみましょう。',
    corePhrases: [
      { phrase: "Where's the nearest taxi rank?", context: '乗り場を尋ねる', rate: 0.82 },
      { phrase: 'Can you take me to this address?', context: '行き先を伝える', rate: 0.8 },
      { phrase: 'Can you drop me here, please?', context: '降車場所を伝える', rate: 0.82 },
      { phrase: 'How long will it take to get there?', context: '所要時間を尋ねる', rate: 0.78 },
      { phrase: 'Hello, can I book a taxi from the airport?', context: '事前予約をする', rate: 0.76 },
      { phrase: 'For how many people and when do you need it?', context: '人数と時間を尋ねる', rate: 0.72 },
      { phrase: 'How many pieces of luggage have you got?', context: '荷物の数を尋ねる', rate: 0.72 },
      { phrase: "Okay. That's all booked for you.", context: '予約完了を伝える', rate: 0.78 },
      { phrase: 'Can we make an extra stop?', context: '途中の立ち寄りを頼む', rate: 0.82 },
      { phrase: 'Keep the change.', context: 'チップを渡す', rate: 0.9 },
      { phrase: 'Can I pay with contactless?', context: '支払い方法を尋ねる', rate: 0.8 },
      { phrase: 'I left my laptop in one of your taxis.', context: '忘れ物を伝える', rate: 0.72 },
    ],
    dialogues: [
      { title: 'Taking a taxi', lines: ['Can you take me to this address?', "No problem. Let me put your case in the boot.", 'How long will it take to get there?', 'Sure, that will be £19.10.'] },
      { title: 'Booking in advance', lines: ['Hello, can I book a taxi from the airport?', 'For how many people and when do you need it?', 'Tomorrow at 11am. There are four of us.', "Okay. That's all booked for you."] },
      { title: 'More phrases', lines: ['Can we make an extra stop?', 'Of course.', 'Can I pay with contactless?', 'Keep the change.'] },
    ],
    natural: [
      { full: 'Could you drive me to the address shown here?', natural: 'Can you take me to this address?' },
      { full: 'What is the estimated travel time to that destination?', natural: 'How long will it take to get there?' },
      { full: 'Would it be possible to pay by contactless card?', natural: 'Can I pay with contactless?' },
    ],
  },
}
