/** Chapter 28 · At the theatre. */
export const theatreLesson = {
  id: 'theatre',
  kind: 'theatre',
  number: '28',
  title: 'なぜ「劇場で使う英語」を学ぶのでしょうか？',
  enTitle: 'At the theatre',
  ja: 'チケット、座席、館内案内、休憩時間、劇場の語彙を確認します。',
  cando: '劇場でチケットや席について尋ね、開演前と休憩中に必要な情報を確認できる。',
  learn: {
    intro: [
      '劇場での観劇は、映画館とは少し違います。チケットを受け取ったり、座席を確認したり、館内アナウンスを理解したり、休憩時間について知ったりする必要があります。',
      'また、劇場には、舞台、座席、演者、劇場内の場所などを表す独特の語彙があります。単語を知っていると、案内を聞いたときに場面を想像しやすくなります。',
      'この章では、公演の前や途中で必要になる実用的な英語と、劇場でよく使われる基本的な言葉を学びます。',
    ],
    functions: [
      ['01', 'チケットを受け取る'],
      ['02', '席を見つける'],
      ['03', '休憩を確認する'],
      ['04', '劇場の言葉を読む'],
    ],
    tickets: {
      title: 'チケット窓口で・その他の質問',
      enTitle: 'At the box office & more phrases',
      intro: '予約したチケットを受け取り、残っている席や公演の情報を尋ねます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "I'm picking up the tickets I ordered online.", meaning: 'ネットで注文したチケットを受け取りに来ました。', context: '予約チケットを受け取る', register: 'polite' },
        { phrase: 'Okay, I just need your booking reference.', meaning: 'わかりました、予約番号をお願いします。', context: 'スタッフが予約番号を求める', register: 'polite' },
        { phrase: 'Any seats left for tonight?', meaning: '今夜の席はまだ残っていますか？', context: '当日券の有無を尋ねる', register: 'casual' },
        { phrase: "Yes, I've just had two returns.", meaning: 'はい、ちょうど2枚のキャンセル券が出たところです。', context: '空いた席を案内する', register: 'neutral' },
        { phrase: 'When is the opening night?', meaning: '初日はいつですか？', context: '初演の日を尋ねる', register: 'polite' },
        { phrase: "I've booked seats in the stalls.", meaning: '1階席を予約しました。', context: '予約席の場所を伝える', register: 'neutral' },
        { phrase: "Is tonight's performance sold out?", meaning: '今夜の公演は売り切れですか？', context: '公演の空席を尋ねる', register: 'polite' },
        { phrase: 'Where is the cloakroom?', meaning: 'クロークはどこですか？', context: '荷物預かり所を尋ねる', register: 'polite' },
      ],
      recognition: [
        { phrase: 'booking reference', meaning: '予約番号・照会番号', note: 'オンライン予約を窓口で確認するときに使います。' },
        { phrase: 'returns', meaning: '払い戻しで戻ったチケット', note: 'キャンセルによって再び販売できる席を指します。' },
        { phrase: 'opening night', meaning: '初日・初演の夜', note: '公演が初めて上演される夜です。' },
      ],
    },
    before: {
      title: '開演前と休憩時間',
      enTitle: 'Before the performance & the interval',
      intro: '席へ案内してもらい、開演前のアナウンスと休憩時間を理解します。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Can I see your tickets, please?', meaning: 'チケットを拝見できますか？', context: 'スタッフがチケットを確認する', register: 'polite' },
        { phrase: "Follow me, you're in the front row.", meaning: 'ついてきてください、最前列ですよ。', context: '席まで案内する', register: 'neutral' },
        { phrase: 'Please switch off your phones. The show is about to start.', meaning: '携帯電話の電源をお切りください。まもなく開演いたします。', context: '開演前のアナウンス', register: 'polite' },
        { phrase: 'Is there an interval?', meaning: '休憩時間はありますか？', context: '休憩の有無を尋ねる', register: 'polite' },
        { phrase: 'How long is the interval?', meaning: '休憩時間はどのくらいですか？', context: '休憩の長さを尋ねる', register: 'polite' },
        { phrase: "It's 20 minutes. Time for a drink at the bar!", meaning: '20分です。バーで一杯飲む時間がありますね！', context: '休憩時間を答える', register: 'casual' },
      ],
      recognition: [
        { phrase: 'about to start', meaning: 'まもなく始まる', note: 'show is about to start で「公演がまもなく始まります」です。' },
        { phrase: 'interval', meaning: '劇中の休憩（UK）', note: 'アメリカ英語では intermission と言うことが多いです。' },
      ],
    },
    vocabulary: {
      title: '劇場内のボキャブラリー',
      enTitle: 'Vocabulary inside the theatre',
      intro: '劇場の構造や舞台に関わる言葉を、案内と結びつけて覚えます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'audience', meaning: '観客', context: '客席にいる人々', register: 'neutral' },
        { phrase: 'performer', meaning: '演者・パフォーマー', context: '舞台で演じる人', register: 'neutral' },
        { phrase: 'stage', meaning: 'ステージ・舞台', context: '演者が立つ場所', register: 'neutral' },
        { phrase: 'set', meaning: '舞台セット', context: '舞台上の背景や装置', register: 'neutral' },
        { phrase: 'prop', meaning: '小道具', context: '演技で使う物', register: 'neutral' },
        { phrase: 'curtain', meaning: '幕・カーテン', context: '舞台を隠す幕', register: 'neutral' },
        { phrase: 'seat / front row', meaning: '座席／最前列', context: '客席の場所', register: 'neutral' },
        { phrase: 'box', meaning: 'ボックス席・特別席', context: 'バルコニーの特別な席', register: 'neutral' },
        { phrase: 'stalls', meaning: '1階席・平土間席', context: '舞台に近い客席', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'theatre / theater', meaning: '劇場（UK / US）', note: 'イギリスでは theatre、アメリカでは theater とつづることが多いです。' },
        { phrase: 'stalls / orchestra seats', meaning: '1階席（UK / US）', note: 'アメリカでは orchestra seats と呼ばれることがあります。' },
      ],
    },
    dialogues: [
      {
        id: 'tickets',
        label: 'Pattern A · At the box office',
        title: 'チケットを受け取る',
        lines: [
          { speaker: 'A', en: "I'm picking up the tickets I ordered online.", ja: 'ネットで注文したチケットを受け取りに来ました。' },
          { speaker: 'B', en: 'Okay, I just need your booking reference.', ja: 'わかりました、予約番号をお願いします。' },
          { speaker: 'A', en: "I've booked seats in the stalls.", ja: '1階席を予約しました。' },
        ],
      },
      {
        id: 'interval',
        label: 'Pattern B · Before the performance',
        title: '席と休憩を確認する',
        lines: [
          { speaker: 'A', en: 'Can I see your tickets, please?', ja: 'チケットを拝見できますか？' },
          { speaker: 'B', en: "Follow me, you're in the front row.", ja: 'ついてきてください、最前列ですよ。' },
          { speaker: 'A', en: 'Is there an interval?', ja: '休憩時間はありますか？' },
          { speaker: 'B', en: "It's 20 minutes. Time for a drink at the bar!", ja: '20分です。バーで一杯飲む時間がありますね！' },
        ],
      },
      {
        id: 'inside',
        label: 'Pattern C · Inside the theatre',
        title: '劇場の場所を確認する',
        lines: [
          { speaker: 'A', en: 'Where is the cloakroom?', ja: 'クロークはどこですか？' },
          { speaker: 'B', en: 'It’s just beside the stalls.', ja: '1階席のすぐ隣です。' },
          { speaker: 'A', en: 'Thank you. The set looks amazing.', ja: 'ありがとうございます。舞台セットが素晴らしいですね。' },
        ],
      },
    ],
    tip: 'イギリスでは theatre、stalls、interval がよく使われます。アメリカ英語では theater、orchestra seats、intermission にあたります。',
  },
  practice: {
    title: '劇場での案内と質問を、自然に声にする',
    instructions: '日本語の説明はここまで。チケット、席、休憩、劇場内の場所を英語だけで声に重ねます。',
    coreHeading: 'まずは、劇場でそのまま使える一文から。',
    dialogueHeading: '受け取って、座って、休憩を確認する流れを感じる。',
    dialogueDescription: 'スタッフの案内を聞き、必要な場所や時間を自然な英語で尋ねます。',
    finishTitle: '次に劇場へ行ったら、ひとつだけ英語で質問してみましょう。',
    corePhrases: [
      { phrase: "I'm picking up the tickets I ordered online.", context: 'チケットを受け取る', rate: 0.78 },
      { phrase: 'I just need your booking reference.', context: '予約番号を確認する', rate: 0.8 },
      { phrase: 'Any seats left for tonight?', context: '空席を尋ねる', rate: 0.84 },
      { phrase: "I've booked seats in the stalls.", context: '席の場所を伝える', rate: 0.8 },
      { phrase: 'Can I see your tickets, please?', context: 'チケットを確認する', rate: 0.82 },
      { phrase: "You're in the front row.", context: '席へ案内する', rate: 0.86 },
      { phrase: 'Is there an interval?', context: '休憩を尋ねる', rate: 0.84 },
      { phrase: 'How long is the interval?', context: '休憩の長さを尋ねる', rate: 0.78 },
      { phrase: 'Where is the cloakroom?', context: 'クロークを尋ねる', rate: 0.82 },
      { phrase: 'The set looks amazing.', context: '舞台セットをほめる', rate: 0.84 },
    ],
    dialogues: [
      { title: 'At the box office', lines: ["I'm picking up the tickets I ordered online.", 'I just need your booking reference.', "I've booked seats in the stalls."] },
      { title: 'Before the performance', lines: ['Can I see your tickets, please?', "Follow me, you're in the front row.", 'Is there an interval?'] },
      { title: 'Inside the theatre', lines: ['Where is the cloakroom?', 'It’s just beside the stalls.', 'The set looks amazing.'] },
    ],
    natural: [
      { full: 'I am here to collect the tickets I ordered online.', natural: "I'm picking up the tickets I ordered online." },
      { full: 'Is there a break during the performance?', natural: 'Is there an interval?' },
      { full: 'The stage design looks wonderful.', natural: 'The set looks amazing.' },
    ],
  },
}
