/** Chapter 13 · Talking about the weather. */
export const weatherLesson = {
  id: 'weather',
  kind: 'weather',
  number: '13',
  title: 'なぜ「天気」について話すのでしょうか？',
  enTitle: 'Talking about the weather',
  ja: '天気を説明し、会話を始め、予報を聞き取る表現を学びます。',
  cando: '天気の様子や感想を伝え、天気をきっかけに会話を続けられる。',
  learn: {
    intro: [
      '天気は、誰もが毎日経験するものなので、相手と共有しやすい話題の一つです。天気について話すとき、必ずしも重要な情報を交換しているわけではありません。多くの場合、自然に会話を始めたり、会話を続けたりするためのきっかけとして使われます。',
      'また、天気は常に変化するため、今の状況を説明したり、それについて感想を言ったり、これからどうなるかを話したりする練習にも適しています。',
      'この章では、天気の説明の仕方、スモールトークでの使い方、そして天気予報でよく使われる表現を学びます。',
    ],
    functions: [
      ['01', '天気をたずねる'],
      ['02', '感想を伝える'],
      ['03', '会話を続ける'],
      ['04', '予報を聞き取る'],
    ],
    describe: {
      title: '天気のたずね方と答え方',
      enTitle: 'Describing the weather',
      intro: '今日の天気や旅行先の様子をたずね、感じたことまで一緒に伝えます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: "What's the weather like out there?", meaning: 'そっちの天気はどうですか？', context: '今の天気をたずねる', register: 'neutral' },
        { phrase: 'How was the weather on your holiday?', meaning: '旅行中の天気はどうでしたか？', context: '過去の天気をたずねる', register: 'neutral' },
        { phrase: "What's the temperature like?", meaning: '気温はどのくらいですか？', context: '気温をたずねる', register: 'neutral' },
        { phrase: "It's boiling! Over 30 degrees every day.", meaning: '猛暑です！毎日30度超えですよ。', context: '暑さを強調する', register: 'casual' },
        { phrase: 'A bit mixed — the usual sunshine and showers!', meaning: '少し不安定でした。晴れたり、にわか雨が降ったりです！', context: '変わりやすい天気を伝える', register: 'casual' },
        { phrase: "It's freezing outside!", meaning: '外は凍えるほど寒いです！', context: '寒さを強調する', register: 'neutral' },
        { phrase: "It's really windy!", meaning: 'すごく風が強いです！', context: '風の強さを伝える', register: 'neutral' },
        { phrase: "It's absolutely pouring!", meaning: '完全に土砂降りです！', context: '強い雨を伝える', register: 'casual' },
        { phrase: "It's blowing a gale out there!", meaning: '外は強風が吹いています！', context: '暴風を強調する', register: 'casual' },
      ],
      recognition: [
        { phrase: 'mixed', meaning: '変わりやすい／不安定な天気。', note: 'sunshine and showers のように、晴れと雨が入れ替わる様子です。' },
        { phrase: 'a gale', meaning: '強風、大風。', note: 'blowing a gale は「強い風が吹いている」という言い方です。' },
      ],
    },
    smallTalk: {
      title: '天気を話題にしたスモールトーク',
      enTitle: 'Making small talk',
      intro: '天気の話を入口にして、相手と気持ちを共有します。付加疑問文を使うと、自然に返事を促せます。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: "Lovely weather, isn't it?", meaning: 'いいお天気ですよね？', context: '晴れた日に話しかける', register: 'casual' },
        { phrase: "It's a bit chilly today, isn't it?", meaning: '今日は少し肌寒いですよね？', context: '肌寒さを共有する', register: 'neutral' },
        { phrase: "Yes, the weather's turned, hasn't it?", meaning: 'ええ、天気が変わりましたね？', context: '急な天気の変化に反応する', register: 'neutral' },
      ],
      recognition: [
        { phrase: "Yes, beautiful! / Yes, it is.", meaning: 'ええ、素晴らしいですね。／ええ、そうですね。', note: 'Lovely weather, isn’t it? と聞かれたときの自然な返しです。' },
      ],
    },
    forecast: {
      title: '天気予報の表現',
      enTitle: 'The weather forecast',
      intro: 'ニュースや天気アプリで聞こえてくる、少しまとまった予報の表現を読み、音の流れに慣れます。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: "Here's the forecast for tomorrow...", meaning: '明日の天気予報です…', context: '予報を始める', register: 'neutral' },
        { phrase: '...it will be mainly cloudy...', meaning: '…概ねくもりでしょう…', context: '主な空模様', register: 'neutral' },
        { phrase: '...with a few sunny spells...', meaning: '…所により晴れ間が見えるでしょう…', context: '雲の合間の晴れ間', register: 'neutral' },
        { phrase: '...and a slight chance of a shower...', meaning: '…にわか雨の可能性が少しあります…', context: '雨の可能性', register: 'neutral' },
        { phrase: '...with temperatures a little below normal.', meaning: '…気温は平年より少し低めでしょう。', context: '平年との比較', register: 'neutral' },
        { phrase: "Today we'll see scattered showers.", meaning: '今日は所によりにわか雨が降るでしょう。', context: '所により雨が降る', register: 'neutral' },
        { phrase: 'Mist and fog will form later.', meaning: '後ほど、もやと霧が発生するでしょう。', context: '霧の予報', register: 'neutral' },
        { phrase: "There'll be plenty of warm sunshine.", meaning: 'たっぷりの暖かな日差しがあるでしょう。', context: '晴れの予報', register: 'neutral' },
        { phrase: 'Snow is expected.', meaning: '雪が予想されます。', context: '雪の予報', register: 'neutral' },
        { phrase: 'Temperatures are above average for the time of year.', meaning: '気温はこの時期の平均より高いでしょう。', context: '平年より高い気温', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'sunny spells', meaning: '雲の合間から見える晴れ間。', note: '天気予報でよく使われる、短い晴れの時間を表す表現です。' },
        { phrase: 'scattered showers', meaning: '所により降るにわか雨。', note: 'scattered は「散らばった」から「所により」という意味になります。' },
      ],
    },
    dialogues: [
      {
        id: 'weather-now',
        label: 'Pattern A · Ask and answer',
        title: '今の天気を話す',
        lines: [
          { speaker: 'A', en: "What's the weather like out there?", ja: 'そっちの天気はどうですか？' },
          { speaker: 'B', en: 'A bit mixed — the usual sunshine and showers!', ja: '少し不安定です。晴れたり、にわか雨が降ったりです！' },
        ],
      },
      {
        id: 'weather-chat',
        label: 'Pattern B · Make small talk',
        title: '天気をきっかけに話す',
        lines: [
          { speaker: 'A', en: "Lovely weather, isn't it?", ja: 'いいお天気ですよね？' },
          { speaker: 'B', en: 'Yes, beautiful!', ja: 'ええ、素晴らしいですね！' },
        ],
      },
      {
        id: 'weather-forecast',
        label: 'Pattern C · Hear a forecast',
        title: '予報を聞き取る',
        lines: [
          { speaker: 'A', en: "Here's the forecast for tomorrow...", ja: '明日の天気予報です…' },
          { speaker: 'B', en: 'Mainly cloudy, with a few sunny spells.', ja: '概ねくもりで、所により晴れ間が見えるでしょう。' },
        ],
      },
    ],
    tip: '天気の会話は、情報交換だけではありません。Lovely weather, isn’t it? と話しかけられたら、Yes, beautiful! や Yes, it is. と笑顔で返すだけでも、相手に「友好的に話したい」というサインを返せます。まずは短い返事を一つストックしておきましょう。',
  },
  practice: {
    title: '天気をきっかけに、会話を続ける',
    instructions: '日本語の説明はここまで。天気をたずね、感想を返し、予報のまとまりを英語のリズムで声に重ねます。',
    coreHeading: 'まずは、天気の短いまとまりを声にする。',
    dialogueHeading: '天気をたずねて、自然に返す。',
    dialogueDescription: '今の天気、スモールトーク、明日の予報を英語だけで練習します。',
    finishTitle: '明日、天気についてひとこと英語で話してみましょう。',
    corePhrases: [
      { phrase: "What's the weather like out there?", context: '天気をたずねる', rate: 0.82 },
      { phrase: "It's boiling!", context: '暑さを伝える', rate: 0.86 },
      { phrase: 'A bit mixed — sunshine and showers.', context: '不安定な天気を伝える', rate: 0.78 },
      { phrase: "It's freezing outside!", context: '寒さを伝える', rate: 0.82 },
      { phrase: "It's absolutely pouring!", context: '強い雨を伝える', rate: 0.8 },
      { phrase: "Lovely weather, isn't it?", context: 'スモールトークを始める', rate: 0.82 },
      { phrase: 'Yes, beautiful!', context: '天気に返事する', rate: 0.88 },
      { phrase: "Here's the forecast for tomorrow.", context: '予報を始める', rate: 0.8 },
      { phrase: 'Mainly cloudy, with a few sunny spells.', context: '予報を伝える', rate: 0.76 },
      { phrase: 'Snow is expected.', context: '雪の予報を伝える', rate: 0.84 },
    ],
    dialogues: [
      { title: 'Ask and answer', lines: ["What's the weather like out there?", 'A bit mixed — the usual sunshine and showers!'] },
      { title: 'Make small talk', lines: ["Lovely weather, isn't it?", 'Yes, beautiful!'] },
      { title: 'Hear a forecast', lines: ["Here's the forecast for tomorrow...", 'Mainly cloudy, with a few sunny spells.'] },
    ],
    natural: [
      { full: 'The weather is very rainy.', natural: "It's absolutely pouring!" },
      { full: 'The weather has changed, has it not?', natural: "The weather's turned, hasn't it?" },
      { full: 'There will be some sunny periods.', natural: "There'll be a few sunny spells." },
    ],
  },
}
