/** Chapter 52 · In the workplace. */
export const workplaceLesson = {
  id: 'workplace',
  kind: 'workplace',
  number: '52',
  title: '第52章に入る前に：なぜ「職場で使う英語」を学ぶのでしょうか？',
  enTitle: 'In the workplace',
  ja: '職場の予定、シフト、休憩、変更、トラブルについて話す英語を学びます。',
  cando: '職場の予定やシフトを共有し、変更やトラブルを分かりやすく伝えられる。',
  learn: {
    intro: [
      '職場では、一人で仕事をするだけではなく、周りの人と予定や仕事の流れを共有しながら働きます。会議の時間を確認したり、休憩やシフトについて話したりすることも大切なコミュニケーションです。',
      '予定を変更したり、問題が起きたときに報告したりする場面もあります。大切なのは、難しい英語ではなく、必要な情報を分かりやすく伝えて周りの人と調整することです。',
      'この章では、職場での予定やシフト、休憩時間についての会話や、変更のお願い、トラブルを伝える表現について学びます。',
    ],
    functions: [
      ['01', '会議の予定を共有する'],
      ['02', '休憩とシフトを確認する'],
      ['03', '予定変更をお願いする'],
      ['04', 'トラブルを報告する'],
    ],
    routines: {
      title: '職場の日常ルーティン',
      enTitle: 'Workplace routines',
      intro: '会議の予定を共有し、手帳に書き留め、同僚と休憩時間を確認します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'We have a team meeting at 4pm on Tuesdays.', meaning: '毎週火曜日の午後4時にチームミーティングがあります。', context: '定例会議を共有する', register: 'neutral' },
        { phrase: 'And a full staff meeting once a month.', meaning: 'それから、月に1回全スタッフミーティングがあります。', context: '会議の頻度を伝える', register: 'neutral' },
        { phrase: "Thanks. I'll put it in my diary.", meaning: 'ありがとう。スケジュール帳に書いておきます。', context: '予定を記録する', register: 'casual' },
        { phrase: 'What time is your lunch break?', meaning: 'お昼休みは何時ですか？', context: '休憩時間を尋ねる', register: 'casual' },
        { phrase: "It's in half an hour. How about yours?", meaning: 'あと30分後だよ。あなたの休憩は？', context: '休憩時間を答える', register: 'casual' },
        { phrase: 'I usually take a tea break in the afternoon.', meaning: '私はたいてい午後にお茶休憩を取ります。', context: '小休憩を話す', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'diary', meaning: 'スケジュール帳・予定表', note: 'イギリス英語では日記ではなく予定表の意味でも使います。' },
        { phrase: 'full staff meeting', meaning: '全スタッフミーティング', note: '職場全体の会議を指します。' },
        { phrase: 'once a month', meaning: '月に1回', note: '会議やルーティンの頻度を表します。' },
      ],
    },
    issues: {
      title: '職場のトラブルや要望',
      enTitle: 'Workplace issues',
      intro: 'シフト変更をお願いしたり、レジやシステムの不具合を報告したりします。',
      image: '/assets/illustrations/greeting-online-wishes.svg',
      phrases: [
        { phrase: 'Sorry, I have to change my shift on Monday.', meaning: 'すみません、月曜日のシフトを変更しなければなりません。', context: 'シフト変更を切り出す', register: 'polite' },
        { phrase: 'Which one are you down for?', meaning: 'どのシフトに入ることになっていますか？', context: '担当シフトを確認する', register: 'casual' },
        { phrase: "I'm down for the morning shift. Could I change to the afternoon?", meaning: '朝のシフトに入っています。午後に変更できますか？', context: '別のシフトをお願いする', register: 'polite' },
        { phrase: 'This till is down again. It keeps crashing!', meaning: 'このレジがまた動かなくなりました。フリーズしてばかりです！', context: '機械の不具合を報告する', register: 'casual' },
        { phrase: "Not again! Okay, let's call the supervisor.", meaning: 'また！？よし、スーパーバイザーを呼ぼう。', context: 'トラブルに対応する', register: 'casual' },
        { phrase: 'Could someone cover my shift, please?', meaning: '誰か私のシフトを代わってもらえますか？', context: '代わりをお願いする', register: 'polite' },
      ],
      recognition: [
        { phrase: 'be down for', meaning: '〜に割り当てられている', note: 'シフト表に名前が載っていることを表します。' },
        { phrase: 'till', meaning: 'レジ', note: 'イギリス英語で cash register の意味です。' },
        { phrase: 'keep crashing', meaning: '何度もフリーズする', note: '機械やシステムが繰り返し落ちるときに使います。' },
      ],
    },
    vocabulary: {
      title: '職場で使うボキャブラリー',
      enTitle: 'Vocabulary · At work',
      intro: '職場のスケジュール、役職、設備、勤務時間に関する基本語彙を整理します。',
      image: '/assets/illustrations/greeting-casual-chat.svg',
      phrases: [
        { phrase: 'meeting', meaning: '会議', context: '予定・仕事の流れ', register: 'neutral' },
        { phrase: 'lunch break', meaning: '昼休み', context: '休憩時間', register: 'neutral' },
        { phrase: 'tea break', meaning: 'お茶休憩・小休憩', context: '短い休憩', register: 'neutral' },
        { phrase: 'morning shift', meaning: '朝のシフト・早番', context: '勤務時間', register: 'neutral' },
        { phrase: 'afternoon shift', meaning: '午後のシフト・遅番', context: '勤務時間', register: 'neutral' },
        { phrase: 'evening shift', meaning: '夜のシフト・夜勤', context: '勤務時間', register: 'neutral' },
        { phrase: 'manager', meaning: 'マネージャー・管理者', context: '職場の役職', register: 'neutral' },
        { phrase: 'supervisor', meaning: '指導・監督者', context: '職場の役職', register: 'neutral' },
        { phrase: 'colleague', meaning: '同僚', context: '一緒に働く人', register: 'neutral' },
        { phrase: 'team', meaning: 'チーム', context: '仕事のグループ', register: 'neutral' },
        { phrase: 'clock in / clock out', meaning: '出勤・退勤を打刻する', context: '勤務記録', register: 'neutral' },
        { phrase: 'locker', meaning: 'ロッカー', context: '職場の設備', register: 'neutral' },
      ],
      recognition: [
        { phrase: 'diary', meaning: '予定表', note: 'イギリス英語の職場では schedule book のように使います。' },
        { phrase: 'down for a shift', meaning: 'シフトに入っている', note: '担当や割り当てを確認する表現です。' },
        { phrase: 'till', meaning: 'レジ', note: '店舗でのトラブル報告によく登場します。' },
        { phrase: 'crash', meaning: 'フリーズする・突然落ちる', note: '機械やアプリの不具合に使います。' },
      ],
    },
    dialogues: [
      {
        id: 'routines',
        label: 'Pattern A · Workplace routines',
        title: '会議と休憩時間を確認する',
        lines: [
          { speaker: 'A', en: 'We have a team meeting at 4pm on Tuesdays.', ja: '毎週火曜日の午後4時にチームミーティングがあります。' },
          { speaker: 'B', en: 'And a full staff meeting once a month.', ja: 'それから、月に1回全スタッフミーティングがあります。' },
          { speaker: 'A', en: "Thanks. I'll put it in my diary.", ja: 'ありがとう。スケジュール帳に書いておきます。' },
          { speaker: 'B', en: 'What time is your lunch break?', ja: 'お昼休みは何時ですか？' },
        ],
      },
      {
        id: 'shifts',
        label: 'Pattern B · Shift changes',
        title: 'シフト変更を相談する',
        lines: [
          { speaker: 'A', en: 'Which one are you down for?', ja: 'どのシフトに入ることになっていますか？' },
          { speaker: 'B', en: "I'm down for the morning shift. Could I change to the afternoon?", ja: '朝のシフトに入っています。午後に変更できますか？' },
          { speaker: 'A', en: 'Sorry, I have to change my shift on Monday.', ja: 'すみません、月曜日のシフトを変更しなければなりません。' },
          { speaker: 'B', en: 'Could someone cover my shift, please?', ja: '誰か私のシフトを代わってもらえますか？' },
        ],
      },
      {
        id: 'till',
        label: 'Pattern C · Reporting a problem',
        title: 'レジの不具合を報告する',
        lines: [
          { speaker: 'A', en: 'This till is down again. It keeps crashing!', ja: 'このレジがまた動かなくなりました。フリーズしてばかりです！' },
          { speaker: 'B', en: "Not again! Okay, let's call the supervisor.", ja: 'また！？よし、スーパーバイザーを呼ぼう。' },
          { speaker: 'A', en: "I'm stuck. Could you show me what to do?", ja: '行き詰まってしまいました。どうすればよいか教えていただけますか？' },
          { speaker: 'B', en: "Sure. We'll sort it out together.", ja: 'もちろん。一緒に解決しましょう。' },
        ],
      },
    ],
    tip: 'diary はイギリス英語で「スケジュール帳・予定表」を指すことがあります。be down for はシフトに割り当てられているという意味です。till はレジ、down は機械が動かない状態、keeps crashing は何度もフリーズする状態を表します。',
  },
  practice: {
    title: '職場の予定と問題を、英語で調整する',
    instructions: '日本語訳は見ずに、会議、休憩、シフト変更、機械トラブルを声に重ねます。',
    coreHeading: 'まずは、職場でそのまま使える一文から。',
    dialogueHeading: 'ルーティン、シフト、トラブル報告の場面で役を切り替える。',
    dialogueDescription: '会議と休憩を確認する、シフト変更を相談する、レジの不具合を報告する3つの場面を練習します。',
    finishTitle: '次に職場で予定が変わったとき、必要な情報を英語でひとつ共有してみましょう。',
    corePhrases: [
      { phrase: 'We have a team meeting at 4pm on Tuesdays.', context: '定例会議を共有する', rate: 0.76 },
      { phrase: 'And a full staff meeting once a month.', context: '会議の頻度を伝える', rate: 0.8 },
      { phrase: "Thanks. I'll put it in my diary.", context: '予定を記録する', rate: 0.82 },
      { phrase: 'What time is your lunch break?', context: '休憩時間を尋ねる', rate: 0.82 },
      { phrase: "It's in half an hour. How about yours?", context: '休憩時間を答える', rate: 0.78 },
      { phrase: 'Which one are you down for?', context: '担当シフトを確認する', rate: 0.8 },
      { phrase: "I'm down for the morning shift. Could I change to the afternoon?", context: '別のシフトをお願いする', rate: 0.74 },
      { phrase: 'Sorry, I have to change my shift on Monday.', context: 'シフト変更を切り出す', rate: 0.76 },
      { phrase: 'This till is down again. It keeps crashing!', context: '機械の不具合を報告する', rate: 0.78 },
      { phrase: "Not again! Okay, let's call the supervisor.", context: 'トラブルに対応する', rate: 0.8 },
      { phrase: 'Could someone cover my shift, please?', context: '代わりをお願いする', rate: 0.78 },
      { phrase: "I'm stuck. Could you show me what to do?", context: '助けを求める', rate: 0.76 },
    ],
    dialogues: [
      { title: 'Workplace routines', lines: ['We have a team meeting at 4pm on Tuesdays.', 'And a full staff meeting once a month.', "Thanks. I'll put it in my diary.", 'What time is your lunch break?'] },
      { title: 'Shift changes', lines: ['Which one are you down for?', "I'm down for the morning shift. Could I change to the afternoon?", 'Sorry, I have to change my shift on Monday.', 'Could someone cover my shift, please?'] },
      { title: 'Reporting a problem', lines: ['This till is down again. It keeps crashing!', "Not again! Okay, let's call the supervisor.", "I'm stuck. Could you show me what to do?", "Sure. We'll sort it out together."] },
    ],
    natural: [
      { full: 'I will write this in my schedule book.', natural: "I'll put it in my diary." },
      { full: 'Which shift have you been assigned to?', natural: 'Which one are you down for?' },
      { full: 'This cash register is not working again.', natural: 'This till is down again.' },
    ],
  },
}
